### ISSUE TITLE
Error saving data for phy

### ISSUE THREAD

**Issue by chris-weinberger** [MouseLand/Kilosort#106]
Hello!

I am running into an error in Kilosort2 whenever I run our data through it. It gets through all the steps except saving for phy, and gives this error:

> Error saving data for phy! Reference to non-existent field 'Wphy'.

I checked and made sure the npy-matlab folder is in my path and verified by running a test to use it. Does anyone know why that is or where this error is coming from? 
Thank you in advance!
-Chris

**Comment by Alkohost** [comment]
I was getting this error when one of previous steps failed. I recommend to run Kilosort2 using scripts (classic method) to localize the problem.
