### ISSUE TITLE
Assigning an identified unit to a corresponding channel of the recording electrode

### ISSUE THREAD

**Issue by chrisan97** [MouseLand/Kilosort#118]
Hi,

I'm having some trouble figuring out how to assign an identified unit (sorted from Kilosort2) to a channel that is recorded from. Does Kilosort have an output file that has this information? (i.e. unit 1 -> channel 16, unit 2 -> channel 30 etc...)

Thank you!

**Comment by marius10p** [comment]
You have the entire waveform, rez.dWU, so you can just take the max from there.
