### ISSUE TITLE
spike sorting for small and sparse neurons

### ISSUE THREAD

**Issue by metmic** [MouseLand/Kilosort#123]
Hi,

1st of all, I want to say that kilosort is a great application. However, I have a couple of issues regarding the sorting algorithm.

I am recording from small midbrain neurons in fish that have a broad range of firing rates (from as low as ~0.1Hz up to ~50Hz). Some of these neurons only respond to specific stimulus features and are silent otherwise. Moreover, most spikes are small and do sometimes not extend over more than one channel.

That said, I noticed for some instances that, although I see clear spikes on one channel of the NPIX-probe (phase 3B1), this channel is set to be "bad" after the preprocess of kilosort. If I include all channels in kilosort (i.e., setting 'min. firing rate per chan' to zero), I am getting a lot of false detections, since my recordings are contaminated by an internally generated rhythm by the animal oscillating at around 1000Hz, which is about the duration of these spikes, too. So pre-filtering does not always help here.

Is there any way to set the min / max number of channels a spike has to occur on in kilosort?

Thanks,
Michael

**Comment by marius10p** [comment]
Yes, but you have to run it directly from the master file. The config option is ops.spkTh. You can also decrease the minimum firing rate. Be advised that channels with spikes that small are unlikely to be sortable, but maybe it's different in fish, who knows.
