### ISSUE TITLE
Contamination Percent

### ISSUE THREAD

**Issue by sina253** [MouseLand/Kilosort#143]
Hi
Kilosort2 calculating a value named: ContamPct, which I guess should be contamination percentage.
For some of our sorting sessions this number is low for good labeled clusters and all 100 for the MUA labeled clusters. However, for the other sorting sessions  ContamPct values are very different and are even more than 100 for clusters.  

Is this a bug?

**Comment by marius10p** [comment]
Share screenshots please. I don't know why it would be above 100.

**Comment by Stefxnia83** [comment]
Hi Marius,
I attached two example where you can see the value of the contamination percentage for all the multiunits is always 100. I also attached an example of a cluster labeled as good and the value of the contamination percentage is always 100. 
Also, the data have been collected by a 96 channels Utah Array. The recording loci do not have different depths, but as you can see the channels are attributed to different depths and look like they are attributed to one shank. Could that affect the output of the sorting?

![ContamPct_MUA_100](https://user-images.githubusercontent.com/36707545/70161990-f3cfc800-168a-11ea-915c-5e3bf17cc4d1.PNG)
![ContamPct_MUA_100_2](https://user-images.githubusercontent.com/36707545/70161993-f6322200-168a-11ea-9a29-3588a0511c6c.PNG)
![ContamPct_SUA_100](https://user-images.githubusercontent.com/36707545/70161995-f7634f00-168a-11ea-994a-9bd89fe32ea5.PNG)

**Comment by marius10p** [comment]
I am not sure why a cluster would be labelled as good even though the contamination is computed as 100%. I'll double check, but in any case, that label is meant to be used as guidance. Works very well on some data, and poorly on other data. 

"Depth" is interpreted as the y-dimension of your channel map file. This won't really make an impact on the sorting in your case, it's just for visualization in Phy.

**Comment by JoseGuzman** [comment]
I have exactly the same issue (see attached screenshot).
![ContamPct](https://user-images.githubusercontent.com/6409964/70985442-647bd900-20bc-11ea-9f25-b2cf90c005b9.png)

- There are clusters with **ContamPct = 100**  labeled as 'good' (green line)
- There are clusters with **ContamPct > 100** (pink line)

I am not sure what can be the reason, but it seems to happen when the templates are on the same channel (see colors in the figure). I am using 128 channels from Cambridge Neurotech probes.

**Comment by Stefxnia83** [comment]
Thank you!

**Comment by marius10p** [comment]
Ok, I'll have to look into that. Looks like the ones labelled as good with ContamPct=100 might have very few spikes. I thought I had a special case to exclude those, but I'll have to check it.
