### ISSUE TITLE
Out of RAM for recording with millions of spikes

### ISSUE THREAD

**Issue by dimokaramanlis** [MouseLand/Kilosort#152]
Hi,

I get an "out of memory" problem when trying to sort a good 8h-long recording from the retina (252 channels, 10k sampling rate). 

In particular, the algorithm crashes at some point here, when it's trying to expand the arrays that hold the spikes and spike features:

https://github.com/MouseLand/Kilosort2/blob/3e247065c2627a91dcc4ab20c572a431fa87655d/mainLoop/trackAndSort.m#L185-L190

The computer's RAM is 64GB. I used the default thresholds (ops.Th = [10 4]). To give you an idea about the size of the problem, I got around 250 million spikes from the same recording with KS1 and a threshold of 4 during the final pass. 

I tried dropping NchanNear and Nnearest to 16 (code uses 32) to reduce the features saved, but the computer still goes out of memory...

This issue is also mentioned in the hardware guide. I was wondering whether you have any ideas on how to overcome this, besides using more RAM or increasing the thresholds. Would it be possible by using tall arrays to hold the individual spikes?

Best,
Dimos

**Comment by marius10p** [comment]
That is an order of magnitude more spikes per recording than I've ever tested. The way the spikes and features are constructed is the same as in Kilosort1, so I don't know why one of them works and the other doesn't. 

Take a look at issue #135, which has some ideas for how to process long datasets, but they would require a bit of work from you to make an appropriate script for your data. Eventually we plan to have an example script for long recording, but I don't have time right now to do it. I am surprised you don't run into the CUDA problems the other users are reporting.

**Comment by dimokaramanlis** [comment]
Ok, thanks for the link, I'll try to come up with something.

No CUDA problems so far. I think it's because the sampling rate is lower than usually used (10k), which also results in fewer batches with the default ops.NT = 64*1024 + ops.ntbuff. Furthermore, the graphics card we're using has 11GB of memory.
