### ISSUE TITLE
Error using gpuArray/subsasgn

### ISSUE THREAD

**Issue by dervinism** [MouseLand/Kilosort#178]
The following error comes up when trying to spike sort:

Error using gpuArray/subsasgn
An unexpected error occurred trying to launch a kernel. The CUDA error was:
invalid argument

Error in triageTemplates2 (line 13)
W(:,idrop,:) = []; % remove those templates everywhere

Error in learnTemplates (line 173)
                triageTemplates2(ops, iW, C2C, W, U, dWU, mu, nsp, ndrop);

Error in learnAndSolve8b (line 12)
    rez     = learnTemplates(rez, iorder0);

The error would not occur with an earlier version of kilosort 2.

**Comment by marius10p** [comment]
How many channels are you spike sorting and how large is your ops.NT? You might want to increase that.

**Comment by dervinism** [comment]
384 channels and ops.NT = 65600. What is a more appropriate size of ops.NT?

**Comment by marius10p** [comment]
This should be fine. Does the data look ok in the Matlab GUI? Is the configuration loading ok? 

At what point in spike sorting does this occur? Please copy paste the entire command line output.

**Comment by dervinism** [comment]
The full output is below. I have inspected the data in Neuroscope and it looks fine.

Time   0s. Determining good channels.. 
found 466760 threshold crossings in 216.48 seconds of data 
found 1 bad channels 
Time 135s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time 320s. Loading raw data and applying filters... 
Time 5519s. Finished preprocessing 5641 batches. 
Time 5544s. Optimizing templates ...
5545.54 sec, 1 / 5642 batches, 73 units, nspks: 10.5094, mu: 15.4873, nst0: 148, merges: 0.0000, 0.0000 
5650.22 sec, 101 / 5642 batches, 644 units, nspks: 2977.1750, mu: 18.0233, nst0: 2116, merges: 161.0984, 0.8422 
5763.19 sec, 201 / 5642 batches, 619 units, nspks: 2605.5461, mu: 16.0886, nst0: 3175, merges: 191.7767, 0.3088 
5888.27 sec, 301 / 5642 batches, 709 units, nspks: 7335.9526, mu: 17.0413, nst0: 21916, merges: 181.7466, 0.0375 
6325.21 sec, 401 / 5642 batches, 943 units, nspks: 18447.2108, mu: 18.3517, nst0: 17200, merges: 181.5536, 0.6145 
6813.57 sec, 501 / 5642 batches, 949 units, nspks: 19390.8017, mu: 17.3007, nst0: 19142, merges: 191.8793, 0.9471 
7347.50 sec, 601 / 5642 batches, 990 units, nspks: 22840.3854, mu: 17.7964, nst0: 24606, merges: 189.9499, 1.1294 
7839.86 sec, 701 / 5642 batches, 943 units, nspks: 18537.4612, mu: 16.1950, nst0: 2395, merges: 192.7472, 1.4088 
8369.98 sec, 801 / 5642 batches, 929 units, nspks: 21237.7122, mu: 16.4087, nst0: 24493, merges: 196.6207, 1.5093 
8870.91 sec, 901 / 5642 batches, 933 units, nspks: 20239.3667, mu: 15.8552, nst0: 20696, merges: 198.8503, 0.8396 
9406.39 sec, 1001 / 5642 batches, 980 units, nspks: 20660.9258, mu: 16.7722, nst0: 17581, merges: 192.6847, 1.0744 
9932.23 sec, 1101 / 5642 batches, 990 units, nspks: 20860.3573, mu: 16.3507, nst0: 22802, merges: 192.7324, 0.9377 
10451.44 sec, 1201 / 5642 batches, 977 units, nspks: 20121.9869, mu: 15.8568, nst0: 20031, merges: 189.2927, 0.7484 
10967.25 sec, 1301 / 5642 batches, 971 units, nspks: 19968.8203, mu: 15.7011, nst0: 19520, merges: 196.7373, 0.7241 
11474.12 sec, 1401 / 5642 batches, 968 units, nspks: 20556.5244, mu: 15.1839, nst0: 19869, merges: 200.2376, 0.6578 
12010.41 sec, 1501 / 5642 batches, 953 units, nspks: 20078.1549, mu: 15.2764, nst0: 19475, merges: 200.4092, 1.0238 
12531.12 sec, 1601 / 5642 batches, 953 units, nspks: 20763.7382, mu: 15.3400, nst0: 24758, merges: 197.2555, 0.7744 
13031.27 sec, 1701 / 5642 batches, 958 units, nspks: 20075.2219, mu: 15.1028, nst0: 22702, merges: 196.7768, 0.8559 
13553.13 sec, 1801 / 5642 batches, 946 units, nspks: 19941.0031, mu: 14.9568, nst0: 18682, merges: 200.5547, 0.5993 
14062.60 sec, 1901 / 5642 batches, 970 units, nspks: 20002.2660, mu: 14.9212, nst0: 17685, merges: 197.8236, 0.4033 
14583.65 sec, 2001 / 5642 batches, 989 units, nspks: 20359.3396, mu: 14.6510, nst0: 18905, merges: 195.2433, 0.2824 
Error using gpuArray/subsasgn
An unexpected error occurred trying to launch a kernel. The CUDA error was:
invalid argument

Error in triageTemplates2 (line 13)
W(:,idrop,:) = []; % remove those templates everywhere

Error in learnTemplates (line 173)
                triageTemplates2(ops, iW, C2C, W, U, dWU, mu, nsp, ndrop);

Error in learnAndSolve8b (line 12)
    rez     = learnTemplates(rez, iorder0);

Error in ks_master_file2 (line 33)
rez = learnAndSolve8b(rez);

Error in spikeSortingPipeline (line 389)
        ks_master_file2;

Error in init (line 27)
spikeSortingPipeline(inp);

**Comment by dervinism** [comment]
I cannot launch the kilosort gui. I get the following error:

>> kilosort
No constructor 'handle.listener' with matching signature found.

Error in uiextras.Container (line 95)
            obj.Listeners{end+1,1} = handle.listener( containerObj, findprop( containerObj, 'PixelBounds' ), 'PropertyPostSet',
            @obj.onResized );

Error in uiextras.Box (line 38)
            obj@uiextras.Container( varargin{:} );

Error in uiextras.VBox (line 44)
            obj@uiextras.Box( varargin{:} );

Error in ksGUI/build (line 100)
            obj.H.root = uiextras.VBox('Parent', f,...

Error in ksGUI (line 47)
            obj.build(parent);

Error in kilosort (line 17)
h = ksGUI(f);

**Comment by nsteinme** [comment]
this gui error comes from having installed the wrong version of the
uiextras toolbox. please uninstall then follow the link given when you try
running kilosort without having it installed.

**Comment by dervinism** [comment]
I have looked at the data using kilosort gui but I don't see any issues with the data.

**Comment by dervinism** [comment]
Any progress on this issue recently?

**Comment by marius10p** [comment]
Can you post screenshots from the GUI please, after scrolling to different sections of the data? It looks to me like it's finding way too many spikes, which usually indicates a configuration problem or artifacts that dominate the variance of the data.

**Comment by dervinism** [comment]
There might be more than usual of low amplitude high frequency noise in the data. Is there an amplitude threshold parameter that can be adjusted to reduce detectability of such unwanted events?

**Comment by marius10p** [comment]
If you can post pictures, I can give a more informed opinion. There is a threshold parameter in the GUI, same one that you can set in the configuration script (ops.Th).

**Comment by dervinism** [comment]
The kilosort gui no longer works...

**Comment by dervinism** [comment]
There was an old toolbox version on the path. Here is the screenshot with the GUI. What is the meaning of the threshold parameter values. Default values appear to be 10 and 4.
![trace_example](https://user-images.githubusercontent.com/50549306/74469637-fc1b5f00-4e94-11ea-9239-44e3e82a5749.png)

**Comment by marius10p** [comment]
[readme](https://github.com/MouseLand/Kilosort2)
[Kilosort1 paper](https://www.biorxiv.org/content/10.1101/061481v1) (the threshold works the same way)

**Comment by TRuikes** [comment]
@dervinism did you manage to solve this?
