### ISSUE TITLE
mexGetSpikes2 returns a 2-dimensional result in learnTemplates

### ISSUE THREAD

**Issue by ckemere** [MouseLand/Kilosort#218]
I've been dealing with issues related to trying to sort data with not-so great (i.e., lower amplitude and somewhat sparse) firing neurons recorded using Buzsaki-style Neuronexus probes over a long period.

I changed the threshold parameters `ops.spkTh = -5`,  `ops.ThPre = 3`, and `ops.Th = [3, 2]` to deal with the fact that I was getting a lot of `Batch XX has fewer than Nfilt spikes.` errors, and succeeded in getting up to the `learnAndSolve8b()` function without errors or warnings. However, I discovered that things are now breaking right at the beginning, and it appears to be because `mexGetSpikes2` is not returning any spikes. 

It revealed an odd bug (?), which is that `size(dWU,3) = 1` even though the size returns as `61  8` (which is dimension 2, not 3!).  Any thoughts on why mexGetSpikes2 wouldn't return spikes when the initial clustering seems to be working fine?

thanks!

```
    if ibatch==1
       % only on the first batch, we first get a new set of spikes from the residuals,
       % which in this case is the unmodified data because we start with no templates
        [dWU, cmap] = mexGetSpikes2(Params, dataRAW, wTEMP, iC-1); % CUDA function to get spatiotemporal clips from spike detections
        W = W0(:,ones(1,size(dWU,3)),:); % initialize the low-rank decomposition with standard waves
        Nfilt = size(W,2); % update the number of filters/templates
        nsp(1:Nfilt) = m0; % initialize the number of spikes for new templates with the minimum allowed value, so it doesn't get thrown back out right away
        Params(2) = Nfilt; % update in the CUDA parameters
    end
```

**Comment by JoseGuzman** [comment]
The same problem here, for a similar issue with noisy recordings. The clustering was working well until the Commits on May 14, 2020. I did a `git pull` today and got messages with` 'Batch x has fewer than Nfilt spikes' `and the following error

```
One or more output arguments not assigned during call to "mexMPnu8".

Error in learnTemplates (line 149)
        mexMPnu8(Params, dataRAW, single(U), single(W), single(mu), iC-1, iW-1, UtU, iList-1, ...

Error in learnAndSolve8b (line 15)
    rez     = learnTemplates(rez, iorder0);

Error in master_kilosort (line 53)
rez = learnAndSolve8b(rez);
```
