### ISSUE TITLE
Memory error on a 6 hour 64 channel recording

### ISSUE THREAD

**Issue by KaiserArndt2** [MouseLand/Kilosort#227]
When trying to run KS2 I can't get past learnAndSolve8b.  I have tried modifying the ops.NT in config file (using values ranging from 16 X 1024 to 128 X 1024), all attempts have ended in memory errors at the learnAndSolve8b step.  I have seen thread 135 about possibly cutting the recordings or template matching and neither of those options work for us.  I was hoping you would have a solution to this memory error.

Thanks,
Kaiser

**Comment by JoseGuzman** [comment]
I'm not sure that it's related to issue #135. It happens also to me with smaller data. I suggested to checkout 48bf2b81d8ad3bece919f358e071520d5b0930e1 in issue #218 to solve temporarily the problem.

**Comment by marius10p** [comment]
What Jose said, try increasing your batch size much more.  Also, remember to add ops.ntbuff:

``ops.NT                  = 64*1024+ ops.ntbuff; % must be multiple of 32 + ntbuff. This is the batch size (try decreasing if out of memory). ``
