### ISSUE TITLE
mexMPnu8 error

### ISSUE THREAD

**Issue by julieelie** [MouseLand/Kilosort#240]
Hello,
I'm just coming back to kilosort2 after a break (new dataset), and after updating with the last version of the code I get a strange error under matlab 2019b. I am using kilosort2 on long  tetrode recordings (4 tetrode per recording, so 16 channels). Here is the error:

`One or more output arguments not assigned during call to "mexMPnu8".

Error in learnTemplates (line 149)
        mexMPnu8(Params, dataRAW, single(U), single(W), single(mu), iC-1, iW-1, UtU, iList-1,
        ...

Error in learnAndSolve8b (line 15)
    rez     = learnTemplates(rez, iorder0);`

If you want to reproduce the error, I loaded the rez file under google drive here:
https://drive.google.com/file/d/1BkdTUlT0VPnXhH0IO_y18DDggw-poKRe/view?usp=sharing

Thank you for your help!
Julie

**Comment by marius10p** [comment]
Julie, can you please try turning off "stable mode" from mexGPUall, and run that script again. 

@jenniferColonell any idea what this might be?

**Comment by julieelie** [comment]
I set the variable  enableStableMode = false; in mexGPUall.m and still get the same error.

**Comment by jenniferColonell** [comment]
Hi Julie,

I'm unfamiliar with this error.

One possibility is that you have a data batch with some odd property, for example, no spikes detected.

Can you see from the command line output if the error is occurring during the processing of the first batch?

jennifer


________________________________

**Comment by julieelie** [comment]
Hello Jennifer,
Yes the issue is happening right from the first batch (see the output below).
How can this problem be fixed?
Thank you for your help!
Julie

-------------
Looking for data inside C:\Users\Dell Workstation\Documents\DataKilosort220190116 
Time   0s. Determining good channels.. 
found 5528 threshold crossings in 411.24 seconds of data 
found 2 bad channels 
Time  22s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time  37s. Loading raw data and applying filters... 
Time 411s. Finished preprocessing 3311 batches. 
random seed for clusterSingleBatches: 1
Obtained 7 PC waveforms in 4.63 seconds 
time 0.63, pre clustered 1 / 3311 batches 
time 20.27, pre clustered 501 / 3311 batches 
time 39.37, pre clustered 1001 / 3311 batches 
time 57.70, pre clustered 1501 / 3311 batches 
time 76.03, pre clustered 2001 / 3311 batches 
time 93.88, pre clustered 2501 / 3311 batches 
time 112.21, pre clustered 3001 / 3311 batches 
time 0.14, compared 1 / 3311 batches 
time 2.76, compared 501 / 3311 batches 
time 5.38, compared 1001 / 3311 batches 
time 7.98, compared 1501 / 3311 batches 
time 10.59, compared 2001 / 3311 batches 
time 13.17, compared 2501 / 3311 batches 
time 15.74, compared 3001 / 3311 batches 
time 26.27, Re-ordered 3311 batches. 
Time  47s. Optimizing templates ...
One or more output arguments not assigned during call to "mexMPnu8".

Error in learnTemplates (line 149)
        mexMPnu8(Params, dataRAW, single(U), single(W), single(mu), iC-1, iW-1, UtU, iList-1,
        ...

Error in learnAndSolve8b (line 15)
    rez     = learnTemplates(rez, iorder0);

Error in mymaster_kilosort (line 81)
rez = learnAndSolve8b(rez);

**Comment by jenniferColonell** [comment]
Hi Julie,

Since you are seeing the issue in the first batch, can you post a short (5 min) extract of your data on Dropbox? I'll see if I can run it.

jennifer

________________________________

**Comment by julieelie** [comment]
I posted the full dataset under Google drive, you can see the URL above, is it working?
If necessary I can cut that extract though, but since it's already online...
Here is the link again:
https://drive.google.com/file/d/1BkdTUlT0VPnXhH0IO_y18DDggw-poKRe/view?usp=sharing

**Comment by jenniferColonell** [comment]
Hi Julie,

I did look at your rez.mat file, but that doesn't include the raw data.

Your raw data is pretty big, so it will be slow to upload to Google drive...so if you have an easy means to extract a few minutes of data to post, that would be useful for debugging.

by the way, are you running using a master file or the GUI?

________________________________

**Comment by julieelie** [comment]
I regenerated a smaller raw file, you'll find it here:
https://drive.google.com/file/d/1DLcrNf-yawZ8pD4vuaWaL2HkmT7DFNPE/view?usp=sharing

And yes I am running a master file. I can push the last version on GitHub if you want to see that as well.
Thank you very much!
Julie

**Comment by jenniferColonell** [comment]
Hi Julie,

yes, it would be useful to see your master file and config file.

thanks!

________________________________

**Comment by julieelie** [comment]
Hey Jennifer,
My master file (mymaster_kilosort) is available here, along with the configfiles.
https://github.com/julieelie/Kilosort2_Tetrode
Thanks!

**Comment by jenniferColonell** [comment]
Thanks, Julie. I ran your data excerpt, with your master and config files, without any issues. So, there is nothing unusual in your data. I think there must be some sort of problem with your KS2 build.

The nature of your problem looks like the version of learnTemplates is not matched to the CUDA code. Is there any way this could have happened? Did you update an existing clone of KS2, or make a whole new clone?





________________________________

**Comment by julieelie** [comment]
I pull under Github the last version of Kilosort 2 under MouseLand...
Where is the CUDA code? Is it not in MouseLand/Kilosort2/CUDA?
That should have been updated as well when I pulled the whole  Kilosort2 folder.... I think.

**Comment by jenniferColonell** [comment]
Hi Julie,

You are correct, that's where the CUDA code is.

I am not a git expert. I think the "pull" command should update everything in the repo. as you say....but this does look like a version problem.

If the KS2 build that is giving you trouble is a repo that you updated with "pull"...

Could you try making a brand new clone of the whole repo? I believe this should avoid any possible version problems.

thanks,

jennifer

________________________________

**Comment by julieelie** [comment]
Hello Jennifer,
I'll try to make a brand new version of the code. I'm sharing that computer with some other folks, so need to wait until I can have access... I hope that will fix the problem!

**Comment by Idavr** [comment]
Hi @julieelie ,

I had this same problem when I tried installing KS2 for the first time earlier this year, and a weirdly enough this was due to (in my case) the compiler putting invalid characters into into one of the temporary file names, which can happen for some European language settings in Windows. Not sure if you are running Windows or if your language setting is a European language, but if so my fix was simply to change the Windows region and language setting to either US or UK English.

**Comment by jenniferColonell** [comment]
Hi Julie,

@Idavr is correct: in particular, the CUDA compile can have errors if the computer is using particular European language settings in Windows. If that were happening in your case, you would have seen errors when you ran mexGPUAll. If you were working with a repo that you updated (rather than a new one), you might wind up running with old compiled CUDA versions -- which might lead to the errors that you are seeing.

To keep things simple, I still recommend starting with a whole new clone of KS2. Let us know if you run into any errors when you run mexGPUAll to compile the CUDA code.

jennifer

________________________________
