### ISSUE TITLE
dirver is too old for CUDA

### ISSUE THREAD

**Issue by lamugou** [MouseLand/Kilosort#241]
Hi, I meet an error in matlab below, it claims that my dirver is too old for CUDA, does anyone know how to resolve this error? Thanks!

**>> kilosort
There is a problem with the CUDA driver or with this GPU device. Be sure that you have a supported GPU and that the latest driver is installed.

Error in ksFilter (line 15)
    dataRAW = gpuArray(buff);

Error in ksGUI/updateDataView (line 872)
                    datAllF = ksFilter(datAll, obj.ops);

Error in ksGUI/updateFileSettings (line 541)
                obj.updateDataView()

Error in ksGUI/selectFileDlg (line 474)
                obj.updateFileSettings();

Error in ksGUI>@(~,~)obj.selectFileDlg (line 179)
                'Callback', @(~,~)obj.selectFileDlg);

Caused by:
    The CUDA driver was found, but it is too old. The CUDA driver on your system supports CUDA version 5.5. The required CUDA version
    is 7.5 or greater.
 
Error while evaluating UIControl Callback

There is a problem with the CUDA driver or with this GPU device. Be sure that you have a supported GPU and that the latest driver is
installed.

Error in ksFilter (line 15)
    dataRAW = gpuArray(buff);

Error in ksGUI/updateDataView (line 872)
                    datAllF = ksFilter(datAll, obj.ops);**

**Comment by marius10p** [comment]
You need to upgrade your CUDA driver. Use the version appropriate for your matlab version from here: https://www.mathworks.com/help/parallel-computing/gpu-support-by-release.html
