### ISSUE TITLE
WaveformView in the closest channels

### ISSUE THREAD

**Issue by butterflyfei1127** [MouseLand/Kilosort#243]
I used a 8x8 NeuroNexus electrode to do the spike sorting, and the cluster showed in the channels not close to each other. Does it make sense?

![Screenshot from 2020-10-26 18-21-23](https://user-images.githubusercontent.com/73470592/97161026-31b07000-17b8-11eb-87f3-e691e71220ef.png)

I am new to kilosort, and could you please give me some suggestions? Thanks.

**Comment by marius10p** [comment]
Doesn't look right, you probably need to assign the correct x and y positions to the channels, as well as check your channel map.
