### ISSUE TITLE
Bad merge in recent commit

### ISSUE THREAD

**Issue by peterzh** [MouseLand/Kilosort#247]
When I run KS2.5 on a dataset I get an error due to a syntax error in this code:

[https://github.com/MouseLand/Kilosort/blob/2b2fc658849fd31112a10216ec2d479262558662/postProcess/get_good_units.m#L8](https://github.com/MouseLand/Kilosort/blob/2b2fc658849fd31112a10216ec2d479262558662/postProcess/get_good_units.m#L8)

**Comment by marius10p** [comment]
Thanks for catching this, should be fixed now.
