### ISSUE TITLE
Bug when selecting 'Phase 3B1 (staggered)' probe layout

### ISSUE THREAD

**Issue by peterzh** [MouseLand/Kilosort#248]
The configFiles folder contains three profiles which share the naming `Neuropixels Phase3B1 (staggered)` within the .mat file `name` variable. This creates a problem because at line

https://github.com/MouseLand/Kilosort/blob/0e2edcb37d06e12690fe08696d308ba4082d3cdf/gui/ksGUI.m#L1191

the cm variable will contain three sets of channel maps, and therefore the later lines will throw errors. For example at
https://github.com/MouseLand/Kilosort/blob/0e2edcb37d06e12690fe08696d308ba4082d3cdf/gui/ksGUI.m#L1195 the `unique` function will throw an error because it expected a vector but instead receives a collection of multiple vectors.

This can be fixed by removing the extra maps, or ensuring that Line 1191 only gets one profile which matches the name. I wasn't sure which strategy you'd prefer.

**Comment by marius10p** [comment]
Thanks for finding this bug as well! I removed the extra channel maps, which I must have added on accident.
