### ISSUE TITLE
Update eMouse_drift to new kilosort2.5 methods error

### ISSUE THREAD

**Issue by nmtimme** [MouseLand/Kilosort#250]
Hello

I started running the eMouse_drift simulation to test the kilosort2.5 installation and I received an error that clusterSingleBatches was not found. In looking at main_kilosort, it appears that this function has been removed from the primary analysis workflow in kilosort2.5, but that these updates have not been made to main_eMouse_drift. Thanks!

~Nick

**Comment by marius10p** [comment]
This should be fixed now. - Marius

**Comment by nmtimme** [comment]
Thanks! I appreciate you acting on this so quickly!
