### ISSUE TITLE
non-existent field 'iorig'

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#251]
Dear Marius,
i am giving kilosort another shot, cloned and compiled, tried running with default config384.m settings.

I get an error in the main optimization stage- reference to non-existent field 'iorig'.
Then Error saving data for Phy! reference to non-exsistent field 'Wphy'.

if i try to turn off registration i get : "not enough input arguments"  in datashift2, line 129 if do_correction

rez file attached.
[rez.zip](https://github.com/MouseLand/Kilosort/files/5464550/rez.zip)

Shahaf

**Comment by marius10p** [comment]
Are you running it through the GUI? There was a bug, I just fixed it. 

The first error is strange, I think you are combining an old installation with a new installation (check the Matlab path). There should be no way to turn off registration at the moment.

**Comment by WeissShahaf** [comment]
yes, i'm using the GUI. 
im getting the same issue with two PCs. one running ubuntu 18.04 and one with Win 10.

by registration i mean i the N blocks for registration- default is 5, i tried 0 ("none")

**Comment by marius10p** [comment]
Did you try the GUI again? I had fixed the problem 1h ago. I now also fixed the problem with nblocks = 0.

**Comment by WeissShahaf** [comment]
thanks, it does work now. mostly, Matlab sometimes crashes, but that could be a local thing.
for the N blocks for registration, how many is a reasonalbe N for long recordings (~17 hours)

**Comment by marius10p** [comment]
It is not a function of the recording length, but probe length. For <=1000um, I'd recommend nblocks = 1. For 3000um the default is 5.
