### ISSUE TITLE
Sorting of packed spiking activity with low SNR

### ISSUE THREAD

**Issue by mdandola** [MouseLand/Kilosort#253]
Hi,

I'm trying to sort spinal-cord recordings with opto-genetic stimulation. What we have is a network mostly silent during spontaneous activity, but with a clear high-frequency response to stimulation. Referring to the image below, If I look at the filtered LFP outside of KS2 (bandpass [300 6000] Hz), I can observe a clear difference between baseline and stimulation periods. 

![stim_zoom](https://user-images.githubusercontent.com/22916421/97884279-2b754300-1d26-11eb-8eb6-d1e8615150ac.png)

- With respect to my previous experience with brain recordings, this looks very "packed" (lots of spikes in short time ranges) and with a lower SNR. It is a bit difficult to identify single spikes by eye
- At the beginning, but mostly at the end of every stimulation period, there are very sharp peaks reflecting turning on and off the laser, of intensity proportional to the stimulation
- The recordings were made through and open-ephys box using a probe with 32channels with interspacing of 16 µm, at a Fs of 30 KHz

I'm aware that the filtering of KS is not a bandpass, but high-pass + common average referencing. In this case thought, such filtration mostly flatten the response, resulting then into exclusion of many channels, and almost empty units identification in the remaining ones (the units that are identified are all noise). 
Is there anyway to avoid this? Would you suggest some pre-filtering the data manually or change the filtering parameters in KS such as to highlight this type of response?

thank you very much!
Mattia

<img width="1738" alt="Schermata 2020-11-02 alle 16 33 23" src="https://user-images.githubusercontent.com/22916421/97886670-2e256780-1d29-11eb-9dda-f997f14784fe.png">

<img width="1740" alt="Schermata 2020-11-02 alle 14 29 13" src="https://user-images.githubusercontent.com/22916421/97887564-61b4c180-1d2a-11eb-9e71-c565fb7c548d.png">

<img width="1744" alt="Schermata 2020-11-02 alle 16 41 57" src="https://user-images.githubusercontent.com/22916421/97887614-71340a80-1d2a-11eb-8810-a192bef93696.png">

**Comment by marius10p** [comment]
Hi Mattia, I don't see any spikes in your data, and it sounds like Kilosort has not found any either. Unless you can see spikes clearly by eye, Kilosort won't be able to find them. Look carefully at the filtered traces, maybe they are there after all... 

Btw, you can turn off the dropping of the channels (it's not even an option anymore in Kilosort2.5).

**Comment by JoseGuzman** [comment]
Hi @mdandola !

I'm dealing with a similar problem, and you will have to play quite a bit with **main_kilosort.m** and your **config.m** file. Below you can find an example that I use as a master for such files, and [here](https://raw.githubusercontent.com/JoseGuzman/minibrain/master/Matlab/master_kilosort.m) you can access one of my config.files too. 

Just if  - as @marius10p mentioned - you're able to see visually some spikes in the binary file. If not, I would recommend you to repeat the experiments with lower impedance and/or more dense electrodes.

Hope it helps!


```matlab
%=========================================================================
% main_kilosort.m
%
% For recording FS004_blanked
% Jose Guzman, jose.guzman<at>guzman-lab.com
% Created: 
%
% this script will execute Kilosort2 by first reading a configFile called
% 'OptoConfig.m' and the probe created with 'CreateE_Probes.m'
%=========================================================================
%
addpath(genpath('~/git/Kilosort2')) % path to KiloSort2 folder
addpath('~/git/npy-matlab/npy-matlab/') % for converting to python
rootZ = './'; % the raw data binary file is in current directory
outDir = './sorting'; % output directory
rootH = '/data/tmp'; % path to temporary binary file ( on fast SSD)
pathToYourConfigFile = '~/SiliconProbes/Kilosort2/configFiles'; 

chanMapFile = '64F.mat';

ops.trange = [30 inf]; % time range to sort
ops.NchanTOT = 67; % total number of channels in your recording

run(fullfile(pathToYourConfigFile, 'OptoConfig.m'))
ops.Th = [8 4];  % default [10 4]

ops.fproc       = fullfile(rootH, 'temp_wh.dat'); % proc file on a fast SSD
ops.chanMap = fullfile(pathToYourConfigFile, chanMapFile);

%% this block runs all the steps of the algorithmO
fprintf('Looking for data inside %s \n', rootZ)

% is there a channel map file in this folder?
fs = dir(fullfile(rootZ, 'chan*.mat'));
if ~isempty(fs)
    ops.chanMap = fullfile(rootZ, fs(1).name);
end

% find the binary file
fs          = [dir(fullfile(rootZ, '*.bin')) dir(fullfile(rootZ, '*.dat'))];
ops.fbinary = fullfile(rootZ, fs(1).name);

% preprocess data to create temp_wh.dat
rez = preprocessDataSub(ops);

% NEW STEP TO DO DATA REGISTRATION
rez = datashift2(rez, 1); % last input is for shifting data

% ORDER OF BATCHES IS NOW RANDOM, controlled by random number generator
iseed = 1;
                 
% main tracking and template matching algorithm
rez = learnAndSolve8b(rez, iseed);

% OPTIONAL: remove double-counted spikes - solves issue in which individual spikes are assigned to multiple templates.
% See issue 29: https://github.com/MouseLand/Kilosort/issues/29
%rez = remove_ks2_duplicate_spikes(rez);

% final merges
rez = find_merges(rez, 1);

% final splits by SVD
rez = splitAllClusters(rez, 1);

% decide on cutoff
rez = set_cutoff(rez);
% eliminate widely spread waveforms (likely noise)
rez.good = get_good_units(rez);

fprintf('found %d good units \n', sum(rez.good>0))

% write to Phy
%rezToPhy(rez, rootZ);
fprintf('Saving results to Phy \n')
rezToPhy(rez, outDir);

%% if you want to save the results to a Matlab file...

% discard features in final rez file (too slow to save)
rez.cProj = [];
rez.cProjPC = [];

% final time sorting of spikes, for apps that use st3 directly
[~, isort]   = sortrows(rez.st3);
rez.st3      = rez.st3(isort, :);

% Ensure all GPU arrays are transferred to CPU side before saving to .mat
rez_fields = fieldnames(rez);
for i = 1:numel(rez_fields)
    field_name = rez_fields{i};
    if(isa(rez.(field_name), 'gpuArray'))
        rez.(field_name) = gather(rez.(field_name));
    end
end

% save final results as rez2
fprintf('Saving final results in rez2  \n')
%fname = fullfile(rootZ, 'rez2.mat');
fname = fullfile(outDir, 'rez2.mat');
save(fname, 'rez', '-v7.3');
```

**Comment by mdandola** [comment]
Hi,

thank you both for your answers. Even if a bit difficult to identify by naked eye because of the low SNR, I am quite sure  of the presence of spiking activity. 
@JoseGuzman, thanks for the files, they will be very useful!

**Comment by mdandola** [comment]
Hi @JoseGuzman ,

I think you linked me another master file instead of your config file. Could you please send me the config file?
thanks a lot

Mattia

**Comment by JoseGuzman** [comment]
Take a look [here](https://raw.githubusercontent.com/JoseGuzman/minibrain/master/Matlab/configFiles/OptoConfig.m). You will find more examples and configurations in my minibrain python package: https://github.com/JoseGuzman/minibrain/tree/master/Matlab/configFiles
