### ISSUE TITLE
Error while running KS2.5

### ISSUE THREAD

**Issue by AamnaLawrence** [MouseLand/Kilosort#254]
Hi,

I was trying to run KS2.5 on one of the neuropixel files but the preprocessing takes too long and redirects me to keyboard input. In the GUI, I get the following error:

Error preprocessing! Undefined function 'spikedetector3'for input arguments of type gpuArray.

**Comment by marius10p** [comment]
Remember to run mexGPUall again.

**Comment by AamnaLawrence** [comment]
Hi, 
Thank you for your help. Can you also help me understand what the drift traces and drift map mean?

**Comment by marius10p** [comment]
The details are here: https://www.biorxiv.org/content/10.1101/2020.10.27.358291v1.abstract

Check out the methods for extra details.
