### ISSUE TITLE
Error in getClosestChannels2

### ISSUE THREAD

**Issue by nmtimme** [MouseLand/Kilosort#255]
Hello

I'm running kilosort2.5 and I'm getting this error:

Index in position 1 exceeds array bounds (must not exceed 51).

Error in getClosestChannels2 (line 16)
iC= isort(1:NchanClosest, :);

Error in standalone_detector (line 40)
[iC2, dist2] = getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp);

Error in datashift2 (line 30)
[st3, rez] = standalone_detector(rez, spkTh);

Error in stage2Core (line 418)
        rez = datashift2(rez, 1); % last input is for shifting data

I checked and NchanClosest = 100. I think the problem might be due to the geometry of my probe. It has 23 channels in a line (all the x-coordinates are 0). Is fixing this as easy as the following change on line 16 of getClosestChannels2:

iC= isort(1:NchanClosest, :);

goes to

iC= isort(1:min(NchanClosest,size(isort,1)), :);

Or, is there something else happening. Thanks!

~Nick

**Comment by marius10p** [comment]
that should be it, can you try it and let us know?

**Comment by nmtimme** [comment]
That seems to have fixed it. Thanks!
