### ISSUE TITLE
Incorrect channel_map.npy

### ISSUE THREAD

**Issue by AnnaCSales** [MouseLand/Kilosort#256]
Hi all,
I've just upgraded to KS2.5 and I noticed that in rezToPhy there's a line of code 

chanMap0ind = int32([1:rez.ops.Nchan]-1);

Which leads to the channel_map.npy file containing a list from 1 to nchans, rather than the actual channel map you've used to cluster. I've just commented it out in my version but thought it'd be worth flagging
Atb

**Comment by marius10p** [comment]
Sorry, I must have accidentally left that in there. Fixed now.

**Comment by rajatsaxena** [comment]
The incorrect channel_map.npy line is still there. Any specific reason for leaving it in?

**Comment by jessiburd** [comment]
I'm wondering about this too
