### ISSUE TITLE
rezToPhy writes temporary data name to params.py 

### ISSUE THREAD

**Issue by LaurenzMuessig** [MouseLand/Kilosort#258]
Hi,

I noticed that rezToPhy now writes 'ops.fproc' as the filename to params.py instead of 'ops.fbinary' (l.187). Is that on purpose?

Cheers

Laurenz

**Comment by marius10p** [comment]
Yes, it's on purpose, this is the drift-corrected file, which gives a better picture of what's going on.

**Comment by LaurenzMuessig** [comment]
Thanks Marius, that makes sense.

**Comment by LaurenzMuessig** [comment]
HI Marius,

Sorry for pestering you more on this, but could you explain to me what the format of the drift corrected file is (it is e.g. slightly smaller than the original binary)? I can load it into phy e.g. but the waveforms then look mostly wrong as do the amplitudes. If I wanted to extract waveforms from the binary, is the idea to use the drift corrected file?
