### ISSUE TITLE
Running Kilosort on CPU

### ISSUE THREAD

**Issue by claysmyth** [MouseLand/Kilosort#259]
How can I go about running Kilosort (any version) on a CPU? Unfortunately I am on a mac without an NVIDIA GPU, but only plan on running sorts on a few channels as preliminary tests.

**Comment by marius10p** [comment]
Sorry, we don't currently have plans to maintain a non-GPU version. The very earliest [Kilosort 1.0](https://github.com/cortex-lab/KiloSort) has a CPU version, but that's a 5-year old algorithm now. You could start with that if you just want to explore your data, look at it in Phy etc, but keep in mind there is no drift correction and the results will be rather suboptimal.
