### ISSUE TITLE
KS2.5 output leads to error in Phy2

### ISSUE THREAD

**Issue by stagkourakis** [MouseLand/Kilosort#265]
Hi Marius,
I just tried out KS2.5 but although it runs smoothly, I can't load it's output to Phy2. Phy 2 gives an error as seen in the picture attached. Any tips?

Many thanks,
Stefanos

![phy2ErrorWithKS2 5](https://user-images.githubusercontent.com/53228356/98185108-d6b9ff80-1ec0-11eb-8def-da50ecb5f958.png)

**Comment by marius10p** [comment]
Thanks for catching this. I made a mistake earlier modifying rezToPhy and that is undone now. Can you see if it works now? Make sure to delete your params.py file too, because rezToPhy doesn't touch that if it already exists.

**Comment by stagkourakis** [comment]
Thanks for fixing this promptly Marius! Works great now!
