### ISSUE TITLE
full parameter list

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#266]
Dear Marius,
KS2,5 is great, but can you post on the wiki, the full list of optional paramters and what they are, like:

 ops.verbose
 ops.fslow
 ops.parfor
ks.ops.whitening
ks.ops.initialize

Thanks
Shahaf

**Comment by marius10p** [comment]
I will rewrite the wiki soon. The only important new parameters from KS2 are in the main_kilosort file:

% main parameter changes from Kilosort2 to v2.5  
ops.sig        = 20;  % spatial smoothness constant for registration  
ops.fshigh     = 300; % high-pass more aggresively  
ops.nblocks    = 5; % blocks for registration. 0 turns it off, 1 does rigid registration. Replaces "datashift" option.

**Comment by WeissShahaf** [comment]
thank you Marius,
are these on by default or do we need to write them into config384.m?

**Comment by marius10p** [comment]
You need to adapt your main_kilosort file by copying the example from the repository. I put these options in there to emphasize them, but you can also put them in your config file.
