### ISSUE TITLE
size ops.froc < ops.fbinary

### ISSUE THREAD

**Issue by LaurenzMuessig** [MouseLand/Kilosort#267]
Hi

I noticed that ops.fproc is slightly smaller in terms of file size compared to the original binary. Is that because the drift corrected file has channels set as not connected in the channel map removed (so e.g. the ref channel)? What about the sync channel? 
@marius10p : Could you let me know what exactly the format of the drift corrected file is? Thanks a lot for your help.

PS: Also, I hardly see any differences in phy for the waveforms if I compare the drift corrected file with the original binary - is that because there isn't much drift - the output from KS2.5 shows ~+/- 6um for that data set (and if I run KS2 on the same data set the waveform data looks much worse).

Cheers

Laurenz

**Comment by marius10p** [comment]
It's after taking the "connected" channels from the channel map. It's up to you what you designate as "connected" channels, but this usually comes with your probe configuration. 

There won't be large differences if you don't have much drift. However, the drift corrected file is high-pass filtered and channel-whitened, which will change the shapes of the waveforms a little (make them more spatially and temporally localized). 

I will add some of this information to the wiki, thanks for asking.

**Comment by LaurenzMuessig** [comment]
Thanks for your answer Marius. I have another quick question. Why is ops.fproc longer in terms of duration - is that to do with the batch size for clustering, i.e. some padding at end to make length(last batch) == batch size?

Cheers

**Comment by marius10p** [comment]
Yes.

**Comment by LaurenzMuessig** [comment]
Thanks
