### ISSUE TITLE
Error after batch preprocessing. 

### ISSUE THREAD

**Issue by AlexSonneborn** [MouseLand/Kilosort#268]
I am getting the error below after preprocessing. I am not using a Neuropixels probe, but a bundle of 32 randomly arranged wires. I am sure the issue is something stupid that I am missing but I can't figure it out. I should note that Kilosort2 worked perfectly for me. 

```
Time  22s. Finished preprocessing 275 batches. 
pitch is 1 um
Index in position 1 exceeds array bounds (must not exceed 63).

Error in getClosestChannels2 (line 15)
iC= isort(1:NchanClosest, :);

Error in standalone_detector (line 40)
[iC2, dist2] = getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp);

Error in datashift2 (line 31)
[st3, rez] = standalone_detector(rez, spkTh);

Error in main_kilosort (line 42)
rez = datashift2(rez, 1); % last input is for shifting data
```

**Comment by AlexSonneborn** [comment]
Okay, I just realized the issue was also raised and solved in the Insights tab [here](https://github.com/MouseLand/Kilosort/issues/255)

**Comment by linussun** [comment]
I think it's a bug as I get the same error using 32 channel raw data file. It has something to do with standalone_detector.m line 39 which multiplies NchanNear by 10, and then runs getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp); I don't know the function of getClosestChannels2 is supposed to do, but the sorted distance between channels (isort) is a 32x32 matrix. Line 15 of this function is: isort(1:NchanClosest, :); and NchanClosest is 100 in my case, which is a lot larger than the 32 row isort matrix.

Here's is details of the exception:
K>> ex.stack(1)
ans =  struct with fields:
    file: 'D:\OEP-localD\Kilosort2.5\mainLoop\getClosestChannels2.m'
    name: 'getClosestChannels2'
    line: 15

**Comment by linussun** [comment]
I am just working with 2.5 for the first time and don't understand algorithm yet. However, I was able to get past this bug by editing standalone_detector.m line 39 from:

`NchanNearUp =  10*NchanNear; %this is equal to 100 (which is okay for neuropixel probes with hundreds of channels, but for 32 channel arrays too long)`

to:

`NchanNearUp =  32; %This eliminated the error and allowed for spike sorting`

However, I wonder if the randomly arranged wires you are using would be less ideal for this version of KS(2.5) for drift mapping as opposed to linear arrays like the neuropixel or neuronexus linear arrays.

**Comment by AlexSonneborn** [comment]
This worked! Thanks, but now I ran into another issue. 
Channel-whitening matrix computed. 
```
Time   0s. Loading raw data and applying filters... 
Time  18s. Finished preprocessing 275 batches. 
pitch is 1 um
0.02 sec, 1 batches, 81 spikes 
3.98 sec, 101 batches, 14473 spikes 
6.88 sec, 201 batches, 22602 spikes 
9.02 sec, 275 batches, 26616 spikes 
Error using matlab.internal.math.interp1
Sample points must be unique and sorted in ascending order.

Error in interp1 (line 154)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in shift_batch_on_disk2 (line 14)
    shifts = interp1(ysamp, shifts, rez.yc, 'makima', 'extrap');
```
After debugging it is due to the fact that I have repeating values for the variables ysamp and shift, I have no idea why this happens though. 

shift = [-385,-385,-360,-360,-360,-360,-360,-360,-360]

ysamp = [2.500000000000000;7.500000000000000;12.500000000000000;17.500000000000000;22.500000000000000;22.500000000000000;27.500000000000000;32.500000000000000;37.500000000000000]
