### ISSUE TITLE
unwhitening of ops.fproc

### ISSUE THREAD

**Issue by LaurenzMuessig** [MouseLand/Kilosort#270]
Hi,

How do I unwhiten the data in ops.fproc? If I do ops.fproc * (rez.Wrot/200)^-1 (as indicated in the wiki), and then transform to uV, I don't get realistic values for my data. Am I missing something or am I doing something wrong? Any help is appreciated.

Cheers

Laurenz

**Comment by marius10p** [comment]
I think it's just ops.fproc * (rez.Wrot)^-1, since fproc has been rescaled to int16 values. Where in the wiki is this?

**Comment by LaurenzMuessig** [comment]
Hi Marius,

Thanks for the quick response. Sorry the '/200' isn't in the wiki, but I went though the pre-processing code and saw that Wrot is multiplied by 200 before the whitening step, so I thought this has to be factored in, too.

**Comment by LaurenzMuessig** [comment]
Apologies for all these questions, but I have another related one. If my datas is already highpass-filtered and CAR'd and I skip this step in the data pre-processing for kilosort 2.5, I should probably skip this step as well for the calculation of the whitening matrix, right?

Cheers

Laurenz
