### ISSUE TITLE
Drift correction error

### ISSUE THREAD

**Issue by shira-hadar** [MouseLand/Kilosort#271]
Hello,

I am trying to run Kilosort2.5 on a NeuroNexus probe which contains 32 channels.
If I set the parameter (in kilosort GUI) N blocks for registration to a number bigger than 0 I get the following error:
"Error preprocessing! Index in position 1 exceeds array bounds (must not exceed 31)."
(When I used Kilosort2 everything worked fine).

How can I use the drift correction properly?

Thank you in advance,
Shira

**Comment by cllantz** [comment]
I get this same, error and also used Kilosort2 with no issues. My probe contains 16 channels, so my error is "Error preprocessing! Index in position 1 exceeds array bounds (must not exceed 15)"

I also noticed that in the plot of the recording, my bottom 2 channels are completely flat, and do not show waveforms at all, they appeared fine in Kilosort2 and when I plot the raw data in MATLAB.

**Comment by marius10p** [comment]
I have not really tested it on 32 channels, but it's on my to do list.

**Comment by shira-hadar** [comment]
Thank you for the answer!
I’ll be happy to get a notification when you know it’s working correctly on 32 channels.
Thanks in advance,
Shira
