### ISSUE TITLE
saving to destination

### ISSUE THREAD

**Issue by stagkourakis** [MouseLand/Kilosort#272]
Hi Marius,

A minor bug; on a specific desktop, when I use KS2.0 everything runs smoothly, but KS2.5 gives an error at the very end of the spike sorting process: "Error writing to destination. Use the 'f' option to override." Any thoughts?

Best wishes,
Stefanos

**Comment by marius10p** [comment]
Hi Stephanos, exactly when does this happen? Send more of the error please.

**Comment by stagkourakis** [comment]
Of course! Does the following picture help?
![errorSavingKS2-5](https://user-images.githubusercontent.com/53228356/98573300-8ef1fa00-226b-11eb-803c-c93259813063.png)

**Comment by stagkourakis** [comment]
Hi again Marius. Here is an update to this issue:

KS2.5 generates and saves all output files to the output directory apart from the params.py file. By manually adjusting the contents of the params.py file, I can see that the spike sorting with KS2.5 was successful, and do the manual curation in phy without problems.

Overall it works, apart from this minor nuisance. Feel welcome to close this issue.

**Comment by marius10p** [comment]
Could you run in debug mode so we can see exactly what line it fails on? It is curious that it works differently between 2.0 and 2.5.

**Comment by stagkourakis** [comment]
Hi Marius!
The issue I reported here, did not occur again, and I don't think it was an issue generated by Kilosort. My understanding is that it occurred due to Administrator rights and because the KS output folder was READ ONLY. Sorry for the false alarm.

I will now close this issue, and thanks for your attention to this.
Stefanos
