### ISSUE TITLE
highpass filter in hardware and software

### ISSUE THREAD

**Issue by LaurenzMuessig** [MouseLand/Kilosort#276]
Hi,

I am analysing neuropixel data which has already been HP filtered in hardware (300Hz). One of the first pre-processing steps in KS is to apply a HP filter at 300Hz in software. Is this additional filter necessary for the whitening, etc to work properly or can I safely skip this step (or is kilosort assuming unfiltered wideband data as input)? Thanks a lot for any input.

**Comment by marius10p** [comment]
We always use the software filter and it's not easy to turn it off. The hardware filters are too "soft" to rely on.

**Comment by LaurenzMuessig** [comment]
HI Marius. Thanks for your response. FYI, I had run some test clustering with or without the highpass filter in kilosort and indeed the results are slightly 'better' including the filter. I get almost the same set of units in both cases but slightly better unit isolation when I use the HP filter. Cheers
