### ISSUE TITLE
Error with function interp1

### ISSUE THREAD

**Issue by AlexSonneborn** [MouseLand/Kilosort#277]
I keep getting the following error, I think it has something to do with my electrode geometry. I am just using 32 wires in a random bundle. 

```
Channel-whitening matrix computed.
Time   0s. Loading raw data and applying filters... 
Time  18s. Finished preprocessing 275 batches. 
pitch is 1 um
0.02 sec, 1 batches, 81 spikes 
3.98 sec, 101 batches, 14473 spikes 
6.88 sec, 201 batches, 22602 spikes 
9.02 sec, 275 batches, 26616 spikes 

Error using matlab.internal.math.interp1
Sample points must be unique and sorted in ascending order.

Error in interp1 (line 154)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in shift_batch_on_disk2 (line 14)
    shifts = interp1(ysamp, shifts, rez.yc, 'makima', 'extrap');
```

After debugging it is due to the fact that I have repeating values for the variables ysamp and shift that are not in ascending order, I have no idea why this happens though. Below are the variables

shift = [-385,-385,-360,-360,-360,-360,-360,-360,-360]

ysamp = [2.500000000000000;7.500000000000000;12.500000000000000;17.500000000000000;22.500000000000000;22.500000000000000;27.500000000000000;32.500000000000000;37.500000000000000]

**Comment by agbondy** [comment]
What are you telling kilosort the electrode geometry is? It's not totally surprising that a bundle of 32 wires would not work with kilosort 2.5 since the drift correction algorithm only works in one dimension, so is better suited to probes with a linear shank. You may want to try kilosort 2 instead which does not explicitly model the drift in the spatial way. https://github.com/MouseLand/Kilosort/releases/tag/v2.0

**Comment by AlexSonneborn** [comment]
@agbondy Well even when I set my geometry to a straight line it does not help. I have used Kilosort2 for about a year and it works fine, but I wanted to try out the new movement artifact subtraction on 2.5 as I think it would help clean up my data.

**Comment by AlexSonneborn** [comment]
I actually just figured it out, I had to set the field ops.nblocks to 0 (it is set to 5 by default) in main_kilosort.m

`ops.nblocks    = 0; % blocks for registration. 0 turns it off, 1 does rigid registration. Replaces "datashift" option.`
