### ISSUE TITLE
how many threads kilosort2 uses?

### ISSUE THREAD

**Issue by gmaggi** [MouseLand/Kilosort#278]
Hi,

I understand that kilosort2 uses a single GPU. But I wonder how many threads in that GPU kilosort uses?
If that can use multiple threads, should I have MATLAB Parallel Computing Toolbox? Like explained in: https://www.mathworks.com/solutions/gpu-computing.html 

Thanks!

**Comment by marius10p** [comment]
Yes, you need the parallel computing toolbox. We are hoping to release a free Python version soon, if you can wait another month or two.
