### ISSUE TITLE
Question regarding channel mapping and drift correction/sorting in KS2/2.5

### ISSUE THREAD

**Issue by Hankslab-ABG** [MouseLand/Kilosort#280]
Greetings,

We're recording from both banks 0 and 1 in a standard NPx probe using 384 channels in a freely moving rat model. For the drift correction or subsequent spike sorting, will there be issues if numerically adjacent channels correspond to electrode sites that are several mm apart? For example, if channel 1 is at y-coord of 3850 microns and channel 2 is at a y-coord of 10 microns, or does that not matter? Similarly, are there any issues you've encountered using non-standard channel map configurations? We're currently using one where our ROIs dictate an uneven distribution of channel densities: we're using every other electrode for electrodes 0-129, every electrode from 130 - 384, and every other electrode from 385-512. Will this present an issue with drift correction/sorting in either version of KS? If so, are there steps that might ameliorate those issues (e.g. setting the nblocks for registration to a value besides 5)?

Thanks,

-Adam

**Comment by marius10p** [comment]
I think everything should still work out of the box for the scenarios you described. Give it a shot, the drift plots and drift traces can be pretty convincing when it works (and when it doesn't).
