### ISSUE TITLE
Kilosort 2.5 upgrade: missed spikes

### ISSUE THREAD

**Issue by m-beau** [MouseLand/Kilosort#281]
Hi,

Before fully transitioning to Kilosort 2.5, I decided to make a few quick checks to make sure that everything works as expected, and I have made a few observations that I would like to share here. I compared the outcome of kilosort 2 and kilosort 2.5 with the same set of parameters (for those which are shared between the two versions) on the same dataset, and found out that **kilosort 2.5 yields more 'good' units, and that these contain significantly fewer spikes**:
![ks2_2 5_bis (1)](https://user-images.githubusercontent.com/25953361/99194236-1a8cee80-2776-11eb-861c-944ae2d6b896.png)
Importantly, the difference in spikes per unit cannot be explained by the difference in the number of good clusters - there is also a big difference in the total number of 'good' spikes found by the two runs (about ~100000 for ks2.5 versus ~300000 for ks2). This means that there are overall fewer spikes detected by kilosort 2.5, and that these get dealt in many more clusters.

**1) Evidence that ks2.5 finds more 'good' units**

There is a lot of post-template-subtraction-residuals misclustering, which pollutes clusters from the same neuron and prevents them to be merged together. This means that 87 real units could end up split into 120 clusters (for this dataset).

This is an issue that I know you are aware of given the optional step that you suggest to run in the main loop of kilosort (which refers to [this github issue](https://github.com/MouseLand/Kilosort/issues/29)), but I was not experiencing it in the past whereas this is very dramatic in ks2.5. These residuals are impossible to split easily, and I do not wish to use the overlapping-spikes-handling option as I am very interested in sub-millisecond correlations between cells in a close spatial range (which would be altered by removing spikes happening in a close spatiotemporal window).

Example below:
![Screenshot from 2020-11-14 00-47-35](https://user-images.githubusercontent.com/25953361/99194254-385a5380-2776-11eb-90e3-9efb8e2e798c.png)

**2) Evidence that ks2.5 misses spikes**

The scatter plot observation is confirmed by visual inspection of the dataset, where visually obvious spikes seem to be missed:
- case where no spikes at all were found by ks2.5 but were found by ks 2 (grey events, the colors come from other clusters above or below the screenshot):
![Screenshot from 2020-11-14 00-32-17](https://user-images.githubusercontent.com/25953361/99194276-50ca6e00-2776-11eb-9c5b-4ad0e49dbd21.png)
- case where 100000 spikes were found by ks2.5 but 600000 were found by ks2:
-> ks2.5: 161998 spikes found (all the grey events should be clustered together with the blue events - they were not clustered in any other unit and this is after manual curation to the best of my ability)
![Screenshot from 2020-11-14 00-07-20](https://user-images.githubusercontent.com/25953361/99194300-7eafb280-2776-11eb-8663-033a915dae77.png)
-> ks2 (at a different point in time but this is the same channel and it makes the point): 688106 spikes found, after manual curation as well
![Screenshot from 2020-11-15 17-01-56](https://user-images.githubusercontent.com/25953361/99194293-70fa2d00-2776-11eb-9ec2-954b483668df.png)

Do you think that this drastic difference has anything to do with the new drift-correction approach, by some other difference between kilosort 2 and 2.5, or that I am doing anything wrong? You can find the kilosort parameters that I used attached below. I used the master branch version after commit ddf63e4bb9781ebfe424e2777563fed5ac3e174b (downloaded the 29th of October, after public release).

[Kilosort 2 parameters](https://drive.google.com/file/d/1l1RaNsHNKJAGdcKhDO4aUzjFuK73Tidp/view?usp=sharing)
[Kilosort 2.5 parameters](https://drive.google.com/file/d/1I_K-cbLvFlk17v-E4qyreczQnKUi117Z/view?usp=sharing)

Best,
Maxime

**Comment by m-beau** [comment]
New idea: could it be that the residuals are considered like drifted waveforms and hence co-clustered with proper waveforms?

**Comment by marius10p** [comment]
It looks like you changed a few of the default settings in Kilosort 2.5. In particular, fshigh should be 300 and that will make a big difference. minFR should be 0, but I don't think that makes a difference. Please try running with the supplied config384 file, and let us know how that changes things.

**Comment by m-beau** [comment]
2 comments:
1) This is a Neuropixels 1.0 recording which is already pre-filtered at 300Hz
2) I used 150kHz for kilosort 2 as well, so it should not account for the difference between the two datasets, except if the new drift-tracking pipeline is particularly sensitive to the filter cutoff frequency

Thanks for the feedback, I will run it once more using 300Hz and come back to you

Maxime

**Comment by m-beau** [comment]
Hi,

I ran it again (as well as with a different second pass threshold another time, Th=[10 4]), and here is the result:
![ks2-2 5](https://user-images.githubusercontent.com/25953361/100262780-8a546380-2f44-11eb-9484-36e1c3b9a317.png)

**Comment by sachira-denagamage** [comment]
We have been running into these same issues as well. KS2.5 consistently has more units labelled as "good" but with considerably fewer spikes per cluster. As the other user mentioned, when looking at individual channel traces, we also see that KS2.5 will often miss very obvious spikes. In one particular session, KS2 detected ~2.5 million spikes while KS2.5 detected only ~1.0 million spikes, while finding twice as many "good" units. These were both run with the recommended settings from config 384.
