### ISSUE TITLE
Kilosort 2.5: Support for neuroshare file format?

### ISSUE THREAD

**Issue by vatsunlab** [MouseLand/Kilosort#282]
Thank you for this spike sorter! Do you support the .ns5 file format that is used by Blackrock and Ripple neural data acquisition systems? Alternatively, is there an easy way to convert these files into a *.bin or other format that Kilosort 2.5 can read? Thanks so much for your help!

**Comment by marius10p** [comment]
Others may have made such converters, but if you know how to get your data out of the proprietary ns5 format, then it should be straightforward to convert to a flat int16 binary file.

**Comment by chris-angeloni** [comment]
This may complicate your pipeline a bit, but it looks like spike interface has support for Blackrock recordings: https://spikeinterface.readthedocs.io/en/latest/supported.html
