### ISSUE TITLE
Error preprocessing, Reference to non-existent field "sig"

### ISSUE THREAD

**Issue by Hankslab-ABG** [MouseLand/Kilosort#283]
Greetings,

We recently started using KS 2.5 and had good sorts for the first couple of weeks of use, but now we're getting an error right as the drift map comes up stating "Error preprocessing, Reference to non-existent field "sig"". I looked in ops and sure enough there's no 'sig' value for the gaussian process smoothing used for registration within datashift2.

We first noticed this when we were messing around with some new configuration files, but now we're starting to see the error come up even when we use our older config files that previously worked just fine. Is it possible that this is due to something new in our recordings?

Thanks,

-Adam

**Comment by Hankslab-ABG** [comment]
Quick update: So if I manually enter the value for sig before preprocessing (ks.ops.sig=20), it runs just fine. However I still can't figure out why KS 2.5 can sometimes find that default value on its own and why at other times I need to provide it. Is this a parameter that should load a default or is this something we need to enter in a config file?

**Comment by Hankslab-ABG** [comment]
Figured this out: KS 2.5 was looking at the configFile384.m from the KS2 directory, which contains no value for ops.sig.

**Comment by neurvanna** [comment]
I have the same issue. Can't figure out where it addresses the KS2 directory...

**Comment by Hankslab-ABG** [comment]
It's in configFile384.m. The KS2 version has no value specified for ops.sig. The configFile384.m version for KS2.5 does. I just removed the path for the KS2 directory and that did the trick. You can also check the ops parameters when you load KS2.5 by clicking "set advanced options" and following the instructions.

**Comment by neurvanna** [comment]
Thank you! Yes, I understood from you previous comment that it's in that file but I don't have KS2 in my path so not sure how it gets the wrong config. Anyways, I am trying your suggestion with the advanced options now. Thanks a lot!

**Comment by Hankslab-ABG** [comment]
Are you saving channel map/config files to the old directory? That was my initial mistake: I was using KS2.5 but was saving all of my channel maps to the old configFiles directory from KS2. Another option is to change the filename of that file in the old path so it can't be called.

**Comment by neurvanna** [comment]
I did that as well! My old configFile384.m is now called  configFile384_old.m, and yet somehow when I open ksGui, it manages to get the wrong parameters O_O

**Comment by neurvanna** [comment]
Alright it was my bad - resetting the GUI solved it, and now when I select a new dataset the configFile384 is correct.
