### ISSUE TITLE
standalone_detector errors related to data sets with only a few channels

### ISSUE THREAD

**Issue by nmtimme** [MouseLand/Kilosort#285]
Hello

I'm running into multiple different size errors in datashift2. All of my data sets have between 4 and 32 channels. There doesn't appear to be a clear relationship between the type of error and the number of channels in the data set, at least in terms of the number of channels fed into Kilosort. Perhaps after some automated channel rejections in datashift2 or before, the number is dropping below some threshold. If this is happening, it would be nice if Kilosort errored with a clear report of the problem (e.g., too few channels). Here are the errors I've received for different data sets:

Error 1:

Index in position 2 exceeds array bounds (must not exceed 5).

Error in extractTemplatesfromSnippets (line 72)
wPCA = gpuArray(single(U(:, 1:nPCs))); % take as many as needed

Error in standalone_detector (line 21)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in datashift2 (line 30)
[st3, rez] = standalone_detector(rez, spkTh);

Error in stage2Core (line 417)
        rez = datashift2(rez, 1); % last input is for shifting data

Error 2:

Error using .*
Matrix dimensions must agree.

Error in standalone_detector (line 74)
    yct = sum(cF0 .* ys(:, iChan), 1);

Error in datashift2 (line 30)
[st3, rez] = standalone_detector(rez, spkTh);

Error in stage2Core (line 417)
        rez = datashift2(rez, 1); % last input is for shifting data

Here is what I've done to try to correct these errors. First, I tried to fix error 1 by changing line 72 of extractTemplatesfromSnippets from:

wPCA = gpuArray(single(U(:, 1:nPCs)));

to 

wPCA = gpuArray(single(U(:, 1:min([size(U,2),nPCs]))));

This change removed error 1, but now causes error 2.

To resolve error 2, I changed line 27 of standalone_detector from:

NchanNear = 10;

to 

NchanNear = min([10,length(rez.yc)]);

This change may render the change I discussed in issue #255 unnecessary, but it does appear that the change I discussed in issue #257 is still necessary. Other users appeared to have similar errors in issue #268.

**Comment by marius10p** [comment]
I will have to find some time to test it with 32 sites. It works with 64 (the eMouse simulation).

**Comment by epakr** [comment]
Is there any update on this issue?
Using 32 (4x 8) probe having the same issue

**Comment by czuba** [comment]
@nmtimme @epakr 
I fixed this by capping the value of `NchanNearUp` (line 39) in `preProcess/standalone_detector.m`

See [this commit](https://github.com/czuba/Kilosort/commit/a22c4bf4307983064c08d4ed2518c3ea408e0e92) in my fork

**Comment by czuba** [comment]
@marius10p  Same error in standalone_detector.m persists in Kilosort 3.0
Cannot scale NchanNear by 10 without constraint to remain <= .NchanTot

**standalone_detector.m  (line 38)**
``` matlab
% number of nearby templates to compare for local template maximum
NchanNearUp =  min([10*NchanNear, ops.NchanTot]);
```

**Comment by marius10p** [comment]
Can you submit a pull request please? Was there anything else you had to change?

**Comment by czuba** [comment]
Yep, there was another 10*NchanNear in extract_spikes.m.

Also crashing in final_clustering.m due to what looks like a missing gather in the `else` fork of svdecon.m
 - returned `U` is still a 'gpuArray', not a 'single') 

...finishing up as part of a pull request as soon as it stops erroring out

**Comment by marius10p** [comment]
Great, thanks! I think the "gather" thing is Matlab version dependent. Let me know if you still get that weird issue with the waveform shape changing erratically (you shouldn't!).

**Comment by czuba** [comment]
**Pull request** with `NchanNear` fixes submitted!

**Comment by ghpetty** [comment]
I had the same issue using a 64 channel linear probe. I was able to fix it by czuba's fork of kilosort3.
