### ISSUE TITLE
Re-create analysis images

### ISSUE THREAD

**Issue by Idavr** [MouseLand/Kilosort#291]
I've tried finding the answer to this question reading around without success so I hope any of you can help me with a quick question: How do I re-create/pull back up the pop-up images that were made during analysis with KS2.5, specifically the drift map?

**Comment by rajatsaxena** [comment]
I have used this in the past: https://github.com/cortex-lab/neuropixels/wiki/Other_analysis_methods

the script mentioned in the link above might have to be modified for your specific probe geometry

**Comment by Idavr** [comment]
I have used this one as well, but I noticed that it is less granular than the one that originally pops up during KS2.5 analysis, specifically the KS2.5 analysis better shows whether there is some (if small) spikes by the grey coloured dots, and complete absence (close to, at least) with white, but if using this above method what would have been light grey in the original pop up is completely white instead. This is why I was hoping to fetch back the original.

**Comment by frikyng** [comment]
just commenting for the notifications + as a reminder that this is still open. Cheers
