### ISSUE TITLE
Cluster amplitude is missing … 

### ISSUE THREAD

**Issue by rivlinoa** [MouseLand/Kilosort#292]
I am trying Kilosort2.5 on Neuropixels1.0 data (used Kilosort2 up till now). I don’t know if my question addresses a change from Kilosort2 to kilosort2.5 or am I doing something wrong in the installation or usage. 
When I try to go over the sorting results in Phy I cannot see clusters amplitude in the clusters view. I find the amplitude a useful metric for throwing noise clusters, which are usually of low amplitude. If I look at the files in the folder, there is no ‘cluster_Amplitude.tsv’ that used to be there for Kilosort2, and in ‘cluster_info.tsv’ there is no column for cluster amplitude like I used to have before. Moreover, there is no ‘cluster_KSlabel.tsv’ file, whereas ‘cluster_group’ contained KS labels overwritten by my manual labels in Phy … 
If I am missing something, I would be happy to get any advice. 
If those parameters are indeed missing from Kilosort2.5 would you consider adding them again? 
Thank you very much!
Noa

**Comment by rajatsaxena** [comment]
I have run the recent version, and it saves the `cluster_Amplitude.tsv` and `cluster_KSlabel.tsv` as well as the amplitude in the info file. Are you sure that you have the most recent version?

Another possibility is that there was an error in the `rezToPhy.m` script while saving the output, and you missed that?
