### ISSUE TITLE
individual channels in KS 1.0

### ISSUE THREAD

**Issue by alpeq** [MouseLand/Kilosort#293]
We want to sort data from individual channels. Looking at the config files and your suggestions in [this issue](https://github.com/cortex-lab/KiloSort/issues/125) I modify the channelMap to set kcoords to be a different integer for each channel. 

Comparing the sorting with kcoords all ones the algorithm does not change the clusters. 
Is this option (individual channels) available for kilosort version 1? Unfortunately we don't have available a gpu right now.
There are other big changes in KS1 respect the KS2.5 aside of the drift correction ? 

Thanks.

**Comment by marius10p** [comment]
Kilosort 1 is no longer supported, sorry, and this is not the right repository to post for it. You can find cheap GPUs fairly easy these days, even something older like 1060 would work fine for smaller numbers of channels.
