### ISSUE TITLE
Kilosort default channelmap

### ISSUE THREAD

**Issue by bruno-f-cruz** [MouseLand/Kilosort#294]
Hi everyone,

I am a bit confused regarding the default channelmaps included in the current version of kilosort.
From the spikeGLX website, NPX1.0 = 3B2 version: "Neuropixels 1.0 probes (also called phase3B2)."
Additionally, if I am not mistaken, all these probes have a staggered pattern on each column, as a result, I would expect 4 unique values in channelmap.xcoords.

Loading the 3B1 and 3B2 channelmaps i get the following:
unique(ChMap3B1.xcoords) =     11    27    43    59
unique(ChMap3B2.xcoords) =     11    43   

It seems that the 3B1 is the staggered version.

Although I am fairly certain that I should be using the 3B1 channelmap I wanted to make sure I am not missing something obvious.

Thanks,
Bruno

**Comment by marius10p** [comment]
@nsteinme
