### ISSUE TITLE
Nvidia Geforce 3080

### ISSUE THREAD

**Issue by jonjwilson89** [MouseLand/Kilosort#295]
Hi,

We recently upgraded our GPU to a geforce 3080 but are having some trouble with the preprocessing step - it's coming up with a CUBLAS error. Is it known whether kilosort 2 works with the new architecture of the 3080?

Cheers,

Jon

**Comment by marius10p** [comment]
Wow, if I could get my hands on one, I'll be happy to test it. Probably a lack of Matlab/CUDA support at this point.

**Comment by jonjwilson89** [comment]
Thanks Marius. If only we had a spare for you to give it a whirl.

I'll see where I can get and if I find a solution I'll post it back up on here. Cheers, Jon

**Comment by nikolaskaralis** [comment]
I guess this is related to [this](https://ch.mathworks.com/matlabcentral/answers/592198-does-matlab-support-nvidia-ampere-cards-for-gpu-computation) issue.

I would be interested to know if you get it to work, since I am considering an upgrade.

Cheers,
Nikolas

**Comment by jonjwilson89** [comment]
I seem to have got it to work using the pre-release of MATLAB 2021 and VisualStudio2019 - so definitely an issue of support in earlier MATLAB versions. 

Jon

**Comment by marius10p** [comment]
Just got a 3090! What CUDA version did you use?

**Comment by WeissShahaf** [comment]
@jonjwilson89. which cuda version / VS worked best?
