### ISSUE TITLE
incorrect waveform view using the drift corrected file in phy

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/Kilosort#297]
I am using kilosort2.5 to sort my dataset. When I load the dataset using phy, the `mean waveforms` in the `waveform view` looks messed up for a majority of units even though the `templates `in the `waveform view` look normal. This issue gets fixed once I change params.py to point to raw binary file rather than the drift corrected file. 

![Capture](https://user-images.githubusercontent.com/5181888/102849773-b7bdf100-43cc-11eb-97fc-4e22aaa1bb94.PNG)

**Comment by marius10p** [comment]
Can you try it now? There was an issue when ops.trange(1) > 0.

**Comment by rajatsaxena** [comment]
the waveform view looks good now. Thanks!
