### ISSUE TITLE
Kilosort sees more channels than in the data file

### ISSUE THREAD

**Issue by lachioma** [MouseLand/Kilosort#298]
I recorded some experiments using Open Ephys and Neuropixels, saving only 128 channels instead of the total 384.
When opening the data file with Kilosort, Kilosort somehow sees 384 channels and is even able to plot traces for each of the 384 channels, including channels that do not exist in the data file.
After spike sorting, Phy2 shows waveforms from channels that were not saved at all in the original Open Ephys data file.

I tried to change the number of channels from 384 to 128 in the Kilosort GUI, but it does not do anything and the value is reset to 384.
Am I doing something wrong? Shall I create a configFile ad hoc, to deal with fewer channels than 384?

Thank you!

**Comment by marius10p** [comment]
If you are only saving 128 channels to file, then you need a new configuration file for this data. You can do this by subsampling a Neuropixels config to just the 128 channels you recorded.

**Comment by lachioma** [comment]
Thanks Marius. I then figured that you need to change the config file.
