### ISSUE TITLE
Cluster ID change in cluster_KSLabel

### ISSUE THREAD

**Issue by nef2** [MouseLand/Kilosort#299]
Before manually sorting in Anaconda = the cluster_KSLabel file is reading 0-20 for cluster IDs, but once opening Anaconda the cluster IDs are starting from 2 and going to 20 - after manually sorting the cluster_KSLabel file is updating to this new cluster ID which is incorrect

**Comment by marius10p** [comment]
Some cluster ids can drop out due to merges. Then the cluster IDs change in Phy if you are doing any manual curation where you merge and split neurons. This is intended behavior.
