### ISSUE TITLE
out of memory issue

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/Kilosort#300]
I am using 128channel UCLA silicon probes to record for ~5hours, and the final output binary file is of the order of 140GB. I am running into memory issues. I have 64GB RAM and 8GB GPU. Here is the error output:

```
9471.83 sec, 5401 / 8421 batches, 154 units, nspks: 7777541.0000, mu: 17.1072, nst0: 2342 
9498.16 sec, 5501 / 8421 batches, 154 units, nspks: 7872951.0000, mu: 17.1072, nst0: 7256 
Out of memory. Type HELP MEMORY for your options.

Error in trackAndSort (line 185)
        fWpc(:,:,2*size(st3,1)) = 0;

Error in runTemplates (line 34)
[rez, st3, fW,fWpc] = trackAndSort(rez, iorder);

Error in learnAndSolve8b (line 39)
rez         = runTemplates(rez);

Error in main_kilosort_VR8_fullRecording (line 46)
rez = learnAndSolve8b(rez, iseed)
```

**Comment by marius10p** [comment]
We normally don't have problems with recordings of up to 30 mil spikes and with less RAM. Can you monitor your RAM useage to see where it's going? Are you on a Linux machine?

**Comment by rajatsaxena** [comment]
this got resolved in ks3
