### ISSUE TITLE
Running a shared installation?

### ISSUE THREAD

**Issue by ifittakesallnight** [MouseLand/Kilosort#303]
We installed Kilosort on a GPU-equipped many-core large-RAM-capacity linux server. The Kilosort GUI has to be able to write to the Kilosort/gui directory. We could of course make this directory write-able by all users as there's only one GPU installed and only one user would use it at a time. But given that the GUI seems to write the location of the previously opened file, cutoff values, number of channels, etc, this might still cause problems in a shared install scenario. Is there an option so that Kilosort saves these to the user's home directory rather than the Kilosort/gui directory? Or do you just recommend that each user install Kilosort for themselves?

**Comment by nsteinme** [comment]
I guess the easiest thing is just for each user to have an individual
"installation" (where this of course just means an individual copy of the
code). Sorry that I didn't write it with that scenario in mind, you're
right that the home directory would have made more sense, but given the
easy workaround I'd prefer not to modify this behavior now.
