### ISSUE TITLE
Similarity matrix

### ISSUE THREAD

**Issue by Dradeliomecus** [MouseLand/Kilosort#304]
Hi,

I'm using `Kilosort` on my datasets, which I visualize with `Phy`. I really like how the similarity matrix is computed, and it really helps with my work!

After Kilosort, I modify a bit the phy output to work out some things, which means I need to recompute stuff (like PCA, amplitudes ... and similarity matrix), and I would like to implement it a similar way to what Kilosort does as it is very good.

I took a look at `mainLoop/getMeWtW.m`, but I don't understand what `W` and `U0` mean or stand for.

Is it allowed for me to use the same idea for computing the similarity matrix?
If yes, can you explain what those variables are and how it works?

Thank you!

**Comment by Dradeliomecus** [comment]
After looking for a while, I understood that `W` and `U` are the result of a three-dimensional SVD on `K` (mean waveform of a cluster).
But in the code, how `W` and `U` are made is pretty complicated.

How can I simply recreate `W` and `U` when I have all of the spike times of all my units, in order to compute the similarity matrix between them?

Thanks

**Comment by marius10p** [comment]
Not sure what you need, but I think the similarity matrix gets exported to Phy, so it should be available there. It is one of the .npy output files.

**Comment by Dradeliomecus** [comment]
What I am doing is merging multiple Kilosort output (done on the ame dataset but with different parameters).
In my use case, I found that it yields more good units.

But then I have units that were found in different Kilosort output, and thus I do not have the similarity between them.
What I wanted was to calculate this similarity the same way Kilosort does, given the spike times / mean waveform.

**Comment by marius10p** [comment]
That doesn't seem like the right thing to do. You'll have the same units extracted with slightly different mistakes every time. Why don't you give Kilosort3 a try? It should produce more units in a more stable fashion.

**Comment by Dradeliomecus** [comment]
I'm doing recordings on the cerebellar cortex, and from my testing, CS (complex spikes) need a seperate analysis because they are very low-frequency, very sparse, and can sometimes have very similar waveforms. Doing a seperate analysis with a 150-1500 Hz filtering seems to extract them way better, but I don't find "normal" spikes anymore since the low-pass filter is very low.

Additionally, I found that units with low SNR are not found unless I decrease `Th` from `[10, 4]` to `[8, 3]`. But in doing that, the units with good SNR are more contaminated usually.
Hence, I do both analysis, and merge them by either keeping one of the two units, or both (using a custom scoring method).

I compared this method with doing only one of the analysis, and (in my case at least), I found out that I had more good units, and with lower contamination.

I would love to give Kilosort3 a try, unfortunately I do not use Matlab and I am working with the `pykilosort` version (which I know isn't 100% done, but works really well for my use case).

**Comment by marius10p** [comment]
Oh, this issue is the wrong repository then... We'll upgrade the python version as well.

**Comment by Dradeliomecus** [comment]
I know this is `Kilosort` ans not `pykilosort`, but my question had to do with the similarity matrix, which is calculated the same way in both versions (at least when it was 2.5).

Is there no way to re-compute the similarity after spike-sorting?

**Comment by marius10p** [comment]
You can track it down in the code, it only needs W, U and mu.

**Comment by Dradeliomecus** [comment]
I did track it down, but I don't know how to re-make `W` and `U` as they seem to be updated in a lot of different functions.

Is there a way to approximate them efficiently?

**Comment by marius10p** [comment]
They are just the low rank decomposition of the templates, and they should be available in the final output.

**Comment by Dradeliomecus** [comment]
Ah ok thank you very much!
