### ISSUE TITLE
MUA activity

### ISSUE THREAD

**Issue by jofrony** [MouseLand/Kilosort#306]
Hi,

I have some issues with the manual curation following Kilosort. 

A lot of the recordings had MUA activity for 70-80% of the spike shapes. Although I looked at them and I would consider them individual spikes. 

I preprossed the recordings by applying CAR and double-checked the probe mapping so these cannot be the reason.

Are there specific parameters within the algorithm which I could modify or is it the length of the recording (usually 1 hr) which could the issue? 

Thank you,

Johanna

**Comment by marius10p** [comment]
Hi Johanna, the MUA label which Kilosort assigns are primarily based on the auto-correlogram. If you don't have a clean refractory period, then it can't be a single unit, and that's what Kilosort calculates in its contamination score. You can reduce the threshold on contamination to be less stringent, or you can use MUA of large amplitude units if you don't mind units that have 2 or more neurons mixed.

**Comment by jofrony** [comment]
Hi,

Thank you for the response. I was looking into the config-files, but I could not find the specific parameter for changing the contamination score. Is it possibly the ops.criterionNoiseChannels?

Best Regards,

Johanna

**Comment by marius10p** [comment]
No, the contamination score is an output of Kilosort, so you can find it in the "rez" structure. If you are using Phy for visualizing the results, then you can change "rez.good"  based on a different thresholding of the contamination score.

**Comment by jofrony** [comment]
Okay, thank you!

//Johanna
