### ISSUE TITLE
Missing "spikedetector3PC" in KS3

### ISSUE THREAD

**Issue by bruno-f-cruz** [MouseLand/Kilosort#308]
Hi,

First of all congrats on the new release!
I am starting to sort a new dataset and I wanted to compare the output of 2.5 with the new 3.0.
Unfortunately, after trying to run KS3 I keep getting the following error:

```
Undefined function or variable 'spikedetector3PC'.

Error in extract_spikes (line 66)
        spikedetector3PC(Params, dataRAW, wTEMP, iC-1, dist, v2, iC2-1, dist2, wPCA); 
```

Any chance this was left out of the commit? I believe it is a new mexcuda function

Thanks,
B

**Comment by marius10p** [comment]
Oops, let's find it.

**Comment by marius10p** [comment]
Should be working now, sorry about that.

**Comment by bruno-f-cruz** [comment]
Awesome it is working now! 

I have encountered a few more crashes that I will list here. However, if it makes your life easier, close this issue and let me know if I should open individual issues ;)

1. When running "template_learning",
in the line 102: rez.W(:,t,:) = wsign * w(:,1:3);

```
The following error occurred converting from gpuArray to single:
Conversion to single from gpuArray is not possible. 
```
I got around it by using "gather()" but I am not sure if this is the intended fix  =/

    rez.W(:,t,:) = gather(wsign * w(:,1:3)); 
    rez.U(:,t,:) = gather(wsign * u(:,1:3) * s(1:3,1:3)); 

2. I believe there is another missing function, "check_clusters", that is called for the first time during "final_clustering()" (line 107) in the main script. At least I couldn't find it in the repo

Once again, thanks,

B

**Comment by marius10p** [comment]
I had the wrong folders in my path, sorry. Testing it end-to-end again now (I have pushed the fix).

**Comment by bruno-f-cruz** [comment]
Yep, after fixing another "gather" crash in 
`The following error occurred converting from gpuArray to single:
Conversion to single from gpuArray is not possible.
Error in final_clustering (line 118)
    rez.W(:,t,:) = wsign * w(:,1:3); `

I can confirm that it runs until the end and I can see spikes in Phy. 

Thanks a lot and sorry for the trouble ^^
