### ISSUE TITLE
Kilosort3_spikedetector3PC_undefined_function

### ISSUE THREAD

**Issue by aarac** [MouseLand/Kilosort#309]
Hi,
Thanks for the Kilosort3.

I installed and tried to run it. Preprocessing worked well, but in Spikesorting, this error came up:
<img width="1094" alt="screenshot1" src="https://user-images.githubusercontent.com/28713580/106386882-f2338a00-638b-11eb-9ad3-ad621a7d7e6e.png">

Then, I found where this function is used but then it said this file does not exist.
<img width="971" alt="screenshot2" src="https://user-images.githubusercontent.com/28713580/106386907-14c5a300-638c-11eb-81cd-917791b2a86b.png">
<img width="712" alt="screenshot4" src="https://user-images.githubusercontent.com/28713580/106386998-8a317380-638c-11eb-973f-5c247fabdb5e.png">

Could you please help with this?
Thanks!

**Comment by marius10p** [comment]
Sorry, this was just fixed, please update the repository.

**Comment by aarac** [comment]
Thanks Marius. Works well now.
