### ISSUE TITLE
Preprocessing error

### ISSUE THREAD

**Issue by SusanL82** [MouseLand/Kilosort#310]
Hello, 

I am trying to sort spikes from my Neuralynx recordings (64 channels, 16 tetrodes) with Kilosort2.5, but I'm running into an error during/after preprocessing: "Error preprocessing! Index in position 1 exceeds array bounds (must not exceed 31)"

Is this possibly because I formatted my input files incorrectly? I have not changed any of the standard settings yet (other than making a 16x4 channel map for my 64 traces). 
I recorded my data as .ncs files (one file per channel), that I then imported into matlab with the function provided by Neuralynx (from here: https://neuralynx.com/software/category/matlab-netcom-utilities). 
Because my files are too large (about 3.5 hours recorded at 20kHz), I cannot build a single matrix with all data and write that to a .dat file. Instead, I read each .ncs file separately and use the append option in fwrite to add them to my .dat file.

It looks like Kilosort is reading the .dat file correctly (I get a recording with 64 traces that seems to be the correct length in seconds), but I'm also a kilosort newbie so it is very possible I messed something up. 
I get the same error when I use a .dat file that only has 16 of my channels in it. 
Any ideas?

**Comment by marius10p** [comment]
Hi Susan, did you check it out in the Kilosort GUI? That's the easiest way to check if the data is read incorrectly. In this case, you wrote the channels sequentially in the data file, but they should be intermingled: ch1 t1, ch2 t1, ch3 t1, .... , ch1 t2, ch2 t2,... You will need to do a loop and portions of all channels into memory at the same time. 

I don't think this would explain your error, but I would need more information about where it breaks (in debug mode). Make sure your channel map is flatten 64 by 1, similar to the examples, and that the xcoords and ycoords are accurate.

**Comment by SusanL82** [comment]
Thanks for your reply, I'm changing the way I write the .dat files and that seems to have helped (and I removed my accidental timestamp trace). I have now loaded a section of each trace into a matrix (one row per channel) and wrote that to a .dat file. 
The displayed traces in the GUI also look much more like my original recording now. 
I'm just having some trouble adding all these sections to the .dat file, because it seems to append vertically (so I get (Nsection x Nchan) x Nsamp, and not a big Nchan x Nsamp file). Is it possible to somehow work with a Nsamp X Nchan .dat file instead?

**Comment by marius10p** [comment]
You need to append Nchan x Nsection matrices to the binary files. If you matrix is the other way, you need to transpose it before you write it to the dat. If it still doesn't work, post a little code snippet here and I can help.

**Comment by SusanL82** [comment]
I tried to make my .dat files again and the preprocessing seems to work now. At least, I get no more errors when run preprocessing from the GUI and it's even telling me that there are spikes (yay! progress!)
I am getting a different error when I then try spike sort (Error running kilosort! Subscript indices must either be real positive integers or logicals). But I need to check if I have any very wrong settings. I didn't change anything except probe layout, sampling rate and number of channels.

```
Channel-whitening matrix computed. 
Time   6s. Loading raw data and applying filters... 
Time 169s. Finished preprocessing 1365 batches. 
pitch is 1 um
    14

0.13 sec, 1 batches, 206 spikes 
11.61 sec, 101 batches, 13715 spikes 
22.58 sec, 201 batches, 29062 spikes 
33.52 sec, 301 batches, 41985 spikes 
44.27 sec, 401 batches, 59180 spikes 
54.87 sec, 501 batches, 80132 spikes 
65.45 sec, 601 batches, 99160 spikes 
75.89 sec, 701 batches, 121036 spikes 
86.49 sec, 801 batches, 141998 spikes 
97.28 sec, 901 batches, 165613 spikes 
108.06 sec, 1001 batches, 188193 spikes 
118.88 sec, 1101 batches, 214218 spikes 
129.66 sec, 1201 batches, 233021 spikes 
140.43 sec, 1301 batches, 252013 spikes 
147.26 sec, 1365 batches, 266199 spikes 
time 298.25, Shifted up/down 1365 batches. 
vertical pitch size is 1 
horizontal pitch size is 0 
     1
```

**Comment by marius10p** [comment]
You need to change the site coordinates in um,  xcoords and ycoords in your configuration file. This can also be created via the GUI and saved for future use. The pitch size should be inferred to be the vertical distance between electrodes on your probe (typically tens of um).

**Comment by SusanL82** [comment]
I've made a new channel map with channels from 1 tetrode spaced 10um apart and the tetrodes 390um apart in a grid that matches our implanted bundle and this solved the error listed above. And it works now! 
There's probably still a bit of tweaking I can do, but it's off to a good start. Thanks so much for your help!

**Comment by dmkobylkov** [comment]
Hi @SusanL82 ,

I suppose I have a very similar issue, but with Plexon data. I am trying to convert them to a .dat file, but kilosort gives me an error `Index in position 2 exceeds array bounds. Index must not exceed 3.`. Could you, please, share a code for data transfer and channels mapping that worked for you? It would be really great....
