### ISSUE TITLE
unable to save to phy

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#314]
in two different PCs, kilosort3 runs but then:
"Error saving data to phy! invalid file identifier. Use fopen to generate a vild file identifier"

**Comment by Kasia-Bz** [comment]
I have the same issue, I change the path in the: main_kilosort3.m file, but I still have the error of saving data to phy.

**Comment by marius10p** [comment]
There was a problem running it through the GUI that I just fixed, try it out please. Do you also have a problem running it from the script?

**Comment by Kasia-Bz** [comment]
It works now! thank you :)

**Comment by WeissShahaf** [comment]
works again!

btw, is there a way to save the drift plots?

**Comment by marius10p** [comment]
No, but it's a good idea to save them automatically, I'll add that.
