### ISSUE TITLE
Error running datashift2 during preprocessing

### ISSUE THREAD

**Issue by yves-weissenberger** [MouseLand/Kilosort#318]
Hi,

I was trying out kilosort3 and am running into the following error during preprocessing:
      
      
      obj.rez = datashift2(obj.rez, 1);
      pitch is 1.250000e+01 um
          27
      
            Index in position 1 exceeds array bounds (must not exceed 84).
            
            Error in getClosestChannels2 (line 15)
            iC= isort(1:NchanClosest, :);
            
            Error in standalone_detector (line 40)
            [iC2, dist2] = getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp);
            
            Error in datashift2 (line 40)
            [st3, rez] = standalone_detector(rez, spkTh);
       
I have previously used kilosort2.5 to sort this data without errors and have not made any changes to the probe layout configuration or changed from any default params. Any help would be much appreciated :]

**Comment by marius10p** [comment]
How many channels do you have? I know about the limitation for small numbers of channels, and I'll fix it, but I am surprised you ran fine on Kilosort 2.5, since that particular function (standalone_detector) shouldn't have changed at all.

**Comment by yves-weissenberger** [comment]
64 channels.

**Comment by marius10p** [comment]
Try it now, it should work...

**Comment by yves-weissenberger** [comment]
Hey,  the preprocessing runs through fine but I get the same error as soon as I try to spikesort. I can have a look at exactly where its going wrong if that would be helpful

**Comment by marius10p** [comment]
Can you please post the full error? It should be at least a little different if it's during the "spikesort" step.

**Comment by yves-weissenberger** [comment]
Hi,

sorry this seems to have been a mistake on my end. There seems to have been a corruption issue with the file I had tried it on. I've run it on two others and it seems to be working perfectly. Thanks a lot!
