### ISSUE TITLE
out of memory error in run_pursuit in kilosort3

### ISSUE THREAD

**Issue by rajatsaxena** [MouseLand/Kilosort#319]
Ran into a new out of memory error. Here is the trace:

```
578.30 sec, 4401 batches, 5710465 spikes 
591.40 sec, 4501 batches, 5770613 spikes 
600.97 sec, 4574 batches, 5809551 spikes 
time 0.00, GROUP 1/12, units 0 
Error using  * 
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.

Error in bimodal_pursuit (line 12)
clp = clp * u; % * s(ipc, ipc);

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin, use_CCG);

Error in template_learning (line 82)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in main_kilosort3_swil3 (line 42)
rez                = template_learning(rez, tF, st3);
```

I have ~2hour 40minutes of recording using UCLA 128ch silicon probe. GPU = Nvidia GeForce 1070i. I am going to dig deeper into the problem later tomorrow to capture what might be causing it.

I ran a smaller segment of data ~1 hour with the output spikes definitely looking much cleaner compared to kilosort2. Although, the feature view is not functional cause of missing pc_features files. rez.cProj = [] in the rez structure

**Comment by marius10p** [comment]
What is your Matlab version? It shouldn't run out of GPU memory there. Could you please put a break point to see the sizes of clp?

**Comment by rajatsaxena** [comment]
Matlab 2018a. size(clp) = [801514  768]

**Comment by marius10p** [comment]
768 = 128 * 6, so your spikes are spanning all 128 channels for some reason. Are your xcoords and ycoords right?

**Comment by rajatsaxena** [comment]
yes, I confirmed the xcoords and ycoords. They are correct. I came across the same issue with a different dataset, different probe geometry. Note that the kilosort3 ran okay with both the datasets when I used a subset of data.

**Comment by Aegoerd** [comment]
Thanks for any clue on this. I might be getting a similar 'out of memory on device' error. I'm using:
Matlab 2020b, 256ch probe, 2hr recording, GeForce GTX 1080, Kilosort 3
Size(data)=  1403591           6         253;
`
Error using gpuArray
Out of memory on device. To view more detail about available memory on the GPU, use
'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.

Error in run_pursuit (line 3)
Xd = gpuArray(data(:, :));

Error in template_learning (line 82)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);`

**Comment by marius10p** [comment]
What are you xcoords and ycoords? It shouldn't try to use all the channels for the clustering, as it seems to be, unless it thinks they're all very close to each other.

**Comment by Aegoerd** [comment]
Thank you, Marius. Here are my coordinates - it should be 30µm vertical and 80µm horizontal pitch. Is there a good way to change the number of channels it's using for each cluster?

![Probe coordinates](https://user-images.githubusercontent.com/27200250/106985882-180bb680-671f-11eb-920f-a2a4f9d7a2b4.jpg)

**Comment by marius10p** [comment]
Can you send the full command line output please? I am curious what
vertical and horizontal pitch it detected. The channel grouping is
optimized for single electrode geometries, but it should still not take all
the channels in your case.

**Comment by Aegoerd** [comment]
It seems like it's taking the vertical pitch to the electrode from an adjacent shank (15um), although the effective pitch is 30um.
I am seeing templates spread multiple shanks, if that's the concern about not using a single electrode (ie shank)?
Below the command line output:

`Looking for data inside H:\Recordings\wt21\wt21_day13_Pav_210203_212646\EPhys 
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time  14s. Loading raw data and applying filters... 
Time 464s. Finished preprocessing 2186 batches. 
vertical pitch size is 15 
horizontal pitch size is 160 
  Columns 1 through 7

          80         160         240         320         400         480         560

  Columns 8 through 14

         640         720         800         880         960        1040        1120

  Columns 15 through 21

        1200        1280        1360        1440        1520        1600        1680

  Columns 22 through 28

        1760        1840        1920        2000        2080        2160        2240

  Columns 29 through 32

        2320        2400        2480        2560

    47

0.43 sec, 1 batches, 2914 spikes 
29.83 sec, 101 batches, 297635 spikes 
58.89 sec, 201 batches, 575747 spikes 
88.16 sec, 301 batches, 858320 spikes 
118.06 sec, 401 batches, 1137667 spikes 
147.34 sec, 501 batches, 1430984 spikes 
177.08 sec, 601 batches, 1705070 spikes 
206.84 sec, 701 batches, 1976645 spikes 
236.14 sec, 801 batches, 2247380 spikes 
265.34 sec, 901 batches, 2517359 spikes 
294.64 sec, 1001 batches, 2780457 spikes 
324.00 sec, 1101 batches, 3067244 spikes 
353.32 sec, 1201 batches, 3316902 spikes 
382.56 sec, 1301 batches, 3596493 spikes 
411.85 sec, 1401 batches, 3868173 spikes 
441.41 sec, 1501 batches, 4132962 spikes 
470.91 sec, 1601 batches, 4362742 spikes 
500.35 sec, 1701 batches, 4591590 spikes 
529.78 sec, 1801 batches, 4821710 spikes 
559.44 sec, 1901 batches, 5075375 spikes 
588.88 sec, 2001 batches, 5382955 spikes 
618.20 sec, 2101 batches, 5606052 spikes 
642.96 sec, 2186 batches, 5800948 spikes 
time 1054.97, Shifted up/down 2186 batches. 
0.46 sec, 1 batches, 3530 spikes 
32.14 sec, 101 batches, 348768 spikes 
63.50 sec, 201 batches, 673640 spikes 
95.64 sec, 301 batches, 1002099 spikes 
126.94 sec, 401 batches, 1328332 spikes 
157.95 sec, 501 batches, 1671138 spikes 
188.57 sec, 601 batches, 1992815 spikes 
220.27 sec, 701 batches, 2310771 spikes 
250.72 sec, 801 batches, 2629402 spikes 
281.13 sec, 901 batches, 2948754 spikes 
311.82 sec, 1001 batches, 3258677 spikes 
342.30 sec, 1101 batches, 3594516 spikes 
372.72 sec, 1201 batches, 3888963 spikes 
405.28 sec, 1301 batches, 4216216 spikes 
435.74 sec, 1401 batches, 4536195 spikes 
466.20 sec, 1501 batches, 4843412 spikes 
499.47 sec, 1601 batches, 5107292 spikes 
529.97 sec, 1701 batches, 5372436 spikes 
560.43 sec, 1801 batches, 5637325 spikes 
590.85 sec, 1901 batches, 5926499 spikes 
624.36 sec, 2001 batches, 6269190 spikes 
654.96 sec, 2101 batches, 6514075 spikes 
681.01 sec, 2186 batches, 6727632 spikes 
time 0.00, GROUP 1/8, units 0 
82      kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);
Error using gpuArray
Out of memory on device. To view more detail about available memory on the GPU, use
'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.

Error in run_pursuit (line 3)
Xd = gpuArray(data(:, :));

Error in template_learning (line 82)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in main_kilosort3 (line 42)
rez                = template_learning(rez, tF, st3);`

**Comment by marius10p** [comment]
Your geometry is fine for spike sorting, I just don't know why Kilosort doesn't see it right. Could you send me a very short (10sec) snippet of data and your channel map and configuration file and running script?

**Comment by DanEgert** [comment]
Shouldn't be anything out of the ordinary - I just downloaded today and ran it with minimal modifications:

https://drive.google.com/drive/folders/1fa4Fnq2NfuXwUprHlNw7NHyWBSVReA-s?usp=sharing

Please let me know if there's a better way of sharing files > 10MB

**Comment by DanEgert** [comment]
Here my running script: 

`clear all; close all;

addpath('G:\My Drive\matlab_scripts\My\my_kilosort_scripts\npy-matlab') % for converting to Phy
rootZ = 'H:\Recordings\wt21\wt21_day13_Pav_210203_212646\EPhys'; % the raw data binary file is in this folder
rootH = 'H:\Kilosort_working'; % path to temporary binary file (same size as data, should be on fast SSD)
pathToYourConfigFile = 'G:\My Drive\matlab_scripts\Kilosort\configFiles'; % take from Github folder and put it somewhere else (together with the master_file)
chanMapFile = 'H:\Recordings\wt21\WT21_KS_Channelmap.mat';

ops.trange    = [0 Inf]; % time range to sort
ops.NchanTOT  = 256; % total number of channels in your recording

run(fullfile(pathToYourConfigFile, 'KS3_config_dan.m'))
ops.fproc   = fullfile(rootH, 'temp_wh.dat'); % proc file on a fast SSD
ops.chanMap = chanMapFile;

%% this block runs all the steps of the algorithm
fprintf('Looking for data inside %s \n', rootZ)

% main parameter changes from Kilosort2 to v2.5
ops.sig        = 20;  % spatial smoothness constant for registration
ops.fshigh     = 300; % high-pass more aggresively
ops.nblocks    = 5; % blocks for registration. 0 turns it off, 1 does rigid registration. Replaces "datashift" option. 

% main parameter changes from Kilosort2.5 to v3.0
ops.Th       = [9 9];

% is there a channel map file in this folder?
% fs = dir(fullfile(rootZ, 'chan*.mat'));
% if ~isempty(fs)
%     ops.chanMap = fullfile(rootZ, fs(1).name);
% end

% find the binary file
fs          = [dir(fullfile(rootZ, '*.bin')) dir(fullfile(rootZ, '*.dat'))];
ops.fbinary = fullfile(rootZ, fs(1).name);

rez                = preprocessDataSub(ops);
rez                = datashift2(rez, 1);

[rez, st3, tF]     = extract_spikes(rez);

rez                = template_learning(rez, tF, st3);

[rez, st3, tF]     = trackAndSort(rez);

rez                = final_clustering(rez, tF, st3);

rez                = find_merges(rez, 1);

rootZ = fullfile(rootZ, 'kilosort3');
mkdir(rootZ)
rezToPhy2(rez, rootZ);

%% 
`

**Comment by marius10p** [comment]
Thanks. I see now, I am assuming a sequential channel map somewhere to take nearby channels. I will fix this today.

**Comment by marius10p** [comment]
I pushed a fix, please give it a try. This is now no longer dependent on the order in the channel map AND makes the groups of channels local in 2D space, not just vertically. I hope I didn't break anything else though...

**Comment by rajatsaxena** [comment]
it worked for me. Thanks!

@DanEgert once you are done testing it, I will close the issue.

**Comment by DanEgert** [comment]
Thanks for addressing this so quickly, Marius. Yes, it completed the sort after the update! 
It may or may not be cosmetic, but the command line output still reads my vertical pitch as 15um and horizontal pitch as 160um Maybe it should be 30/80, depending on how it's calculated.

**Comment by marius10p** [comment]
Yeah, that's a little difficult to determine automatically for all types of probes, but I'll make it a parameter in the channel map soon. It shouldn't impact your spike sorting quality much, if at all.

**Comment by DanEgert** [comment]
Hi Marius,

happy to ask on github, but might be a quick answer. Have to decide on a
spike sorter for a paper. KS3 ran great for us but it's tricky to publish
if we don't understand the algorithm. Will this be published soon (if so,
within weeks/months/years) or could you give us an idea how KS3 is
different to template matching done in previous versions (or point to a
source)? Also, is it correct that so far Phy2 will not run on KS3 results
and there is no direct way to manually split clusters? Would you recommend
using KS2.5 for now?

Thanks for any clue,
Dan
