### ISSUE TITLE
iseed error in kilosort3 learnAndSolve8b

### ISSUE THREAD

**Issue by nmtimme** [MouseLand/Kilosort#320]
I'm receiving the following error when I run the eMouse_drift test in kilosort3:

Unrecognized function or variable 'iseed'.

Error in learnAndSolve8b (line 6)
rng(iseed);

I believe this can easily be fixed by changing iseed to iorder. Line 6 of learnAndSolve8b becomes:

rng(iorder);

**Comment by marius10p** [comment]
Sorry, I haven't updated that for Kilosort3 yet. "learnAndSolve8b" is no longer used.

**Comment by BrainOdyssey2050** [comment]
> Sorry, I haven't updated that for Kilosort3 yet. "learnAndSolve8b" is no longer used.

Hi, I want to learn the code with some demos, so I tried emouse_drift. but it doesn't work. It seems you havn't updated emouse folder? Is there any other demos that I can play with?
