### ISSUE TITLE
Kilosort3 fails for probes with too few channels

### ISSUE THREAD

**Issue by johnmbarrett** [MouseLand/Kilosort#321]
Steps to reproduce:

1). Untar the attached [data, config files, and script](https://github.com/MouseLand/Kilosort/files/5916095/test_kilosort3_crash.tar.gz) to some folder
2). Change the paths in test_kilosort3_crash.m to wherever you untarred the tarball to
3). Run test_kilosort3_crash.m

Expected behaviour: kilosort doesn't crash

Actual behaviour: kilosort crashes with the following error

```
Index in position 1 exceeds array bounds (must not exceed 63).
Error in getClosestChannels2 (line 15)
iC= isort(1:NchanClosest, :);
Error in extract_spikes (line 55)
[iC2, dist2] = getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp);
Error in test_kilosort3_crash (line 40)
[rez, st3, tF]     = extract_spikes(rez); 
```

Additional notes:

Offending lines seem to be lines 44 and 54 of mainLoop/extract_spikes.m, where NchanNearUp that is passed to getClosestChannels2 is hardcoded to 10*16 = 160. However, the attached dataset only contains 32 channels, which get upsampled to 63 channels, so getClosestChannels2 falls over when asked to get the 160 out of 63 nearest neighbours. Changing line 15 of getClosestChannels2 to

`iC= isort(1:min(NchanClosest,size(isort,1)), :);`

seems to solve the issue.

**Comment by johnmbarrett** [comment]
That said, even after making the change I still get a bunch of other errors when I try to run the test script. I won't describe them in detail for now (although I can if I want to), but to get the test script (which is just a copy of main_kilosort.m with some path changes and ops.nblocks set to 0) to run successfully I have to make two additional changes:-

1). Add to the end of clustering/extract_spikes.m

```
rez.wPCA = gather(wPCA);
rez.wTEMP = gather(wTEMP);
```

2). Wrap the right hand side of lines 118-9 of clustering/final_clustering.m in a call to `gather()`

**Comment by marius10p** [comment]
I'll look into this today, it seems more weird than I thought.

**Comment by marius10p** [comment]
What are your xcoords and ycoords?

**Comment by johnmbarrett** [comment]
They're in test.mat in the attached tarball, but xcoords = zeros(32,1) and ycoords = [550;150;350;1550;1350;1150;950;750;650;850;1050;1250;1450;250;50;450;600;200;400;1600;1400;1200;1000;800;700;900;1100;1300;1500;300;100;500]

**Comment by marius10p** [comment]
Thanks for the tarball. I fixed it and I checked the results in Phy.  Let me know if there are other problems.

**Comment by johnmbarrett** [comment]
Just updated kilosort and ran the test again, seems to work. Thanks! Will see if I can get it running on the full dataset now...

**Comment by johnmbarrett** [comment]
Tested the latest version on my last three days recordings. It ran fine (apart from when I accidentally ran it on EMG data) and the spikes look great. Thanks again!
