### ISSUE TITLE
eMouse_drift: Undefined function or variable 'iseed'.

### ISSUE THREAD

**Issue by BrainOdyssey2050** [MouseLand/Kilosort#322]
Hi there,

when I ran main_eMouse_drift.m, ERROR: (Undefined function or variable 'iseed'.) pop up. I check the main file and the function learnAndSolve8b(rez, order), where the ERROR occurs, I could find any iseed pre-defined. 

since rng(iseed); is a pseudo number generator, may I define iseed by myself, for example, iseed = 1? Or kissed has been defined?

Thank you!

**Comment by nmtimme** [comment]
Yeah, I found that problem too (see #320). @marius10p said he hasn't updated main_eMouse_drift.m yet. Apparently, learnAndSolve8b is no longer used in kilosort3.
