### ISSUE TITLE
Error saving data for phy! Reference to non - existent filed 'W'

### ISSUE THREAD

**Issue by lmontelisciani** [MouseLand/Kilosort#325]
Once I run Kilosort, Matlab gives me the following output.

![image](https://user-images.githubusercontent.com/63074401/106863616-10b9be00-66c9-11eb-983b-2907c319dbee.png)

I click to learn more, the output is the following:

![image (1)](https://user-images.githubusercontent.com/63074401/106863654-1c0ce980-66c9-11eb-8e1d-b7f2d28a88cf.png)

However, I can still run Kilosort3, but in the end, I get this result, and I cannot save my data in Phy.

![image (2)](https://user-images.githubusercontent.com/63074401/106863684-26c77e80-66c9-11eb-9927-e877368d0b70.png)

Do you know if the Matlab output I get when running Kilosort is related to this last problem? In any case, do you know a solution for it?

**Comment by marius10p** [comment]
Update your Nvidia drivers. What is your GPU and Matlab version?

**Comment by lmontelisciani** [comment]
GPU: NVIDIA GeForce RTX 2060 
Matlab: 2018a

**Comment by marius10p** [comment]
Looks like a driver problem then. If updating doesn't solve it, then maybe uninstall and reinstall Matlab.

**Comment by lmontelisciani** [comment]
I updated the driver, uninstalled and reinstalled Matlab, but now I get the following error:

![image](https://user-images.githubusercontent.com/63074401/106903919-dec14f80-66fa-11eb-9274-5eb9f7baea31.png)

**Comment by marius10p** [comment]
This was just fixed an hour ago... can you please update the repository and try again?

**Comment by lmontelisciani** [comment]
Thank you a lot for the suggestion. I did not get the previous errors anymore, and I could preprocess short recordings. However, when I try to process the longer one, I got the following error in Matlab.

![image](https://user-images.githubusercontent.com/63074401/107020472-30251980-67a3-11eb-9f8b-2c84a432d9d2.png)

**Comment by marius10p** [comment]
I forgot to mention, but you also need to install the specific version of CUDA that your Matlab version requires: https://www.mathworks.com/help/parallel-computing/gpu-support-by-release.html;jsessionid=f68ff768914bd294d61356fc7d1d

**Comment by lmontelisciani** [comment]
I installed matlab2020b, and it worked! 

Thank you.
