### ISSUE TITLE
KS3 preprocessing error - nonexistent field 'dmin'

### ISSUE THREAD

**Issue by dleventh** [MouseLand/Kilosort#326]
I keep getting the following error during preprocessing in KS3 - that there is a nonexistent field 'dmin'. I believe I traced it to line 29 in standalone_detector: dNearActiveSite = rez.ops.dmin.

The data look good in the GUI display window.

Data collected with an Intan system, 64-channel (8x8) neuronexus probe. Running on windows 10, Matlab R2019b, CUDA 10.1

**Comment by marius10p** [comment]
It is fixed now, can you please update the repository?

**Comment by dleventh** [comment]
Thanks! It's running now.

**Comment by Moyu0014** [comment]
Hi,

I guess my current issue encountered now is similar to what @dleventh asked. It output as unrecognized field name "dmin" on my kilosort 3 but I am pretty sure it does exist in Rez.ops. I am new to Matlab, so it will be excellent if anybody can tell me how to solve this in detail. Thanks very much!
![thumbnail_image](https://github.com/MouseLand/Kilosort/assets/159174957/b5b4485a-2c08-4f11-832c-695ee7568d34)


Kind Regards,

Moyu0014
