### ISSUE TITLE
Error in KS3 left side doesn't match right side...

### ISSUE THREAD

**Issue by rivlinoa** [MouseLand/Kilosort#327]
![image](https://user-images.githubusercontent.com/20164106/106896407-2e534b80-66fa-11eb-8ed9-8bcc5fc041a1.png)

Hi, I get this error trying to run KS3 in Neuropixels1.0 data.
Nothing informative in the command window, it just stops at this point:
![image](https://user-images.githubusercontent.com/20164106/106896646-8722e400-66fa-11eb-9341-b01deeafec5d.png)

Thanks in advance,
Noa

**Comment by marius10p** [comment]
I think it's fixed now, can you try it please?

**Comment by rivlinoa** [comment]
Its working!!! Thanks a lot!
