### ISSUE TITLE
rootH could not open for writing

### ISSUE THREAD

**Issue by Dradeliomecus** [MouseLand/Kilosort#331]
Hi,

I'm trying to usr the matlab version of `Kilosort` for the first time, and I have the following error:
```
>> main_kilosort3
Looking for data inside /users/nsr/wyngaard/Documents/cells_tracking/0153/session_1/rec 
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   3s. Loading raw data and applying filters... 
Error using preprocessDataSub (line 69)
Could not open /users/nsr/wyngaard/Documents/tmp for writing.

Error in main_kilosort3 (line 37)
rez                = preprocessDataSub(ops);
```

I ran `matlab` as `sudo`, the path `/users/nsr/wyngaard/Documents/tmp` correctly exists and has permission `777`.
Why cannot it open it?

Thank you

**Comment by marius10p** [comment]
I don't know... could it be that the file is already open elsewhere, or hasn't been closed properly? Could try restarting Matlab and/or the computer.

**Comment by Dradeliomecus** [comment]
It's a folder that's not being used in any other application and isn't opened.

I tried restarting Matlab, but not restarting the computer (yet).

**Comment by Dradeliomecus** [comment]
I looked at the source code and it seems that this folder is opened correctly in mode `'r'`, but not in mode `'w+'` which makes no sense since it has permissions `777`.

**Comment by marius10p** [comment]
Kilosort tries to make temp_wh.bin file there with 'w+'. This deletes any preexisting file, although I guess it should inherit the permissions of that folder...

**Comment by Dradeliomecus** [comment]
I tried rebooting the computer, adding the target folder to the MATLAB path, still the same error...

**Comment by marius10p** [comment]
Sorry, I'm out of ideas over here. Have you tried different folders?

**Comment by Dradeliomecus** [comment]
Ah, my mistake.

I actually changed the `ops.fproc` variable to the folder, and not the `temp_wh.dat` file inside of it.
It now works!
