### ISSUE TITLE
Unrecognized function or variable "extract_spikes"

### ISSUE THREAD

**Issue by Idavr** [MouseLand/Kilosort#334]
Hi!

I am trying to run KS3 for the first time, and I ran into issues during the "extracting spikes for clustering" stage with this error:

Unrecognized function or variable 'extract_spikes'.

Error in ksGUI/runSpikesort (line 786)
                [obj.rez, st3, tF]     = extract_spikes(obj.rez);

Error in ksGUI/runAll (line 628)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 319)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.

I updated Kilosort right before running this as I noticed there had been some changes done, but there still seems to be something missing in the code I have or am I reading the error wrong?

**Comment by metmic** [comment]
Hello,
I am having a similar issue:

Undefined function or variable 'extract_spikes'.

Error in ksGUI/runSpikesort (line 786)
[obj.rez, st3, tF]     = extract_spikes(obj.rez);

Error in ksGUI>@(~,~)obj.runSpikesort() (line 337)
'Callback', @(~,~)obj.runSpikesort());
 
Error while evaluating UIControl Callback.

Thanks.

**Comment by marius10p** [comment]
The function is here: https://github.com/MouseLand/Kilosort/blob/main/clustering/extract_spikes., and it should be in your Matlab path. Could it be that you added an old version of Kilosort to the path instead?

**Comment by metmic** [comment]
Thank you. Yep, that was probably the reason. The folder clustering was not in my Matlab path.

**Comment by Idavr** [comment]
Thank you @marius10p , it does indeed seem like this was the reason. All good now :)
