### ISSUE TITLE
fprintf invalid format in rezToPhy2

### ISSUE THREAD

**Issue by Dradeliomecus** [MouseLand/Kilosort#336]
Hi,

I'm trying out `Kilosort 3`, and I managed to make it run, but it crashes at the very end (it saves everything to phy except for the `params.py` file)

The error is:
```
Error using fprintf
Invalid format.

Error in rezToPhy2 (line 197)
        fprintf(fid,['dat_path = ''', strrep(rez.ops.fproc, '\', '/') '''\n']);

Error in main_kilosort3 (line 52)
rezToPhy2(rez, rootZ);
```

**Comment by marius10p** [comment]
Can you stop it in debug mode to see what fprintf is upset about? The problem seems to be specific to your data paths and maybe file system format. What OS?

**Comment by Dradeliomecus** [comment]
I'm re-running it with a breakpoint on the `fprintf`, but I'm not sure how to debug it (this is the very first time I'm using Matlab).

I'm on Ubuntu 20.04, with Matlab R2019b.

**Comment by marius10p** [comment]
You could try sprintf instead of fprintf, it might be more informative.
Also, just disp the relevant variables (ops.fproc) and post the results
here.

Is this a new line in the actual code or just in the error:

```fprintf(fid,['dat_path = ''', strrep(rez.ops.fproc, '\', '/') '''\n']);```


There shouldn't be one there.

**Comment by Dradeliomecus** [comment]
`sprintf` did not change anything.

The value of `rez.ops.fproc` is `/users/nsr/wyngaard/Documents/tmp/temp_wh.dat` (shouldn't it point to the original `dat` file?).

The error is the line `fprintf(fid,['dat_path = ''', strrep(rez.ops.fproc, '\', '/') '''\n']);` itself.

**Comment by marius10p** [comment]
It's supposed to point to the drift-corrected file created by Kilosort, otherwise the clusters won't make sense if you have a lot of drift. I don't really know why that line is failing for you. The params.py file should just look like this: 

dat_path = 'G:/Spikes/Sample/temp_wh.dat'
n_channels_dat = 383
dtype = 'int16'
offset = 0
sample_rate = 30000.
hp_filtered = True

**Comment by Dradeliomecus** [comment]
I tried the following in the console, does it help?

```
>> aze = "/users/nsr/wyngaard/Documents/tmp/temp_wh.dat"

aze = 

    "/users/nsr/wyngaard/Documents/tmp/temp_wh.dat"

>> ['dat_path =''', strrep(aze, '\', '/') '''\n']

ans = 

  1×3 string array

    "dat_path ='"    "/users/nsr/wyngaard/Documents/tmp/temp_wh.dat"    "'\n"

>> fid = fopen("/users/nsr/wyngaard/Documents/cells_tracking/0153/session_1/rec/test.py", 'w');
>> fid

fid =

     5

>> fprintf(fid, ['dat_path = ''', strrep(aze, '\', '/') '''\n'])
```

**Comment by marius10p** [comment]
Can you please try it without the strrep, so just

```fprintf(fid, ['dat_path = ''',  aze '''\n'])```

**Comment by Dradeliomecus** [comment]
I tried it, and it still crashes:
```
>> fid = fopen("/users/nsr/wyngaard/Documents/cells_tracking/0153/session_1/rec/test.py", 'w');
>> fprintf(fid, ['dat_path = ''', aze '''\n'])
Error using fprintf
Invalid format.
```

However, I managed to change the line so that it does work (using concatenation instead of an array):
```
>> fid = fopen("/users/nsr/wyngaard/Documents/cells_tracking/0153/session_1/rec/test.py", 'w');
>> fprintf(fid, 'dat_path = ''' + aze + '''\n')

ans =

    59
```

**Comment by marius10p** [comment]
Does params.py look ok, and does it open in Phy? I'll try concatenation on my end too.

**Comment by Dradeliomecus** [comment]
Yes `params.py` looks as it should, and it opens with `Phy`!
