### ISSUE TITLE
Changing parameter 'nt0' results in a crash

### ISSUE THREAD

**Issue by Dradeliomecus** [MouseLand/Kilosort#337]
Hi,

I tried running Kilosort with a different value for `nt0` (from 61 to 75), and I obtained this crash:

```
Unable to perform assignment because the size of the left side is 61-by-1-by-3 and the size of the right side is 75-by-3.

Error in template_learning (line 110)
    rez.W(:,t,:) = gather(wsign * w(:,1:3));

Error in main_kilosort3 (line 42)
rez                = template_learning(rez, tF, st3);
```

From what I saw, this is because in `clustering/template_learning.m`, line 103, `rez.W` is defined as:
```
rez.W = zeros(61,0, 3, 'single');
```

Shouldn't this `61` be replaced by `ops.nt0`?

**Comment by marius10p** [comment]
Sure, yes, but I think the CUDA code will crash with nt0 >61. Unless your data is recorded at >=50Khz, there shouldn't be a reason to change nt0.

**Comment by Dradeliomecus** [comment]
I am recording in the cerebellar cortex, and some spikes are called "complex spikes" which impacts the extracellular voltage quite significantly for ~4/5 ms (see the image below, xaxis is the time in milliseconds)
![ex_CS](https://user-images.githubusercontent.com/3465310/107784295-8cf87500-6d4b-11eb-88ce-3ceaaf859115.png)

I was worried that with a short `nt0`, there would be a residual voltage which might impact `Kilosort` (as I understand, Kilosort tries to explain the extracellular voltage using the spikes).
Btw, my high-pass filter is set at 150 Hz (I find that 300 Hz makes these complex spikes harder to detect).

**Comment by marius10p** [comment]
Could you please show that neuron in Phy with multiple snippets? I am curious if multiple events have the same stereotypical pattern after the initial depolarization.

**Comment by Dradeliomecus** [comment]
The waveforms aren't perfectly aligned (this dataset comes from `MountainSort`, but I can find one that's from `Kilosort` where waveforms are more aligned if you want).

![Screenshot from 2021-02-08 14-48-20](https://user-images.githubusercontent.com/3465310/107794085-4a3c9a00-6d57-11eb-8a0f-5288d1a618b3.png)

The positive phase is usually pretty stereotypical for the same neuron.

**Comment by marius10p** [comment]
This example is very noisy overall. If the positive phase is stereotypical, but the rest of the spike is variable, then Kilosort won't be able to deal with that correctly. In that case, you are better off setting a small nt0, so the clusters don't get split by the variability in the complex part of the spike. It's possible the "tail" of the complex spike will be assigned to a noise unit, which is fine.

**Comment by Dradeliomecus** [comment]
Alright, thank you!
