### ISSUE TITLE
Kilosort3 not working for linear probes

### ISSUE THREAD

**Issue by Jialiang-Lu** [MouseLand/Kilosort#338]
It seems that Kilosort3 doesn't consider the situation of linear probes. Naturally, the xcoords in the channel map for a linear probe have the same value, which means that `rez.ops.dminx` will be 0.

The line
https://github.com/MouseLand/Kilosort/blob/d8942c664ebded8c14dca67b4a160d34c5cbb34c/clustering/template_learning.m#L34

will make `xcenter` an empty array for linear probes and all following computation cannot be done.

I replaced this line with
`if dminx>0
    xcenter = (min(rez.xc) + dminx-1):(2*dminx):(max(rez.xc)+dminx+1);
else
    xcenter = rez.xc(1);
end`
and
https://github.com/MouseLand/Kilosort/blob/d8942c664ebded8c14dca67b4a160d34c5cbb34c/clustering/template_learning.m#L55
with
`    xchan = (abs(ycup - y0) < dmin) & (abs(xcup - x0) <= dminx);`

Same for
https://github.com/MouseLand/Kilosort/blob/d8942c664ebded8c14dca67b4a160d34c5cbb34c/clustering/final_clustering.m#L56
and
https://github.com/MouseLand/Kilosort/blob/d8942c664ebded8c14dca67b4a160d34c5cbb34c/clustering/final_clustering.m#L74

I am not sure if this is the right fix but at least that works for my data collected by a linear probe.

**Comment by HiroyukiKato7** [comment]
I have the same issue of xcenter becoming blank because of the way xcoords are handled for a linear probe.  I'm wondering if there is any update on this.

**Comment by shirquinn** [comment]
hi @Jialiang-Lu 
i had this error using a 32ch linear probe
Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in getMeWtW (line 30)
iList = int32(gpuArray(isort(iNear, :))); % return the list of pairs for each template

Error in trackAndSort (line 100)
[WtW, iList] = getMeWtW(single(W), single(U), Nnearest);

Error in ksGUI/runSpikesort (line 792)
[obj.rez, st3, tF] = trackAndSort(obj.rez);

Error in ksGUI/runAll (line 628)
obj.runSpikesort;

Error in ksGUI>@(,)obj.runAll() (line 319)
'Callback', @(,)obj.runAll());

Error while evaluating UIControl Callback.

after trying your fix, the sorting was preformed with no errors
i am not an expert on this so i hope this fix will get the approval of the creators
thank you

**Comment by marius10p** [comment]
Sorry about that, I pushed a fix now. Re-open this issue if you still have problems.
