### ISSUE TITLE
wav2_best in bimodal_pursuit

### ISSUE THREAD

**Issue by colonnese** [MouseLand/Kilosort#339]
I received this error running Kilosort3 sorting. 

Unrecognized function or variable 'wav2_best'.

Error in bimodal_pursuit (line 99)
    wav2 = wav2_best;

From the code it looks like wav2_best is only assigned if r0>mean((wav1-wav).^2)
which was not true in my case. Don't know if this is an oversight or you thought there was no way that condition would not be met.  

do_roll = 0;
    r0 = mean((wav1-wav2).^2);
    for j = 1:size(wroll,3)
        
       wav = wroll(:,:,j) * reshape(wav2, [6, numel(wav2)/6]);
       wav = wav(:)';
       if r0 > mean((wav1-wav).^2)
          wav2_best = wav;
          r0 =  mean((wav1-wav2).^2);
          do_roll = 1;
       end
    end
    wav2 = wav2_best;

**Comment by Dradeliomecus** [comment]
Got the same error,

Here is my output:
```
>> main_kilosort3
Looking for data inside /users/nsr/wyngaard/Documents/cells_tracking/0153/session_1/rec 
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   1s. Loading raw data and applying filters... 
Time  63s. Finished preprocessing 882 batches. 
vertical pitch size is 1.250000e+01 
horizontal pitch size is 250 
  -25.0000  104.1667  233.3333  362.5000  491.6667  620.8333  750.0000

    39

0.10 sec, 1 batches, 1271 spikes 
2.89 sec, 101 batches, 95679 spikes 
5.63 sec, 201 batches, 173596 spikes 
8.38 sec, 301 batches, 259637 spikes 
11.13 sec, 401 batches, 348632 spikes 
13.88 sec, 501 batches, 432859 spikes 
16.64 sec, 601 batches, 533203 spikes 
19.88 sec, 701 batches, 647911 spikes 
22.78 sec, 801 batches, 745832 spikes 
25.01 sec, 882 batches, 826548 spikes 
time 60.81, Shifted up/down 882 batches. 
0.05 sec, 1 batches, 1512 spikes 
2.96 sec, 101 batches, 108622 spikes 
6.14 sec, 201 batches, 210546 spikes 
8.77 sec, 301 batches, 324856 spikes 
11.40 sec, 401 batches, 444861 spikes 
14.05 sec, 501 batches, 559738 spikes 
16.70 sec, 601 batches, 690282 spikes 
19.33 sec, 701 batches, 832220 spikes 
21.97 sec, 801 batches, 954993 spikes 
24.55 sec, 882 batches, 1053705 spikes 
time 0.00, GROUP 1/16, units 0 
Unrecognized function or variable 'wav2_best'.

Error in bimodal_pursuit (line 99)
    wav2 = wav2_best;

Error in bimodal_pursuit (line 129)
    [x, iclust, flag] = bimodal_pursuit(clp, wroll, ss, rmin, nlow, retry-1, use_CCG);

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin, use_CCG);

Error in template_learning (line 88)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in main_kilosort3 (line 42)
rez                = template_learning(rez, tF, st3);
```

**Comment by colonnese** [comment]
For comparison/completeness here is my error (also 0 units).

>> kilosort
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time  88s. Loading raw data and applying filters... 
Time 133s. Finished preprocessing 366 batches. 
vertical pitch size is 20 
horizontal pitch size is 32 
    11    27    43    59

   766

0.44 sec, 1 batches, 3317 spikes 
17.21 sec, 101 batches, 422401 spikes 
34.30 sec, 201 batches, 831681 spikes 
51.32 sec, 301 batches, 1250418 spikes 
62.37 sec, 366 batches, 1550348 spikes 
time 107.67, Shifted up/down 366 batches. 
0.30 sec, 1 batches, 592 spikes 
16.47 sec, 101 batches, 104972 spikes 
32.65 sec, 201 batches, 205507 spikes 
48.87 sec, 301 batches, 312524 spikes 
59.48 sec, 366 batches, 396766 spikes 
time 0.00, GROUP 1/96, units 0 
Unrecognized function or variable 'wav2_best'.

Error in bimodal_pursuit (line 99)
    wav2 = wav2_best;

Error in bimodal_pursuit (line 129)
    [x, iclust, flag] = bimodal_pursuit(clp, wroll, ss, rmin, nlow, retry-1, use_CCG);

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin,
    use_CCG);

Error in template_learning (line 88)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in ksGUI/runSpikesort (line 789)
                obj.rez                = template_learning(obj.rez, tF, st3);

Error in ksGUI>@(~,~)obj.runSpikesort() (line 337)
                'Callback', @(~,~)obj.runSpikesort());
 
Error while evaluating UIControl Callback.

**Comment by Dradeliomecus** [comment]
@colonnese This issue can be closed, it was fixed in the latest commit.
