### ISSUE TITLE
error in calculating rez.ops.xup in KS3

### ISSUE THREAD

**Issue by Hankslab-ABG** [MouseLand/Kilosort#340]
Greetings,

We're using a Npx probe configuration where only 1 electrode per row is used (this is for the stagged 3B probe) for all but the middle section of our active sites are used. As a result, in datashift2 our dminx ends up being 0, nx becomes inf and thus causes an error in line  35 of that function:

Error in linspace (line 30)
        y = d1 + (0:n1).*((d2 - d1)./n1);

Error in datashift2 (line 35)
rez.ops.xup = linspace(xmin, xmax, nx); % centers of the upsampled x positions

I noticed that this is being calculated slightly differently than in KS2.5's datashift2 function. There's also a commented-out calcuation for dminx in the newer version reading:

%dminx = median(diff(unique(rez.xc)));

Will uncommenting that calculation for dminx and commenting out lines 21-30 of datashift to be an an acceptable workaround or do you anticipate this causing issues for us?

Many thanks,

-Adam

**Comment by marius10p** [comment]
Thanks, this has been fixed now.
