### ISSUE TITLE
Invalid MEX-file 'Kilosort3/CUDA/spikedetector3.mexa64

### ISSUE THREAD

**Issue by CarloCerquetella** [MouseLand/Kilosort#342]
Hi,

I have downloaded Kilosort on my Ubuntu 18.04 computer, I have successfully run mexGPUall.m (I got some warnings like "variable x was declared/set but never referenced/used" but I got the message "mex completed successfully" in the end). I modified the main_kilosort and the standardconfig files according to my settings. I run Kilosort but I get the following error: 

Invalid MEX-file '/mnt/Carlo/Kilosort3/CUDA/spikedetector3.mexa64':
/mnt/Carlo/Kilosort3/CUDA/spikedetector3.mexa64: failed to map segment from shared object Failed to map segment from shared object

I am using MATLAB R2020b, Cuda 10.2, GCC7.5 on a GeForce GTX 1080.
Does anyone have an idea?

Best,
Carlo

**Comment by marius10p** [comment]
The warnings are fine, just variables I forgot to take out and your configuration seems fine, I don't really know why the mex file fails (make sure you don't also have an old kilosort version in the path). Does gpuDevice(1) work?

**Comment by CarloCerquetella** [comment]
Hi Marius,
Thanks a lot for your help. I couldn't really see where the problem was so I uninstalled Ubuntu and installed Windows and started everything from scratch. It worked.

Best,
Carlo
