### ISSUE TITLE
Viewing Kilosort3 output in Phy-Gui shows distorted waveforms

### ISSUE THREAD

**Issue by asgorin** [MouseLand/Kilosort#343]
Thank you for publishing Kilosort3. 

I was successfully able to create a rez file and converted it for Phy GUI using 'rezToPhy'. I then called the Phy GUI and saw the following:

![Huh](https://user-images.githubusercontent.com/8754626/108569430-bae83700-72c0-11eb-89c0-85fb6efc8a7f.PNG)

The waveforms are horribly scaled for every cluster. 

I do not have this issue when I use Kilosort or Kilosort2, so I do not believe this to be a Phy GUI issue. I have not tried out Kilosort2.5.  I also tried converting the rez file for Phy GUI using 'rezToPhy2' in case there was some issue between using 'phy' and 'phy2', and I had a similar issue.

**Comment by marius10p** [comment]
I think this is an issue with the templates, right? You can scale them down manually in Phy for visualization until we work out what the correct scaling should be.

**Comment by asgorin** [comment]
Yes, this is an issue with the templates.
