### ISSUE TITLE
KS3 having peoblem with getMeWtW while KS2 works!

### ISSUE THREAD

**Issue by alirezasaeedi1988** [MouseLand/Kilosort#345]
Hello everyone,

I am using a Neuronexus 32 channel electrode and facing the following error in Kilosort3 while kilosort2 works fine on my data!
Index in position 1 is invalid. Array indices must be
positive integers or logical values.

Error in getMeWtW (line 30)
    iList = int32(gpuArray(isort(iNear, :))); % return the
    list of pairs for each template

Error in trackAndSort (line 100)
[WtW, iList] = getMeWtW(single(W), single(U), Nnearest); 

Somehow rez.W and rez.U are empty arrays. Do you have any suggestions?

Thank you in advance.

**Comment by shirquinn** [comment]
i'm haveing the same issue
>> kilosort
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   1s. Loading raw data and applying filters... 
Time  25s. Finished preprocessing 596 batches. 
vertical pitch size is 25 
horizontal pitch size is 0 
     0

   157

0.09 sec, 1 batches, 628 spikes 
4.88 sec, 101 batches, 67439 spikes 
8.95 sec, 201 batches, 136865 spikes 
12.87 sec, 301 batches, 208768 spikes 
16.54 sec, 401 batches, 284892 spikes 
20.05 sec, 501 batches, 364819 spikes 
23.49 sec, 596 batches, 443026 spikes 
time 39.20, Shifted up/down 596 batches. 
0.03 sec, 1 batches, 600 spikes 
5.07 sec, 101 batches, 64531 spikes 
9.06 sec, 201 batches, 131621 spikes 
12.76 sec, 301 batches, 201529 spikes 
16.15 sec, 401 batches, 275777 spikes 
19.53 sec, 501 batches, 353484 spikes 
22.64 sec, 596 batches, 429278 spikes 
Elapsed time is 0.000074 seconds.
Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in getMeWtW (line 30)
    iList = int32(gpuArray(isort(iNear, :))); % return the list of pairs for each template

Error in trackAndSort (line 100)
[WtW, iList] = getMeWtW(single(W), single(U), Nnearest);

Error in ksGUI/runSpikesort (line 792)
                [obj.rez, st3, tF]     = trackAndSort(obj.rez);

Error in ksGUI/runAll (line 628)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 319)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.

**Comment by alejandrotorrado** [comment]
I believe this is related to the use of linear probes, see issue #338. 
I was running into the same issue with 16-channel linear Neuronexus probes.

**Comment by shirquinn** [comment]
I tried the fix offered in issue #338 and the sorting worked fine, thanks

**Comment by marius10p** [comment]
That fix should be fine. I pushed an official fix now setting the minimum horizontal pitch to 5um.
