### ISSUE TITLE
Error shifting data on Matlab R2016b

### ISSUE THREAD

**Issue by justinlieber** [MouseLand/Kilosort#349]
In shift_batch_on_disk2.m, line 14, the function calls interp1() using the interpolation method 'makima'. On earlier versions of Matlab, 'makima' isn't implemented. Changing the method to 'pchip' seemed to resolve the issue.

**Comment by marius10p** [comment]
That should be almost as good. I know 'makima' isn't widely used, but there's some difference in what happens at the edges that I haven't had time to work out with a simpler method yet.
