### ISSUE TITLE
GPU Error while running Kilosort3 Spike Extraction

### ISSUE THREAD

**Issue by mastroK** [MouseLand/Kilosort#351]
Hello, 

Following preprocessing, the spike extraction is able to work through some of the batches but runs the following error:

`0.37 sec, 1 batches, 646 spikes 
29.73 sec, 101 batches, 58059 spikes 
58.88 sec, 201 batches, 114975 spikes 
82.89 sec, 283 batches, 161902 spikes 
time 132.77, Shifted up/down 283 batches. 
0.36 sec, 1 batches, 897 spikes 
32.96 sec, 101 batches, 83110 spikes 
65.25 sec, 201 batches, 165078 spikes 
91.74 sec, 283 batches, 232665 spikes 
time 0.00, GROUP 1/96, units 0 
Error using  * 
Call to sgemm in CUBLAS failed with error status: CUBLAS_STATUS_EXECUTION_FAILED.

Error in bimodal_pursuit (line 12)
clp = clp * u; % * s(ipc, ipc);

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin, use_CCG);

Error in template_learning (line 82)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in ksGUI/runSpikesort (line 789)
                obj.rez                = template_learning(obj.rez, tF, st3);

Error in ksGUI/runAll (line 628)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 319)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.`

Any help would be much appreciated!
Thanks
Kev

**Comment by linussun** [comment]
@mastroK What was your solution to this error? I am also running into it. Thanks.

**Comment by afergu** [comment]
I'm also running into this issue
