### ISSUE TITLE
Polarity inversion of some spikes?

### ISSUE THREAD

**Issue by olinesn** [MouseLand/Kilosort#354]
Hello,

When sorting spikes from a 64Ch 16x4 twisted tetrode array, I'm seeing some of my spikes have [predictions that are inverted](https://i.imgur.com/3pzCmda.png). Has anyone seen this before, and is there a tweak I could make? It almost looks the the ringing from a filter.

Thanks,
Stefan

**Comment by marius10p** [comment]
What version of Kilosort are you using? This looks a little like a known problem in KS2 which we never solved.

**Comment by FernandoSn** [comment]
I may have a similar issue with neuropixels data. The prediction for positive spikes only match the negative deflection. I have tried different ops.Th and I get the same output, I am using kilosort 3. These positive spikes are matched perfectly using kilosort 2.5.

![KS3](https://user-images.githubusercontent.com/47955351/113436422-ae242c00-93b2-11eb-9be1-2bc11e53e92b.jpg)

**Comment by marius10p** [comment]
I don't think it's the same problem. Is the positive-going spike part of the simultaneous 4-ch spike that was captured in the blue trace? If so, that's a very strange spike  shape.

**Comment by FernandoSn** [comment]
Here are my filtered signal and the residuals using KS3. I think the prediction is not the best here because my threshold was very low for this test. What I wanted to highlight is that KS3 seems to be ignoring these positive spikes in my data but KS 2.5 do match them (I tested them using the same parameters ).

![prediction](https://user-images.githubusercontent.com/47955351/113437799-50ddaa00-93b5-11eb-8968-c590af281410.jpg)
![filtered](https://user-images.githubusercontent.com/47955351/113437800-50ddaa00-93b5-11eb-8428-e2c586d90f9e.jpg)
![residual](https://user-images.githubusercontent.com/47955351/113437802-50ddaa00-93b5-11eb-83e1-864c62b50fde.jpg)

**Comment by marius10p** [comment]
Ok, if that's a single-channel positive going spike, then I think I know why it's not detected. Probably the single-channel templates detected from your data did not include a positive going template. I could look into providing a set of fixed templates that do include positive going spikes. Until then, please stick with 2.5 if you need to get those spikes.

**Comment by FernandoSn** [comment]
Yes, that was a single-channel positive going spike. Other positive going 
![correct](https://user-images.githubusercontent.com/47955351/113441410-4541b180-93bc-11eb-9b38-354511cac5b7.jpg)
spikes are detected correctly.

**Comment by marius10p** [comment]
Probably because they also have a negative going part.

**Comment by olinesn** [comment]
> What version of Kilosort are you using? This looks a little like a known problem in KS2 which we never solved.

Sorry I didn't see the notification after a few days that you had responded! I was flipping between KS2 and 2.5. It's interesting that you point out the 'negative going' property. Through habit, I've selected "invert traces" in the Neuralynx Cheetah software gui, maybe Kilosort expects the spikes to be negative going? I hadn't considered that, maybe if I invert my traces, this problem will go away.

**Comment by MMMariel** [comment]
Hi Stefan,
Did you have better results inverting the raw data from neuralynx? I do recordings with the same acquisition system.
Thanks,
Mariel
