### ISSUE TITLE
userSettings.mat not writeable - suggest to move it into home directory

### ISSUE THREAD

**Issue by schloegl** [MouseLand/Kilosort#356]
We have kilosort installed centrally on a cluster were multiple users have access, and should be able to use the centrally installed version of kilosort. unfortunately, userSettings.mat file is part of the installation, in a place were users do not have write access. 

My understanding is that each user should have her own userSettings file. The following patch 
  https://git.ist.ac.at/alois.schloegl/Kilosort/-/commit/87e95625606528678be1a52e86963a7e381b10c8
implements this . (the patch is attached here as well 

[patch-kilosort-0001-userSettings-in-home-directory.diff.gz](https://github.com/MouseLand/Kilosort/files/6124589/patch-kilosort-0001-userSettings-in-home-directory.diff.gz)

**Comment by marius10p** [comment]
We don't really have a way to install that file in a different place, and it wouldn't work across operating systems anyway. We can try to do this for the python version.

**Comment by schloegl** [comment]
Attached are two solutions, that would work on Matlab for Windows, too. 
The v3 is the minimum solution, and would not change anything for Windows, v2 is the version that would move the settings file into the users "Document" folder on windows, too. 

Again, the current situation is not satisfying because Kilosort can not be used in a multi-user environment, like central compute cluster. 
 
[patch-kilosort-0001v2-userSettings-in-home-directory.diff.gz](https://github.com/MouseLand/Kilosort/files/6414819/patch-kilosort-0001v2-userSettings-in-home-directory.diff.gz)
[patch-kilosort-0001v3-userSettings-in-home-directory.diff.gz](https://github.com/MouseLand/Kilosort/files/6414820/patch-kilosort-0001v3-userSettings-in-home-directory.diff.gz)

**Comment by marius10p** [comment]
Why can't each user install Kilosort inside their home directory? This is the preferred solution, especially if you are running Kilosort from the GUI

**Comment by schloegl** [comment]
In our case, the software is installed by sysadmins in a central location, users do not have admin permissions on those machines, and for several users the installation procedure is too complex to install it on their own.

**Comment by marius10p** [comment]
Fair enough! I will look into this.
