### ISSUE TITLE
issue with GUI/channel map

### ISSUE THREAD

**Issue by rclein94** [MouseLand/Kilosort#364]
Hi, I'm trying to use Kilosort2.5 for the 16 channel Buzsaki probe from Neuronexus. The probe has two shanks with one shank having 7 active sites, and the other having 8 active sites. Whenever I load my channel map into the GUI, I get a page that looks like the attached image. I also have an error that says index exceeds the number of array elements (15). I have tried some debugging, but it looks like because I have loaded in several different channel maps in the past to try to test things, all of those channel maps are being used. I'm not sure how to delete channel maps from the GUI's "memory". Whenever I start by loading in my data, the GUI tells me that it cannot calculate the number of channels, but nothing happens even after I enter the number. I'm not really sure what I'm doing wrong, so any advice is appreciated. I should add that I'm using Matlab 2020b, and I think I have downloaded everything correctly, but am not totally sure as I haven't had any success running the eMouse simulation either. I'm very new to ephys so looking for any advice!  Thank you! 

![gui](https://user-images.githubusercontent.com/80166260/112550725-35134c00-8d96-11eb-9e93-994019dbf014.JPG)

**Comment by JoseGuzman** [comment]
Hi @rclein94 ,

I was having similar issues with multi-shank probes. I would design your probes as linear (one shank after each other in the y-axis, see some examples [here](https://github.com/JoseGuzman/minibrain/tree/master/Matlab)). Both KiloSort and Phy are designed for linear probes and the sorting will not be affected since the probes are independent.

**Comment by rclein94** [comment]
Thank you so much!! I will definitely give that a try!!

**Comment by Tywang-720** [comment]
We have similar issues.

Previously I tested KiloSort3 using some 1024 channel map. 

Then, when I tried to run some 128 channel recording, KiloSort3 keeps telling me " index exceeds the number of array elements" at whitening stage.

Perhaps its trying to use the old 1024 channel setting, even though I have already entered a new 128 channel map.

**Comment by rclein94** [comment]
I think that is the same problem I'm having @Tywang-720 . Have you had any luck with it?
