### ISSUE TITLE
GPU type

### ISSUE THREAD

**Issue by shira-hadar** [MouseLand/Kilosort#365]
Hello,

Will Nvidia GPU quadro p1000 or p2000 will be suitable for using Kilosort?

Thanks in advance,
Shira

**Comment by marius10p** [comment]
Depends on your recording size, but you can get much more powerful GPUs for the same money from the GTX and RTX series.

**Comment by shira-hadar** [comment]
Which one from the GTX or RTX series is recommended (for the same amount of money)?
Thank you!

**Comment by marius10p** [comment]
Right now, it's whatever you can actually buy, since there's a worldwide
GPU shortage. Maybe you can get an RTX 3060 if you search carefully.
Barring that, try to find a 2070, 2060 or 1080.

**Comment by shira-hadar** [comment]
Thank you!
