### ISSUE TITLE
error loading in data file kilosort 2.5

### ISSUE THREAD

**Issue by gregvoidman** [MouseLand/Kilosort#366]
Hi, 
I've started setting up Kilsort 2.5 on a new PC and am encountering the following error when I use the gui to load in a data file. 
How do I solve this?
Many thanks

The logical indices in position 1 contain a true value outside of the array bounds.

Error in ksGUI/updateDataView (line 873)
                        Wrot = obj.P.Wrot(conn,conn);

Error in ksGUI/updateFileSettings (line 541)
                obj.updateDataView()

Error in ksGUI/selectFileDlg (line 474)
                obj.updateFileSettings();

Error in ksGUI>@(~,~)obj.selectFileDlg (line 179)
                'Callback', @(~,~)obj.selectFileDlg);
 
Error while evaluating UIControl Callback.

**Comment by marius10p** [comment]
Looks like something is wrong in the configuration. Does the same recording and configuration work on your old PC?
