### ISSUE TITLE
timestamp.npy file got removed by ksGUI.m and rezToPhy.m

### ISSUE THREAD

**Issue by Linoki** [MouseLand/Kilosort#367]
Be careful while using Kilosort3 GUI while analyzing openephys recorded data. It wipes out the timestamps.npy file.

While using GUI version kilosort3, it sets output path same as data input path. In the final part when the results are written to be used in phy, which uses code rezToPhy2.m, it detects all existed .npy file and remove them. Which is problematic for openephys recorded data.

I solved this issue by change the output file folder line in ksGUI.m by adding a /kilosrt3 folder to original input path, which is what is been done in main_kilosort. I wish it were done in ksGUI.m before I notice this issue.

Just want to alert people who use openephys and kilosort3 GUI. Either manually make sure you used a different output folder, or add a line in ksGUI.m to automatically generate a new sub folder. Maybe developers can update this small issue for everyone.

**Comment by marius10p** [comment]
Thanks, yes, we should do that. I forgot to update it in the GUI.
