### ISSUE TITLE
Error in extractTemplatesfromSnippets

### ISSUE THREAD

**Issue by nicolomeneghetti** [MouseLand/Kilosort#368]
Hello there.

I am trying to use Kilosort3 for sorting spikes collected from a single-shank 16 channels linear probe.

Unfortunately I receive the following error message:

Error using gpuArray/subsref
Subscript indices must either be real positive integers or logicals.

Error in extractTemplatesfromSnippets (line 56)
wTEMP = dd(:, round(linspace(1, size(dd,2), nPCs)));

Error in extract_spikes (line 42)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in ksGUI/runSpikesort (line 795)
                [obj.rez, st3, tF]     = extract_spikes(obj.rez);

Error in ksGUI/runAll (line 634)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 321)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.

I have already tried to decrease the ks.ops.spkTh  to -4 (even -1) but I keep receiving the same error message. 

Thank you in advance for the help.

Best,

Nicolò

![Immagine](https://user-images.githubusercontent.com/82510633/114719649-972cf480-9d37-11eb-8248-e1df5ff75b21.png)

**Comment by nicolomeneghetti** [comment]
Here's also what kilosort GUI is printing in the command window.



Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   1s. Loading raw data and applying filters... 
Time  70s. Finished preprocessing 1665 batches. 
vertical pitch size is 1 
horizontal pitch size is 5 
     1

     5

0.02 sec, 1 batches, 48 spikes 
1.21 sec, 101 batches, 7295 spikes 
2.35 sec, 201 batches, 16173 spikes 
3.53 sec, 301 batches, 25350 spikes 
4.66 sec, 401 batches, 35897 spikes 
5.81 sec, 501 batches, 46898 spikes 
6.93 sec, 601 batches, 58542 spikes 
8.10 sec, 701 batches, 69659 spikes 
9.24 sec, 801 batches, 79716 spikes 
10.40 sec, 901 batches, 91155 spikes 
11.53 sec, 1001 batches, 102593 spikes 
12.68 sec, 1101 batches, 113405 spikes 
13.84 sec, 1201 batches, 125685 spikes 
14.97 sec, 1301 batches, 138871 spikes 
16.12 sec, 1401 batches, 151976 spikes 
17.27 sec, 1501 batches, 165035 spikes 
18.44 sec, 1601 batches, 178168 spikes 
19.18 sec, 1665 batches, 187118 spikes 
time 71.23, Shifted up/down 1665 batches.

**Comment by nicolomeneghetti** [comment]
I have solved this issue simply by modifying the channel maps. For example, for a linear 16 channel probe here's what I have put:

X coordinates: zeros(1,16)
Y coordinates: 50*[1:16]      %the electrodes have 50 um of spacing
Shank index: ones(1,16)
Chanel Map: 1:16

**Comment by TAK95** [comment]
Ciao Nicolo,
I have recently started using Kilosort3 for spike sorting, and I was wondering if you also have experience with the upgraded version. Then I might have some questions for you, if that is possible
