### ISSUE TITLE
How were units sorted/merged across days in the neuropixels 2.0 paper

### ISSUE THREAD

**Issue by timsainb** [MouseLand/Kilosort#370]
Hi @marius10p congrats on the new paper!

I was hoping you could shed some light on how you sorted units over days/weeks in the paper. I couldn't find an explanation in the paper/supplemental, beyond this:

> To track neurons across sessions, we implemented a version of the motion correction algorithm that inferred and corrected the shift only at the point where datasets from the 2 days are spliced together, i.e., at the end of the first and start of the second dataset (see materials and methods). After this step, spikes were sorted together across the splicing point, using only the shapes and spatial footprints of the waveforms. Thus, spikes were joined into single clusters across days without reference to their functional properties

Do you have a code example? Was there any curation for merging units over days? 

Thanks,
Tim

**Comment by marius10p** [comment]
Good catch, sorry for the lack of detail. There is one branch of Kilosort2 where this is implemented, but I think I have to clean it up first. It just does drift correction across the splicing point, before running Kilosort2 on the concatenated file. We've been trying to update this branch to 2.5 (and 3.0), but weirdly only the original 2.0 version worked well. 

I will come back here with an update once I update the chronic branch,

**Comment by timsainb** [comment]
Hey @marius10p and @achristensen56 did you ever put together something there? I was thinking about trying to write a spikeinterface plug in, it would be useful to have some reference material. Thanks!

**Comment by timsainb** [comment]
Hey - I just wanted to check in again on this now that you've released KS4.

**Comment by marius10p** [comment]
Sorry no, that was not a goal of this release, nor is the original strategy compatible with Kilosort4 (we don't have the non parametric tracking from Kilosort2). You can look at the other tools people have shared for merging cells over days. You can also hope that Kilosort4 just works now if you concatenate data over days. The step drift simulation suggests it might.

**Comment by timsainb** [comment]
All good! Thanks for the quick reply. Closing this unless you have a suggestion for a merging tool you like/reccomend.
