### ISSUE TITLE
error in the second clustering Kilosort 3

### ISSUE THREAD

**Issue by ffredes** [MouseLand/Kilosort#382]
Hi There,

I am getting the following error in the second clustering, any idea? 

Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time  10s. Loading raw data and applying filters... 
Time 362s. Finished preprocessing 1648 batches. 
vertical pitch size is 20 
horizontal pitch size is 32 
    11    27    43    59

   766

0.42 sec, 1 batches, 4656 spikes 
39.71 sec, 101 batches, 406023 spikes 
78.81 sec, 201 batches, 826152 spikes 
118.01 sec, 301 batches, 1252951 spikes 
157.25 sec, 401 batches, 1701173 spikes 
196.49 sec, 501 batches, 2164584 spikes 
235.63 sec, 601 batches, 2619168 spikes 
274.88 sec, 701 batches, 3108314 spikes 
314.04 sec, 801 batches, 3617258 spikes 
353.32 sec, 901 batches, 4128989 spikes 
392.53 sec, 1001 batches, 4630613 spikes 
431.76 sec, 1101 batches, 5133229 spikes 
471.02 sec, 1201 batches, 5651280 spikes 
510.35 sec, 1301 batches, 6142099 spikes 
549.60 sec, 1401 batches, 6655371 spikes 
588.93 sec, 1501 batches, 7169510 spikes 
628.13 sec, 1601 batches, 7697526 spikes 
646.56 sec, 1648 batches, 7945398 spikes 
time 1016.17, Shifted up/down 1648 batches. 
0.45 sec, 1 batches, 5014 spikes 
42.62 sec, 101 batches, 432228 spikes 
85.68 sec, 201 batches, 898052 spikes 
129.62 sec, 301 batches, 1384767 spikes 
173.36 sec, 401 batches, 1899742 spikes 
218.13 sec, 501 batches, 2437166 spikes 
262.62 sec, 601 batches, 2971007 spikes 
307.30 sec, 701 batches, 3544711 spikes 
353.19 sec, 801 batches, 4138114 spikes 
397.68 sec, 901 batches, 4741180 spikes 
443.92 sec, 1001 batches, 5327894 spikes 
488.64 sec, 1101 batches, 5916443 spikes 
535.35 sec, 1201 batches, 6513932 spikes 
580.27 sec, 1301 batches, 7076577 spikes 
625.13 sec, 1401 batches, 7665253 spikes 
672.56 sec, 1501 batches, 8245563 spikes 
717.34 sec, 1601 batches, 8837103 spikes 
741.30 sec, 1648 batches, 9114335 spikes 
time 0.00, GROUP 1/96, units 0 
time 35.43, GROUP 6/96, units 61 
time 79.09, GROUP 11/96, units 127 
time 108.01, GROUP 16/96, units 164 
time 128.45, GROUP 21/96, units 196 
time 193.70, GROUP 26/96, units 277 
time 257.18, GROUP 31/96, units 354 
time 265.34, GROUP 36/96, units 374 
time 269.02, GROUP 41/96, units 383 
time 314.44, GROUP 46/96, units 459 
time 368.54, GROUP 51/96, units 539 
time 378.73, GROUP 56/96, units 556 
time 385.62, GROUP 61/96, units 569 
time 397.81, GROUP 66/96, units 593 
time 445.20, GROUP 71/96, units 665 
time 466.50, GROUP 76/96, units 706 
time 504.04, GROUP 81/96, units 757 
time 562.81, GROUP 86/96, units 834 
time 624.45, GROUP 91/96, units 922 
time 654.29, GROUP 96/96, units 963 
Elapsed time is 655.336247 seconds.
Time 660s. Final spike extraction ...
660.46 sec, 1 / 1648 batches, 965 units, nspks: 6373, mu: 16.3769, nst0: 6373 
695.14 sec, 101 / 1648 batches, 965 units, nspks: 565339, mu: 16.3769, nst0: 5252 
731.91 sec, 201 / 1648 batches, 965 units, nspks: 1180107, mu: 16.3769, nst0: 6235 
769.83 sec, 301 / 1648 batches, 965 units, nspks: 1831326, mu: 16.3769, nst0: 5956 
809.39 sec, 401 / 1648 batches, 965 units, nspks: 2528950, mu: 16.3769, nst0: 9687 
849.95 sec, 501 / 1648 batches, 965 units, nspks: 3259123, mu: 16.3769, nst0: 6119 
889.95 sec, 601 / 1648 batches, 965 units, nspks: 3973284, mu: 16.3769, nst0: 6733 
931.68 sec, 701 / 1648 batches, 965 units, nspks: 4739757, mu: 16.3769, nst0: 8171 
974.14 sec, 801 / 1648 batches, 965 units, nspks: 5530888, mu: 16.3769, nst0: 8262 
1017.18 sec, 901 / 1648 batches, 965 units, nspks: 6333857, mu: 16.3769, nst0: 6535 
1059.43 sec, 1001 / 1648 batches, 965 units, nspks: 7121962, mu: 16.3769, nst0: 8297 
1101.70 sec, 1101 / 1648 batches, 965 units, nspks: 7907125, mu: 16.3769, nst0: 8879 
1144.22 sec, 1201 / 1648 batches, 965 units, nspks: 8698630, mu: 16.3769, nst0: 6799 
1185.19 sec, 1301 / 1648 batches, 965 units, nspks: 9445056, mu: 16.3769, nst0: 7076 
1231.87 sec, 1401 / 1648 batches, 965 units, nspks: 10220245, mu: 16.3769, nst0: 6305 
1273.19 sec, 1501 / 1648 batches, 965 units, nspks: 10992338, mu: 16.3769, nst0: 10856 
1315.17 sec, 1601 / 1648 batches, 965 units, nspks: 11770360, mu: 16.3769, nst0: 7660 
Elapsed time is 1334.745226 seconds.
time 0.00, GROUP 1/96, units 0 
Error using ccg
Too many output arguments.

Error in bimodal_pursuit (line 112)
    [K, Qi, Q00, Q01, rir] = ccg(ss1, ss2, 500, dt); % compute the cross-correlogram between spikes in the putative new clusters

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin, use_CCG);

Error in final_clustering (line 92)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in ksGUI/runSpikesort (line 795)
                obj.rez                = final_clustering(obj.rez, tF, st3);

Error in ksGUI>@(~,~)obj.runSpikesort() (line 337)
                'Callback', @(~,~)obj.runSpikesort());
 
Error while evaluating UIControl Callback.

**Comment by marius10p** [comment]
This actually happens in the post-processing in the ccg function. I think you might have an old version of Kilosort in the path, that you need to remove.

**Comment by ffredes** [comment]
Thank you! Solved!
