### ISSUE TITLE
Kilosort running Error

### ISSUE THREAD

**Issue by paul-aparicio** [MouseLand/Kilosort#384]
Hello, I am having two problems while running kilosort3 and I am not really sure how to utilize the error messages to figure out what is wrong with my data, any help would be very appreciated. I am running kilosort 3 on matlab 2020b on ubuntu 18.04.

(1)  The first error I get is the following: 
  Error Running Kilosort! An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument.
(2) The second error is:
  Error saving data to phy! Reference to non-existent field 'Wphy'

The output to the command window is:
>> 
Channel-whitening matrix computed. 
Time   8s. Loading raw data and applying filters... 
Time 717s. Finished preprocessing 2545 batches. 
pitch is 400 um
0.09 sec, 1 batches, 10000 spikes 
8.75 sec, 101 batches, 994143 spikes 
27.28 sec, 201 batches, 1922768 spikes 
35.73 sec, 301 batches, 2814145 spikes 
44.20 sec, 401 batches, 3644829 spikes 
52.46 sec, 501 batches, 4537196 spikes 
60.97 sec, 601 batches, 5462584 spikes 
69.40 sec, 701 batches, 6422091 spikes 
78.44 sec, 801 batches, 7422091 spikes 
86.92 sec, 901 batches, 8418679 spikes 
95.27 sec, 1001 batches, 9351200 spikes 
103.60 sec, 1101 batches, 10211299 spikes 
112.26 sec, 1201 batches, 11123574 spikes 
120.66 sec, 1301 batches, 11960540 spikes 
129.02 sec, 1401 batches, 12862619 spikes 
137.50 sec, 1501 batches, 13794744 spikes 
145.69 sec, 1601 batches, 14701479 spikes 
153.98 sec, 1701 batches, 15596164 spikes 
162.27 sec, 1801 batches, 16528884 spikes 
170.67 sec, 1901 batches, 17528884 spikes 
179.41 sec, 2001 batches, 18475806 spikes 
187.53 sec, 2101 batches, 19409601 spikes 
189.55 sec, 2201 batches, 20284130 spikes 
191.59 sec, 2301 batches, 21215634 spikes 
193.86 sec, 2401 batches, 22115751 spikes 
195.72 sec, 2501 batches, 22362084 spikes 
196.53 sec, 2545 batches, 22362084 spikes 
time 541.99, Shifted up/down 2545 batches. 
Time 546s. Optimizing templates ...

**Comment by marius10p** [comment]
Looks like too many spikes. What kind of probe is this? Is the pitch really 400um? Maybe there is a configuration error, does the data look right in the GUI ?

**Comment by paul-aparicio** [comment]
Thank you for your reply. The probe is a 96 channel utah array. I have the probe configured as an imaginary line where the distance between probes is set to 400um. The data looks fine in the gui, and I have run several smaller datasets (2-3gb) through successfully with the same configuration, but larger datafiles (~32gb) produce the same error.

**Comment by marius10p** [comment]
What gpu are you using? Do you get the same error in Kilosort 2.5?

**Comment by paul-aparicio** [comment]
Hi, I am using an RTX2070 Super (8gb memory). I have tried the dataset using 2.5 and 3.0, both return the same error.

**Comment by marius10p** [comment]
Send a screenshot of the data from the GUI please. Both the raw and
filtered views.

**Comment by paul-aparicio** [comment]
Here are a few screen shots of two time points (filtered and raw):
 
![Screenshot from 2021-05-03 09-33-34](https://user-images.githubusercontent.com/25209714/116891099-f02fd000-abf3-11eb-8e2a-ff5022b59bff.png)
![Screenshot from 2021-05-03 09-33-57](https://user-images.githubusercontent.com/25209714/116891109-f32ac080-abf3-11eb-9049-0dcbc922c08c.png)

![Screenshot from 2021-05-03 09-34-25](https://user-images.githubusercontent.com/25209714/116891138-f9b93800-abf3-11eb-9430-b361c48a1f22.png)
![Screenshot from 2021-05-03 09-34-41](https://user-images.githubusercontent.com/25209714/116891148-fc1b9200-abf3-11eb-9cc0-b0db4d0c9b50.png)


![Screenshot from 2021-05-03 09-39-55](https://user-images.githubusercontent.com/25209714/116891188-08075400-abf4-11eb-9f7c-b31aea0508bb.png)
![Screenshot from 2021-05-03 09-40-10](https://user-images.githubusercontent.com/25209714/116891198-0b024480-abf4-11eb-9c97-a0ada8457ec3.png)

![Screenshot from 2021-05-03 09-39-14](https://user-images.githubusercontent.com/25209714/116891229-15bcd980-abf4-11eb-86a9-5f4c31e5a501.png)
![Screenshot from 2021-05-03 09-39-33](https://user-images.githubusercontent.com/25209714/116891261-1bb2ba80-abf4-11eb-837f-bdf8d3169b9b.png)
With the scale increased to better show the filtered data
![Screenshot from 2021-05-03 09-40-43](https://user-images.githubusercontent.com/25209714/116891273-1f464180-abf4-11eb-82e0-ba50436f5880.png)

**Comment by paul-aparicio** [comment]
Hi @marius10p , were these images ok?
