### ISSUE TITLE
Error while evaluating UIControl Callback

### ISSUE THREAD

**Issue by Hojeongg** [MouseLand/Kilosort#387]
Hi, I'm running kilosort3 for my data, but I have an issue with running the gui. My data file and the probe layer can be select via the gui, but nothing happens in the data view panel. Probe view panel is working tho.
The error code I got is

Unrecognized function or variable 'get_file_size'.

Error in ksGUI/checkNChan (line 578)
                b = get_file_size(obj.H.settings.ChooseFileEdt.String);

Error in ksGUI/updateFileSettings (line 533)
            nChan = obj.checkNChan();

Error in ksGUI>@(~,~)obj.updateFileSettings() (line 281)
                'String', '30000', 'Callback', @(~,~)obj.updateFileSettings());
 
Error while evaluating UIControl Callback.

I wonder what the problem was..Can anyone tell me what should I fix?

**Comment by krlee0000** [comment]
Hi
