### ISSUE TITLE
ERROR in DATA REPRESENTATION & SPIKE SORTING but not with data preprocessing... HELP pls!

### ISSUE THREAD

**Issue by epmgs97** [MouseLand/Kilosort#391]
Hi Marius, 
Pleasure! I have some issues with Kilosort GUI, it seems to have not read my data correctly (19 linear channels in a 3 sec 25Khz Fs probe). Kilosort GUI shows 19 flat lines in the traces mode representation and nothing in the colormap mode (like if the file was empty). The matrix is structure following the instructions at (https://github.com/MouseLand/Kilosort/wiki/1.-The-GUI)    and in    ( https://github.com/cortex-lab/KiloSort/blob/master/configFiles/createChannelMapFile.m). Despite this, Kilosort reports me no errors, so I suppose something may be happening the default parameters?

*This is how my data looks in the GUI... (I hope you are able to see the images cause I can not)
![Foto1](https://user-images.githubusercontent.com/58771490/116671204-f67a3e00-a9a0-11eb-9a5c-eca3fe0d3b17.PNG)
![foto2](https://user-images.githubusercontent.com/58771490/116671201-f5e1a780-a9a0-11eb-9bc8-85240f61f39a.PNG)

I have tried to zoom in the GUI but with no success nor change... and I really don't know whats going on.  Moreover, when I try spike sorting kilosort reports me an error  with an undefined function or variable 'W': 
![foto3](https://user-images.githubusercontent.com/58771490/116671202-f67a3e00-a9a0-11eb-8c2f-1975674ca676.PNG)

Any help on what may be causing this problem and how to solve it would be appreciated.
Thanks for yor time,

Cheers

**Comment by marius10p** [comment]
The data should be an an int16 binary file. This looks like either the file only has zeros, or the format is different. Also, 3 sec is really short, I would try to start with a 60sec file just to make sure you don't run into other strange problems.

**Comment by epmgs97** [comment]
Thanx Marius, you've been very helpful. I will give that a try!

**Comment by epmgs97** [comment]
Hello again Marius,
Enrique here, still working! My data is in a ".txt" format; the matrix inside the ".txt" file is structured as [nChannels x nTimepoints] and the voltage values of the recordings are all decimals "0.something" or "-0.something" (data matrix picture bellow; hope you can see it). This in fact appears to be problematic for the convertion into int16 datatype...

<img width="522" alt="Captura2" src="https://user-images.githubusercontent.com/58771490/117495421-e1d81000-af75-11eb-8ce4-4026d78ab7fd.PNG">

I have tried to load this data using the code in (https://github.com/MouseLand/Kilosort/wiki/1.-The-GUI), but when I convert it into a int16 datatype it transforms the data inside the matrix into zeros. Appears to be only taking the integers from my data ("0" in this case because they are all decimals) to create the matrix then save in the ".bin" file (that is why in Kilosort is empty when I run the ".bin" wtih my data). 

Is there anything I can do to make my data suitable to Kilosort?

Again, thank you for your time,

Cheers
