### ISSUE TITLE
Minimum pitch and specifying channel maps (difference from v.2.0)

### ISSUE THREAD

**Issue by shiralupkin** [MouseLand/Kilosort#396]
Hi, 

I am new to kilosort and have a few (related) questions about how to specify pitch (vertical and horizontal) in the mapping files and about the  pitch minimums (implicit for vertical, explicit for horizontal) in v3.

- My understanding is that vertical pitch is determined based off of the difference between the values specified in ycoords and xcoords for horizontal. My first question is to confirm that the units for the coordinates are in um, right? (as opposed to, say, mm)

- There is a minimum horizontal pitch of 5, and therefore the program defaults to 5 if anything less is given. What do you do for single linear probes where there is no horizontal spacing (I am using 32-channel linear vprobes with 50um spacing between contacts)? Does the fact that kilosort defaults to 5 pose a problem for these types of electrodes?

- In v3, the interpolation on line 14 of shift_batch_on_disk2 fails if the vertical pitch is anything smaller than 3 (I tested it and 3 works fine, 1 and 2 fail). I think I saw that another person noted an issue with this step a few days ago. Is there a minimum vertical pitch requirement?

- In v2.0, neither of these pitch requirements seem to come into play (you can input a horizontal pitch of 0 and a vertical pitch of 1 and the program will run without issue). So, what role does pitch play (vertical and/or horizontal) in the respective versions? Do the minimums in v3 preclude users whose probes do not meet them?

Thank you for this great program!

**Comment by marius10p** [comment]
The pitch is used only in v3, and only to determine how to group channels for the clustering algorithm. V2.0 uses a different clustering algorithm. As long as it runs, it should be fine.

**Comment by marius10p** [comment]
For your probe you can use 100um for the vertical and that should roughly be what Kilosort determines.

**Comment by shiralupkin** [comment]
Sorry, I promise this is the last question. But, if I know I have 50um spacing vertically, why would I enter 100? My question is much more about the horizontal pitch and whether letting it default to 5 will cause any problems.


-----

Shira M. Lupkin

Ph.D. Candidate - McGinty Laboratory

Behavioral and Neural Sciences Graduate Program

Rutgers University - Newark

***@***.***


________________________________
