### ISSUE TITLE
CUDA_ERROR_LAUNCH_FAILED for gpuArray

### ISSUE THREAD

**Issue by LiuDaveLiu** [MouseLand/Kilosort#398]
I got an error in KS2.5 that I can't figure out, the drif map looks fine for the Neuropixels 1.0 data.

The full error is,

Warning: An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_LAUNCH_FAILED
> In learnTemplates (line 4)
In learnAndSolve8b (line 35)
In main_kilosort_multiversion (line 61)
Warning: An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_LAUNCH_FAILED
> In learnAndSolve8b (line 5)
In main_kilosort_multiversion (line 61)
Error using gpuArray/reshape
An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_LAUNCH_FAILED

Error in learnTemplates (line 185)
    fexp = reshape(fexp, 1,1,[]);

Error in learnAndSolve8b (line 35)
    rez     = learnTemplates(rez, rez.iorig);

Error in main_kilosort_multiversion (line 61)
        rez = learnAndSolve8b(rez, iseed);

My gpuDevice() is 
CUDADevice with properties:

                      Name: 'Quadro M4000'
                     Index: 1
         ComputeCapability: '5.2'
            SupportsDouble: 1
             DriverVersion: 10.2000
            ToolkitVersion: 10.2000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 8.5899e+09
           AvailableMemory: 7.5819e+09
       MultiprocessorCount: 13
              ClockRateKHz: 772500
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

**Comment by YGUO29** [comment]
It looks like I have the same error. How did you solve it?
