### ISSUE TITLE
Information about threshold parameters

### ISSUE THREAD

**Issue by llobetv** [MouseLand/Kilosort#399]
Hi,

I'd like to use kilosort2 but I have some question about parameters, it's not totally clear for me.

There is 3 parameters about threshold (see below), and I don't manage to understand the exact application for all thease threshold. Could you give me more info about that?

ops.Th = [10 4];  
ops.ThPre = 8; 
ops.spkTh = -6;

Furthermore, ops.spkTh is signed, so does it mean that kilosort 2 only detect negative spikes? (I have a lot of positive spikes)

Thank you,

Best,
Victor

**Comment by TomBugnon** [comment]
https://github.com/cortex-lab/KiloSort/issues/118#issuecomment-389313432

**Comment by Dradeliomecus** [comment]
Could we get a little bit more information please?

It says `ops.Th` is the threshold on a per spike basis. But why is there 2 values?
It doesn't answer what `ops.ThPre` is.
Also, we did not understand the explanation for `ops.spkTh` ...

Thank you!

**Comment by florian6973** [comment]
Hi,

I was reading spikeinterface documentation, and I was finding that the description between 'detect_cluster' (spkTh), 'projection_threshold' (Th) and 'preclust_threshold' (ThPre) is not very clear.

By any chance has someone figured it out? Thanks!

Best,
