### ISSUE TITLE
nt0 is hard-coded

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#401]
Hello,
I've been experimenting with increasing the sample window nt0 to =81 in kilosort3 (but this issue probably exists in kilosort2+), as my spikes are very long.
unfortunately, I've had to recursively change many lines in the code to do that, as the 61 value is assumed at various points in the code. 

not sure I got it all.

perhaps you can fix this more easily than me.

thanks

**Comment by JonathanAMichaels** [comment]
Were you able to get the code working for nt0 > 61 @WeissShahaf? I changed all the hardcoded entries, but I'm getting CUDA errors. So, there may be aspects of the CUDA code that do not allow this.

**Comment by WeissShahaf** [comment]
@JonathanAMichaels 
yes, i went up to 81. without issue.

**Comment by WeissShahaf** [comment]
81 worked for me. but i did have to change alot of code

**Comment by WeissShahaf** [comment]
unfortunately no. sorry.
i quit using kilosort since, maybe will return one day

**Comment by JonathanAMichaels** [comment]
@WeissShahaf do you still have that code lying around anywhere that you could send for me to look at? It seems that nt0 > 64 breaks mexGetSpikes2.cu

**Comment by WeissShahaf** [comment]
I used a value of 81 specifically.

Shahaf Weiss, PhD

Max Planck Institute for Brain Research

NSK - Laurent department
Max-von-Laue-Str. 4
60438 Frankfurt am Main, Germany
www.brain.mpg.de

***@***.***

***@***.***

Tel:+49 17657814689
