### ISSUE TITLE
More informative error for GPU memory errors [Feature request]

### ISSUE THREAD

**Issue by timsainb** [MouseLand/Kilosort#404]
I noticed that when you're GPU's is over-allocated by another process, not allowing kilosort to run, the error message is pretty opaque. 

It would probably make sense to add a check in kilosort at some point to see how much memory is available and raise a flag letting them know if they need to free up some GPU memory. 

```
An unexpected error occurred during CUDA execution. The CUDA error was:

CUDA_ERROR_ILLEGAL_ADDRESSError using gpuArray/sum

An unexpected error occurred during CUDA execution. The CUDA error was:

CUDA_ERROR_ILLEGAL_ADDRESSWarning: An unexpected error occurred during CUDA execution. The CUDA error

was:

CUDA_ERROR_ILLEGAL_ADDRESS 
```

**Comment by marius10p** [comment]
Sorry, this would be impossible, because the CUDA scheduler assigns computation blocks on the GPU in pseudo-random order and it's impossible to predict how much GPU RAM it needs at any one time. However, I think there should never be another process running on the GPU while Kilosort is running, since you'll be getting slowdowns well before you get actual errors.

**Comment by timsainb** [comment]
Hey Marius, 

For what it's worth, I've implemented this in my python wrapper and it works just fine. I've got multiple GPUs per machine and I look for the one with the most GPU memory available. If there's not enough memory on the device (ballpark) I raise an error. II also have no trouble running kilosort alongside other GPU intensive processes on the same core, so long as other processes haven't allocated too much of the GPU. Maybe something like this will be useful for other users:

```python
def get_gpu_memory():
    _output_to_list = lambda x: x.decode("ascii").split("\n")[:-1]

    ACCEPTABLE_AVAILABLE_MEMORY = 1024
    COMMAND = "nvidia-smi --query-gpu=memory.free --format=csv"
    memory_free_info = _output_to_list(sp.check_output(COMMAND.split()))[1:]
    memory_free_values = [int(x.split()[0]) for i, x in enumerate(memory_free_info)]
    return memory_free_values


def choose_gpu():
    free_gpu_memory = get_gpu_memory()
    print("Free memory: {}".format(free_gpu_memory))
    gpu_to_use = np.argmax(free_gpu_memory)
    print("GPU to use: {}".format(gpu_to_use))
    print("Setting GPU")
    os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
    os.environ["CUDA_VISIBLE_DEVICES"] = "{}".format(gpu_to_use)
```

**Comment by marius10p** [comment]
If the goal is just to choose the GPU with the most available memory, you can do that outside of Kilosort, or in the Matlab script that you use to run Kilosort. 

However, estimating the amount of GPU RAM required by Kilosort for an arbitrary dataset would be a very painful task, as there are ~50 variables dynamically allocated and destroyed across all the CUDA kernels we use.

**Comment by timsainb** [comment]
Agreed, you definitely wouldn't want to make a dynamic estimate. 

I thought it wouldn't be too difficult to make a reasonable estimate at the beginning of kilosort of the max memory needed during whatever part of kilosort has the biggest memory bottleneck and raise an error if that memory isn't available at the beginning of the sort. Rather than waiting till that part of the sort is reached then failing. 

Maybe I'm wrong and those numbers are based on variables you can't know till you reach them (e.g. the # of channels & batch size are known beforehand while # of clusters templates aren't).
