### ISSUE TITLE
Local instead of global CAR?

### ISSUE THREAD

**Issue by pbotros** [MouseLand/Kilosort#413]
Have there been any attempts at using a "local" common-average-referencing (CAR) scheme, as opposed to global? "Local" CAR -- which is how it's termed in the original Neuropixels Nature paper -- would be subtracting from a given channel the mean (or median) of a handful of channels spatially close to it. My understanding is that Kilosort2 currently implements "global" CAR, which is the median across _all_ channels on the shank.

In some of our chronic recordings in freely behaving rats, we occasionally see large-amplitude spikes across many, but not all, channels, typically corresponding to chewing on enrichment, itching, or otherwise clenching the jaw/moving the head. A first-pass at implementing "local" CAR on this snippet of data seems to work better at removing these artifacts than global:

[example_noise_traces.pdf](https://github.com/MouseLand/Kilosort/files/6660538/example_noise_traces.pdf)

where "local" CAR here is implemented as using the median of the closest 8 channels more than 100 microns away but less than 200 microns away. Trying a few combinations of parameters seems to work relatively the same (e.g., using 4 channels instead of 8, having a > 50 micron threshold instead of 100, etc.).

Have there been any thoughts or attempts of using "local" CAR instead of global CAR in Kilosort? If so, any suggestions on parameters? I'm happy to try to add an option to allow for this; I haven't tried this yet to see if/how it impacts the actual sorted spikes.

**Comment by LaurenzMuessig** [comment]
Hi,
Not sure if this helps, but if you use spikeglx to record your data you can use the command line tool 'CatGt' from BIll Karsh to use a local CAR and you can also use a custom artifact removal option, before kilosorting your data. 
https://billkarsh.github.io/SpikeGLX/#catgt

Laurenz

**Comment by pbotros** [comment]
Good point! Seems like CatGT already implements two types of non-global CAR, one within the channels on a single ADC and another based on physical location. I'm asking around on the NP slack to see what the former's implementation is like so that we could replicate it here / in other packages.
