### ISSUE TITLE
High rate of zero-lag autocorrelogram (ACG) peak

### ISSUE THREAD

**Issue by ArAbolghasemi** [MouseLand/Kilosort#415]
We did recording with Neuropixels probe and used Kilosort3 with default setting for spike sorting. After spike sorting there were lots of units with zero-lag autocorrelogram (ACG) peak, like the following examples.
I am wondering what is the reason of these zero-lag ACG peaks and how can I solve this problem? Sorry for my questions I am really new to this field.

![e1](https://user-images.githubusercontent.com/57106378/122807874-6683b100-d2cc-11eb-9450-8e6387948d10.png)
![e2](https://user-images.githubusercontent.com/57106378/122807907-73a0a000-d2cc-11eb-98cf-287bdd22beb2.png)
![e3](https://user-images.githubusercontent.com/57106378/122807912-756a6380-d2cc-11eb-8a6a-75dd67dc4532.png)

**Comment by panichem** [comment]
I am encountering the same issue and would be interested in anyone's thoughts on this.

**Comment by LaurenzMuessig** [comment]
See #29  for more information on why that happens and what you can do as a workaround.

Cheers
