### ISSUE TITLE
Error in rezToPhy2

### ISSUE THREAD

**Issue by gaiabianchini** [MouseLand/Kilosort#419]
Hi all,
I am running Kilosort3 on Nueopixels dataset. All the output files are saved and it seems to work but it just crushes when saving the cluster_group and the params file. I made my own params file to check if the output was fine and I ran Phy2. The number of clusters and spikes seems reasonable so I don't really understand where this error is coming from.
This is what I get: 

```
Error using copyfile
Cannot write to destination:
/'dir'/kilosort3.
Use the 'f' option to override.
Error in rezToPhy2 (line 184)
    copyfile(KSLabelFilename, fullfile(savePath, 'cluster_group.tsv'));
Error in main_kilosort (line 52)
rezToPhy2(rez, rootZ);
```

Thank you for your help!

**Comment by czuba** [comment]
Looks like you've got some kind of mashup between an older & newer version of Kilosort.  The script version of running Kilosort3 is `main_kilosort3.m`, _not_ simply `main_kilosort.m`.  ...in the "3" version, it tacks on & creates a sub directory on top of your intended save directory, but that output directory appears to not exist in your usage.

https://github.com/MouseLand/Kilosort/blob/74c64485d8dd0bc5dd976d7bf51a46873b08351f/main_kilosort3.m#L50-L52
