### ISSUE TITLE
No prediction after whitening filter

### ISSUE THREAD

**Issue by prophesyPPI** [MouseLand/Kilosort#420]
Hello,
I am loading data in ks3, and in the data view, there is blank in prediction mode. I tried different parameters but still I cannot find a way.  Looking forward to your help. Lots of thanks.
![pic](https://user-images.githubusercontent.com/24997521/123513454-ed1b0280-d6bf-11eb-8262-c1ad0b363368.PNG)

**Comment by prophesyPPI** [comment]
I reckoned maybe the prediction will show up after preprocessing, but the preprocessing was aborted every times due to an error:
![pic2](https://user-images.githubusercontent.com/24997521/123530662-9cdb8900-d72f-11eb-80b4-1f27ebd71f3a.PNG)
Also, I read issue #134, in which the problem solved by flipping the data, but after flipping I still got the same problem. My data have a nagetive wave, so maybe my problem is a different one. Pls help me. Thanks!

**Comment by xy103** [comment]
Running into a similar issue with blank predictions. Adjusting the scale doesn't help at all. Would also really appreciate some help!
