### ISSUE TITLE
Channel map template construction

### ISSUE THREAD

**Issue by warnerwarner** [MouseLand/Kilosort#421]
Hi, I'm using Kilosort with probes for which we don't have a channelmap. I was under the impression that Kilosort doesn't need an accurate channel map, and the channel map was only used by phy for visualization. I've been running Kilosort with a single linear array of my channels, and I have noticed that the templates that are being generated have similar waveforms across neighbouring channels in the faux map I've generated. Is this correct, or does it in fact need to know the relative positioning of the channels for clustering?

Thanks,
Tom

**Comment by aboharbf** [comment]
Have you tried generating a map file with very large distances b/t xcoords and ycoords? The system might default to generate 1:NChannel arrays for these if you don't use them, and that may lead to the algorithm classifying units across channels.

**Comment by warnerwarner** [comment]
I'm sorry, I don't fully understand what you mean. If the algorithm defaults to using 1:Nchannel arrays then I'd still be in the same situation as I'm in now.

**Comment by aboharbf** [comment]
I mean rather than using 1:NChannel for instance, use 1:NChannel * pitch. For me, rather than 1:16, I'm using 1:16 * 100.

**Comment by warnerwarner** [comment]
Ah I see, but if I was to do that does it just act as 16 single channel spikesorters? E.g. will I be double counting some of my spikes? Unfortunately I know I'll have channels detecting spikes from the same unit, but I just can't say for sure there position relative to one another. I was wondering if Kilosort actually takes into account the positioning of the channels relative to one another when it does sorting? I had some impression that the templates are constructed using all channels and therefore the relative positioning of the channels doesn't matter.

**Comment by aboharbf** [comment]
I am under the same impression as you, but I imagine (though don't quote me) that the x y and z coordinates are factored into what constitutes a realistic cross channel spike and what doesn't. It seems like 2 identical wave forms on channels 50 um apart would be categorized as the same unit while the same events happening 1 mm apart would be categorized as distinct units. I myself lean towards providing as accurate information as possible and assuming the algorithm utilizes it in same way.
