### ISSUE TITLE
Kilosort3 - CUBLAS Error

### ISSUE THREAD

**Issue by aferguso2** [MouseLand/Kilosort#423]
I'm running into an issue sorting with ks3. I've seen other (closed) issues with CUBLAS error, but none of them have solutions. I'm running it on ~250GB of neuropixel data. I'm running on MATLAB 2018b

Error Message: 

Error using *
Call to sgemm in CUBLAS failed with error status:
CUBLAS_STATUS_EXECUTION_FAILED.

Error in preprocessDataSub (line 106)
    datr    = datr * Wrot; % whiten the data and scale by 200 for int16 range

Error in main_kilosort3 (line 77)
rez                = preprocessDataSub(ops);
}^H

**Comment by aboharbf** [comment]
Same problem, running MATLAB 2018a, CUDA 9.0 (Though I have an ampere card), and setup (mex -setup C++) with Microsoft Visual C++ 2013. Not sure whats up.

**Comment by j-moore94** [comment]
Hi, just wondering if anyone figured this out? I'm also running MATLAB 2018a with CUDA 9.0 and getting the same error.

Thanks!
