### ISSUE TITLE
CUDA 'invalid configuration' errors, and an odd fix

### ISSUE THREAD

**Issue by aboharbf** [MouseLand/Kilosort#427]
I've run into the error below twice:
`An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument.`

once in find extract_spikes, line 106, and a second time in template_learning, line 70. I've gotten around them replacing the code with a seemingly identical bit of code:

for extract spikes, 
```
    try
        st(5,:) = cF;
    catch 
        st = [st; cF];
    end
```

for template learning,
```
    try
        ich = unique(iC(:, itemp));
    catch
        tmpS = iC(:, itemp);
        ich = unique(tmpS);
    end
```

It seems like they function identically to the lines causing the error, but they appear to get around them. Something to try if you're having these issues.

**Comment by Yliew6-gt** [comment]
Hi, I am running to similar issue multiple times and can't seem to get around it in Kilosort 2.5. Can you share your code?

**Comment by JeffreyBoucher** [comment]
This solved an error I had with kilosort3 as well
