### ISSUE TITLE
sort several recordings as a single session

### ISSUE THREAD

**Issue by DanEgert** [MouseLand/Kilosort#428]
There's some cases where it's better to interrupt a recording but still to cluster/sort the segments like a single recording. For example when using multiple paradigms or sleep. Since recordings can get large it may not be straight forward to concatenate them before sorting. Is there a way for Kilosort to be pointed to multiple binary files and sort them as one? Thanks for any pointers.

**Comment by LaurenzMuessig** [comment]
Hi Dan. If you use spikeGLX you can use CatGT from Bill Karsh to concatonate files to a single binary (https://billkarsh.github.io/SpikeGLX/#catgt). Alternatively you can also use fread/fwrite in Matlab (fairly slow) or from a command line the cat or dd commands in linux or copy in Windows to generate a single binary from multiple recordings.  
Cheers
