### ISSUE TITLE
Double Counting shifted spikes

### ISSUE THREAD

**Issue by congcong96** [MouseLand/Kilosort#432]
It seems somehow, the spikes are shifted in time and double counted. You can tell by the overlay of the waveform and the peak at 0 in CCG. 
Not sure hoe did this happen. As only a subset of the spikes are double counted and the blue one has lower amplitude, my guess is that after subtracting the spike from the trace, a little bump is detected around the original spike.

![phy_screenshot_20210729175814_WaveformView](https://user-images.githubusercontent.com/54606463/127584073-fce381fa-d5cf-4091-ae64-97bfd10af28d.png)
![phy_screenshot_20210729175952_CorrelogramView](https://user-images.githubusercontent.com/54606463/127584087-9b52a787-ab38-418b-8fbb-ae28808efc60.png)
![phy_screenshot_20210729180352_AmplitudeView](https://user-images.githubusercontent.com/54606463/127584505-42ab87d3-d1f8-41e0-b602-dc14d5f9419d.png)
![phy_screenshot_20210729180328_ClusterView](https://user-images.githubusercontent.com/54606463/127584541-1db712d1-a119-4a69-92cc-ad95155b5b67.png)

**Comment by agbondy** [comment]
You are describing the same issue previously discussed here: https://github.com/MouseLand/Kilosort/issues/29

There is no perfect solution, but that thread provides some workarounds.
