### ISSUE TITLE
Turning Off Drift Correction

### ISSUE THREAD

**Issue by EricZhu0313** [MouseLand/Kilosort#433]
I'm testing Kilosort on some v-probe data. Since the spacing is too big to have one unit recorded on multiply channels, I assume the drift correction doesn't work well anyway, and it may mess up the data. So I'm wondering if there's any way to turn off the drift correction.

**Comment by dervinism** [comment]
In Kilosort3 this gives a subsequent error:
```
Unrecognized field name "dmin".

Error in template_learning (line 31)
dmin = rez.ops.dmin;
```

**Comment by ImJustKenSteel** [comment]
> In Kilosort3 this gives a subsequent error:
> 
> ```
> Unrecognized field name "dmin".
> 
> Error in template_learning (line 31)
> dmin = rez.ops.dmin;
> ```
 
Hello,

Please could you get back to me if you found a fix for this because I am encountering the same issue.

Best wishes,

Ken

**Comment by dervinism** [comment]
Hi,

No, I don't think I was able to solve this issue. I tried it for testing purposes and it didn't work, so I switched back to drift correction. Why do you want to switch off drift correction?

**Comment by ImJustKenSteel** [comment]
Hi, 

Thanks for getting back to me, I  don't want to turn it off but I am having an issue running kilosort3.

Unrecognized field name "dmin".

Error in template_learning (line 31)
dmin = rez.ops.dmin;

Error in master_file_kilosort3_Kenneth (line 42)
rez                = template_learning(rez, tF, st3); 
 
I am a kilosort novice and so I am stumped at this error as to why dmin does not exist.
