### ISSUE TITLE
preprocessing error - interp1 when finding spikes

### ISSUE THREAD

**Issue by neurojaym** [MouseLand/Kilosort#434]
I'm running preprocessing for a 32channel linear probe array, feeding in the continuous.dat file from open ephys and I'm getting the following error. Any idea where this could be coming from? Notably, there are 32 channels/wires on the probe and 32 channels in the probe file, but the continuous.dat file has channels 33-35 because there's an accelerometer that is also feeding data into open ephys. But I figured since the channel map file matches the number of wires, the first 32 channels should be selected for preprocessing and the final 3 accelerometer channels will be ignored. Any ideas hwere this ascending order error may come from? Is this a timestamp issue?:

28.65 sec, 1601 batches, 1152 spikes 
30.39 sec, 1701 batches, 1254 spikes 
31.17 sec, 1744 batches, 1254 spikes 
Error using matlab.internal.math.interp1
Sample points must be unique and sorted in ascending order.

Error in interp1 (line 188)
        VqLite = matlab.internal.math.interp1(X,V,method,method,Xqcol);

Error in shift_batch_on_disk2 (line 14)
    shifts = interp1(ysamp, shifts, rez.yc, 'makima', 'extrap');

Error in datashift2 (line 149)
        dprev = shift_batch_on_disk2(rez, ibatch, dshift(ibatch, :), yblk, sig,
        dprev);

Error in ksGUI/runPreproc (line 732)
                obj.rez = datashift2(obj.rez, 1);

Error in ksGUI>@(~,~)obj.runPreproc() (line 333)
                'Callback', @(~,~)obj.runPreproc());
 
Error while evaluating UIControl Callback.

**Comment by hbirge06** [comment]
I am having the same error- did you find the issue?

**Comment by Lorena-J** [comment]
I am having the same error, did you find the issue???
