### ISSUE TITLE
Not able to detect spikes from tetrode data in kilosort 2.0

### ISSUE THREAD

**Issue by EdShen-hub** [MouseLand/Kilosort#437]
Hello, 

I ran into a **spike detection** problem on my sample **tetrode** data (5 mins long, 16 channels, converted from plx file) in **kilosort 2.0.**

This is a screenshot of the GUI I used to run kilosort 2.0 

![image](https://user-images.githubusercontent.com/75377352/130169259-00d3e66f-618b-4f49-84c7-9522fcae8fef.png)

PS: I changed the "min firing rate per channel" to be 0, and lowered the "Threshold" to be [10 2]. 

Here are the outputs in the command window after running preprocessing (successful) and spikesort, which failed to detect any spikes.

Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   1s. Loading raw data and applying filters... 
Time  13s. Finished preprocessing 140 batches. 
random seed for clusterSingleBatches: 1
Obtained 7 PC waveforms in 0.07 seconds 
Batch 1 has fewer than Nfilt spikes.
Warning: data batch #1 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
time 0.01, pre clustered 1 / 140 batches 
Batch 2 has fewer than Nfilt spikes.
Warning: data batch #2 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 3 has fewer than Nfilt spikes.
Warning: data batch #3 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 4 has fewer than Nfilt spikes.
Warning: data batch #4 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 5 has fewer than Nfilt spikes.
Warning: data batch #5 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 6 has fewer than Nfilt spikes.
Warning: data batch #6 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 7 has fewer than Nfilt spikes.
Warning: data batch #7 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 8 has fewer than Nfilt spikes.
Warning: data batch #8 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 9 has fewer than Nfilt spikes.
Warning: data batch #9 only had 0 spikes
 
> In clusterSingleBatches (line 122)
In ksGUI/runSpikesort (line 785)
In ksGUI>@(~,~)obj.runSpikesort() (line 337) 
Batch 11 has fewer than Nfilt spikes.
Batch 12 has fewer than Nfilt spikes.
Batch 13 has fewer than Nfilt spikes.
Batch 14 has fewer than Nfilt spikes.
Batch 15 has fewer than Nfilt spikes.
Batch 16 has fewer than Nfilt spikes.
Batch 17 has fewer than Nfilt spikes.
Batch 18 has fewer than Nfilt spikes.
Batch 19 has fewer than Nfilt spikes.
Batch 20 has fewer than Nfilt spikes.
Batch 21 has fewer than Nfilt spikes.
Batch 22 has fewer than Nfilt spikes.
Batch 23 has fewer than Nfilt spikes.
Batch 24 has fewer than Nfilt spikes.
Batch 25 has fewer than Nfilt spikes.
Batch 26 has fewer than Nfilt spikes.
Batch 27 has fewer than Nfilt spikes.
Batch 28 has fewer than Nfilt spikes.
Batch 29 has fewer than Nfilt spikes.
Batch 30 has fewer than Nfilt spikes.
Batch 31 has fewer than Nfilt spikes.
Batch 32 has fewer than Nfilt spikes.
Batch 33 has fewer than Nfilt spikes.
Batch 34 has fewer than Nfilt spikes.
Batch 35 has fewer than Nfilt spikes.
Batch 36 has fewer than Nfilt spikes.
Batch 37 has fewer than Nfilt spikes.
Batch 38 has fewer than Nfilt spikes.
Batch 39 has fewer than Nfilt spikes.
Batch 40 has fewer than Nfilt spikes.
Batch 41 has fewer than Nfilt spikes.

I have checked the plots of the converted signals from .plx, and the signals after filters, and they all look reasonable to me. I have also been playing around with filtering parameters, and threshold for detecting spikes, but I still could not get kilosort to detect spikes from this data.

Is this because of some parameters that I did not set correctly, or something else I should change in kilosort?

Thanks for your help!

Ed

**Comment by EdShen-hub** [comment]
Sorry, I meant by "parameters that I did not set correctly".

**Comment by chris-angeloni** [comment]
If I had to guess, your recording may be 1) Too noisy (the raw data looks very noisy), and/or 2) Too short.

In general, I've not had great results sorting recordings less than 10 minutes with KS2: I usually get a lot of clusters requires a lot of manual curation in phy. Noise in the raw data greatly exacerbates this issue.

I would recommend recording for a longer time and also preprocessing your data beforehand. What I have found most useful is first doing a high-pass filter at 500Hz, then doing a common average reference on the filtered data (I think KS2 does this internally, but maybe it will resolve your issue). You could also try increasing your batch size by changing ops.NT in the configuration, but I have never had to do this, even for ~5 minute recordings
