### ISSUE TITLE
Drift traces look strange

### ISSUE THREAD

**Issue by aboharbf** [MouseLand/Kilosort#439]
![image](https://user-images.githubusercontent.com/25850560/130979185-c9490f8d-baf1-4816-b6dd-4600c3645137.png)

This seems obviously incorrect. What might be going on? I Imagine the resultant sorting can't be correct if it thinks the probe is shuffling back and forth like this.

**Comment by rajatsaxena** [comment]
another possibility could be that there are very few or no spikes in those batches. I would recommend increasing the batch time and rerunning to see if that helps.
