### ISSUE TITLE
Error saving data for phy! Reference to non-existent field 'connected'

### ISSUE THREAD

**Issue by chrisan97** [MouseLand/Kilosort#441]
Hello,

I am using Kilosort2 to sort my tetrode data. I get a strange error during the saving step of KiloSort : "Error saving data for phy! Reference to non-existent field 'connected'". I am using the GUI if that makes any difference.

Thanks!

**Comment by macayladonegan** [comment]
We are also having this issue- can you let us know if you've found a solution?

**Comment by blaje42** [comment]
Hi,

I just started having this issue with Kilosort 2. Was working fine last month and now all of a sudden I'm getting this error. Any resolution?
