### ISSUE TITLE
out of memory error in run_pursuit in kilosort3

### ISSUE THREAD

**Issue by McKenzieNeuro** [MouseLand/Kilosort#442]
I am receiving the same error as issue #319 (which has been closed).  I just cloned the repo today (Sept 1 2021)

any tips on where to start debugging?

thank you
sam

---

time 0.00, GROUP 1/12, units 0 
time 277.47, GROUP 6/12, units 54 
Error using  * 
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset
the GPU by calling 'gpuDevice(1)'.

Error in bimodal_pursuit (line 12)
clp = clp * u; % * s(ipc, ipc);

**Comment by McKenzieNeuro** [comment]
I worked on this a bit more and I can begin to see that the issue is that

on line 88 of template_learning.m

`kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);`

the variable dd is huge

size(dd)   =    [ 2473220           6          16]

this looks like a 'dd' is a (large) subselection of data but it is tough to follow how that is done without knowing what is stored in the second column of st3 which is defined in the cuda code. intuitively it seems like it should be about the anatomical localization of the largest spike and I wonder if there is still some channel sorting issue, like in #319

**Comment by alirezasaeedi1988** [comment]
Hi Sam,
I was facing the same error (but in KiloSort 2) while I was trying to sort a 250 GB data file! 
First I tried to reduce the batch size "ops.NT" in the config file. The result was having a bigger number of batches and the same error again. Then I increased the batch size and it worked!
Maybe you can try it too.

Best,
Alireza
