### ISSUE TITLE
Subscript indices must be either real positive integers or logicals

### ISSUE THREAD

**Issue by SaraMolas** [MouseLand/Kilosort#443]
Hi,

I’m trying to use Kilosort 2.0 to process data obtained from 8 tetrodes in OpenEphys. The data file is in the correct format and the number of channels in the recording correspond to the number of channels specified in the GUI and in the channel map. However, when I run kilosort, at the step of ‘pre-clustering to re-order batches by depth’ I get the following error message ‘Subscript indices must be either real positive integers or logicals’, as shown in the attached image. I am very new to Kilosort and Ephys in general, and I’m not sure what the problem is, any help will be very appreciated! 
![kilosort_error](https://user-images.githubusercontent.com/90054828/132036301-47b9d3df-2008-40e5-b7d9-6778fcc120c3.PNG)

Thanks!

**Comment by vincisLab** [comment]
We're experiencing something similar using KiloSort3. This is the output we got when running kilosort3_master.m:

>> kilosort3_master
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   5s. Loading raw data and applying filters... 
Time  85s. Finished preprocessing 2146 batches. 
40  catch
----------------------------------------Error using gpuArray/subsref
Subscript indices must either be real positive integers or logicals.K>> 

Any help would be highly appreciated!

**Comment by SaraNeuro** [comment]
Hi, I managed to make Kilosort work by using the channel map with 32 channels, and in the GUI manually specifying that the number of channels is 40 (although in OpenEphys version v0.5.4 I specify in the record node to only record from 32 channels). By doing this Kilosort works well and I can spike sort my data in Phy. Hope this helps!

**Comment by vincisLab** [comment]
Thanks for the info. We're trying to run KiloSort through spikeinterface so specifying the number of channels in the GUI unfortunately isn't an option. However we will investigate our data a bit more and make sure the numbers of channels are aligning. Thanks!
