### ISSUE TITLE
Error using uiextras.Panel

### ISSUE THREAD

**Issue by javierzsm** [MouseLand/Kilosort#448]
Hello, 

I am on W10 and Matlab 2021a
Until last week everything seemed to work fine but now I get this message when I launch the GUI, any hint?

Error using uiextras.Panel
Cannot define property 'Enable' in class 'uiextras.Panel' because the property has already been defined in the superclass
'matlab.ui.container.Panel'.

Error in ksGUI/build (line 112)
            obj.H.logPanel = uiextras.Panel(...

Error in ksGUI (line 47)
            obj.build(parent);

Error in kilosort (line 18)
h = ksGUI(f);
 
Unrecognized field name "settings".

Error in ksGUI/saveGUIsettings (line 1486)
            saveDat.settings.ChooseFileEdt.String = obj.H.settings.ChooseFileEdt.String;

Error in ksGUI/cleanup (line 1584)
                obj.saveGUIsettings();

Error in ksGUI>@(~,~)obj.cleanup() (line 102)
                'DeleteFcn', @(~,~)obj.cleanup(), 'Visible', 'on', ...
 
Error using closereq (line 18)
Error while evaluating VBox DeleteFcn.

**Comment by javierzsm** [comment]
I did both and it doesn't change the result.

I recently ran CellExplorer (cellexplorer.org) and after that I started having this issue, any chance this is related?
Thanks for your help

**Comment by zsong30** [comment]
Any follow-ups on this?  I am having the  same issue,

**Comment by javierzsm** [comment]
Hi, sorry for not having left the feedback and thanks for asking.
I think that there are name conflicts between some functions of the Layout GUI add-on and others; in my case this came up when I used Cell Explorer.
I solved it bringing up in the list the paths corresponding to Kilosort.

**Comment by zsong30** [comment]
Could you explain more on ' I solved it bringing up in the list the paths
corresponding to Kilosort. '   Changing the path for the kilosort folder or
any function?

Thanks!
-Eric

**Comment by CloeLhrx** [comment]
Hello, 
I just had the same problem, trying to run kilosort after using CellExplorer. 
I solved it by removing CellExplorer from the path. Not a long term solution but at least it worked ! 
Have a nice day, 
Hope it helped
Cloé
