### ISSUE TITLE
The grid vectors must contain unique points

### ISSUE THREAD

**Issue by 410pfeliciano** [MouseLand/Kilosort#449]
I have Win10pro and MATLAB R2018a. I've been using kilosort2 for a while with no problems. But I was planning to do the transition to KS3 and this is the error that I get. Everything in the GUI looked fine.

Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   8s. Loading raw data and applying filters... 
Time 240s. Finished preprocessing 4940 batches. 
vertical pitch size is 1 
horizontal pitch size is 5 
     1     4

     5

0.23 sec, 1 batches, 216 spikes 
3.69 sec, 101 batches, 20708 spikes 
6.92 sec, 201 batches, 41951 spikes 
10.11 sec, 301 batches, 64764 spikes 
13.29 sec, 401 batches, 80489 spikes 
16.36 sec, 501 batches, 97777 spikes 
19.45 sec, 601 batches, 116069 spikes 
22.56 sec, 701 batches, 132741 spikes 
25.63 sec, 801 batches, 158279 spikes 
28.68 sec, 901 batches, 187692 spikes 
31.74 sec, 1001 batches, 214990 spikes 
34.83 sec, 1101 batches, 240945 spikes 
37.87 sec, 1201 batches, 265816 spikes 
40.90 sec, 1301 batches, 292406 spikes 
43.93 sec, 1401 batches, 319218 spikes 
46.98 sec, 1501 batches, 350623 spikes 
50.04 sec, 1601 batches, 381142 spikes 
53.06 sec, 1701 batches, 406751 spikes 
56.10 sec, 1801 batches, 434139 spikes 
59.19 sec, 1901 batches, 452458 spikes 
62.22 sec, 2001 batches, 478232 spikes 
65.25 sec, 2101 batches, 501865 spikes 
68.28 sec, 2201 batches, 523087 spikes 
71.34 sec, 2301 batches, 549483 spikes 
74.38 sec, 2401 batches, 575599 spikes 
77.40 sec, 2501 batches, 602602 spikes 
80.43 sec, 2601 batches, 629059 spikes 
83.48 sec, 2701 batches, 655090 spikes 
86.52 sec, 2801 batches, 680151 spikes 
89.56 sec, 2901 batches, 711154 spikes 
92.61 sec, 3001 batches, 736832 spikes 
95.64 sec, 3101 batches, 754501 spikes 
98.68 sec, 3201 batches, 785156 spikes 
101.72 sec, 3301 batches, 810539 spikes 
104.72 sec, 3401 batches, 832653 spikes 
107.76 sec, 3501 batches, 856665 spikes 
110.80 sec, 3601 batches, 879206 spikes 
113.83 sec, 3701 batches, 900049 spikes 
116.85 sec, 3801 batches, 923007 spikes 
119.89 sec, 3901 batches, 944092 spikes 
122.92 sec, 4001 batches, 966680 spikes 
125.98 sec, 4101 batches, 992688 spikes 
129.06 sec, 4201 batches, 1014671 spikes 
132.11 sec, 4301 batches, 1036141 spikes 
135.18 sec, 4401 batches, 1056293 spikes 
138.26 sec, 4501 batches, 1076680 spikes 
141.31 sec, 4601 batches, 1095740 spikes 
144.35 sec, 4701 batches, 1112784 spikes 
147.42 sec, 4801 batches, 1130630 spikes 
150.19 sec, 4901 batches, 1148848 spikes 
151.05 sec, 4940 batches, 1155992 spikes 

Error using griddedInterpolant
The grid vectors must contain unique points.

Error in interp1 (line 151)
        F = griddedInterpolant(X,V,method);

Error in shift_batch_on_disk2 (line 14)
    shifts = interp1(ysamp, shifts, rez.yc, 'makima', 'extrap');

Error in datashift2 (line 149)
        dprev = shift_batch_on_disk2(rez, ibatch, dshift(ibatch, :), yblk, sig, dprev);

Error in ksGUI/runPreproc (line 732)
                obj.rez = datashift2(obj.rez, 1);

Error in ksGUI/runAll (line 633)
            obj.runPreproc;

Error in ksGUI>@(~,~)obj.runAll() (line 321)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.

**Comment by kate-prime** [comment]
Commenting to follow. Running KS3 and also experiencing this problem. Thought it might be due to a low number of spikes, but I am now suspicious that is not the problem and that it is something to to with the registration offset. Let me know if you figured it out!
