### ISSUE TITLE
How to map clusters to position on probe?

### ISSUE THREAD

**Issue by SiddharthaJoshiLC** [MouseLand/Kilosort#454]
How do I map the sorted clusters to a position on a linear probe (ie - the map that we provvide to Kilosort at the first step)?

thank you,

- Siddhartha Joshi

**Comment by rajatsaxena** [comment]
you can use `rez.ops.chanMap, rez.xcoords, rex.ycoords`  in matlab or the `channel_map.npy` and `channel_positions.npy` file

**Comment by SiddharthaJoshiLC** [comment]
Thank you, Rajat. Those files only have channel maps but not the mapping
from sorted cluster to channel (or channel position). However, we did find
that this information is saved after running Phy.

Siddhartha Joshi, PhD
Senior Staff Scientist
Department of Neuroscience
Baylor College of Medicine


Web:
https://siddsrecipes.blogspot.com/

https://scholar.google.com/citations?user=X4EKHG4AAAAJ&hl=en

https://www.ncbi.nlm.nih.gov/myncbi/1TyYsjkdmK2Aa/bibliography/public/

https://twitter.com/SiddJoshi75

**Comment by GrimmSnark** [comment]
Hello Siddhartha,

Would you mind pointing me in the right direction for the cluster to probe channel mapping? Which phy output holds this information? I am trying to figure out the same issue. 

Thanks,

Michael

**Comment by LaurenzMuessig** [comment]
Hi Michael. Note that the function calculates the centre of mass to assign the template depths, rather than just using the peak channel itself (which I think phy uses). Are all of these clusters in your list nice units or simply the first 40 in your recording, so might contain mua/noise? In the latter case the centre of mass and the peak channel might differ by a number of channels
Also not sure I understand why your KiloSort channels aren't a list of integers?

Cheers

Laurenz

**Comment by GrimmSnark** [comment]
Hello Laurenz,

These are just the first forty clusters in this particular recording so a mix of good cells and MUA. I understand that kilosort calculates center of mass and I would be willing to believe the result if it matched remotely the phy output or even mean waveform templates when I plot then. I just don't understand what phy is doing differently from kilosort. 

The kilosort channel is just the `templateDepths` variable from the `templatePositionsAmplitudes` function in the spikes library, so I have no idea why it would contain decimal places. 

Best,

Michael

**Comment by LaurenzMuessig** [comment]
So, 'templateDepths' will be the actual depths of the cluster in um, not a channel ID. you'd need to use the depths to find the closest channel to that according to your channel map. However, I can see that the values you are getting don't seem to make much sense (in comparison to the channel phy gives you) as it should increment by 20um every 2 channels (assuming you are using neuropixels 1.0). For my data (neuropixels), I get a match of mainly +/-20um between phy and using the code in templatePositionsAmplitudes for any decent cluster that is not noise or a mix of different units. Not sure what's going wrong in your case.

Cheers

Laurenz

**Comment by SiddharthaJoshiLC** [comment]
Thanks for all the useful information in this discussion, Laurenz and
Michael.

Michael - I wonder if the mismatch might be due to the electrode map file
that you provide to Kilosort (the file that maps Channel number to the
x,y,x coordinates of the actual channel)? Probably not, but may be worth a
quick check...

- Siddhartha

--------------------------
Siddhartha Joshi, PhD
Senior Staff Scientist
Department of Neuroscience
Baylor College of Medicine


Web:
https://siddsrecipes.blogspot.com/

https://scholar.google.com/citations?user=X4EKHG4AAAAJ&hl=en

https://www.ncbi.nlm.nih.gov/myncbi/1TyYsjkdmK2Aa/bibliography/public/

https://twitter.com/SiddJoshi75
