### ISSUE TITLE
HELP!! Error running Kilosort: An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument

### ISSUE THREAD

**Issue by AmirSamanSajad** [MouseLand/Kilosort#458]
Thanks in advance to the Kilosort community for taking time to help with my question.
I am trying to run Kilosort (tried different versions, but currently working on v2.5). I am getting the error message: "Error running Kilosort: An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument".
Checking other online posts, I see this issue is encountered by several others, but there is no single solution that reliably works. I was wondering what can result in this error and what steps one should take to resolve this issue?
I apologize for repeating this question once again. I hope the answer to this question can complement other answers and serve future users.

Here is some information specific to my case:
- Windows 10 system, 64 bit
- MATLAB 2018a
- I have success running the mexGPUall command
- I have not yet had Kilosort running successfully
- I followed the installation instructions suggested by developers of Kilosort with no messages or warnings

Thank you!

**Comment by GrimmSnark** [comment]
See #383, this worked for me
