### ISSUE TITLE
Issue with setting N blocks for registration

### ISSUE THREAD

**Issue by TOMORI233** [MouseLand/Kilosort#460]
Hi,
I am looking for suitable parameter settings for my data analysis using kilosort, especially N blocks for registration.
I have a spike data set recorded from rats using a neuropixel probe with 32 channels evenly spaced along the y axis. The raw data is from a TDT system and is converted to an int16 binary file with a sampling rate of 12.2 kHz.
The problem is when the N is set larger than zero, errors are reported during preprocessing. The exact error code is `shifts = interp1(ysamp, shifts, rez.yc, 'makima', 'extrap');`. The error message is _matlab.internal.math.interp1_, which means the variable `ysamp` contains repeated elements.
What should I set for this _N blocks for registration_ item? What chanMap should I create for it or what else parameters of my probe are needed to generate a chanMap?

**Comment by nicolasmt22** [comment]
Did you figure this out? I am having a similar issue.
