### ISSUE TITLE
find_merges crash

### ISSUE THREAD

**Issue by enelken** [MouseLand/Kilosort#463]
I'm sorting neuropixels data (matlab 2020a). On one set of data, find_merges crashes with the following message:
----------------------
Error using accumarray
First input SUBS must contain positive integer subscripts.

Error in find_merges (line 40)
nspk = accumarray(rez.st3(:,2), 1, [Nk, 1], @sum);
----------------------
and indeed rez.st3(:,2) contains a few entries that are 0.
How to proceed?

**Comment by JohannesStriebel** [comment]
Hi @enelken,
I get the same error for some files of my in vitro recordings. Any new insights on this?

**Comment by neuraldino** [comment]
I have this workaround that is a bit suboptimal, but works. 
k = rez.st3(:,2) == 0; %find clusters w 0
rez.st3(k,2) = 1; %assign them to cluster 1
rez = find_merges(rez, 1); %run again

**Comment by luiztauffer** [comment]
I've also found this error for Kilosort3, at the very end of the processing... sounds like an easy bug to fix according to @neuraldino 
@neuraldino could you make a PR for that?
