### ISSUE TITLE
Overwriting ops.spkTh during mainLoop

### ISSUE THREAD

**Issue by FilippoHei** [MouseLand/Kilosort#468]
Hi there. After running Kilosort2 with a few different settings I noticed that the `ops.spkTh` variable is overwritten several times in the mainLoop (see picture). It is even commented with `ops.spkTh = -6; % why am I overwriting this here?`

![image](https://user-images.githubusercontent.com/63241700/149754514-b0b4e318-e633-4ee4-b0c1-3a1a52d2fcad.png)

So, is there a reason for this overwriting? I commented out the lines, and it worked just fine, with the additional benefit of being able to set the spkTh parameter myself.

**Comment by eintzandt** [comment]
I found that in the actual step that detects spikes based on thresholds it is also overwritten: main_kilosort.m line 29 -> datashift2.m line 27 "spkTh = 8" instead of "spkTh=ops.spkTh". Is there a reason for this?
