### ISSUE TITLE
Threshold for spike amplitude and truncated distribution

### ISSUE THREAD

**Issue by cpiette95** [MouseLand/Kilosort#473]
Hello, 

I am new to Kilosort 2.5 and spike clustering and I am a little confused by what I sometimes see in the "Amplitude View" panel in Phy, especially for small units. 

It seems that the distribution of spike amplitudes for some units (in blue) is truncated, even though I am not at the bottom limit of the overall grey distribution. It happens both for units for which the amplitude is relatively stable over time (example 1) and for those whose amplitude drifts over time and becomes lower (example 2). 
Should these units be discarded because too many spikes are probably lost? When I lowered the threshold (from the default [10 4] to [8 2] or [6 3]), it did not seem to change much the number of units found... 

Also in some cases, the choice of channel does not seem to be the most relevant one (example 3), and thus the amplitude does not really reflect the real spike amplitude. Is it possible to change the channel label manually and have the associated information updated? 

Thank you for your help!

![example_1](https://user-images.githubusercontent.com/36566014/153172695-05c4426a-77ff-4d00-8f35-8ff8aba2561c.png)
![example_2](https://user-images.githubusercontent.com/36566014/153172727-f26c45de-229e-4f58-a136-57474cf68b41.png)
![example_3](https://user-images.githubusercontent.com/36566014/153172742-f236219f-87e4-44bc-82f8-6bb54db78a9d.png)

**Comment by jia1214** [comment]
Hi, did you solve this problem? I also met the same problem.
