### ISSUE TITLE
Test dataset?

### ISSUE THREAD

**Issue by cafalchio** [MouseLand/Kilosort#476]
Would be nice to have a small sample dataset with channel map inside the package, just to run a installation and features test.

**Comment by GrimmSnark** [comment]
Hello,

Look at the eMouse_drift folder within the kilosort main folder. It contains some scripts to generate fake data to play with. There are a few errors due to changes in naming conventions but it seems to be working pretty easily for me.

Michael

**Comment by cafalchio** [comment]
Thanks, I will look at it.
