### ISSUE TITLE
Extracting the channel in which spike amplitude is the largest

### ISSUE THREAD

**Issue by yasminya** [MouseLand/Kilosort#478]
The channel assigned to each cluster is some kind of interpolation predicting to which channel the neurons is closest too. However, in many cases this does not result in the channel where the largest events appear. Is there a way to re-assign channel number to cluster so that the channel selected is the one with the largest amplitude spikes?

**Comment by zm711** [comment]
If you go to the spikes `https://github.com/cortex-lab/spikes` repo by Nick Steinmetz, there's a function called getWaveForms in the analysis folder which allows you get the raw waveforms. Then you could calculate the max amplitudes of the raw waveforms for a cluster and do a weighting by amplitudes instead to calculate the max channel.
