### ISSUE TITLE
kilosort GUI shows no prediction before clustering

### ISSUE THREAD

**Issue by Minako-375** [MouseLand/Kilosort#485]
Hi
I have some trouble with kilosort GUI and spike extraction.

After the preprocessing, no spikes are detected as a "prediction" and "residual" is completely the same as a "filtered".
I also checked colormap mode but it was the same with trace mode.

I use neuropixels1.0 for recording and kilosort2.5 for manual clustering with default parameters.

After the clustering step, GUI shows the "right" prediction and residual.

Is it possible to show prediction and residual before clustering?
Because clustering takes a lot of time, it would be helpful if I could check the parameters of preprocessing before clustering.

Does anyone have some suggestions?

![filtered](https://user-images.githubusercontent.com/102357463/160103160-39899423-dd37-4103-a637-03d030d8a9e5.png)
![prediction](https://user-images.githubusercontent.com/102357463/160103157-a7a755c3-4637-4d47-9f90-67875276dc23.png)
![residual](https://user-images.githubusercontent.com/102357463/160103164-5c63f228-65fe-46a0-ac2f-a779a69fad50.png)

Thank you,

**Comment by GrimmSnark** [comment]
Hello,

As far as I understand it, they GUI just tries to plot the calculated spike extractions in the predicted and residuals. So if you have not run the full KS pipeline then they will be blank and then the same as filtered, respectively.

The only thing I can suggest to quickly go through a variety of parameter values is to either cut down on the number of channels or reduce the timeframe for the analysis. 

Best,

Michael

**Comment by Minako-375** [comment]
Thank you for your answer.
I'll try to reduce the timeframe to find good paramaters.

Best,
