### ISSUE TITLE
Question: Does Kilosort only look for drift along the y-axis?

### ISSUE THREAD

**Issue by djhavert** [MouseLand/Kilosort#491]
We are using a 512 channel rectangular MEA, and are recording from organotypic slices. These slices tend to flatten and spread out in all directions slowly throughout the recording. I realize Kilosort was originally designed for vertical probes rather than rectangular arrays, and the documentation only discusses drift in regards to depth, or the y-values. I am hoping someone could tell me if Kilosort is able to find both vertical and horizontal drift, or if it is limited to only vertical drift?

**Comment by xy103** [comment]
From the kilosort paper (https://www.biorxiv.org/content/10.1101/2020.10.27.358291v1.full.pdf) I think they assume only vertical drift and do not try to find horizontal drift.
