### ISSUE TITLE
Kilosort3 not producing pc_features.npy file

### ISSUE THREAD

**Issue by mtvrdic1** [MouseLand/Kilosort#494]
Kilosort3 does not produce a PC_features.npy file after sorting. I am sorting a Neuropixels recording. Can you help?

**Comment by PathwayinGithub** [comment]
I don't get the PC_features.npy file too. I can use _phy... files to run the Phy, but the _phy files are subsets of spikes, how can I get the whole data with pc features (number spikes * number pcs * number channels)
