### ISSUE TITLE
Could anyone please show the data structure of standard .bin file for Kilosort or the instructions for how to write a now probe layout

### ISSUE THREAD

**Issue by AmaranthCao** [MouseLand/Kilosort#496]
My EP data is not from the neuropixel, so I need to convert them into the standard bin file for kilosort. But I really don't know the data structure of the .bin file from neuropixel.  what kind of data this .bin file will include, such as sampling frequency, timestamps?  And how the each kind of data is represented in this .bin file? For example, will Timestamps be a 1*N integer vector or whatever? Can anyone please support an example .bin file? Thanks a lot for your help!
Futhermore, does anyone know how to write a now probe layout? Thanks for any kind of help!

**Comment by djhavert** [comment]
Hi, I just recently did these steps myself. We also don't use neuropixel. I was able to follow the instructions [here](https://github.com/MouseLand/Kilosort/wiki/1.-The-GUI) and get Kilosort working on our data. Best of luck!

**Comment by AmaranthCao** [comment]
Hello, thanks a lot for your help and suggestion!  It is really helpful to me. Could you please also tell me what are the values in that [nChannels x nTimepoints] matrix, how to calculate these values. Because my .ncs file from Neuralynx can only output the valus like Timestamps, ChannelNumbers and SampleFrequencies. but I am sure they are not the values for that matrix. Thanks again for your help!
