### ISSUE TITLE
CUDA error when beginning main optimization 

### ISSUE THREAD

**Issue by Wenqing-1** [MouseLand/Kilosort#497]
Hello, when I try to procced .dat file with kilosort 3.0, it has the following error in message log:
![image](https://user-images.githubusercontent.com/93006577/167706823-e0efe29b-4878-4c9c-a5a1-981bdd16a607.png)
![image](https://user-images.githubusercontent.com/93006577/167706921-32212652-d362-46ff-84ab-8ef3c2bf5fa7.png)

The matlab command window shows:
```
Time   0s. Computing whitening matrix.. 
Getting channel whitening matrix... 
Channel-whitening matrix computed. 
Time   2s. Loading raw data and applying filters... 
Time  45s. Finished preprocessing 634 batches. 
pitch is 25 um
0.14 sec, 1 batches, 898 spikes 
11.77 sec, 101 batches, 101532 spikes 
20.07 sec, 201 batches, 187033 spikes 
28.08 sec, 301 batches, 274405 spikes 
36.12 sec, 401 batches, 358286 spikes 
44.20 sec, 501 batches, 432072 spikes 
52.28 sec, 601 batches, 506712 spikes 
54.95 sec, 634 batches, 528814 spikes 
time 106.95, Shifted up/down 634 batches. 
Time 108s. Optimizing templates ...
```
When I try the kilosort with the same probe, same file format and the same day recording but larger file size, the other file works fine. Also if I only pick part of channels instead of the whole channels, kilosort works too.

I read some of the similar issues and tried on kilosort 2 and 2.5 and it gives the same error. I appreciate any help with debugging or solving this error. Please let me know if any other information would be helpful here.

**Comment by Batter-Wang** [comment]
I think it could be solved by adding phy to you matlab work path. https://github.com/cortex-lab/phy
