### ISSUE TITLE
Custom templates/spike waveforms similarity index

### ISSUE THREAD

**Issue by GrimmSnark** [MouseLand/Kilosort#503]
Hello,

So I have been trying out some custom inter spike interval clean up routines on the outputs of kilosort 3 just to deal with some of my noisier cells. At the moment I take the cluster outputs from KS3 and split them in matlab based on ISI violations. Now, I am trying to feed these new spike waveforms back into KS3 so I can get recalculated amplitudes, similarity indices, phy outputs etc. 

However, I can not seem to find the correct place to feed these into the existing KS3 pipeline, or even the correct code snippets to run to do this. Has anyone gotten any experience doing this before?  

Best,

Michael

**Comment by marius10p** [comment]
This sounds like a very bad idea! Cleaning up the ISI intervals is data manipulation, and should never be used to make your data look better than it really is. The refractory period violations are a symptom of a bad cluster. You don't fix the problem by cleaning up these violations.

**Comment by GrimmSnark** [comment]
Thank you for the advice! I will play with the threshold values a little more then.
