### ISSUE TITLE
Out of memory on device kilosort 3 

### ISSUE THREAD

**Issue by lmontelisciani** [MouseLand/Kilosort#506]
I am preprocessing 4 hrs of recording done with Neuropixel probe and continually getting the following error:

Hardware/Software
Windows 10
RAM: 32 GB
GPU: NVIDIA GeForce RTX 2060 (6GB)
Matlab2021b

```
19253.78 sec, 6801 / 6966 batches, 1525 units, nspks: 51376067, mu: 15.7297, nst0: 7574 
19511.90 sec, 6901 / 6966 batches, 1525 units, nspks: 52177327, mu: 15.7297, nst0: 7416 
Elapsed time is 19678.903635 seconds.
time 0.08, GROUP 1/96, units 0 
time 112.82, GROUP 6/96, units 53 
time 250.51, GROUP 11/96, units 119 
time 421.56, GROUP 16/96, units 207 
Error using  * 
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling
'gpuDevice(1)'.

Error in bimodal_pursuit (line 12)
clp = clp * u; % * s(ipc, ipc);

Error in run_pursuit>break_a_cluster (line 41)
    [x, iclust, flag] = bimodal_pursuit(dd, wroll, ss(ix), rmin, nlow, 1, use_CCG);

Error in run_pursuit (line 12)
    [ix, xold, xnew] = break_a_cluster(Xd(ind, :), wroll, ss(ind), nlow, rmin, use_CCG);

Error in final_clustering (line 100)
    kid = run_pursuit(dd, nlow, rmin, n0, wroll, ss(tin), use_CCG);

Error in ksGUI/runSpikesort (line 804)
                obj.rez                = final_clustering(obj.rez, tF, st3);

Error in ksGUI/runAll (line 634)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 321)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.
```

![KS_problem](https://user-images.githubusercontent.com/63074401/172804900-7cf5d3e3-4cc7-449f-89de-47e4e94f2135.JPG)

Did you have the same problem? If so, how can I solve it?

Thanks in advance.

**Comment by marius10p** [comment]
Something is not right, looks like you have too many neurons. Check the data in the GUI to make sure the number of channels is correct, check the channel ordering and xpos/ypos etc.

**Comment by farazmoradi** [comment]
I have the same problem, and everything is ok with my channel locations. The same inputs work on kilosort 2 but not on 3!

**Comment by DanEgert** [comment]
Same problem during final clustering. Kilosort 2.5 ran fine but 3 threw an out of GPU memory error. 
610 units, 40 Million spikes. GTX1080 with 8GB memory. 
Any way we can change the parameters to reduce the memory load? Would buying a card with more memory solve this?

Thanks for any clue,
Dan
