### ISSUE TITLE
Trouble with the Estimated drift traces

### ISSUE THREAD

**Issue by Minako-375** [MouseLand/Kilosort#507]
I am having trouble understanding the figure named 'estimated drift traces'.

1. What does the color indicate?
I assume that the color indicates the depth and the figure shows how each depth drifts. Is it correct?
If so, which color corresponds to which channel(depth)?

3. One line (yellow) looks as saturated as the attached picture.
Since only one line (and it is not likely to be the deepest or shallowest channel because the yellow line is date3) shows significant drift, I am concerned that the drift tracking did not work correctly.
-Is it conceivable that only one line can drift significantly?
-If not, how can I fix the drift tracking.
I'm using kilosort2.5 and neuropixels probe. In this preparation, the neural network, and possibly shape of spikes, in the recording region were changed dramatically so I'm wondering if it is possible to track neurons.

![estimated drift](https://user-images.githubusercontent.com/102357463/173819857-aa60d534-22b7-4dd6-bf0a-55f46cf38ce2.jpg)
 
 I would be grateful if you could let me have your comment and advice.

Best,

**Comment by marius10p** [comment]
It looks like you have a region on the probe with few spikes / high noise. You can reduce the number of blocks for drift correction and/or you can increase the batch size. Since it looks like different regions drift differently, I would increase the batch size first., even by a factor of 10.

**Comment by Minako-375** [comment]
Thank you. I'll increase the batch size and try again.
To increase the batch size, should I increase ops.NT or ops.ntbuff? These parameters should be a power of 2?
