### ISSUE TITLE
Issue with ephys data file? Error running Kilosort: An unexpected error occurred trying to launch a kernel. The CUDA error was: invalid configuration argument

### ISSUE THREAD

**Issue by dakotablackman** [MouseLand/Kilosort#512]
I am unfortunately running into an issue where each time I try to run kilosort on a particular data file (~45min long, collected with a 2x32 NeuroNexus Silicon Probe and using the Intan RHD2000), I am running into this error, followed by an error saving data to phy due to a nonexistent field 'Wphy'. I have tested the channel map configuration and it works on other files, and I'm not sure how to troubleshoot beyond this. If it is an issue with the datafile, I would appreciate some guidance for how to check this. Kilosort just stops after this point:

<img width="430" alt="Screen Shot 2022-07-12 at 10 44 58 AM" src="https://user-images.githubusercontent.com/47334765/178520373-9658346f-00fc-4efd-a585-419c27d50c51.png">

Any help would be appreciated!

**Comment by dwhzlh2021** [comment]
Any updates? I have the exactly same problem
