### ISSUE TITLE
Problem with mexGPUall

### ISSUE THREAD

**Issue by freyja87** [MouseLand/Kilosort#515]
I'm trying to run kilosort on my machine (windows, matlab 2021a).  When I run mexGPUall it lists a bunch of messages saying MEX completed successfully and then eventually it throws me this error message:

Error using mex
fatbinary fatal   : '44_device.compute_35.cubin' is not in 'keyword=value' format
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are
deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mexMPnu8.obj
c_mexapi_version.obj

Error in mexcuda (line 168)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 18)
        mexcuda -largeArrayDims -dynamic -DENABLE_STABLEMODE mexMPnu8.cu

Any idea what's causing this?

**Comment by LaurenzMuessig** [comment]
See #514. Sounds like it's the same thing.

Laurenz

**Comment by freyja87** [comment]
Thanks @LaurenzMuessig I've tried replcaing the environment so it matches the one used in #514, but I still get the same error. 
I'm slightly at a loss now

**Comment by LaurenzMuessig** [comment]
Hey Freyja. Sorry to hear you are still having trouble. Not sure I can be of any more help here unfortunately. I am running kilosort on a linux machine with Matlab 2020a and Cuda 10.1. Cheers

**Comment by freyja87** [comment]
Ok, so it seems to be solved.  Apparently the problem is with the date format the windows uses in Europe differs from the one used in the US. I just spoke to some colleagues (at the Donders Institute in the Netherlands) who had the same issue. And the hack is basically to disable enableStableMode (mexGPUAll line 5).  This is probably not the best thing to do but at least it runs mexGPUall now successfully.

**Comment by LaurenzMuessig** [comment]
Okay. Why don't you temporarily set your computer to US date and time, compile the code and then set it back again afterwards. Kilosort should hopefully just run fine if the code is compiled. Cheers
