### ISSUE TITLE
Raw Amplitude View Not showing Up

### ISSUE THREAD

**Issue by pstarski** [MouseLand/Kilosort#516]
Hi,

I am trying to utilize the raw amplitude view in Phy2. I have recordings sorted with KS2 and have previously used the raw amplitude view to curate my clusters. After switching computers and reinstalling phy2, I have been unable to find the Raw amplitude view. I have the raw recording in the same file directory as the npy files. 

Anyone know what I am missing? or Why I cannot find this view?

Thanks,
Phil

**Comment by TomBugnon** [comment]
Subscribed... I've been searching for this view for years

**Comment by pstarski** [comment]
Hey Tom,

You will want to install the dev version and comment out like 1370 and 1371.

To download the dev version in anaconda:

git clone git@github.com/cortex-lab/phy.git
cd phy
pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .
cd ..
git clone git@github.com/cortex-lab/phylib.git
cd phylib
pip install -e . --upgrade

Credit goes to Cyrille Rossant for communicating this through email with me.

As the the template_feature....no real clue. I use the raw amplitude to eliminate noise in short (sub 10 min) neural recordings.

**Comment by mariehemelt** [comment]
I'm also wondering about this. Which file are you referring to, where you can comment out line 1370 and 1371?
