### ISSUE TITLE
Issue with kilosorting 4-shank probe data

### ISSUE THREAD

**Issue by antaramaj16** [MouseLand/Kilosort#517]
I am trying to phy sort my kilosorted data for a session where we used a 4-shank probe and I am running into an issue. 

When I Kilosorted, I used this probe layout file provided and it worked because it had the same x-coordinates, y-coordinates, among other things which we used during our recording. This was the probe layout we used:
![image](https://user-images.githubusercontent.com/74184866/198343873-8119303f-4e4b-4351-b8f5-3ea0c4152e6e.png)

Then when I try to phy sort this kilosorted data - the spikes look fine and in the probe view I can see that different clusters are in different shanks but in the Cluster view in the column that says 'sh' there is only 0 across all of the clusters. I am wondering if there is a problem and thereby it is not registering and not assigning each cluster with a different shank id number which it should not all be zero. 
![image](https://user-images.githubusercontent.com/74184866/198344094-fa6e88c7-bff5-4c6a-95a2-e3dd5064bfb9.png)

Could someone help me with this please?

**Comment by nsteinme** [comment]
I think you can get the shank ID by finding the peak channel and taking its
x-coordinate. Or you could sort each shank separately in kilosort. I'm not
sure how to get the sh column in phy to show a meaningful number but I
expect that you shouldn't need it.
