### ISSUE TITLE
`Error using indexing Subscript indices must either be real positive integers or logicals.` probably actually caused by low values for `dati` in `shift_batch_on_disk2`

### ISSUE THREAD

**Issue by tiburona** [MouseLand/Kilosort#525]
I get this error in `extractTemplatesfromSnippets`.

```
Error using indexing
Subscript indices must either be real positive integers or logicals.

Error in extractTemplatesfromSnippets (line 56)
wTEMP = dd(:, round(linspace(1, size(dd,2), nPCs)));

Error in extract_spikes (line 42)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in main_kilosort3_ks (line 41)
[rez, st3, tF]     = extract_spikes(rez);
```

I'm pretty sure the underlying cause is actually in `shift_batch_on_disk2`:

In these lines

```
% kernel prediction matrix
M = Kyx /(Kxx + .01 * eye(size(Kxx,1)));

% the multiplication has to be done on the GPU
dati = gpuArray(single(dat)) * gpuArray(M)';
```
`M` winds up being a matrix of quite small numbers, which means `dati` is also a matrix of small numbers, and eventually when the function `int16` is called they all get converted to 0, leading eventually to my error.  Or so it seems to me.  Does anyone have any ideas what's going wrong in this process?

If I set `nblocks` to 0 and skip registration Kilosort runs (or, rather, it runs in the fork of Kilosort 2.5 where the zero padding issue is fixed).

**Comment by IsabelDAlessandro** [comment]
I'm experiencing a similar error running Kilosort3: 

```time 362.03, Shifted up/down 1945 batches. 
Error using indexing
Subscript indices must either be real positive integers or logicals.

Error in extractTemplatesfromSnippets (line 56)
wTEMP = dd(:, round(linspace(1, size(dd,2), nPCs)));

Error in extract_spikes (line 42)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in ksGUI/runSpikesort (line 795)
                [obj.rez, st3, tF]     = extract_spikes(obj.rez);

Error in ksGUI/runAll (line 634)
            obj.runSpikesort;

Error in ksGUI>@(~,~)obj.runAll() (line 321)
                'Callback', @(~,~)obj.runAll());
 
Error while evaluating UIControl Callback.
```

Does anyone know what might be the source of this issue or how to resolve it? 
@tiburona Where are you setting `nblocks` to 0 to skip registration? Is this workaround specific to the earlier version of Kilosort 2.5? 

Thank you!

**Comment by tiburona** [comment]
Hi, you can set nblocks in `main_kilosort.m`.  This is the line: `ops.nblocks = 5`.
