### ISSUE TITLE
 CUDA error invalid configuration argument (KS 2.5)

### ISSUE THREAD

**Issue by aloksneurobot1** [MouseLand/Kilosort#527]
Hi everyone,
We have been using KS 2.5 for our data recorded using Neuropixel probes with Spikeglx. We had a smooth run to date. However, when trying to run KS 2.5 with a specific session, we end up with the following error in the Message log space of the GUI :
Error running kilosort! An unexpected error occured trying to launch a kernel. The CUDA error was: invalid configuration argument

We found the probable source of the issue:
line 119 of the learnTemplates file may be the source of the error, as variable 'dWU' ends up being empty .

We would appreciate any suggestions or corrections from the community about this error. 
Thank you

**Comment by tiburona** [comment]
Hi, you can try using this forked version of Kilosort 2.5 and see if it solves your issue: https://github.com/RobertoDF/Kilosort/tree/solve_zero_padding. Here's the pull request, never merged, with some background: https://github.com/MouseLand/Kilosort/pull/288

**Comment by kingsEffy** [comment]
I'm having this issue using kilosort3 on particualr dataset as well... i have to set ops.nblock =0 to get running but the results is very noisy ... so, does anyone know what is going on here?
