### ISSUE TITLE
Electrode map for long column bank selection in Neuropixels 1.0

### ISSUE THREAD

**Issue by SiddharthaJoshiLC** [MouseLand/Kilosort#533]
We are looking to use the long column bank selection IMRO file from:

https://billkarsh.github.io/SpikeGLX/

My question is: for the sorting step (using  Kilosort), how do we create a new electrode configuration file (or does one already exist)?

Any tips or suggestions would be most appreciated!

- Sidd

**Comment by LaurenzMuessig** [comment]
Hey Sidd,

You can e.g. use this MATLAB [function ](https://billkarsh.github.io/SpikeGLX/Support/SGLXMetaToCoords.zip) from Bill Karsh/Jennifer Colonell to generate a channel map from the settings info in the .meta file of the recording data. 
Cheers
Laurenz

**Comment by SiddharthaJoshiLC** [comment]
Thanks, Laurenz! We will try that out.

- Sidd
