### ISSUE TITLE
kilosort repo not found, or inaccessible

### ISSUE THREAD

**Issue by wujixuezhe** [MouseLand/Kilosort#541]
I download the kilosort, and add to the path in matlab2022a. CUDA, visual studio community 2019 were installed. mexGPUall was run successfully, but when I ran kilosort, input my data and run preprocessing. the error message was:  errString ='kilosort repo not found, or inaccessible'. Can anybody help me with this?Thanks a lot~

**Comment by zm711** [comment]
Happy to try to help if its not solved, but could you copy the full error message here? Which file and line is the error occurring in?

**Comment by kermit000000** [comment]
Hi I am experiencing the same issue as @wujixuezhe. The error message " errString = kilosort repo not found, or inaccessible" appears on the command window of Matlab (2022b) as soon as I initiate preprocessing on the KS2 GUI. The error doesn't stop KS running and generate all the expected files, including params.py, but I have a concern regarding any potential issues that may arise as a result of this error.
Your thoughts and comments on this matter would be greatly appreciated.

**Comment by kermit000000** [comment]
@zm711 Thanks for your reply! Your clear explanation alleviated my concern and I'm so grateful for your kindness and knowledge-sharing.
