### ISSUE TITLE
Issue on sorting concatenated runs

### ISSUE THREAD

**Issue by thugeun** [MouseLand/Kilosort#550]
Hi. I am using Neuropixel 1.0 and recording with spikeglx. 
I have acutely recorded 2 runs (45 min, 10 min each) on a single mouse, and concatenated them using catgt. Now I am in trouble kilosorting (Kilosort 2.5). It cannot create data for phy.

**Catgt log:** 
Cmdline: CatGT -dir="my data directory" -run=<my runname> -g=0,1 -t=0 -prb_fld -t_miss_ok -ap -prb=0 -apfilter=butter,12,300,9000 -gfix=0.4,0.1,0.02 -dest="my destination"
Gap before file '"my data directory"_g1_t0.imec0.ap.bin' out_start_smp=81170172 inp_gap_smp=2956655 out_zeros_smp=2956655.

**Message Log from Kilosort:** 
Error running kilosort! An unexpected error occured trying to launch a kernel. The CUDA eror was:
invalid configuration argument
...
Error saving data for phy! Unrecognized field name "Wphy".

I thought it was because of zero paddings between two runs, which is added by catgt, so I tried RobertoDF's solution (#288, https://github.com/RobertoDF/Kilosort/tree/solve_zero_padding). 
I downloaded the whole repo, added them to the Matlab path, and tried sorting with GUI but the same error persists.

How can I concatenate data without zero paddings, or handle zero-padded data using kilosort? 
Or, any other suggestions on sorting multiple runs?

Thank you.

**Comment by jiumao2** [comment]
Try to add `-zerofillmax=100` in CatGT. It works for me.

**Comment by thugeun** [comment]
@jiumao2 Seems it works. Thank you!

**Comment by Lorena-J** [comment]
Where is CatGT??
