### ISSUE TITLE
Severe over-splitting in KS3 

### ISSUE THREAD

**Issue by RikkelBob** [MouseLand/Kilosort#551]
I'm trying to optimize my sorting pipeline for my 64-channel Neuronexus mouse cortex recordings. For sessions with many clear spikes, ks2.5 and ks3 perform decent enough, where only minimal manual merging / splitting is necessary. However, sessions with slightly more noise or fewer good units tend to be sorted very poorly. In these cases, ks tends to split the data in many "good" neurons, with only a few hundred spikes each (on a 60-90 minute recording). When looking at the traceview, it is clear that over splitting is happening (see image below for an example, ks3 + default settings).

I'd like to do a parameter sweep and re-sort the same session to see how clustering is affected. Which parameters, and which ranges, make sense in this case?

Thanks in advance!

![Capture2](https://github.com/MouseLand/Kilosort/assets/81039361/ac95cb60-e963-4d80-aced-8601ac9b26be)

**Comment by RikkelBob** [comment]
To clarify, many of these spikes are counted as being part of multiple neurons (multiple overlapping colors not visible in traceview above). This keeps me from merging the clusters, because it would result in a very high number of 0 ms refractory period violations

**Comment by kingsEffy** [comment]
I'm having the same issue, quite identical issue actually.

**Comment by kingsEffy** [comment]
> I'm having the same issue, quite identical issue actually.

![Screenshot 2024-02-02 133716](https://github.com/MouseLand/Kilosort/assets/100651591/5dffe8ca-011a-4cfd-9d7f-c004a5302211)

**Comment by kingsEffy** [comment]
> > I'm having the same issue, quite identical issue actually.
> 
> ![Screenshot 2024-02-02 133716](https://private-user-images.githubusercontent.com/100651591/301977883-5dffe8ca-011a-4cfd-9d7f-c004a5302211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MTAyMDUsIm5iZiI6MTcwNjkwOTkwNSwicGF0aCI6Ii8xMDA2NTE1OTEvMzAxOTc3ODgzLTVkZmZlOGNhLTAxMWEtNGNmZC05ZDdmLWMwMDRhNTMwMjIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQyMTM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTk1YWJiOTUyMWQ5N2JhMzFmNGU5ODdlYWYyNmNlOWY1MDVlMDI1OGRiMTlkMjY1OWNhY2EwMjNhNWIzOGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W7DW71NAar9HuA6kKkpS-wDtU37r7_bwLiAKyWTkW1s)
find this example, you can see actually green spikes and grouped together with artifacts - the large amplitude across all channels..

anyone know why is this happening?
