### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sdcushing** [MouseLand/Kilosort#552]
I'm pretty new to CUDA, and I've been trying to install and run kilosort.
Version info:
Matlab2023a
Visual C++ 2022

gpuDevice
  CUDADevice with properties:

                      Name: 'NVIDIA GeForce GTX 1660'
                     Index: 1
         ComputeCapability: '7.5'
            SupportsDouble: 1
             DriverVersion: 12.2000
            ToolkitVersion: 11.2000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 6.4421e+09
           AvailableMemory: 5.2271e+09
       MultiprocessorCount: 22
              ClockRateKHz: 1815000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
           DeviceAvailable: 1
            DeviceSelected: 1

Every time I run mexGPUall it gives the error
Warning: The selected C++ compiler is not supported for CUDA compilation.
Searching for a supported compiler. 
> In mexcuda (line 96)
In mexGPUall (line 7) 
Error using mex
Supported compiler not detected. For options, visit
https://www.mathworks.com/support/compilers.

Error in mexcuda (line 168)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in mexGPUall (line 7)
    mexcuda -largeArrayDims spikedetector3.cu

I have run mex -setup C++ and it says that mex is now configured to use Visual C++.

After getting this error, I've tried using Matlab 2022a as well as Mingw64 for the compiler, and I get the same result.

**Comment by zm711** [comment]
The mix of CUDA, compiler, and Matlab can be super tricky. I'm no expert, but at least for my most recent setup I did
Matlab 2021a with Visual Studio C++ 2019. I know Visual Studio has been a bit inconsistent in having full support for C++ compiling so I would verify 2022 is definitely what you want (but I can confirm 2019 worked in the past). Also downloading the right CUDA for your specific Matlab isn't always straightforward. I would double check that you have the right combo of those as well.

**Comment by emwonghiu** [comment]
Matlab 2022a worked for me using VS C++ 2019 and CUDA Toolkit 11.2. I found toolkit compatibility here: https://www.mathworks.com/help/parallel-computing/run-mex-functions-containing-cuda-code.html

**Comment by RuthKassahun** [comment]
@sdcushing I've had the same error and this [answer ](https://www.mathworks.com/matlabcentral/answers/309117-how-to-get-mexcuda-running-compiler-settings#comment_2830547)from matlab helped me. As you can see from your ```gpuDevice()``` output the ```ToolkitVersion: 11.2``` this indicated that you should use CUDA version 11.2. After installing that keep the bin folder in your environmental variables CUDA_PATH. For a sanity check you can use ```nvcc --version```  in the command line to see the CUDA version you're running. In addition, in the visual studio 2022 installer make sure you download C++.
