### ISSUE TITLE
Packaging Kilosort for use without a Matlab license

### ISSUE THREAD

**Issue by yqushair** [MouseLand/Kilosort#553]
Hello! I've been looking for a way to package up Kilosort as a standalone Matlab app or a Python library in order to use it without a Matlab license, but keep running into issues with the MEX-related code. I then saw the discussion in #215. Just wanted to confirm two things:

1. As it stands, there is no way to use Kilosort without owning a Matlab license, and
2. There are plans to release Kilosort4 soon, which is implemented in Python

If these are correct, is there an estimated release date for KS4? Thanks and take care!

_Originally posted by @yqushair in https://github.com/MouseLand/Kilosort/issues/215#issuecomment-1618336879_

**Comment by ja-94** [comment]
SpikeInterface has Docker/Singularity [images](https://hub.docker.com/u/spikeinterface) for this :)
