### ISSUE TITLE
Error After Preprocessing

### ISSUE THREAD

**Issue by NMTorrens** [MouseLand/Kilosort#554]
I am running into an error after the preprocessing finishes in the GUI on kilosort3.

![Matlab Preprocessing 2 error](https://github.com/MouseLand/Kilosort/assets/80142957/25d3d5c8-cbba-4609-8adb-c16ce4ec36f2)

I think that the error might be in the channel map configuration. I am using 4 shanks that contain 2 tetrodes each, with each tetrode having 8 electrodes. 

![unnamed](https://github.com/MouseLand/Kilosort/assets/80142957/5440d2d5-5cae-4215-a175-b2cc180e61b1)

![unnamed](https://github.com/MouseLand/Kilosort/assets/80142957/bdca5867-fa3c-46fb-9e60-5e2b44d0aea2)

Currently I am using a linear 32 channel map for kilosort. 

![Kilosort GUI Filtered](https://github.com/MouseLand/Kilosort/assets/80142957/8405f05c-c2e2-46f8-9f1f-6420fd69606d)

I am not sure if I should instead create my own channel map with the "new" option in the GUI, and if I need to include the spacing between each shank, or between each electrode (vertically and/or horizontally). When I run kilosort, the preprocessing finishes without a problem, identifying the batches and the spikes, but it throws an error after, as shown in the first uploaded image. Some other forums mention using a "pitch" but not sure how to include that here (if needed).

**Comment by zm711** [comment]
@NMTorrens .Worth giving #414 a read as it discusses the two strategies for multi-shank map generation. Kilosort isn't really designed for multishank so that thread gives a couple work arounds.
