### ISSUE TITLE
Kilosort GUI error when saving for phy - Unrecognized function or variable 'writeNPY'.

### ISSUE THREAD

**Issue by RuthKassahun** [MouseLand/Kilosort#569]
Hello, 

When I use the Kilosort GUI, I am able to successfully run the Preprocessing and Spike Sorting steps. However, I encountered an error when attempting to save the results for Phy. The error message in the command window looks like this. 

```
Unrecognized function or variable 'writeNPY'.

Error in rezToPhy2 (line 141)
    writeNPY(spikeTimes, fullfile(savePath, 'spike_times.npy'));

Error in ksGUI/runSaveToPhy (line 837)
                rezToPhy2(obj.rez, fullfile(obj.ops.saveDir));

Error in ksGUI>@(~,~)obj.runSaveToPhy() (line 345)
                'Callback', @(~,~)obj.runSaveToPhy());
 
Error while evaluating UIControl Callback.
```
In my output directory I have ```cluster_Amplitude.tsv```, ```cluster_ContamPct.tsv```, ```cluster_KSLabel.tsv```, ```rez.mat``` and ```temp_wh.dat``` files.

Thanks!

**Comment by zm711** [comment]
@RuthKassahun 
Do you have this on your matlab path? It is required for exporting to phy. It should display a warning in the actual KS gui to download.

https://github.com/kwikteam/npy-matlab

**Comment by RuthKassahun** [comment]
@zm711 Thank you for the answer. It has solved my issue.
