### ISSUE TITLE
Error saving data for phy! Unrecognized field name "Wphy"

### ISSUE THREAD

**Issue by Tianyulied** [MouseLand/Kilosort#571]
In some data,i got this error. I run this data in 3 different computer with different GPU, then get the same error.So, I think is not the drive problem. Can you help me, please?
![1](https://github.com/MouseLand/Kilosort/assets/119161703/5d9f320e-074d-48a4-8bee-86886ed89d1c)

**Comment by zm711** [comment]
@Tianyulied, what does Matlab itself say? There might be more information there that would be helpful.

**Comment by Tianyulied** [comment]
![image](https://github.com/MouseLand/Kilosort/assets/119161703/b582476f-bdc3-4bda-a786-fec113823835)

 
Unfortunately， there is no information in Matlab console.

**Comment by TheAnton205** [comment]
Any resolution?
