### ISSUE TITLE
Can not use drift correction kilosort3

### ISSUE THREAD

**Issue by WWL606** [MouseLand/Kilosort#577]
Hi,

I am using kilosort3. There is no error when 'N blocks for registration' on GUI is 0. But when it is not zero , I get the following error message:

```
Error using gpuArray/subsref
Subscript indices must either be real positive integers or logicals.

Error in extractTemplatesfromSnippets (line 56)
wTEMP = dd(:, round(linspace(1, size(dd,2), nPCs)));

Error in extract_spikes (line 42)
[wTEMP, wPCA]    = extractTemplatesfromSnippets(rez, NrankPC);

Error in ksGUI/runSpikesort (line 795)
                [obj.rez, st3, tF]     = extract_spikes(obj.rez);

Error in ksGUI>@(~,~)obj.runSpikesort() (line 339)
                'Callback', @(~,~)obj.runSpikesort())

Error while evaluating UIControl Callback.
```

Any help is appreciated!

Thanks,
Wenliang

**Comment by marius10p** [comment]
It means that no spikes were detected. You can double check that the data is loaded correctly (data type especially) and it looks right in the GUI, and if everything looks normal, you can try lowering the spike detection threshold (advanced parameter in the config384 script). The spike threshold is negative.
