### ISSUE TITLE
INSTALLATION: no Qt platform plugin

### ISSUE THREAD

**Issue by janinaf** [MouseLand/Kilosort#597]
### Describe the issue:

Hi, 

I went through the installation with absolutely no problem, but then I got this error message when I tried to run Kilosort

QObject::moveToThread: Current thread (0x1f029354620) is not the object's thread (0x1f0293558e0).
Cannot move to target thread (0x1f029354620)

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, webgl, windows.

Thanks in advance for help

### Provide environment info:

     active environment : kilosort4
    active env location : C:\Users\Janina\.conda\envs\kilosort4
            shell level : 2
       user config file : C:\Users\Janina\.condarc
 populated config files : C:\Users\Janina\.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.3=0
                          __win=0=0
       base environment : C:\ProgramData\anaconda3  (read only)
      conda av data dir : C:\ProgramData\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\anaconda3\pkgs
                          C:\Users\Janina\.conda\pkgs
                          C:\Users\Janina\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Janina\.conda\envs
                          C:\ProgramData\anaconda3\envs
                          C:\Users\Janina\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22631 aau/0.4.2 c/ez6ZKYPLG2bN4asxZTNF1Q s/ZcEWvDTD8E1L0f7ZS8OBVQ e/uRtKNJZVJmnv7B985iDwCA
          administrator : False
             netrc file : None
           offline mode : False

### Operating system information:

Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎21/‎2022
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by janinaf** [comment]
HI Jacob,

thanks for suggestions, I will try. I didn't have time to look very deeply
into this, but if I manage to solve it, I'll certainly post.

**Comment by thugeun** [comment]
Hello, I also had the same error, which seems to be resolved (for now?). Here's what I did:

1) First, I followed steps 1 to 5 from the link in Jacob's suggestion, but it didn't work.
2) I didn't have the variable "QT_PLUGIN_PATH," so I initially thought step 6 wasn't for my case. However, I found this post: https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m. I created a new variable named "QT_PLUGIN_PATH" with the value "C:\ProgramData\Anaconda3\Library\plugins". 

Now GUI appears without any errors.

**Comment by thugeun** [comment]
....And now, I am having the same "qt.qpa.plugin: Could not load the Qt platform" error when I try to run phy.

This can be fixed by undoing the 2nd step of my comment above and then, as you may expected, running kilosort 4 raises the same error (Phy and Kilosort4 are installed on two different environments.)

**Comment by jacobpennington** [comment]
Closing this as a pycharm & pyqt issue. If there ends up being something specific to Kilosort we can re-open it, otherwise I recommend trying the steps mentioned above or launching from a standalone terminal.

**Comment by gianDel99** [comment]
> Hello, I also had the same error, which seems to be resolved (for now?). Here's what I did:
> 
> 1. First, I followed steps 1 to 5 from the link in Jacob's suggestion, but it didn't work.
> 2. I didn't have the variable "QT_PLUGIN_PATH," so I initially thought step 6 wasn't for my case. However, I found this post: https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m. I created a new variable named "QT_PLUGIN_PATH" with the value "C:\ProgramData\Anaconda3\Library\plugins".
> 
> Now GUI appears without any errors.

you are the goat it worked
