### ISSUE TITLE
BuG: Re: spike holes

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#598]
### Describe the issue:

Just making sure the issue isn't lost in kilosort4.
Issue #594 raised a serious concern regarding the data loading.  
Can you confirm if this issue is present in KS4 or being investigated?

Thanks,
Shahaf

### Version information:

Linux win 10

### Context for the issue:

Possible bug carried over from past versions of kilosort

**Comment by runbogao** [comment]
Hi Marius, thanks for testing the issue for all the version of KS. We are using a pipeline (https://github.com/jenniferColonell/ecephys_spike_sorting)) based on KS2.5 to do spike sorting, and all pipeline for downstream analysis are based on that. We would like to stick to KS2.5 for now. Do you have any suggestions to work around the bug (e.g. splitting batches with a small overlap)?   Thank you in advance!

**Comment by jacobpennington** [comment]
Closing this one, it looks like #594 is the right place to continue this discussion.

**Comment by marius10p** [comment]
@runbogao The latest release version 2.5.2 should fix this issue. Would be great if you could test it and give me some feedback.
