### ISSUE TITLE
INSTALLATION: Using pdm

### ISSUE THREAD

**Issue by ChauhanT** [MouseLand/Kilosort#600]
### Describe the issue:

Hi, I am not able to find kilosort using `pdm`. I was able to find and install kilosort4. However, it gives a `ModuleNotFoundError: No module named 'kilosort'` error.

### Provide environment info:

I am using `pdm` and python version 3.11.

### Operating system information:

Debian 12 on kernel 6.1

**Comment by jacobpennington** [comment]
Hello,

We haven't published Kilosort4 to pypi/pip yet (but this will happen soon), so you won't be able to install it with `pdm` yet. You will have to follow the instructions in the readme to clone the repository and install it locally from the downloaded files.

**Comment by ChauhanT** [comment]
Gotcha. I saw Carson closing all the old matlab issues and I thought ks4 was upon us 😄 Closing.
