### ISSUE TITLE
Kilosort 2.5 vs Kilosort 4 on uint16 data

### ISSUE THREAD

**Issue by Lathomas42** [MouseLand/Kilosort#607]
### Describe the issue:

We use the [intan RHD USB board ](https://intantech.com/RHD_USB_interface_board.html) to record 64 channel cambridge neurotech probes in behaving animals.

Currently we use the option of saving 1 rhd file every 30 minutes of recording. 

Testing Kilosort 4 vs Kilosort 2.5 on **just one of the 30 min uint16 recordings** has shown me that Kilosort 4 is not yielding the same units (or any units for that matter) as kilosort 2.5 with default parameters. When inspected with phy, all of the units are either massive motion artefacts (presumably) or flat lines on all channels. I was hoping someone could guide me as to what parameters should be tuned to get comparable performance of kilosort 4 and kilosort 2.5, or if there is a different step I could take.

Two things of note:
- that the channels that yield 'good' units in KS2.5, have 0 units (even 'mua') in my KS4 sorting output.
- The amplitudes are on different scales between KS2.5 and KS4, in KS2.5 my units had amplitudes in the ~1000 range, where as in KS4, my 'units' all have amplitudes in the 0-100 range. Does this indicate something with the uint16 data format?

Attached are the outputs of KS4 (many low amplitude units with high firing rate, however all non neural), and KS2.5 (many 0 low firing rate units with high amplitude, where the good units have higher firing rate)

![ks25](https://github.com/MouseLand/Kilosort/assets/5692020/049d8c56-546a-4163-b0f9-77ea8ffec19e)
![ks4_all](https://github.com/MouseLand/Kilosort/assets/5692020/31a467ff-2edc-443a-93ec-830e0f37fd95)

**Comment by jacobpennington** [comment]
Yes, some sample data and the probe configuration for it would help narrow this down. Thanks!

**Comment by Lathomas42** [comment]
Thanks so much, here is the bin file (uint16, 64 channels) and the probe config https://drive.google.com/drive/u/0/folders/1BUnjBt990FwJs0JTjUgEhpRz0b6DhO4p

**Comment by Lathomas42** [comment]
I should specify that by Kilosort2.5, I meant that I have been using pykilosort on this data, which works well, not the matlab Kilosort2.5 branch.

My apologies for any confusion. Also happy to provide additional data/run additional tests if requested.

**Comment by Darkweiss** [comment]
I also ran Kilosort 4.0 on some data we have previously sorted with Matlab 2.5. 4.0 output seems completely different to 2.5.
I used int16 binary file with Neuropixels3B1 default probe configuration.
![untitled](https://github.com/MouseLand/Kilosort/assets/40541973/4f267e1f-15f9-41cd-af00-8985d9e7bbab)

**Comment by marius10p** [comment]
@Darkweiss did you use the thresholds from Kilosort 2.5 by any chance? That would result in a lot of noise clusters like what you are showing.

**Comment by marius10p** [comment]
@Lathomas42 can you please send the .mat version of the probe file so we can load it into Kilosort 2.5 to replicate your comparison?

**Comment by Lathomas42** [comment]
Sorry @marius10p , as per my previous comment, I was using pykilosort, which claims to be using Ks2.5 algorithm, I realize that was unclear in my original post.

Here is the function i use to create my probe for pykilosort:

```
def cambridge_neurotech_assy_236_h10():
    """ Returns a cambridge neurotech 64 channel H10 probe """
    probe = Bunch()
    probe.NchanTOT = 64
    probe.chanMap = np.arange(64)
    probe.xc = np.zeros(64)
    probe.yc = np.zeros(64)
    probe.kcoords = np.zeros(64)
    probe.chanMap = np.arange(64)
 
    # Intan <- Molex from CNT Digitizer Diagram
    probe_to_intan = np.array([
                        41,39,38,37,35,34,33,32,29,30,28,26,25,24,22,20,
                        46,45,44,43,42,40,36,31,27,23,21,18,19,17,16,14,
                        55,53,54,52,51,50,49,48,47,15,13,12,11,9,10,8,
                        63,62,61,60,59,58,57,56,7,6,5,4,3,2,1,0 
                    ])
    # Molex <- Contacts from Probe Diagram
    probe.chanMap = np.array([
                    32,59,12,29,60,13,61,64,48,16,
                    47,14,31,62,15,42,10,27,58,30,63,46,
                    26,24,25,9,43,57,28,45,11,44,
                    # shank 2
                    8,56,40,22,38,7,23,34,18,54,
                    41,55,20,36,6,52,4,35,1,19,39,49,
                    21,5,53,17,33,3,37,50,2,51]) - 1 # its 1 indexed
    # Intan <- Molex <- Contacts
    probe.chanMap = probe_to_intan[probe.chanMap]
    
    for shank_id in range(2):
        shank_channels = np.arange(32*shank_id,32*(shank_id + 1))
        # go down in columns
        probe.xc[shank_channels] = np.concatenate((np.ones(10)*0.0,np.ones(12)*18.5,np.ones(10)*2*18.5)) + 150 * shank_id
        probe.yc[shank_channels] = np.concatenate(((45.0 + 30*np.arange(10)),(30*np.arange(12)),(45+30*np.arange(10))))
        probe.kcoords[shank_channels] = shank_id

    return probe
```

Happy to provide anything else that could help with this.

**Comment by marius10p** [comment]
Thanks, I think this is related to other problems we have seen for multi-shank probes. The short-term fix is to stack the two shanks on top of each other vertically in the probe file potentially with a small spacing of 100-200um. This should not really affect sorting, and other users have reported good results. Once we have more time, we will implement a built-in solution to treat multi-shank probes correctly.

**Comment by jacobpennington** [comment]
I'm going to close this for now since it appears to be related to the multi-shank issue. If you try stacking the shanks and still get very different results (or other problems), we can reopen it.
