### ISSUE TITLE
warnings when running pytest

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#609]
### Describe the issue:

installation on miniforge mamba went smooth. but got warning running pytest. 
is this just a warning and it actually found all the intended units or is this a crash?

(kilosort) D:\gits\Kilosort4>python -m pytest --runslow
=================================================================== test session starts ====================================================================
platform win32 -- Python 3.8.18, pytest-8.0.2, pluggy-1.4.0
rootdir: D:\gits\Kilosort4
configfile: pytest.ini
plugins: anyio-4.3.0
collected 19 items

tests\test_dtype.py .....                                                                                                                             [ 26%]
tests\test_full_pipeline.py
Starting run_kilosort test...
using probe neuropixPhase3B1_kilosortChanMap.mat
Interpreting binary file as default dtype='int16'. If data was saved in a different format, specify `data_dtype`.
Preprocessing filters computed in  0.57s; total  0.57s

computing drift
Interpreting binary file as default dtype='int16'. If data was saved in a different format, specify `data_dtype`.
Re-computing universal templates from data.
100%
|drift computed in  613.11s; total  613.71s
Interpreting binary file as default dtype='int16'. If data was saved in a different format, specify `data_dtype`.

Extracting spikes using templates
Re-computing universal templates from data.
100%|
99801 spikes extracted in  622.16s; total  1235.91s

First clustering
100%|
264 clusters found, in  28.23s; total  1264.14s

Extracting spikes using cluster waveforms
100%|
139466 spikes extracted in  77.95s; total  1342.10s

Final clustering
100%|
274 clusters found, in  34.69s; total  1376.79s

Merging clusters
267 units found, in  0.31s; total  1377.11s

Saving to phy and computing refractory periods
125 units found with good refractory periods
===================================================================== warnings summary =====================================================================
tests/test_dtype.py::test_int16
  D:\gits\Kilosort4\kilosort\io.py:660: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:212.)
    X = torch.from_numpy(samples.T).to(self.device).float()

tests/test_full_pipeline.py::test_pipeline
  C:\ProgramData\miniforge3\envs\kilosort\lib\site-packages\threadpoolctl.py:1186: RuntimeWarning:
  Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
  the same time. Both libraries are known to be incompatible and this
  can cause random crashes or deadlocks on Linux when loaded in the
  same Python program.
  Using threadpoolctl may cause crashes or deadlocks. For more
  information and possible workarounds, please see
      https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

    warnings.warn(msg, RuntimeWarning)

tests/test_full_pipeline.py::test_pipeline
  D:\gits\Kilosort4\kilosort\postprocessing.py:13: NumbaTypeSafetyWarning: unsafe cast from int32 to undefined. Precision may be lost.
    t0 = cluster_t0.get(c, t-dt)

tests/test_full_pipeline.py::test_pipeline
  D:\gits\Kilosort4\kilosort\postprocessing.py:13: NumbaTypeSafetyWarning: unsafe cast from float64 to undefined. Precision may be lost.
    t0 = cluster_t0.get(c, t-dt)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================= 19 passed, 4 warnings in 1395.49s (0:23:15) ========================================================

(kilosort) D:\gits\Kilosort4>

**Comment by marius10p** [comment]
This is a known warning when accessing the binary file in this way. The "proper" way is much slower for some reason.

**Comment by marius10p** [comment]
Let us know if you find evidence of this resulting in problems. Closing for now.
