### ISSUE TITLE
Does template extraction assume a topological order in the binary file?

### ISSUE THREAD

**Issue by naterenegar** [MouseLand/Kilosort#611]
### Describe the issue:

Hi, 

I am looking at using Kilosort for some _in vitro_ data I've collected, so I was reading through the code to make sure I understand what is going on. When I came across `extract_wPCA_wTEMP`, I found that I didn't understand the peak isolation code.

So `extract_wPCA_wTEMP` extracts isolated spikes to build universal templates using the `pytorch` 2D pooling and averaging operations with default kernel sizes of `[4, 5]` and `[6, 30]`, respectively. The idea is to find isolated spikes in time and space for clean (one spike) templates? However, it doesn't look like any calculation of which channels are near to each other has taken place when this extraction occurs, so the maxing and summing over channels isn't guaranteed to operate on nearby channels. Therefore the peaks this finds may not actually be isolated?

If I were to shuffle the channels in my data and update my probe file accordingly, would it change the extracted templates? I may be misunderstanding something here.

**Comment by marius10p** [comment]
Let us know if you have more comments related to this, closing out this issue for now.
