### ISSUE TITLE
BUG: wrong time

### ISSUE THREAD

**Issue by tiramica** [MouseLand/Kilosort#612]
### Describe the issue:

This is very small bug..

It takes 4200s and it shows 1hour 70min ... maybe it has bug in calculate the time part .
![image](https://github.com/MouseLand/Kilosort/assets/90582481/e41406cc-15ab-448e-9492-331e8dce2da1)

### Reproduce the bug:

```python
.
```

### Error message:

```shell
.
```

### Version information:

.

### Context for the issue:

.

### Experiment information:

.

**Comment by jacobpennington** [comment]
Fixed, thanks!
