### ISSUE TITLE
INSTALLATION: <Please write a comprehensive title.>

### ISSUE THREAD

**Issue by MarcoUniPr** [MouseLand/Kilosort#613]
### Describe the issue:

Hi,
I am currently able to work with Kilosort 3 without any issues. However, I am encountering difficulties while attempting to install Kilosort 4. I receive the following error message:

I have attempted to resolve this issue by reinstalling the application, but unfortunately, this did not solve the problem.

Do you have any advice or suggestions on how to proceed?

Thank you for your assistance.

Best regards,
Marco

### Provide environment info:

(kilosort) C:\Users\lanzi>python -m kilosort
QObject::moveToThread: Current thread (0x2a7734988a0) is not the object's thread (0x2a77349d4e0).
Cannot move to target thread (0x2a7734988a0)

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "C:\Users\lanzi\anaconda3\envs\kilosort\Lib\site-packages\PyQt5" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, webgl, windows.

### Operating system information:

Windows 10

**Comment by jacobpennington** [comment]
Hello,
This is an issue with pycharm and pyqt5 not being compatible without tweaking some settings, not a Kilosort issue. There are some suggested fixes in #597, or you can just launch kilosort from a standalone terminal instead of pycharm.

**Comment by Rodgers-PAC-Lab** [comment]
I'm also getting a related issue. I'm not using PyCharm, just trying to start from the terminal in Linux. 

This is after installing from pip:
```
(kilosort) mouse@octopus:~$ python -m kilosort
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

This is after installing the development version from the github:
```
(kilosort) mouse@octopus:~/dev/Kilosort$ python -m kilosort
Traceback (most recent call last):
  File "/home/mouse/miniconda3/envs/kilosort/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/mouse/miniconda3/envs/kilosort/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mouse/dev/Kilosort/kilosort/__main__.py", line 2, in <module>
    from kilosort.gui.launch import launcher
  File "/home/mouse/dev/Kilosort/kilosort/gui/__init__.py", line 4, in <module>
    from .data_view_box import DataViewBox
  File "/home/mouse/dev/Kilosort/kilosort/gui/data_view_box.py", line 2, in <module>
    import pyqtgraph as pg
  File "/home/mouse/miniconda3/envs/kilosort/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/mouse/miniconda3/envs/kilosort/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/mouse/miniconda3/envs/kilosort/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 54, in <module>
    raise Exception("PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.")
Exception: PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.
```

**Comment by Rodgers-PAC-Lab** [comment]
ok fixed this with some combination of 
```
pip uninstall pyqt5
conda uninstall pyqt
conda install pyqt
```
Somehow, pyqtgraph was not properly finding my PyQt5. Not sure why
Possibly the mix of things installed with conda and pip?

**Comment by jacobpennington** [comment]
Okay, good to know it's not just from pycharm. Unfortunately after doing more searching, it doesn't look like there's any single fix for it. For some people it's an issue with pycharm specifically, for others it's missing libraries that pyqt depends on, for other people `export QT_QPA_PLATFORM=offscreen` seems to fix the issue, or uninstalling/reinstalling like you did.

**Comment by paulbrodersen** [comment]
> For some people it's an issue with pycharm specifically, for others it's missing libraries that pyqt depends on, for other people export QT_QPA_PLATFORM=offscreen seems to fix the issue, or uninstalling/reinstalling like you did.

In case someone else runs into this issue, there is a good stackoverflow thread documenting the various solutions here: https://stackoverflow.com/q/68036484/2912349

---

In my case, I encountered the following error on an Ubuntu 24.04 LTS box:

```
t.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.                                                                                                                                                  
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.                                                                                                                                                              
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.                                                                                                                 
                                                                                                                                                                                                                                                        
Available platform plugins are: offscreen, wayland-egl, vnc, xcb, minimalegl, wayland, eglfs, minimal, vkkhrdisplay, linuxfb.           
```

Installing the missing xcb library resolved the issue:

```sh
sudo apt install libxcb-cursor0
```

**Comment by pas-calc** [comment]
This message might differ
`Available platform plugins are: wayland, eglfs, linuxfb, offscreen, wayland-egl, xcb, vkkhrdisplay, minimal, vnc, minimalegl.`

It seems that `xcb` is used as default unless the environment variable is set differently (set `export QT_QPA_PLATFORM=xxx` where xxx is any of the available plugins, reset: `unset QT_QPA_PLATFORM`). 
The error message will vary and then each needs an individual solution (for example for `wayland`, the error message is:  "Could not load the Qt platform plugin "wayland" in "" even though it was found." )

See also:
- `printenv|grep -i qt` to print Qt related env. variables.
- `pip freeze|grep -i qt` and `dpkg -l |grep -i qt` for pip/system packages related to Qt

**Comment by pas-calc** [comment]
> [...] for other people `export QT_QPA_PLATFORM=offscreen` seems to fix the issue [...]

"QOpenGLWidget is not supported on this platform." and no error message but logs like "QPainter::begin: Paint device returned engine == 0, type: 1", then stuck at "QPainter::end: Painter not active, aborted" and no window
