### ISSUE TITLE
Does KS4 output temp_wh.dat file?

### ISSUE THREAD

**Issue by hemant22** [MouseLand/Kilosort#621]
I didn't find temp_wh.dat file in the output directory of KS4. Do I need to change some settings to allow the output? I use that file to get drift corrected spike waveforms.

**Comment by marius10p** [comment]
Not yet, but @jacobpennington is working on it.

**Comment by hemant22** [comment]
Ok Thanks for the update. I tried KS3 patch 0 that takes care of the missing spikes. But for this version, the spike waveforms extracted from temp_wh.dat shows all noise instead of spikes. Looks like there is some shift in time. The same data works just fine when processed by the old KS3.

**Comment by jacobpennington** [comment]
It looks like the time shift is the same issue people are reporting in #623, so I'm going to close this issue for now.
