### ISSUE TITLE
Error when loading data tpye float32

### ISSUE THREAD

**Issue by AnnaB27** [MouseLand/Kilosort#625]
### Describe the issue:

Good morning,
I am encoutering an issue when tryng to run kilosort on my data. After I open the guide and set all parameters, I click on load but an error appear on the message box:    
Wrot = whitening_local(CC, xc, yc, nrange=nrange, device=f.device)

  File "C:\Users\annab\anaconda3\envs\kilosort\lib\site-packages\kilosort\preprocessing.py", line 30, in whitening_local

    
wrot = whitening_from_covariance(CC[np.ix_(ix, ix)])

  File "C:\Users\annab\anaconda3\envs\kilosort\lib\site-packages\kilosort\preprocessing.py", line 12, in whitening_from_covariance

    
E,D,V =  torch.linalg.svd(CC)

torch._C
.
_LinAlgError
: 
linalg.svd: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 14).

while on the conda prompt this message appear: Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

The thing I don't understand is that it gives error if I select 32float datatype, while if I set 16int the guide runs just fine.
Could you help me?
Thank you!

**Comment by AnnaB27** [comment]
I forgot to mention: I am running kilosort with CPU since my computer does have a grafich card just not NVIDIA.

**Comment by jacobpennington** [comment]
Hello,

It's hard to tell what the issue is just from that error. There could be NaNs in the data for one reason or another, or something else going on. If you're able to share a sample of data and your probe information, I can try to debug this.

I will add that the CPU version is fine for trying it out or sorting a dataset here and there, but it's not a great option if you're wanting to sort a lot of data on an ongoing basis. It's there as a backup, but using a CUDA-enabled GPU is anywhere from 10x to 100x faster (possibly more depending on your data and GPU) and most of our testing and development is being done on the GPU version.

**Comment by AnnaB27** [comment]
Hi,
Sure, is it ok if I just load here a .bin file and the probe file?
Concerning GPU vs CPU I know, this is just temporary and I was just trying to see if I could get kilosort running with my data. I will soon get a computer with an NVIDIA to enable GPU for faster processing

**Comment by jacobpennington** [comment]
Sure, if github will allow you to upload it directly that's fine. Some others have been uploading to google drive and posting a link for that, as an alternative.

**Comment by AnnaB27** [comment]
Here's the link for the Bin file https://drive.google.com/file/d/1Mf_SoIbejTpw7QAAA7MA4-x0mPPutqAn/view?usp=drive_link and the link for the probe info https://drive.google.com/file/d/16pHgj0dna0l6dK0ZN7H2LJJKMyZRtzgJ/view?usp=drive_link.
Thank you very much by the way, I am not an expert with python ecc, so maybe the error is related to something stupid.

**Comment by AnnaB27** [comment]
Sorry, I just realised that I was wrong about the datatype, I cheched and  they actually are int16, not float32 so I was entering the wrong type while running kilosort

**Comment by jacobpennington** [comment]
Great! Everything is working okay then, or did you run into any other issues?
