### ISSUE TITLE
Temporal alignment of channels in Neuropixels recordings

### ISSUE THREAD

**Issue by florgf88** [MouseLand/Kilosort#628]
### Describe the issue:

Hi, I was wondering if Kilosort 4 addresses the issues of multiplexing in the sampling time in Neuropixels recordings, as in the pyKilosort version (I couldn't find this in the documentation). Should be this performed before fitting the data into K4? Any details about this will be very appreciated. Many thanks!

**Comment by florgf88** [comment]
Hi Marius, many thanks for your response. Unfortunately, I cannot provide an example from my data, as I have yet to test differences in clusters with or without channel alignment myself. But I'd also be curious to see if there is a difference. So far, I have been using a similar preprocessing approach as in https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522, where they show that channel-time alignment mitigates artefacts at the spatial filtering stage.

**Comment by marius10p** [comment]
There are multiple steps in the Kilosort pipeline that introduce some amount of robustness to various types of confounds and artifacts. Indeed some artifacts will persist throughout the sorting, but this tends to be dataset-specific. The approach that I recommend is to start with your default sorting results in Phy and see what kinds of problems you might have. Then work backwards if needed to try to improve the results based on the particular weaknesses you observe, either by changing parameters in Kilosort or adjusting your preprocessing pipeline.

**Comment by florgf88** [comment]
Many thanks Marius for the recommendation!
