### ISSUE TITLE
Kilosort Parameters

### ISSUE THREAD

**Issue by PadmasolaGuru** [MouseLand/Kilosort#633]
### Describe the issue:

I am working on data recorded from neuropixel 1.0 probe from dysmorphic neurons where the size of neurons are big and one would assume that the spike spread is on many channels than normal. I am using kilosort 4 for spike sorting and attached is the image of the same. In the yellow rectangles is the spike from same neuron (blue colour), and above and below this there are other spikes detected and kilosort assumes they are from different clusters. And there are few spikes which were not detected in between these spikes. May I know if there are some parameters (like Th_detect and Th_template) we would need to change in kilosort in analysing data from these recordings. It would be really helpful if you could give some information about this. Thank you for your time and consideration. 
![Kilosort](https://github.com/MouseLand/Kilosort/assets/165012288/64e4acaf-7a11-4d4a-8122-342c44a24071)

**Comment by marius10p** [comment]
This seems like just a visualization issue, the channels with those spikes are not colored but that doesn't mean they are not grouped with either the spike above or below.

**Comment by PadmasolaGuru** [comment]
Thank you Marius. May I please ask what about these spikes (one with different colour) detected as different clusters above and below these blue coloured spikes. They appear to be same spike occurring at same time but detected as two different clusters. Thank you.

**Comment by marius10p** [comment]
It's possible that they are from the same unit, or they are from units that happened to fire together a few times. The main way to check would be to look at their cross-correlogram when you select those units together. If you see a huge peak at zero lag, then we can discuss further what parameters in the sorting might help.

**Comment by PadmasolaGuru** [comment]
Thank you Marius for your answer. I looked at these units and here is the image attached. The Blue is marked as good and the other three as MUA. It appears that in CCG, the blue, red and yellow has peak at zero-lag and not the green one. 

<img width="1920" alt="KS_units" src="https://github.com/MouseLand/Kilosort/assets/165012288/96b26d49-1cda-4f4d-90fd-cc41da127526">

**Comment by marius10p** [comment]
I think this is reasonable then. Those cross correlogram peaks are not very large (if the units were always synchronous, the peak would be much larger). In addition, only the blue unit is good, so I wouldn't worry too much about the peaks. What's probably happening is that the mua templates are catching a few of the residuals of the good unit. Since they're all mua, that "contamination" shouldn't really matter for analyses.

**Comment by PadmasolaGuru** [comment]
Thank you very much Marius. This really helps.

**Comment by jacobpennington** [comment]
Looks like this is taken care of so I'm closing this for now, let us know if you encounter more issues.
