### ISSUE TITLE
Sorting comparison between 2.5 and 4

### ISSUE THREAD

**Issue by PadmasolaGuru** [MouseLand/Kilosort#634]
### Describe the issue:

HI, I used Kilosort 2.5 for sorting out data recorded from Neuropixel 1.0 probe. After the release of Kilosort 4, I tried to run KS4 on the same data and compared the sorting quality. It seems that KS4 sorted quite large number of spikes compared to KS2.5. Although the number of Good and MUA clusters are fairly equal between both, but the number of total number spikes in Good clusters is atleast 50% less in KS4 compared to KS2.5. May I know if this is something we need to be concerned of. Attached is the image of comparison between KS2.5 and KS4. 
<img width="467" alt="KS comparison" src="https://github.com/MouseLand/Kilosort/assets/165012288/c0c84380-3cf9-49ca-b024-11aac3726984">

**Comment by marius10p** [comment]
This will depend on your particular experimental prep, probe geometry, thresholds etc. What you can do is load them side by side in Phy and see if the extra good clusters in KS2.5 are actually good or not, and which units are not found in Kilosort4. With that information, you may be able to figure out what parameters to adjust if any (drift correction etc). We'll make a guide for evaluating and fixing problems, when we have time.

**Comment by jacobpennington** [comment]
Closing this for now, related to #642. If you have additional questions please let us know.
