### ISSUE TITLE
BUG: wrong dminx calculated for the Neuropixels probe

### ISSUE THREAD

**Issue by AntonioST** [MouseLand/Kilosort#635]
### Describe the issue:

For our Neuropixels recording, if we do not specify the parameter "dminx", [template_centers](https://github.com/MouseLand/Kilosort/blob/main/kilosort/spikedetect.py#L96) will calculate the wrong value 1, which should be 32 for Neuropixels probe version 2. It will cause [template_match](https://github.com/MouseLand/Kilosort/blob/main/kilosort/spikedetect.py#L116) to allocate 32 times more memory and fail with an OutOfMemoryError.

Changing the "batch_size" and "nt" values won't help in this case.

### Reproduce the bug:

run kilosort with a Neuropixels data and the corresponding probe, but without providing "dmin" and "dminx".

### Error message:

```shell
Traceback (most recent call last):
  File ".../run_kilosort.py", line 116, in <module>
    main(ap.parse_args())
  File ".../run_kilosort.py", line 102, in main
    run_kilosort(
  File ".../Kilosort4/kilosort/run_kilosort.py", line 134, in run_kilosort
    ops, bfile, st0 = compute_drift_correction(
  File ".../Kilosort4/kilosort/run_kilosort.py", line 344, in compute_drift_correction
    ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar)
  File ".../Kilosort4/kilosort/datashift.py", line 192, in run
    st, _, ops  = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)
  File ".../Kilosort4/kilosort/spikedetect.py", line 251, in run
    xy, imax, amp, adist = template_match(X, ops, iC, iC2, weigh, device=device)
  File ".../Kilosort4/kilosort/spikedetect.py", line 149, in template_match
    A = torch.einsum('ijk, jklm-> iklm', weigh, B[iC,:, nb*t:nb*(t+1)])        
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.33 GiB. GPU 0 has a total capacity of 5.94 GiB of which 301.06 MiB is free. Including non-PyTorch memory, this process has 5.64 GiB memory in use. Of the allocated memory 5.26 GiB is allocated by PyTorch, and 215.26 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

This is one example of an error output. This case will raise an error at any large memory allocation, like template_match:133, 134, and 135, which use "Nflit" calculated from the product of the numbers of x and y segmentations.

### Version information:

Linux 5.4.0-169-generic Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
python                    3.9.12               h12debd9_1
torch                     2.2.1                     <pip>
nvidia-cublas-cu12        12.1.3.1                  <pip>
nvidia-cuda-cupti-cu12    12.1.105                  <pip>
nvidia-cuda-nvrtc-cu12    12.1.105                  <pip>
nvidia-cuda-runtime-cu12  12.1.105                  <pip>
nvidia-cudnn-cu12         8.9.2.26                  <pip>
nvidia-cufft-cu12         11.0.2.54                 <pip>
nvidia-curand-cu12        10.3.2.106                <pip>
nvidia-cusolver-cu12      11.4.5.107                <pip>
nvidia-cusparse-cu12      12.1.0.106                <pip>
nvidia-nccl-cu12          2.19.3                    <pip>
nvidia-nvjitlink-cu12     12.4.99                   <pip>
nvidia-nvtx-cu12          12.1.105                  <pip>
```

NVIDIA GeForce GTX 980 Ti

### Context for the issue:

A workaround that provides the correct "dmin" and "dminx" values could fix this issue, but it is difficult to figure out the root cause from the error message.

The other related issue is that using Kilosort4 sort a 4-shank Neuropixels recording. Even I provided "dmin" and "dminx", I still got an OutOfMemoryError error. I know you are working on supporting multiple shanks, and I hope it would help.

**Comment by marius10p** [comment]
That is indeed strange thanks for the issue. Do you mind sending your probe file?

**Comment by AntonioST** [comment]
[issue635.prb.txt](https://github.com/MouseLand/Kilosort/files/14758568/issue635.prb.txt)

We used a half-density checkerboard-arranged map on shank 1, rather than a default map. The blue rectangles indicate the channels, and the yellows are disconnected channels.

![issue635](https://github.com/MouseLand/Kilosort/assets/6375955/9e68f366-71a1-438e-8ad9-428ea458091f)

**Comment by marius10p** [comment]
Thanks for sharing, we think we understand the bug now. dminx will now default to 32 instead of attempting automatic estimation. @jacobpennington please close this issue when that change is pushed. 

For the multishank probe, the temporary solution is to stack the shanks on top of each other vertically. This should have very little if any adverse effects. We are going to work on a more elegant solution, but it will take some time.

**Comment by jacobpennington** [comment]
Changes to `dminx` behavior have been pushed.
