### ISSUE TITLE
FEATURE: PC features for Phy 

### ISSUE THREAD

**Issue by marius10p** [MouseLand/Kilosort#639]
### Feature you'd like to see:

PC features like in previous versions of Kilosort. These should be done on drift-corrected and background-subtracted data. @jacobpennington almost has this implemented.

**Comment by jacobpennington** [comment]
This has been implemented.

**Comment by Virginia9733** [comment]
May I ask kilosort4 also can have the PC_features.npy file or just the updated kilosort 3?

**Comment by jacobpennington** [comment]
@Virginia9733 Kilosort4 does have pc_features.npy now, you may need to reinstall to see that. You can install from source, or upgrade to 4.0.3 through pip.
