### ISSUE TITLE
FEATURE: make a drift-corrected binary file for Phy

### ISSUE THREAD

**Issue by marius10p** [MouseLand/Kilosort#640]
### Feature you'd like to see:

Similar to Kilosort 2.5/3. This helps the visualization in Phy when there is a lot of drift, so that waveform snippets are extracted after drift correction. Like in previous versions, the filtered, whitened and drift-corrected data should be multiplied by 200 before converting to int16 for the binary file. 

Some things to be careful about: the inverse whitening matrix needs to be disabled in this case (replace with identity divided by 200).

**Comment by jacobpennington** [comment]
Implemented with [v4.0.12](https://github.com/MouseLand/Kilosort/releases/tag/v4.0.12)
