### ISSUE TITLE
Kilosort 4 - Creating a Probe

### ISSUE THREAD

**Issue by ckdc2000** [MouseLand/Kilosort#649]
### Describe the issue:

Hello! I had a previous issue #622 that was closed. However, I encountered another problem related to that. I tried to run this script for my probe according to your reply in #622 :

```
import numpy as np
from kilosort.io import save_probe

chanMap = np.arange(16)
kcoords = np.zeros(16)
n_chan = 16

xc = np.ones(16)
yc = np.ones(16)*100

neuronexus_probe = {
    'chanMap': chanMap,
    'xc': xc,
    'yc': yc,
    'kcoords': kcoords,
    'n_chan': n_chan
}

print(neuronexus_probe)

save_probe(neuronexus_probe, './neuronexus_probe_test.json')
```
However, probe view showed only one channel. Would the correct yc be this:
`yc = np.array([1500 + 100*i for i in range(16)])`
Although, I am not sure whether the value of the first yc coordinate should be 1500 micrometer or something else?

**Comment by jacobpennington** [comment]
yc = np.ones(...) was a typo, I meant np.arange which is equivalent to what
you posted. Whether you set the first value to 0 or 1500 doesn't matter for
sorting, only the relative distances affect Kilosort4's behavior.

**Comment by jacobpennington** [comment]
Let us know if you have any more difficulty with this.
