### ISSUE TITLE
BUG: Kilosort 3.0 not loading configFile384.m automatically

### ISSUE THREAD

**Issue by msj220001** [MouseLand/Kilosort#650]
### Describe the issue:

When I run >>Kilosort, the GUI opens, but the defaultOps, ks.ops, are not the parameters I entered into configFile384.m

I think this has something to do with the file paths in one of the functions, but I don't know which function/where to edit the file path to my configFile384.m path.

Kilosort 3.0 Advanced Settings:
![Capture (0)](https://github.com/MouseLand/Kilosort/assets/157846284/a258cb0b-39fa-4c11-b632-70a7fcdf2970)

My configFile384.m parameters:
![Capture (1)](https://github.com/MouseLand/Kilosort/assets/157846284/ac3934ec-04f0-4544-9969-d6096e26be2f)

### Version information:

Matlab 2023b
Kilosort 3.0

### Experiment information:

**Comment by Lorena-J** [comment]
try to do this: 
https://github.com/MouseLand/Kilosort/issues/427
It works to me!!!!

**Comment by msj220001** [comment]
> try to do this: #427 It works to me!!!!

Thanks!
I managed to resolve my previous issue by altering the filtering thresholds.

**Comment by marius10p** [comment]
@msj220001 this is only dependent on how your Matlab paths are configured. You can click on "Set path" in the main matlab menu and exclude all other versions of kilosort. You can also type in the Matlab command line "which configFile384" and it will tell you which one is in the path currently.

**Comment by msj220001** [comment]
> @msj220001 this is only dependent on how your Matlab paths are configured. You can click on "Set path" in the main matlab menu and exclude all other versions of kilosort. You can also type in the Matlab command line "which configFile384" and it will tell you which one is in the path currently.

Got it! Thank you.
