### ISSUE TITLE
Error with probeinterface.plotting in SpikeGLX recording session with load_sync_channel set

### ISSUE THREAD

**Issue by rahim-hashim** [MouseLand/Kilosort#656]
### Describe the issue:

When using `si.read_spikeglx` with load_sync_channel=True set, plotting the probes from the recordings provide an error. It is fixed if you set the load_sync_channel=False.
![sync_channel_true](https://github.com/MouseLand/Kilosort/assets/3630041/8abbb120-e3f1-46a5-9a02-0c2c42249637)
![error_msg](https://github.com/MouseLand/Kilosort/assets/3630041/e0b341d7-9466-4fc4-91ed-4911bf91aa1a)

### Error message:

```shell
ValueError: There is no Probe attached to this recording. Use set_probe(...) to attach one.
```

### Version information:

SpikeInterface version: 0.100.4

### Experiment information:

When setting load_sync_channel=False
![probe_images](https://github.com/MouseLand/Kilosort/assets/3630041/c4c72a20-dc3d-48f8-a340-3e4b23eaab16)

**Comment by jacobpennington** [comment]
Hello,
This appears to be entirely about spikeinterface  / probeinterface. You will need to post this on their Github.
