### ISSUE TITLE
BUG: Kilosort3 output isn't deterministic

### ISSUE THREAD

**Issue by naterenegar** [MouseLand/Kilosort#660]
### Describe the issue:

Hello,

I've found that running the same exact data through kilosort3 results in different outputs each time the algorithm is run. I've skimmed through the code base looking for any random number generation, and nothing obvious stuck out. Is there some randomness in Kilosort3 that I'm unaware of? The next places I was looking was at the CUDA kernels to see if there are any data races or if there are un-initialized buffers, but I figured it is better for the actual devs to check this out.

How I'm checking this is the number of clusters found after each run. For four runs over the same data with the same parameters, the algorithm found 404, 405, 412, and 408 clusters. The number of good clusters also varied. 

I noticed this because running kilosort3 locally and through spikeinterface + docker had different results.

Thanks,
Nathan

### Version information:

OS: Ubuntu 22.04
Matlab Version: R2023b
Kilosort Version: v3.0.2

### Context for the issue:

Results should be reproducible. If there's a stochastic element to the algorithm, then a parameter for seeding the rng should be added.

### Experiment information:

Probe: _in vitro_ 2D HD-MEA
Cells: Mouse Cortical Cells + Astrocytes
Recording: 300s, 916 channels

**Comment by MirArt94** [comment]
Hello,
for Kilosort 2 and 3 this issue has been solved and described in _mexGPUall.m_ line 12ff:

```
        % For algorithm development purposes which require guaranteed
        % deterministic calculations, add -DENSURE_DETERM swtich to
        % compile line for mexMPnu8.cu. -DENABLE_STABLEMODE must also
        % be specified. This version will run ~2X slower than the
        % non deterministic version.
```

However scanning through the files of the kilosort 4 release I have not found any comments indicating if Kilosort4 gives deterministic results or how it could be made determistic if not by default. I would be very interested to know, if Kilosort 4 can be run giving deterministic outputs :)

Thanks,
Mirko

**Comment by jacobpennington** [comment]
@MirArt94 From the testing we've done so far, Kilosort4 will get an exact match for spike count, cluster count, and some intermediate variables used for preprocessing and drift correction when running the same data with the same settings on the same machine. More precise guarantees (like checking that the same spikes are assigned to the same clusters) have not been tested yet.

Different hardware, operating system, or library versions (pytorch, numpy, etc) do seem to affect the results, but we test on a couple different python versions on Ubuntu, Mac & Windows to make sure they stay within 2.5% and 5% differences for spike count and cluster count, respectively.

**Comment by marius10p** [comment]
@MirArt94 the determinism flag in KS2-3 was disabled by default as it made the processing many times slower. We are using pytorch now, and we see deterministic outputs on the same machine but slightly different outputs on different machines. We will not prioritize getting to the bottom of this since it is fairly common situation for GPU computation and it does not influence the results sufficiently that we think it would be a problem (at least for "good" neurons) .
