### ISSUE TITLE
Question About How to Export the Local Field Potential

### ISSUE THREAD

**Issue by MaLab24** [MouseLand/Kilosort#665]
### Describe the issue:

Hello, 

I have kilosort and phy setup and both are working beautifully. However, I was wondering if there was a way to export the local field potential data from the recordings. 

Thanks

**Comment by MaLab24** [comment]
I was also wondering if feature view has been added back. 

Thanks, 

Aidan

**Comment by jacobpennington** [comment]
Feature view is implemented now, yes. Kilosort does not make use of LFP, so I'm not sure what you are looking for there. My understanding is that LFP is typically recorded in a separate data stream, so how you access that would depend on your hardware.
