### ISSUE TITLE
how to tell Kilosort some channels are bad, do not use them?

### ISSUE THREAD

**Issue by zkcsmxz** [MouseLand/Kilosort#666]
### Describe the issue:

Hi, 
How to tell Kilosort some channels are bad, do not use them?
Thank you

**Comment by chris-angeloni** [comment]
I'm also interested in this feature, it looks like it is possible to create a probe object and set dead channels to -1: https://github.com/MouseLand/Kilosort/blob/main/docs/tutorials/load_data.ipynb

I'm going to find some time soon to try this out

**Comment by jacobpennington** [comment]
There is not currently a way to specify this separate from the probe file you use, so you would have to save a new copy of it with those channels excluded. For example, if I originally use:
```
n_chan_bin = 64
probe = {'chanMap': np.arange(64), ... <other entries specifying 64 values>}
```
and then notice that the first 3 channels in the data are bad, I would instead use:
```
n_chan_bin = 64  # this doesn't change
probe = {'chanMap': np.arange(3, 64), ... <other entries specifying 61 values>}
```

**Comment by jacobpennington** [comment]
@zkcsmxz  @chris-angeloni  and anyone else wanting this feature, can you please explain how you would want to use this? I.e. are you trying to sort several data files with the same probe map and just exclude different 'bad' channels each time? Would you want to be able to do that through the GUI, or are you using the API? Adding this to the API will be straightforward, but there are a lot of ways it could be represented in the GUI so I want to make sure we're making it easy for you.

**Comment by zkcsmxz** [comment]
Thanks a lot!
I use GUI; it will be easier for me to type in the number of bad channels somewhere in the GUI.

**Comment by jacobpennington** [comment]
@zkcsmxz Just to clarify, would you want to be able to type in numbers relative to the rows in the data file, or the order in which the contacts are listed on the probe? Sometimes those are not the same.

**Comment by ZhongRenNeuroscience** [comment]
@jacobpennington Thank you for working on this. Because I'm working with Neuropixel V2 probe, it is crazy to manually sort data from 384 channels with 4 shanks in Phy. I think whether I can sort shank by shank to make the manual sorting easier.

**Comment by jacobpennington** [comment]
@ZhongRenNeuroscience There will be an option to do this without modifying the probe file with the next PyPi release. In the meantime, you can accomplish that by making a separate probe file for each shank.

**Comment by igfebbo** [comment]
To change the probe map so that bad channels are marked 'bad', do I set them as -1?

Your example where you exclude the first three values does not apply to me since my bad channels are random throughout the probe.
