### ISSUE TITLE
KS4 over-merging units 

### ISSUE THREAD

**Issue by florgf88** [MouseLand/Kilosort#667]
### Describe the issue:

Hi, I have recently tried KS4, which yielded nice clusters across some regions in a NP 1 recording. However, in one of the areas I'm interested in, which has high activity during my experiments, not several clusters were detected (highlighted in white in the spike position across the probe plot).
![Screenshot 2024-04-12 180243](https://github.com/MouseLand/Kilosort/assets/68202933/4ad155f8-f659-4530-a352-faf0b99c4151)

When I looked at the units from this area in Phy, I noticed that most of them are MUAs with high violations in the RP. In this example, the distribution of the amplitude looks bimodal:
![Capture](https://github.com/MouseLand/Kilosort/assets/68202933/dde1d77d-d71d-4ebd-b1ef-6db49bd8e740)

I have compared the results in pyKilosort for this area,  and it seems that KS4 is over-merging clusters. Is there any way to control this? I tried adjusting Th(universal) and Th(learned), but it didn't help. 

I appreciate any help or suggestion, many thanks!

**Comment by marius10p** [comment]
Have you tried to split this unit by amplitude to see if it's really two
units? Sometimes a small amplitude unit like that can look bimodal. Also,
please send side by side plots from pykilosort to show how that worked
better.

**Comment by florgf88** [comment]
Hi Marius, many thanks for the response. 

I tried to split it, here's the result:
![Screenshot 2024-04-18 141554](https://github.com/MouseLand/Kilosort/assets/68202933/307b97bd-0603-4a9d-9e2d-71aa6dc908a2)

In pyKilosort the clusters look like this: 
![image](https://github.com/MouseLand/Kilosort/assets/68202933/35a933aa-fb2b-4d17-a876-ff349ee259dc)

**Comment by marius10p** [comment]
Thanks, can you please show the good cluster view for this entire area like you did for Kilosort4? It's possible that individual cluster exmaples are segmented better by one algorithm or another, but it would be good to see a picture showing KS2.5 consistently being better in this area.

**Comment by florgf88** [comment]
Yes, of course. I hope this picture helps. It's the area between 2800-2500 um. 
![Screenshot 2024-04-18 160825](https://github.com/MouseLand/Kilosort/assets/68202933/99732fc1-a910-4b74-ba5a-e2cb7437b3e2)

**Comment by marius10p** [comment]
Looks similar doesn't it? The area in 1800-2200 looks like there are plenty of units for both algorithms and the 2200-2800 is similarly sparse for both. That area 2200-2800 just seems like higher noise / lower amplitude units, right?

**Comment by florgf88** [comment]
Yes, exactly. Units in this area have lower amplitude generally. It's true that there are not that many, but we still have some. I tried to decrease the learned Th first, but it got worse in general.

**Comment by marius10p** [comment]
I am not sure if this message means you agree with us, but basically to me it looks like both algorithms perform similarly in terms of how many good units they find in that particular region. Perhaps the different visualizations make this harder to compare but if I just try to count them, I don't see a big difference.
