### ISSUE TITLE
BUG: Creating a New Probe

### ISSUE THREAD

**Issue by yyyaaaaaaa** [MouseLand/Kilosort#669]
### Describe the issue:

When I click select probe layout on the kilosort4 interface and select new, no probe creation tool is displayed. The message log box prompts as follows: 
I tried reinstalling the new Kilosort, but the issue still persists. Could it be a problem with my PyQt version? Are there any specific Qt version requirements for Kilosort 4?

### Error message:

```shell
Traceback (most recent call last):
  File "E:\anaconda\envs\pytorch-py3.9\lib\site-packages\kilosort\gui\settings_box.py", line 539, in on_probe_layout_selected
dialog = ProbeBuilder(parent=self)
  File "E:\anaconda\envs\pytorch-py3.9\lib\site-packages\kilosort\gui\minor_gui_elements.py", line 88, in __init__
self.setup()
  File "E:\anaconda\envs\pytorch-py3.9\lib\site-packages\kilosort\gui\minor_gui_elements.py", line 114, in setup
error_label_palette.setColor(QtGui.QPalette.Foreground, QtGui.QColor("red"))
AttributeError
: 
type object 'QPalette' has no attribute 'Foreground'
```

### Version information:

py 3.9
win 10
pyqt 5/6

**Comment by jacobpennington** [comment]
Hello,

Did you originally install an earlier release of Kilosort4 and then pull the updates from git? If so, you just need to reinstall to fix this. We updated the dependencies a couple releases ago.

**Comment by jacobpennington** [comment]
No, you shouldn't need to uninstall Kilosort3. Can you list the exact version(s) of pyqt you have installed in your environment? If you're using conda you can do that with `conda list pyqt`.

**Comment by yyyaaaaaaa** [comment]
Of course, the version of Qt I'm using is as follows:

# Name                    Version                   Build  Channel
pyqt                      5.9.2            py39hd77b12b_6    defaults
pyqt6                     6.6.1                    pypi_0    pypi
pyqt6-qt6                 6.6.3                    pypi_0    pypi
pyqt6-sip                 13.6.0                   pypi_0    pypi

**Comment by yyyaaaaaaa** [comment]
Of course, the version of Qt I'm using is as follows:

Name Version Build Channel
pyqt 5.9.2 py39hd77b12b_6 defaults
pyqt6 6.6.1 pypi_0 pypi
pyqt6-qt6 6.6.3 pypi_0 pypi
pyqt6-sip 13.6.0 pypi_0 pypi

**Comment by jacobpennington** [comment]
Ah, I see. It looks like QtPy is defaulting to using your pyqt6 install, and there were spots we missed when updating things to be version agnostic. I'll update the code to fix that, it should be pushed today. In the meantime, you can get around the issue by running:
```
pip uninstall pyqt6
pip install --upgrade pyqt5
```
But that might interfere with other software if you're using the same environment for other things. You could also create a new environment and install `pyqt5` before installing Kilosort4 to get the same result.

**Comment by yyyaaaaaaa** [comment]
Yes, it worked, and looking forward to the latest updates!
Thank you, Jaco!
