### ISSUE TITLE
Questions of data from custom electrodes

### ISSUE THREAD

**Issue by dcgggg** [MouseLand/Kilosort#671]
### Describe the issue:

Hello,
        
        I would like to ask how to import the data collected by non-INTAN microfilament array electrodes into kilosort4. I am stuck in the first step of converting to binary.
        Thank you.

**Comment by jacobpennington** [comment]
Hello @dcgggg,

I don't know what format your data is in, so it's hard to give any advice. It needs to end up as a binary file (typically .bin, .bat, .dat or .raw) stored with shape `(time_samples, number of channels)`. Kilosort's data conversion tools are just a thin (and incomplete) wrappers for SpikeInterface functions, so I would start by checking the list of "Raw Data Formats" supported by that package:
https://spikeinterface.readthedocs.io/en/latest/modules/extractors.html

If you see your data format on that list, let me know, and I can add it to the list supported in our GUI, or you can use SpikeInterface directly to convert your data.
