### ISSUE TITLE
BUG: Spike timing in the first batch is not aligned to original signal

### ISSUE THREAD

**Issue by teristam** [MouseLand/Kilosort#673]
### Describe the issue:

Hello, I have posted this in another issue but didn't receive a response. Just want to flag it here so that people are aware of this. I have been testing kilosort 4.0.4. I use the sorted spike timing to extract spike waveform from the original binary file (`bfile`). I find the spike timing in the first batch is offset by `bfile.nt`, while that for the other batches seem to be correct.

I used the following code to extract spikes directly from the bfile

```
clu_id = 3
s = []

chan_best = (templates**2).sum(axis=1).argmax(axis=-1)
chan_best = chan_map[chan_best]

cb = chan_best[clu_id]

spk_t = st[clu==clu_id]

for i in range(300):
    t = spk_t[i] 
    s.append(bfile[(t-bfile.nt//2):(t+bfile.nt//2+1),:])
s = np.stack(s)
```
I noticed the extracted waveforms are mixed:

![image](https://github.com/MouseLand/Kilosort/assets/3406709/a7de1eb4-f08c-449d-9a1a-6f0bef85ef62)

but when I subtract bfile.nt from the spike time, it works:
![image](https://github.com/MouseLand/Kilosort/assets/3406709/f2cf9165-6a88-4c2a-8a9e-cb7692a9c995)

And then spike time from the 2nd batch onward don't seem to need this time shift:

![image](https://github.com/MouseLand/Kilosort/assets/3406709/a87f4113-751d-42e7-94b6-73280b76f3dd)

### Version information:

4.0.4

**Comment by jacobpennington** [comment]
Thanks, we'll take another look at the special cases for the first batch.

**Comment by jacobpennington** [comment]
There was a bug introduced with a previous change, it's been reverted now with version 4.0.7. Please let us know if you still see this behavior with the new version.
