### ISSUE TITLE
Kilosort 4 - Algorithm missing fast-spiking units/narrow shaped units

### ISSUE THREAD

**Issue by msj220001** [MouseLand/Kilosort#675]
### Describe the issue:

Similar to a previous problem on Kilosort 3.0 (Issue #395 ), Kilosort 4.0 is consistently missing the yellow (Plexon Offline Sorter's GUI) fast-spiking unit even after I've adjusted the parameters a few times.
Kilosort 4.0 is able to detect the green unit every time, which is the only one it finds for channel 6.

What parameters would you recommend I change to detect the yellow unit?

![image](https://github.com/MouseLand/Kilosort/assets/157846284/84c0860f-0f56-4c33-9c06-ff341b4db59f)
![image](https://github.com/MouseLand/Kilosort/assets/157846284/de018a9a-fda0-4634-b795-1e91df4ce457)

![image](https://github.com/MouseLand/Kilosort/assets/157846284/4d7cd254-de63-4699-a2e2-a219baddd0ca)

**Comment by msj220001** [comment]
I've updated the version of Kilosort 4 I'm using to the latest version.

Still having some trouble with finding fast spiking units.

This unit on channel 3 phy (which is equivalent to channel 12 on Plexon Offline Sorter) comes close to looking like a fast spiking unit, but in Plexon Offline Sorter, it is still within the regular spiking unit range. I think it's because it has a larger amplitude which makes it look 'spikier.' 
![image](https://github.com/MouseLand/Kilosort/assets/157846284/641a3e84-3208-4d13-b30d-6c0d7ada5d1b)

Here are the current parameters I'm using:
![image](https://github.com/MouseLand/Kilosort/assets/157846284/3bf65cbb-1c97-4958-b4b1-8d055e1e3ebb)

I think this might be due to there not being that many fast-spiking universal templates. Is this reasonable?

**Comment by marius10p** [comment]
Hi, sorry for the slow response. There is no underlying reason why Kilosort would not be able to detect fast spiking neurons. The universal templates are actually obtained from your own data by default ("templates_from_data = True"). If the fast-spiking neurons have threshold crossings then they will be identified. You can also try templates_from_data = False, which will use predefined templates and then you can be sure there is a fast-spiking template in there. It's also possible that your fast spiking units are just a little too noisy to be identified by Kilosort. You can try other algorithms, but in our experiments in the paper we find that Kilosort is typically much better than other algorithms especially at low amplitudes.

**Comment by jacobpennington** [comment]
Another suggestion, I didn't notice before: it looks like you've modified a lot of parameters, some of them in ways that are really not intended. For example, `nt = 801` is well outside the normal range we would use (typically 61 or 81). You also should not need to modify `x_centers` at all, the default of `x_centers = None` should set a single column of grouping centers (which is what you want for a single shank). The thresholds are set quite high as well. I would recommend resetting all of the parameters to their defaults as a starting point.

**Comment by msj220001** [comment]
Thank you! Switching to using the universal templates seems to have worked!

One thing though: I don't know why the units suddenly look cut off in the middle (in phy). I had reset kilosort's gui and then switched to universal templates (templates from data false), so I'm not sure if reseting the gui caused this to happen or if using universal templates does this.
Do you know what might be causing this 'cut off' unit effect?
At first I though it might be the batch size that was too large resulting in each batch size being smaller, but decreasing the batch size didn't do much to reduce how cut off the units were.
![image](https://github.com/MouseLand/Kilosort/assets/157846284/c0b9b687-ed5a-4433-89c4-769e297d5232)
![image](https://github.com/MouseLand/Kilosort/assets/157846284/8c640894-b1e8-495a-aa41-058fd9e89646)
![image](https://github.com/MouseLand/Kilosort/assets/157846284/b3e0ecec-4a03-424a-9f9e-34f686e22819)

**Comment by jacobpennington** [comment]
I think it's because you changed `nt0min`, which sets the expected location of the peak of the waveform. The default of `None` will probably work better. It may also be related to using `nt = 61` with a higher sampling rate, which is effectively shortening the waveforms to be ~1.5ms instead of ~2ms, but that's required for using the default templates.
