### ISSUE TITLE
2D MEA Probe creation

### ISSUE THREAD

**Issue by yyyaaaaaaa** [MouseLand/Kilosort#678]
### Describe the issue:

I browsed through the previous thread regarding 2D MEA, and I'd like to know how to create an array for an electrode up to 26400. The MEA has 26400 electrodes, but only up to 1024 channels are used simultaneously for recording. Should I create an array for all electrodes and then specify the channels to be recorded, or should I only create an array based on the physical information of these 1024 channels?

**Comment by jacobpennington** [comment]
The probe file you provide to Kilosort should only include information about the channels that you actually recorded data from.

**Comment by yyyaaaaaaa** [comment]
Thanks！My electrode spacing is 17.5 um. How can I set the probe parameters to this value? It seems I can only set integer templates.

**Comment by yyyaaaaaaa** [comment]
Thanks！My electrode spacing is 17.5 um. How can I set the parameters for the probe? It seems that only integer templates can be set

**Comment by yyyaaaaaaa** [comment]
Alright, my electrode spacing is 17.5 um. How should I set the template parameters to match my probe? It seems like **_dim_** and **__** can only be set to integers.
This is the probe I'm using.
[19531_2.zip](https://github.com/MouseLand/Kilosort/files/15127132/19531_2.zip)

**Comment by yyyaaaaaaa** [comment]
Looking forward to later updates! I encountered another question. Why is the x-axis aligned after setting dim and dimx to 175, but the y-axis is offset, and the electrode spacing is 87.5um. And when I set the dim to 350, it's good to align my y-axis with half the density.

**Comment by jacobpennington** [comment]
Vertical spacing was set based on `dmin // 2` (floor division, i.e. rounded to an integer) while horizontal spacing was set by `dminx / 2`.  So for `dmin = 350` they're placed vertically every 175um, but for `dmin = 175` they're placed every 87um instead of 87.5, which is why they were aligned at the bottom of the probe and then the alignment got worse going up.

**Comment by yyyaaaaaaa** [comment]
Oh, I got it! What can I do to better match my probe? Can I try to modify the code?

**Comment by jacobpennington** [comment]
You just need to install from source to get the latest code changes if you don't want to wait on a new pip version. There are instructions for that at the bottom of the readme.

**Comment by yyyaaaaaaa** [comment]
Thanks！I will try it！
