### ISSUE TITLE
FEATURE: <Please write a comprehensive title after the 'FEATURE: ' prefix>

### ISSUE THREAD

**Issue by canfora01** [MouseLand/Kilosort#680]
### Feature you'd like to see:

Hello. The electrodes we are using have the distance between each electrode extremely far apart compared to the size of the cell body. However, in kilosort clustering, several electrode-derived spikes belong to one cluster. So, is it possible to do clustering from only one electrode-derived spikes?
Thank you.

### Additional Context

The version of kilosort we are using is kilosort 2.5.

**Comment by jacobpennington** [comment]
Hello @canfora01,  have you tried using Kilosort4 yet? Do you encounter the same issue?

**Comment by canfora01** [comment]
Thanks for your reply.
 We did try it. However, it did not work with kilosort 4 (probably because we are using a very small number of electrodes, 60 electrodes, to record from the retina, not the brain). So I did it with kilosort 2.5, which had a paper that said it recorded retinas, and it worked fine. However, the output results also showed that the response of one cell was taken from multiple electrodes. Even though there is 200µm between the electrodes.
 I would be grateful if you could tell me how to solve this problem if you don't mind. Please let me know if there is anything else you would like us to try.
Thank you.

**Comment by jacobpennington** [comment]
When you say it "did not work," what happened exactly? Do you have some print output you can paste in here, or screenshots?

**Comment by canfora01** [comment]
Thanks for the reply. This is the error statement that was output.
![IMG_2719](https://github.com/MouseLand/Kilosort/assets/167745371/7de158be-e3ea-47eb-a021-ef73d80c1308)
![IMG_2720](https://github.com/MouseLand/Kilosort/assets/167745371/087cb134-0b68-45fb-bf1a-5b4449faaa70)

**Comment by jacobpennington** [comment]
That looks related to some bugs that have been fixed recently. Can you please try installing the latest version and see if you still run into issues?

**Comment by jacobpennington** [comment]
Closing this for now, please let us know if you still encounter problems after updating your version.
