### ISSUE TITLE
##cannot mmap an empty file 

### ISSUE THREAD

**Issue by senioralmog93** [MouseLand/Kilosort#682]
### Describe the issue:

i run kilosort for the first time and when i run the GUI this message pops up on the message log box : "cannot mmap an empty file" and when i try to upload my binary data file it return this message "ERROR: Please select a valid binary file path.
Traceback (most recent call last):
  File "C:\Users\senio\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\settings_box.py", line 413, in on_data_file_path_changed
    assert self.check_valid_binary_path(data_file_path)
AssertionError"

**Comment by jacobpennington** [comment]
Hello,
That error is raised if the file you selected doesn't have an appropriate file extension. What does the full path to the file look like?

**Comment by victornovakov** [comment]
Hello this is happening to me as well. I am trying to use a file from the linked mainenlab public data set in tutorials. I am selecting it in the gui from my downloads.

**Comment by victornovakov** [comment]
I think it is because I am selecting a cbin file instead of a bin file. It seems that the public data set from the flat iron institute which is linked contains only cbin files. Decompressing using mtscomp gives an array object instead of a bin file. I would like to test kilosort with public data and do not know how to go about it. Any help would be greatly appreciated.

**Comment by jacobpennington** [comment]
Correct, a `.cbin` file would not work. There is a way to pass array objects directly to `run_kilosort` through the API, which I can explain if needed, but looking briefly at the `mtscomp` tool you mentioned it looks like it should be able to just output .bin files for you. I'm looking at the instructions here: https://github.com/int-brain-lab/mtscomp, which say to do this for example to convert a .cbin file to .bin:  `# Decompression mtsdecomp data.cbin -o data.decomp.bin`

**Comment by jacobpennington** [comment]
Please let us know if you have any more questions about this, I'm closing this for now.
