### ISSUE TITLE
BUG: noise occupies nearly all the clusters in KS4

### ISSUE THREAD

**Issue by Alchemist-Y** [MouseLand/Kilosort#684]
### Describe the issue:

version: the latest KS4
sort settings: as the figures shows
![image](https://github.com/MouseLand/Kilosort/assets/101684666/222b3cb8-a2d0-462a-9f0a-fbc4c8c1fde4)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/2278381a-3741-4454-a52d-bb5e16378c80)
Probe Map:
![image](https://github.com/MouseLand/Kilosort/assets/101684666/970fd382-1de4-4c9c-8495-659838915f4f)
Noise in Waveform View in phy:
![image](https://github.com/MouseLand/Kilosort/assets/101684666/94903441-ab56-44ad-8528-65d054ab7c63)
Questions:1. should I increase the range of `The Universal` and `The Learned`; 2. what factors will attribute to the Noise Problem?
Evidence: 1. the raw data is Intan with .rhd. During the recording I can clearly find the spike as shows; 2. I choose one record channel and analyse its Power Spectral Densities, found the artefact noise nealy in the 60Hz and 100Hz band.  
![image](https://github.com/MouseLand/Kilosort/assets/101684666/b9c31b1d-f6e9-4a37-9aaa-40ed7610bbf3)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/d4355f82-2dc1-498c-8909-65f3dbd9f7c0)
Thanks in advance!

### Version information:

Latest KS4

**Comment by jacobpennington** [comment]
@Alchemist-Y I'm not sure I understand what you're asking. If the raw data is really noisy, that is going to make sorting more difficult. When you say noise occupies "nearly all the clusters," are you just talking about the "good" units or MUA as well?

**Comment by Alchemist-Y** [comment]
@jacobpennington yes. including “good” and "MUA"

**Comment by jacobpennington** [comment]
Okay. Can you share some more screenshots from Phy, for a few of the noisy good units? Preferably of the full Phy GUI for each unit selected.

**Comment by Alchemist-Y** [comment]
@jacobpennington Here are my screenshots from Phy about the "good" unit 
![image](https://github.com/MouseLand/Kilosort/assets/101684666/cf9f860e-7cee-4e5e-9ea3-7815c57e0a22)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/b1dc5d1c-4960-426e-8d98-8983f81e8593)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/bb6d275d-6abb-4f84-83d2-1107ff8ccd22)
Thanks a lot and wait for your professional advice!

**Comment by jacobpennington** [comment]
Thanks. Yeah, those don't look neural at all and appear to be dominated by the noise artifacts you mentioned. Changing Kilosort settings would not help with that, you would need to preprocess the data yourself to get rid of those artifacts.

**Comment by Alchemist-Y** [comment]
@jacobpennington Yes, I agree with the preprocessing is necessary. But I know the KS4 do will preprocess the raw data like low-cut filter and whitened function. You means these build-in functions are not powerful enough to filter these artefacts? So, Whould you give me more advice to deal with the preprocessing? And Should I preprocess the raw data before converting it to .bin data type or prepross it after converting?
Thanks in advance for your experienced advice!

**Comment by jacobpennington** [comment]
No, the built-in preprocessing steps will not be able to remove all kinds of artifacts. It doesn't matter if you try to process the data before or after putting it in .bin format. There may not even be a way to easily remove artifacts like that, the data may just be too noisy. I know SpikeInterface has worked on adding additional pre- and post-processing utilities to their library, so maybe they can point you in the right direction.

**Comment by Alchemist-Y** [comment]
@jacobpennington Thanks for your advice! I'm willing to have a try!
