### ISSUE TITLE
Different spike length at different sample frequency.

### ISSUE THREAD

**Issue by JiaHaoNCKU** [MouseLand/Kilosort#687]
### Describe the issue:

Hello,

I am new to using Kilosort. Due to equipment limitations, our data is sampled at 32000 Hz instead of the usual 30000 Hz. In this case, the normal spike length is around 500 time points(15 mSec), which is longer than the example in eMouse. However, I am confident that there are no mistakes in our setup.

My question is, does Kilosort have the ability to capture the entire length of the spike waveform, or can it only capture part of it? If I need to capture the entire spike waveform, do I need to change the configuration file or modify the CUDA code?

Thank you.
this is my config file
ops.fs                  = 32000;                            
ops.NchanTOT            = 384;                              
ops.fshigh              = 320;                              
ops.trange              = [0 Inf];   

ops.minfr_goodchannels  = 0;
ops.nfilt_factor        = 12; 
%ops.Nfilt              = 1024;                                
ops.ntbuff              = 64;                               
ops.NT                  = 4*1024 + ops.ntbuff;              

ops.nSkipCov            = 25;                               
ops.whiteningRange      = 32;                               
ops.scaleproc           = 200;                              

ops.nskip               = 25;                               
ops.sigmaMask           = 30;                               
ops.minFR               = 0.01; 
ops.momentum            = [20 400]; 
ops.Th                  = [40 4];  
ops.lam                 = 10; 

ops.NrankPC             = 6;    
ops.Nrank               = 3;    
ops.isolationThreshold  = 1.2;  

ops.spkTh               = -10;  

ops.AUCsplit            = 0.9;

p.s. this is my first time to new the issue if there are any problem please let me know. :)

**Comment by jacobpennington** [comment]
Hello @JiaHaoNCKU,

This looks like it's from a previous version of Kilosort, can you please specify which version you're using?
As for adjusting the length of the waveform captured, you can adjust the parameter `nt` in Kilosort4 if you'd like to try that, I'm not sure about past versions. The default is 61 samples, which corresponds to ~2ms for a 30kHz sampling rate, but you could increase that to the equivalent of 15ms. However, the testing we've done has been with values around 40-100, so increasing it by that much might have other effects. @marius10p do you think setting `nt = 450ish` would cause any problems?

**Comment by JiaHaoNCKU** [comment]
Hello @jacobpennington, 

Thank you for your response. We're using Kilosort version 2.0 for specific reasons. The default nt value is 61, but this falls short of our needs. When we attempt to increase it beyond 81, we encounter CUDA errors. I'm wondering if it's acceptable to modify this value in our situation.

Thank for your reply again.

**Comment by marius10p** [comment]
81 is the maximum for all versions of Kilosort written directly in CUDA (before this one). This is because I need an upper bound to pre-allocate the shared memory in CUDA so the algorithm can be fast. This limit cannot be modified without risking big failures, nor do we ourselves support any further modifications to older versions of Kilosort. Closing this issue now.
