### ISSUE TITLE
Multi-shank issue - incorrect estimation of x centres

### ISSUE THREAD

**Issue by j-moore94** [MouseLand/Kilosort#690]
### Describe the issue:

Hi,
Thanks for updating the features for multi-shank probes. I've been testing the `x_centres` variable and finding the estimation of shank position is not working optimally in certain situations. For example, in one case I have a probe in two brain areas, which I have spaced apart at a greater distance in the channel map, and the algorithm is almost finding the correct positions but not quite! (See the picture below) It's maybe also because there are different numbers of channels on each shank, so they are different lengths/depths. In my chanMap file I have an index to which channels are on which shank (kcoords) - would it be valid/possible to just use this for estimation of the centres instead?

![image](https://github.com/MouseLand/Kilosort/assets/40386054/56037181-c314-4b52-94ab-438c5eccc862)

**Comment by jacobpennington** [comment]
What does it look like when you keep the default `x_centers = None`? I would try sorting with that first and see if it causes any problems for you. There doesn't necessarily need to be a separate column of centers for every shank.

**Comment by j-moore94** [comment]
Ah okay thanks, yes it works better with `x_centers = None`. I think it said on the docs that you need to set this when you have multiple shanks. Here's what I get with the settings displayed on the right - what am I aiming for with the template positions? If I do it with dminx as the x distance between channels on the same shank I get something like this:

![image](https://github.com/MouseLand/Kilosort/assets/40386054/398d1605-1843-41c1-b2b2-f5894bdbb118)

But with dminx as 400 I get this:

![image](https://github.com/MouseLand/Kilosort/assets/40386054/81c48145-9704-487d-8334-bfe3ccddf4c5)

**Comment by j-moore94** [comment]
Perfect, thanks a lot for clearing that up! :)
