### ISSUE TITLE
BUG: <Please write a comprehensive title after the 'BUG: ' prefix>Problems with file type transfer

### ISSUE THREAD

**Issue by StellaFFF** [MouseLand/Kilosort#691]
### Describe the issue:

![image](https://github.com/MouseLand/Kilosort/assets/162967189/7285f8ec-3d61-4738-a52d-a22d4b687f59)
Hi! I am new here and I come across with some problems when I trying to covert .ns6 file recorded in Blackrock system to binary file. The error has been uploaded in the figure. Is there someone knows what's wrong with this issue? Thanks a lot!

### Version information:

kilosort4

**Comment by StellaFFF** [comment]
> @StellaFFF what path did you save the binary file to? If it got saved with an invalid extension somehow, that would cause this error. The conversion finished, so the new binary file should still be present wherever you saved it to.

Thanks for your reply! I have changed file path to such as F:/ which has no invalid extension but it still can not work. And the LOAD button is stayed unpressable when I choose the output binary files.

**Comment by jacobpennington** [comment]
F:/ is not a valid path. It should be something like `F:/whatever/data.bin`

**Comment by StellaFFF** [comment]
> F:/ is not a valid path. It should be something like `F:/whatever/data.bin`
![image](https://github.com/MouseLand/Kilosort/assets/162967189/3e6bcab5-4a6e-4c8c-9da9-5de978717108)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/117e11ec-5392-4820-8b98-767d12769e46)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/5fbf97ca-cfdf-4459-9079-9fb8725584b0)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/7b2befb2-d4eb-42d1-ada5-d8016cb7a4df)
Hi! I am sorry for not express correctly. The above pictures are the processes that I tried, is this path is correct? Iif this path is valid, the outcome is still error. Is there anything else might cause such error? Since the load button can't be pressed, I can not move on to the next step. Thank you again!

**Comment by StellaFFF** [comment]
> F:/ is not a valid path. It should be something like `F:/whatever/data.bin`

I solved this by directly convert in spikeinterface. I use the same path as before. Thanks a lot.
