### ISSUE TITLE
UX request: replace duplicate_spike_bins with  duplicate_spike_ms

### ISSUE THREAD

**Issue by WeissShahaf** [MouseLand/Kilosort#693]
### Feature you'd like to see:

The parameter duplicate_spike_bins is directely related to the sampling rate. but users are not necesserily aware of this relationship. and as most users may not actually read the parameter descriptions, it would be better if it is replaced by a duplicate_spike_ms that dynamically reads the sampling rate and adjusts the bins number accordingly.

a validation step can be added that ensures a suitable range of values is given by the user.

**Comment by jacobpennington** [comment]
Change is pushed, it will be on pypi with the next release.

**Comment by WeissShahaf** [comment]
thanks
