### ISSUE TITLE
Can KS4 analyze a file with 2 segments recordings?

### ISSUE THREAD

**Issue by StellaFFF** [MouseLand/Kilosort#695]
### Describe the issue:

I use spikeinterface ro append two blackrock recording files into a binary file which has two segments. And I run this file in KS4. The results oonly have  one segment data. So I wonder if KS4 can analyze files with more than one segment?

**Comment by jacobpennington** [comment]
Kilosort does not recognize segments in any way, so if it's only showing one segment of the data then the binary file only contains that one segment. I.e. something went wrong with SpikeInterface when you created the data.

**Comment by StellaFFF** [comment]
> Kilosort does not recognize segments in any way, so if it's only showing one segment of the data then the binary file only contains that one segment. I.e. something went wrong with SpikeInterface (either your error or theirs) when you created the binary file.

Thanks so much for your reply! The problem has been solved.
