### ISSUE TITLE
Slow performance with low video memory

### ISSUE THREAD

**Issue by Alkohost** [MouseLand/Kilosort#696]
### Describe the issue:

Hello, I noticed that Kilosort4 runs much longer compared to the previous versions of Kilosort. The problem is that I have 6Gb of video memory installed (it wasn't a problem before) and a processing uses the video memory, but then the main time of work is taken by clustering, at which I have 100% CPU usage. Is it possible to run calculations on GPU with 6Gb video memory? 

Thank you!

**Comment by jacobpennington** [comment]
Hello Alkohost,
Yes you can sort with 6GB of video memory, and in general Kilosort4 runs faster than previous versions. If it's hardware intensive and taking longer to run, there's most likely a different problem causing that. Can you please tell me which version of Kilosort4 you're using, and paste in the output that Kilosort printed to the terminal while sorting? It would also be helpful to know what your probe geometry is, and what parameter values you used (you can click "print settings" in the GUI to copy paste them here).

**Comment by Alkohost** [comment]
Thank you for your reply. As far as I can tell, previous versions of Kilosort used GPU for sorting all the time, but here I have the last step done on CPU for some reason.

I use Poly2 probe and specify real coordinates (50 um vertical separation distance)
https://image.isu.pub/161209192343-4576a73a1ee220287a2cfc3a76eba769/jpg/page_93_thumb_large.jpg

Parameters:
{"main": {"n_chan_bin": 32, "fs": 32000.0, "batch_size": 64000, "nblocks": 1, "Th_universal": 5.0, "Th_learned": 4.0, "tmin": 0.0, "tmax": Infinity}, "extra": {"nt": 61, "artifact_threshold": Infinity, "nskip": 25, "whitening_range": 32, "binning_depth": 5.0, "sig_interp": 20.0, "nt0min": null, "dmin": null, "dminx": 32.0, "min_template_size": 10.0, "template_sizes": 5, "nearest_chans": 10, "nearest_templates": 100, "max_channel_distance": null, "templates_from_data": true, "n_templates": 6, "n_pcs": 6, "Th_single_ch": 6.0, "acg_threshold": 0.2, "ccg_threshold": 0.25, "cluster_downsampling": 20, "cluster_pcs": 64, "x_centers": null, "duplicate_spike_bins": 15}, "misc": {"dtype_idx": 0, "probe_idx": 8, "device_idx": 0}}

In the log I see a recommendation to change the values min_template_size and/or dminx but how should I set them?


When running I get the following warnings

Preprocessing filters computed in  1.51s; total  1.51s

computing drift

Re-computing universal templates from data.

C:\Users\User\anaconda3\envs\kilosort\lib\site-packages\threadpoolctl.py:1223: RuntimeWarning: 
Found Intel OpenMP ('libiomp') and LLVM OpenMP ('libomp') loaded at
the same time. Both libraries are known to be incompatible and this
can cause random crashes or deadlocks on Linux when loaded in the
same Python program.
Using threadpoolctl may cause crashes or deadlocks. For more
information and possible workarounds, please see
    https://github.com/joblib/threadpoolctl/blob/master/multiple_openmp.md

  warnings.warn(msg, RuntimeWarning)

C:\Users\User\anaconda3\envs\kilosort\lib\site-packages\kilosort\spikedetect.py:235: UserWarning: 
              NaNs and/or zeroes present in weights for spikedetect.run,
              may need to adjust `min_template_size` and/or `dminx` 
              for best results.

              If you're using a probe with multiple shanks, see 
              https://kilosort.readthedocs.io/en/latest/multi_shank.html
              
  warnings.warn(msg, UserWarning)

**Comment by jacobpennington** [comment]
The warning about Intel OpenMP always shows up, it's not a problem. You should not see the other warning at all if you're using the latest version of Kilosort, make sure you use `pip install --upgrade kilosort` to get the latest release.

Kilosort4 uses both CPU and GPU for sorting, but all the expensive operations are run on GPU by default. You can confirm that the GPU is being used by looking at the "PyTorch device" dropdown menu in the GUI:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/310112cf-945a-47f6-82a3-1095e686e68a)

**Comment by Alkohost** [comment]
So, in "PyTorch device" my GPU is displayed.
I've updated to the latest version, adjusted min_template_size and dminx to match the channel spacing, but it looks like the issue was the low values of “Th_universal”: 5.0, “Th_learned”: 4.0. The thing is that I generally have few spikes in a recording and I'm trying to collect low amplitude ones. Probably too many noise events were detected and the sorting stage could last for a day or more.
I will still test the new settings on other data, but this issue can be closed I think. Thank you!

**Comment by jacobpennington** [comment]
We do not have any plans to generate .mat versions of the results from Kilosort4.
