### ISSUE TITLE
Value of amplitude

### ISSUE THREAD

**Issue by Lorena-J** [MouseLand/Kilosort#697]
### Describe the issue:

Hello! I have been testing ks4 with a single shank probe and comparing the rating with ks 2.5 and 4 there is a big difference in the amplitude values and I don't know what are the units of this amplitude in ks4: 
<img width="428" alt="Captura de pantalla 2024-05-23 a las 12 00 46" src="https://github.com/MouseLand/Kilosort/assets/146965710/3704a721-26e8-4f63-a35f-f5540e78b49d">

**Comment by jacobpennington** [comment]
Hello,

Kilosort4 does not save amplitudes in exactly the same way that past versions did, so there will be differences. Please see my last reply in #632 for details. However, they should not be nearly as large as you've shown in that screenshot, that's many orders of magnitude larger than expected. Are you using the latest version of Kilosort4? There were updates to the amplitude calculations not too long ago.

**Comment by Lorena-J** [comment]
I am using the lastet version, but is there a problem with other parameters, or can I do the classification and calculate the amplitudes myself?

**Comment by Lorena-J** [comment]
yes, sure, I'm doing the analysis with a single shank probe, it has 64 channels, I don't know why but channel '0' is not represented in the probe view, here are the screenshots: 
<img width="961" alt="Captura de pantalla 2024-05-27 a las 12 33 18" src="https://github.com/MouseLand/Kilosort/assets/146965710/1bcc691e-64f7-4bba-8c5a-ee2357b6b5b9">
<img width="598" alt="Captura de pantalla 2024-05-27 a las 13 27 20" src="https://github.com/MouseLand/Kilosort/assets/146965710/3a2ec616-47e1-4525-942f-bf88187a28ca">
<img width="1120" alt="Captura de pantalla 2024-05-27 a las 13 10 40" src="https://github.com/MouseLand/Kilosort/assets/146965710/4d77f928-1e30-4ba9-be7f-f2f555e46294">
<img width="1124" alt="Captura de pantalla 2024-05-27 a las 13 26 34" src="https://github.com/MouseLand/Kilosort/assets/146965710/7020ab3d-ddda-4acb-b51e-839fe0315f4e">

thank youu!!!

**Comment by jacobpennington** [comment]
If a channel is not showing up in the probe view, then it's either not included in the probe file or the coordinates were entered incorrectly (i.e. possibly overlapping another contact so that you can't see it).

**Comment by jacobpennington** [comment]
Closing this for now, if you still encounter problems after updating the probe file please let us know.
