### ISSUE TITLE
Discontinuous recording

### ISSUE THREAD

**Issue by Shadow7912** [MouseLand/Kilosort#698]
### Describe the issue:

When I use Kilosort4, I find that Kilosort will truncate and discard some record fragments (happends in all channels), while this does not happen in Kilosort2. I tried adjusting Th(universal)(range in [8 10]) and Th(learned)(range in [7 10]), but this did not solve the problem. I want to know why this is happening and how to improve it?
![image](https://github.com/MouseLand/Kilosort/assets/61609908/7bda9d74-9fdc-4a86-a07c-b038ec00a791)

**Comment by Shadow7912** [comment]
> What do you mean by "truncate and discard recording fragments?"

Sorry for my poor English. The spike train after sorting is discontinues. The kilosort4 cuts off a recording into segments and drops some of them.
Shows in the picture, they are the same neuron, but the result of kilosort4 lossing the middle part.
![image](https://github.com/MouseLand/Kilosort/assets/61609908/eb757c01-4e8e-47bb-8826-50d0f5b864e2)

**Comment by jacobpennington** [comment]
Okay, I see what you mean now. A couple things:
1) Can you please show a screenshot of 'amplitude view' from Phy for that neuron, from both versions of Kilosort?
2) How are you determining that they are the same neuron?

**Comment by Shadow7912** [comment]
> Okay, I see what you mean now. A few things:
> 
> 1. Can you please show a screenshot of 'amplitude view' from Phy for that neuron, from both versions of Kilosort?
> 2. How are you determining that they are the same neuron?
> 3. If you're seeing neurons drop out periodically, it usually means the thresholds need to be set lower, and the values you listed are not much different from the default (higher in some cases). Also note that you should not try to use the same threshold values for both versions, Kilosort4 implements them differently. I would try lowering your KS4 thresholds to something like 6 (Th universal) and 4 (Th learned) and see if that resolves the issue, then adjust them accordingly if there's still some drop-out or if it's picking up too much noise.

Thank you for your reply! 
1. Here is the amplitude view for the neuron.
![image](https://github.com/MouseLand/Kilosort/assets/61609908/266ae3f4-7bb4-4153-a0d3-1a74744561d3)
2. They come from the same channel and have similar waveform and ISI. Here is the waveform of this neuron. But I think whether they are the same neuron is not important because all the channel in ks4 have the same lossing part. 
![image](https://github.com/MouseLand/Kilosort/assets/61609908/925bdf73-437f-4c46-a384-9284d3a19313)

3. I tried  6 (Th universal) and 4 (Th learned)  and 2(Th universal) and 4(Th learned) ([2 4] took a long time to sort, I think it found more spikes), the problem still exist and the lossing part is the same.

**Comment by jacobpennington** [comment]
What kind of probe is this? There are differences in how Kilosort4 versus 2 handles drift, which can have a big impact depending on the type of probe.

**Comment by jacobpennington** [comment]
I also want to clarify what you mean when you say all the channels have this issue. Do you mean all the neurons in the recording are showing this effect, or just all channels for this one neuron you're showing? If it's all neurons, can you please show some additional screenshots of the amplitude view for those neurons?

**Comment by Shadow7912** [comment]
> What kind of probe is this? There are differences in how Kilosort4 versus 2 handles drift, which can have a big impact depending on the type of probe.这是什么样的探头？ Kilosort4 与 2 处理漂移的方式有所不同，这可能会产生很大的影响，具体取决于探针的类型。

Thank you again!
My probe is plexon 64 channels linear array. 
I mean all the neurons in the recording are showing this effect,
Here are 2 sessions of my recording. Most of my recording sessions have this effect.
![image](https://github.com/MouseLand/Kilosort/assets/61609908/fcd91cee-fb6e-4ac5-866f-7480db4fa561)
![image](https://github.com/MouseLand/Kilosort/assets/61609908/cf2c6e70-7cff-445e-b387-4aad5745ff76)

**Comment by jacobpennington** [comment]
The only thing that comes to mind that would cause that effect for a lot of neurons simultaneously is drift, which is handled differently for KS4 vs KS2 (so it would make sense that they don't get the same outcome). Did you have drift enabled, i.e. `nblocks >= 1`? If so, what do the first two plots generated from the GUI look like? There should be one titled "Drift Amount" and one titled "Drift Scatter," you would have to run the sorting again to re-generate them.

**Comment by Shadow7912** [comment]
> The only thing that comes to mind that would cause that effect for a lot of neurons simultaneously is drift, which is handled differently for KS4 vs KS2 (so it would make sense that they don't get the same outcome). Did you have drift enabled, i.e. `nblocks >= 1`? If so, what do the first two plots generated from the GUI look like? There should be one titled "Drift Amount" and one titled "Drift Scatter," you would have to run the sorting again to re-generate them.我想到的唯一会同时对许多神经元产生这种影响的事情是漂移，KS4 和 KS2 的处理方式不同（因此它们没有得到相同的结果是有道理的）。您是否启用了漂移，即 `nblocks >= 1` ？如果是这样，从 GUI 生成的前两个图是什么样子的？应该有一个标题为“漂移量”和一个标题为“漂移分散”，您必须再次运行排序才能重新生成它们。
> 
> Also, do you see any neurons that are only active during that time when these neurons become inactive?另外，您是否看到任何神经元仅在这些神经元变得不活动时才活动？

Here are the screenshots of drift amount and drift scatter
![image](https://github.com/MouseLand/Kilosort/assets/61609908/9354f474-233f-4a61-99b3-0669efcc1611)
![image](https://github.com/MouseLand/Kilosort/assets/61609908/2c9a071f-8c14-4d01-9c80-09d45fa5ba39)

Sorry I not sure I correlectly understand. Do you mean whether there are any neruons are only active when the others becomes inactive? If so, there isn't any neuron only activate when the others become inactivite.

**Comment by jacobpennington** [comment]
Yes, that is what I meant re: neurons being active/inactive. Based on the timing of the drift increases it does seem like that's related, I'll talk with @marius10p about it.

One other question for you: based on the drift scatter it looks like the contacts on your probe must be spaced at least 100 microns apart, is that correct?

**Comment by Shadow7912** [comment]
> Yes, that is what I meant re: neurons being active/inactive. Based on the timing of the drift increases it does seem like that's related, I'll talk with @marius10p about it.是的，这就是我的意思：神经元活跃/不活跃。根据漂移增加的时间，这似乎确实是相关的，我将讨论它。
> 
> One other question for you: based on the drift scatter it looks like the contacts on your probe must be spaced at least 100 microns apart, is that correct?还有一个问题要问您：根据漂移散射，探头上的触点之间的距离必须至少为 100 微米，对吗？

Yes, the contacts on my probe is spaced 100mm.

**Comment by Shadow7912** [comment]
> > Yes, that is what I meant re: neurons being active/inactive. Based on the timing of the drift increases it does seem like that's related, I'll talk with @marius10p about it.
> > One other question for you: based on the drift scatter it looks like the contacts on your probe must be spaced at least 100 microns apart, is that correct?
> 
> Yes, the contacts on my probe is spaced 100mm.

Sorry, I typed the wrong unit, it is 100μm.

**Comment by marius10p** [comment]
hi @Shadow7912 , unfortunately it looks like the vertical spacing between the sites on your probe is too large to be able to record neurons stably when drift is so large. There is nothing that Kilosort or any other algorithm can do for you here, since most units are simply going to disappear between sites when the probe moves, and there will be no electrical signature to be able to recover their firing. This is the reason why modern probes like Neuropixels have a vertical spacing of 20 or 15um, to be able to observe neurons continuously as the probe moves up and down. 

It is also not possible that Kilosort2 tracked your units stably. Some units yes, they will be tracked stably, and probably Kilosort4 also does that. But many units will be dropped, or even worse, will be merge with other units in Kilosort2 though that is unlikely.

**Comment by Shadow7912** [comment]
> hi @Shadow7912 , unfortunately it looks like the vertical spacing between the sites on your probe is too large to be able to record neurons stably when drift is so large. There is nothing that Kilosort or any other algorithm can do for you here, since most units are simply going to disappear between sites when the probe moves, and there will be no electrical signature to be able to recover their firing. This is the reason why modern probes like Neuropixels have a vertical spacing of 20 or 15um, to be able to observe neurons continuously as the probe moves up and down.
> 
> It is also not possible that Kilosort2 tracked your units stably. Some units yes, they will be tracked stably, and probably Kilosort4 also does that. But many units will be dropped, or even worse, will be merge with other units in Kilosort2 though that is unlikely.

I see. Thank you for your reply!
