### ISSUE TITLE
NP1 Channel Map Scripts?

### ISSUE THREAD

**Issue by EmmaCondon** [MouseLand/Kilosort#699]
### Feature you'd like to see:

Hi, is there anywhere available the MATLAB script which was used to create the neuropixPhase3B1_kilosortChanMap or neuropixPhase3B2_kilosortChanMap channel maps?

We have a broken NP headstage and only the channels with odd numbers are active and picking up spikes. We need to create a channel map specifying which channels are connected and not connected. As specifying 'bad channels' is not a feature yet in the KS4 GUI, we need to create a new channel map with inactive channels disconnected. 

I've searched extensively online including in git issues and neuropixels slack channel and there is no information available.

**Comment by jacobpennington** [comment]
Hello,

You just need to create a new map that does not include the inactive channels. There is a general tutorial in the documentation here: https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html. You can see a detailed example for a Neuropixels 2 probe in the replies to this issue: #622 . The process would be the same for Neuropixels 1, just follow the [NP1 spec sheet](https://www.neuropixels.org/_files/ugd/328966_c5e4d31e8a974962b5eb8ec975408c9f.pdf) instead for determining the spacing.

If you can't figure it out from those examples, let me know and I can give additional help.

**Comment by EmmaCondon** [comment]
Amazing, thanks a lot Jacob :)
