### ISSUE TITLE
Probe and .bin file

### ISSUE THREAD

**Issue by Lorena-J** [MouseLand/Kilosort#700]
### Probe and .bin file 

Hi, I have a question about how the probe channels are related to the .bin file.
I am logging with a 64 channel probe and openephys. At the end I have 64 .continuous files. 

The probe is connected to an adapter and two intans (each intan with 32 channels). I don't quite understand how it recognises the geometry of the probe, since I understand that the .continuous files (called ch_X.continuous where X = channel number) will be indicating the channel of the intan, but how does it know which channel of the intan corresponds to the channel of the probe? 

That is to say, if channel 1 (with coordinates 1,1) of my probe is connected to channel 3 of the intan, I understand that the .continuous file is ch_3.continuous. How kilosort knows that the ch_3.continuous is equivalent to the channel 1( coordinates 1,1) of my probe?

**Comment by jacobpennington** [comment]
Kilosort does not know anything about that. It only looks at the probe file you provide (.prb, .mat, or .json) and the .bin file. As for how the .continous files get mapped to the .bin file, you would have to ask the SpikeInterface team about that, we're only providing a shortcut to their code in our GUI.

**Comment by Lorena-J** [comment]
Thanks so much for your quick response!
