### ISSUE TITLE
KS4 can't open .json file

### ISSUE THREAD

**Issue by StellaFFF** [MouseLand/Kilosort#701]
### Describe the issue:

Hi! I have some problems with select probe layout from "other" (.json file) as the following pictures show. How can I fix this problem? Thanks a lot!
![image](https://github.com/MouseLand/Kilosort/assets/162967189/6b5ff8d2-a877-45ec-ab74-6b1ba7dcf10d)
![image](https://github.com/MouseLand/Kilosort/assets/162967189/85705516-cd73-46e5-b044-b7d1445b7f03)

**Comment by jacobpennington** [comment]
Can you please attach the .json file you're trying to load so that I can see how it's formatted?

**Comment by StellaFFF** [comment]
[tetrode_setup.json](https://github.com/MouseLand/Kilosort/files/15492274/tetrode_setup.json)

Yes, here is my file.
> Can you please attach the .json file you're trying to load so that I can see how it's formatted?

**Comment by jacobpennington** [comment]
This is not formatted for Kilosort, it's something used by ProbeInterface. Please [check the documentation here](https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html) for an example on how to create a Kilosort4 probe in .json format, or you can look at ProbeInterface's documentation for exporting to .prb format.

**Comment by StellaFFF** [comment]
> This is not formatted for Kilosort, it's something used by ProbeInterface. Please [check the documentation here](https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html) for an example on how to create a Kilosort4 probe in .json format, or you can look at ProbeInterface's documentation for exporting to .prb format.

I see! Thanks so much for your reply and sorry for the dumb problem.
