### ISSUE TITLE
<Index in position 1 exceeds array bounds. Error in getClosestChannels2... >

### ISSUE THREAD

**Issue by mtehrani-code** [MouseLand/Kilosort#705]
### Describe the issue:

Hello,

I'm trying to run kilosort 2.5 on data that was collected using a neuronxus 16-channel linear probe with 100 um site-spacing. When  I run the script in matlab I get the following error:

Index in position 1 exceeds array bounds. Index must not exceed 16.

Error in getClosestChannels2 (line 15)
iC= isort(1:NchanClosest, :);

Error in standalone_detector (line 40)
[iC2, dist2] = getClosestChannels2(ycup, xcup, ycup, xcup, NchanNearUp);

Error in datashift2 (line 31)
[st3, rez] = standalone_detector(rez, spkTh);

Error in main_kilosort2_5_eric (line 43)
rez = datashift2(rez, 1); % last input is for shifting data
 
I was wondering first if it's "OK" to use Kilosort2.5 on data from only 16-channels in the first place? And if so, how I can fix this indexing error?

I would appreciate your help!

MT

**Comment by jacobpennington** [comment]
Hello,
Is there a particular reason you need to use Kilosort2.5? Have you tried using Kilosort4 instead?

**Comment by mtehrani-code** [comment]
Hi,

I think for several reasons I'm trying to work with kilosort 2.5.

I tried running kilosort4 GUI a while back and I wasn't able to load my raw binary data file into it. I also couldn't load my probe map. I didn't spend too much time back then troubleshooting that however.

I know a group nearby who has been using kilosort 2.5 and I'm just adapting their script for my work since it has worked for them, and they don't have any issues with it. They are currently using KS2.5 on their neuropixel data. They use matlab initially to run kilosort, then Phy for curation. I also had the impression that earlier versions of kilosort would be more suited to data from probes with lower channel counts? Is that accurate?

Either way, I assume I would still need to figure out how to create my channel map file correctly...

M

**Comment by jacobpennington** [comment]
Hello,

I'm happy to take a look at your channel map file if you want to attach it here, to see if something is off. However, it looks like the error you got is most likely related to the default value for NchanClosest or NchanNearUp being greater than the number of channels. I don't believe those can be changed in Kilosort2.5, so you may not be able to use it with only 16 channels. You can change these in KS4 though if needed, and I know at least a handful of people have been sorting data with 16 channels (or fewer).

As to your other question, there is no reason why earlier versions should be better suited to data from probes with fewer channels. It's possible Kilosort2 (not 2.5) would work better for specific kinds of drift, but that would be the only difference and only applies to a small number of cases. You can also use Phy for curation with Kilosort4's results.

**Comment by mtehrani-code** [comment]
Thank you for the helpful explanation!

I would appreciate if you could please have a look at my probe map file and let me know if something is off. If your diagnosis is correct, then it would make sense for me to go back to using kilosort 4. 

I'm not able to attach the probe map file that is in .mat format here. Instead, I'm attaching an excel sheet that has all the variables that would show up in matlab workspace. Hopefully, that is useful.

[NNX-ProbeChMap-Variables.xlsx](https://github.com/user-attachments/files/15595659/NNX-ProbeChMap-Variables.xlsx)

Thank you,

M

**Comment by jacobpennington** [comment]
I don't see anything wrong with the probe map. I would try reinstalling Kilosort4 to get the latest version, and let me know if you run into problems using it. There is a GUI guide here with screenshots as well: https://kilosort.readthedocs.io/en/latest/gui_guide.html.

**Comment by mtehrani-code** [comment]
@jacobpennington Thank you very much for your help!

I was able to install KS4, run the Gui and load output to Phy2 (I think my initial issue with KS4 GUI had to do with my GPU drive which I had to fix later on). My results do look strange (eg. waveforms look distorted), probably because the default settings in KS4 aren't optimal for 16 channel data...I'm looking here https://kilosort.readthedocs.io/en/latest/parameters.html#parameters and trying alternate settings at the moment to see if that helps. 

If you have any recommendations or know what settings have worked for other groups who use smaller number of channels, I'd be grateful if you could share them.

Thanks again,

M

**Comment by jacobpennington** [comment]
Most settings should not need to change. I would turn off drift correction (set `nblocks = 0`) since it will likely not work well for this kind of probe, and maybe reduce `nearest chans` and `nearest templates` to something like 3 and 10, since your contacts are so far apart.

Other than that I can't really recommend anything without seeing screenshots of your results in Phy. A screenshot of what the KS4 gui looks like (including the data view and the "extra settings" window) would also be helpful.

**Comment by mtehrani-code** [comment]
Here are some screenshots after I changed nblocks, nearest chans and nearest templates to what you suggested. Looks like it helped?

![KS4_GUI](https://github.com/MouseLand/Kilosort/assets/72168533/5b57d992-7524-4ba3-a8d8-1dfc368b2aca)
![KS4_extra_settings](https://github.com/MouseLand/Kilosort/assets/72168533/8d8035e1-bc0c-4419-bfea-8c270e0df4b1)
![Ph2_screenshot_2](https://github.com/MouseLand/Kilosort/assets/72168533/2a37c5fc-b861-4492-8df8-24aa5d28e96c)
![Ph2_screenshot_all_spikes](https://github.com/MouseLand/Kilosort/assets/72168533/785bfad3-a888-4839-9d34-851c22b7cde6)
![Phy2_screenshot_mean_waveforms](https://github.com/MouseLand/Kilosort/assets/72168533/335a1613-2840-4187-a4c2-ee90f9cecdeb)

**Comment by jacobpennington** [comment]
Most of the channels in the data view in the KS4 GUI and the TraceView in Phy look like noise. That suggests there's a problem with how the binary file was created, or that you're loading it as the wrong data type. Are you sure it's int16?

**Comment by mtehrani-code** [comment]
The correct data type is actually float 32...however, when I set dtype to float32 and load nothing shows up in the data view window...I get this error message in the message log box:


C:\Users\matta\anaconda3\envs\kilosort\lib\site-packages\numpy\lib\function_base.py:4655: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

**Comment by jacobpennington** [comment]
Okay. I'm looking into some issues with float32 data that someone else already reported, so I assume this is related. You do need to load it as float32 though, running it as int16 will essentially be random noise. Can you please try loading it as float32 and running the sorting, even though the whitened data view will be blank?

**Comment by jacobpennington** [comment]
I added a possible fix for this in the latest version (v4.0.11). For another user with the same problem, it was happening because their data was scaled very differently from what KS4 expects for int16 data. I added new "shift" and "scale" parameters to address this (you can find these in the "Extra settings" window in the GUI). I found that setting `scale = 1000` worked well for their data, but yours might be different. You can click "Load" after changing the value to make sure the data shows up as expected. If you already know what scale your data is on, the goal is to get it roughly in the -100 to +100 range for the raw data.

**Comment by mtehrani-code** [comment]
Thank you for adding the fix. I reinstalled the new version and tried a few different values for "scale". Now I'm either getting the same  error: ...invalid value encountered in subtract
diff_b_a = subtract(b, a)

or a different one: RuntimeWarning: overflow encountered in multiply
  samples = samples * self.scale (when I try 1000 for example)

We were wondering what the format for the standard .bin file that kilosort can load is? If it is int16, we can convert our data to that but will have to scale them, so we don't lose precision. If, as you suggest, we want our data to lie in the range [-100  100], the scale factor for us (in matlab) would be 100/max(abs(a)):

>> scalef100 = 100/max(abs(a))

scalef100 =

    0.5000

**Comment by jacobpennington** [comment]
1) Are you sure you're loading the data as float32 when you get that overflow warning? That should not cause an overflow for float32 data unless it's on a very different scale than you're suggesting.

2) Yes, int16 is the standard format. However, -100 to 100 is just a ballpark. If your data is already in the range -200 to 200, then scaling is not the issue and there would be no point converting.

**Comment by mtehrani-code** [comment]
Yes, I'm loading the data as float32...at least I think I am! 

It will be great if you could try sorting my data at this point. Would appreciate it.

My data file is in .bin format. What would be the best format to convert it to in order to attach it here, and how would I do that?

Thanks,
M

**Comment by jacobpennington** [comment]
.bin format is fine, but you can't attach it here directly. You could try zip/tar compressing first, but I suspect it would complain about the size. Most users have been uploading to google drive or dropbox or similar services and sharing a link to that.

**Comment by mtehrani-code** [comment]
Okay. Here is the link to the file in my google drive:

https://drive.google.com/drive/folders/1CuVl_a-gDqYcTBCrB9bCMXG8DOWFk3kY?usp=sharing

Please let me know if you can't access it. Thanks!

**Comment by mtehrani-code** [comment]
Also, I was wondering besides the standard data format being int16, how should the data be organized to successfully load into kilosort? i.e. should the samples be interleaved for the channels, or each channel continguously?  

M

**Comment by jacobpennington** [comment]
It should be in row-major order, the default for Numpy:
![image](https://github.com/MouseLand/Kilosort/assets/35777376/ffbf3228-af97-43f0-9c57-64e26c7b09ec)

**Comment by jacobpennington** [comment]
It looks like there are some other problems with the data. It contains NaN values, and the scale is way off.
![image](https://github.com/MouseLand/Kilosort/assets/35777376/82f7f278-8ce4-467d-9bfb-10daa32a7038)

**Comment by jacobpennington** [comment]
Ah, one more comment: it looks like your data was in 'F' order, not 'C', like you were asking about, so that's probably the remaining issue.

**Comment by jacobpennington** [comment]
If you try those steps to correct the data and still have problems, please let us know.
