### ISSUE TITLE
Kilosort2 vs Kilosort4

### ISSUE THREAD

**Issue by EMerinoM14** [MouseLand/Kilosort#707]
### Describe the issue:

Hi all, I know this is not a problem as such but I would like to check it out on the github forum to see if you can give me an answer. I am starting to use kilosort to perform spike sortings on my recordings. In my center some people use kilosort2, but however I am using kilosort4. I have noticed that Kilosort 4 has more advantages than version 2 (as usual with upgrades). Therefore my idea is to continue using kilosort4. However I have a question, is it suitable to continue doing the spike sortings with version 2?

**Comment by jacobpennington** [comment]
It is still "suitable" to do sorting with version 2, but there are differences in the algorithm. You can read about the different steps in the algorithm for all version of Kilosort in the paper that came out this year: https://www.nature.com/articles/s41592-024-02232-7#Sec10.

However, we are focusing on providing support for Kilosort4, so we recommend everyone tries the latest version first. If you run into problems, it's possible an older version could work better for your specific probe type or brain area, but in most cases Kilosort4 should work just as well (or better).

**Comment by EMerinoM14** [comment]
Hi @jacobpennington 

I would like to tell you something, which may have something to do with the topic I opened this conversation for.

I just noticed something that is happening in kilosort version 2 and that seems to have been improved in version 4, let me explain. I have contacted my former supervisor to ask him how important is the correct configuration of the probe to perform the spike sorting. He told me that it was very important, however it does not seem to be so in Kilosort2. I explain in more detail:

A few days ago, before I started doing my sortings with kilosort4, I was using version 2. The number of clusters I was getting was totally different in both versions (128 in version 2 and 23 in version 4). I “discovered” that this seems to be due to the fact that in the MATLAB code that was given to me (for version 2) the number of clusters to be obtained is set to 128, which would imply these differences. 

However, this is not the problem. I realized that I was using the wrong probe for my records, corrected it and performed the sorting again with kilosort2.  So I had two different outputs: one with the correct configuration of my probe and one with the wrong configuration.
When I opened both kilosort2 ouputs (the one with the correct probe and the one with the wrong one) in phy I could see that the shape of the autocorrelograms, the location of the spikes in time and everything else was exactly the same in both ouputs. 

This made me think that, if there were no differences, it could be because in the wrong version I had created a probe of 32 linear channels, while in the right version I had created my current probe (32 channels but in two columns). However, I decided to do another test, this time I created for kilosort2 a completely different probe: an imaginary probe where the 32 channels are arranged in 4 columns and 8 rows (separated by 100 microns). I performed the spike sorting with this probe configuration and obtained in phy exactly the same results as in the two previous attempts.

Of course this does not happen in kilosort 4, i.e. for each different configuration I get a different number of clusters and even a different number of good or multi-activity clusters. What could be happening here?

Thanks in advance

**Comment by mberns-ru** [comment]
Is it possible to still access Kilosort2 if I did not have it installed before Kilosort4 was released?

**Comment by jacobpennington** [comment]
@mberns-ru yes, there is a Kilosort2 branch for this repository: https://github.com/MouseLand/Kilosort/tree/kilosort2
You can also find a downloadable zipped version in the "releases" section.

@EMerinoM14 There may be some differences in how probes are treated between the two versions, @marius10p  can clarify that. However, you should also make sure the cached ".phy" folder in the results driectory is deleted before loading new results. Kilosort4 does that automatically, and I believe KS2.5 and KS3 do as well, but I'm not sure about KS2.

**Comment by EMerinoM14** [comment]
Yes, I made sure to delete the phy folder on every single test. I can understand that there are some differences between versions, but that they are exactly the same sorting is a bit odd. I'll wait for @marius10p to get back to me. Thanks for the help @jacobpennington

**Comment by marius10p** [comment]
Kilosort2 does not need the probe geometry to do the sorting. Everything starting at Kilosort2.5 uses the probe geometry because: 1) it needs to drift correction geometrically; 2) it needs to cluster spikes locally (in KS3 and KS4).
