### ISSUE TITLE
Kilosort 4 - compatibility with new generation AI chip architectures

### ISSUE THREAD

**Issue by nperentos** [MouseLand/Kilosort#709]
### Describe the issue:

I am in the market for a new laptop and I would like to run Kilosort 4 on it. 
New laptops being released come with chip architectures that deviate from the 'traditional' CPU and GPU combo. Instead, I see references to NPUs (neural processing units), snapdragon chips copilots and other exotic names. Is Kilosort expected to be compatible with these or should I steer away from them?

**Comment by marius10p** [comment]
Sorry, I don't think that will work, especially not for the next few years. NPUs are for deep learning inference (i.e. int16 or int8 operations) and have very little if any support for float32 and general scientific computation. They also don't have that much processing capacity, compared to normal GPUs at least. Separately from that, ARM chips require substantial work on the side of pytorch  for compatibility (and numpy, and scipy and all the other teams). This has been going on already for Macs for several years, and I do not think it has been a smooth process. I don't see any current issues on the github pytorch related to NPUs or windows ARM. Good old Nvidia video cards will probably remain the main chips for scientific computation for a while at least. 

However, one way in which this helps is that slightly older laptops are getting discounted, and you may be able to pick a laptop with an RTX 4060 or 4070 at a good price.

**Comment by nperentos** [comment]
Thank you Marius. Very helpful.
