### ISSUE TITLE
turning off drift correction (nblocks to 0) in v4.0.9 throws st.shape error and aborts

### ISSUE THREAD

**Issue by DanEgert** [MouseLand/Kilosort#711]
### Describe the issue:

Maybe it's my settings, but this is the error I got after setting nblocks to 0. Probably just a matter of renaming a variable. Runs fine with nblocks to 1. : 

logger.debug(f'st shape: {st.shape}')
AttributeError
: 
'NoneType' object has no attribute 'shape'

### Version information:

v4.0.9

**Comment by jacobpennington** [comment]
This was a bug on our end, it's fixed with 4.0.10 which will be live on PyPi in a couple hours, after the tests finish running.
