### ISSUE TITLE
Template in Kilosort4 and spikeinterface

### ISSUE THREAD

**Issue by yyyaaaaaaa** [MouseLand/Kilosort#713]
### Describe the issue:

Hi! I want to know the difference between the templates generated by Kilosort 4 and the templates obtained by extending the sorting results in SpikeInterface. Should the templates be recalculated when calling Kilosort 4 through SpikeInterface?

**Comment by jacobpennington** [comment]
You would have to ask the SpikeInterface team how their templates are generated. You can read about how Kilosort4 handles templates in the paper: https://www.nature.com/articles/s41592-024-02232-7.
