### ISSUE TITLE
BUG:<kilosort4 API to run the kilosort4: too many values to unpack>

### ISSUE THREAD

**Issue by Alchemist-Y** [MouseLand/Kilosort#714]
### Describe the issue:

First way:  use spikeinterface(version = 0.100.7) module-- run_sorter to launch the kilsort4; Second way:  directly use the kilsort4(verion = 4.0.11) module run_kiiosort4. No matter which way I use to boot teh API, I met the same qustion: too many valuses to unpack.

### Version information:

kilosort4 version= 4.0.11
spikeinterface version = 0.100.7

### Context for the issue:

Spikeinterface way:
![image](https://github.com/MouseLand/Kilosort/assets/101684666/5514d441-5e46-4eec-b25e-81ad6378aaa3)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/6eeea363-5511-4166-8160-b17c5047406d)
Kilosort4 way:
![image](https://github.com/MouseLand/Kilosort/assets/101684666/627ebcc9-a777-4838-843f-48dd58bb3335)
![image](https://github.com/MouseLand/Kilosort/assets/101684666/b40b95ca-57cf-4bda-aa86-96cd8107388b)

**Comment by Alchemist-Y** [comment]
@jacobpennington I dig your source code about the run_kilosort.py file and find the reason:  Line 174 you designed to output 9 vaules(including the  _kept_spikes_), while in your [lastest read_doc](https://kilosort.readthedocs.io/en/latest/tutorials/load_data.html) there is no _kept_spikes_.
OK, question has been solved and hope this is a good remind for the read_doc updating.

**Comment by jacobpennington** [comment]
Thank you, I will update the documentation.
