### ISSUE TITLE
BUG: IndexError: The shape of the mask [X] at index 0 does not match the shape of the indexed tensor [1, Y] at index 1

### ISSUE THREAD

**Issue by msj220001** [MouseLand/Kilosort#716]
### Describe the issue:

I was running Kilosort through API and not through the gui to bulk process data files. Most files ran fine and saved at the end. But some files would encounter an issue (Error Message below). I'm not sure what is causing this issue.

I suspect that this is due to too few clusters found (the two files that ran into this error had identified 5 and 1 clusters respectively). But I could be wrong.

### Reproduce the bug:

```python
I am using modified code (I copy and pasted run_kilosort module to create my own run_kilosort module that has parameters adjusted to the probes we work with, that is the only difference).
The parameters we are using are as follows:
settings = {
    'data_dtype': 'int16',
    'n_chan_bin': 16,
    'fs': 40000.0,
    'batch_size': 40000,
    'nblocks': 0,
    'Th_universal': 5.0,
    'Th_learned': 15.0,
    'tmin': 0.0,
    'tmax': inf,
    'nt': 61,
    'artifact_threshold': inf,
    'nskip': 25,
    'whitening_range': 1,
    'binning_depth': 5.0,
    'sig_interp': 20.0,
    'nt0min': None,
    'dmin': None,
    'dminx': 32.0,
    'min_template_size': 6.0,
    'template_sizes': 10,
    'nearest_chans': 1,
    'nearest_templates': 1,
    'max_channel_distance': None,
    'templates_from_data': False,
    'n_templates': 6,
    'n_pcs': 6,
    'Th_single_ch': 10.0,
    'acg_threshold': 0.2,
    'ccg_threshold': 0.25,
    'cluster_downsampling': 25,
    'cluster_pcs': 64,
    'x_centers': None,
    'duplicate_spike_bins': 7
}
```

### Error message:

```shell
Traceback (most recent call last):
  File "e:/matlab/Kilosort Automated Sorting/run kilosort on awake files.py", line 55, in <module>
    sort_awake_files(input_dir, num_chan, probe_path)
  File "e:/matlab/Kilosort Automated Sorting/run kilosort on awake files.py", line 40, in sort_awake_files
    run_kilosort(settings = settings, data_dir=full_path)
  File "C:\Users\msj220001\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort_on_awake.py", line 152, in run_kilosort
    save_sorting(ops, results_dir, st, clu, tF, Wall, bfile.imin, tic0,
  File "C:\Users\msj220001\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort_on_awake.py", line 480, in save_sorting
    io.save_to_phy(
  File "C:\Users\msj220001\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\io.py", line 209, in save_to_phy
    pc_features, pc_feature_ind = make_pc_features(
  File "C:\Users\msj220001\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\postprocessing.py", line 96, in make_pc_features
    Xd, ch_min, ch_max, igood = get_data_cpu(
  File "C:\Users\msj220001\AppData\Local\anaconda3\envs\kilosort\lib\site-packages\kilosort\clustering_qr.py", line 423, in get_data_cpu
    ichan = torch.unique(iC[:, ix])
IndexError: The shape of the mask [46] at index 0 does not match the shape of the indexed tensor [1, 49] at index 1
```

### Version information:

Kilosort 4.0.6

### Experiment information:

Probe is a single shank probe with 16 electrode sites.

**Comment by jacobpennington** [comment]
Please try updating the to latest version and see if you still get this error.

**Comment by msj220001** [comment]
The issue persists even after I updated to 4.0.12
![image](https://github.com/MouseLand/Kilosort/assets/157846284/a14b29c0-f132-4665-9c1a-7fd62b5090da)

This is a screenshot of the second file that ran into this issue.
I can upload the API file or other files if that would help/

**Comment by jacobpennington** [comment]
Yes, please paste in the code you used to run Kilosort. Since you updated to the latest version, there should also be a `kilosort4.log` file in the results directory, please upload that here as well.

**Comment by msj220001** [comment]
I sent you an invite to a repository as I can't attach python files directly to this comment.
https://github.com/msj220001/Kilosort-Files/invitations

There wasn't a kilosort4.log file for these files that ran into an issue. Or it's perhaps because I am using a copied version of kilosort's modules that are an older version and doesn't create a log file.
run kilosort on awake files is the API file the user would run. It call run_kilosort_on_awake which is in kilosort's python directory. awake_parameters is a file with preset parameters copied from the parameters module.

**Comment by jacobpennington** [comment]
Yes, that's happening because you're using an old version of `run_kilosort` with updated version of the other modules, which could cause all sorts of problems as it gets updated whether or not it's responsible for this specific issue. I would strongly recommend you not do that, there are plenty of ways you can set up a script to load your own settings from a file without copy-pasting `run_kilosort`. You can just move this import
```
from kilosort.custom_parameters import DEFAULT_SETTINGS
```
to `custom run kilosort API` for example.


Please run Kilosort4 with the correct version of `run_kilosort` on the problematic recording, and upload the log file here if you still get the error.
