### ISSUE TITLE
Question: What does kcoords do in Kilosort 4

### ISSUE THREAD

**Issue by msj220001** [MouseLand/Kilosort#717]
### Describe the issue:

I was double checking the channel mapping between my data and phy's labeled channels.

Here is the channel mapping I am currently using:
[chanMap.json](https://github.com/user-attachments/files/15594355/chanMap.json)

I had set kcoords to be unique for each channel such that each channel would be considered independent of each other as Kilosort runs.
Should I make kcoords match the chanMap values or keep it as is?

**Comment by jacobpennington** [comment]
kcoords indicates shank index. If all of your channels are on the same vertical shank, then kcoords should be all the same number. Setting it to a unique value for each channel will not cause them to be "considered independently," the fact that they are spaced so far apart will effectively do that already.

**Comment by msj220001** [comment]
Got it! Thanks for confirming
