### ISSUE TITLE
Sorting a subset of channels (Kilosort4)

### ISSUE THREAD

**Issue by a-savoy** [MouseLand/Kilosort#723]
### Describe the issue:

Rather than sort all 384 channels of data, I only want to sort a specific range. I have attempted to do so with the code below, but it still sorts all 384 channels. What is the proper way to limit the sorting to only a subset of channels?

settings = DEFAULT_SETTINGS
settings['n_chan_bin'] = 384  
settings['dat_path'] = 'continuous.dat'
settings['channel_map'] = list(range(45, 65)) #sort only these channels
probe_name = 'neuropixPhase3B1_kilosortChanMap.mat' 
results = run_kilosort(settings=settings, probe_name=probe_name)

**Comment by jacobpennington** [comment]
There is not currently a way to do this through the GUI or API. To sort only certain channels, you need to create a new probe map with only the desired channels included.

Closing this since it's the same feature requested in #666
