### ISSUE TITLE
Running Kilosort4 is very slow.

### ISSUE THREAD

**Issue by yyyaaaaaaa** [MouseLand/Kilosort#725]
### Describe the issue:

Kilosort4 is taking a very long time to complete a sorting run, but about a month ago, it was very fast, and I'm sure I am using the same set of parameters. This is frustrating for me.
I also tried running Kilosort4 with SpikeInterface, but it's still very slow. However, everything was fast a month ago.
Here is the information about my record file.

MaxwellRecordingExtractor: 656 channels - 20.0kHz - 1 segments - 5,999,800 samples 
                           299.99s (5.00 minutes) - uint16 dtype - 7.33 GiB

![微信图片_20240620170710](https://github.com/MouseLand/Kilosort/assets/152130268/e70d5754-e404-490a-84bb-e7161a3a43b8)

 Settings = {
    'data_file_path': WindowsPath('H:/MEA_DATA_binary/yy/20240515/20240515_16883_D7/240515/16883/Network/000002/binary_for_ks4/traces_cached_seg0.raw'),
    'results_dir': WindowsPath('H:/MEA_DATA_binary/yy/20240515/20240515_16883_D7/240515/16883/Network/000002/binary_for_ks4/kilosort4'),
    'probe': '... (use print probe)',
    'probe_name': '19531_6.prb',
    'data_dtype': 'int16',
    'n_chan_bin': 656,
    'fs': 20000.0,
    'batch_size': 60000,
    'nblocks': 1,
    'Th_universal': 9.0,
    'Th_learned': 8.0,
    'tmin': 0.0,
    'tmax': inf,
    'nt': 41,
    'shift': None,
    'scale': None,
    'artifact_threshold': inf,
    'nskip': 25,
    'whitening_range': 32,
    'binning_depth': 5.0,
    'sig_interp': 20.0,
    'drift_smoothing': [0.5, 0.5, 0.5],
    'nt0min': None,
    'dmin': 35.0,
    'dminx': 35.0,
    'min_template_size': 10.0,
    'template_sizes': 5,
    'nearest_chans': 10,
    'nearest_templates': 100,
    'max_channel_distance': None,
    'templates_from_data': True,
    'n_templates': 6,
    'n_pcs': 6,
    'Th_single_ch': 6.0,
    'acg_threshold': 0.2,
    'ccg_threshold': 0.25,
    'cluster_downsampling': 20,
    'x_centers': 15,
    'duplicate_spike_bins': 7
}

**Comment by jacobpennington** [comment]
Hello @yyyaaaaaaa,

What version of Kilosort4 are you running? Can you please upload `kilosort4.log` from the results directory here? It should be present even if the sorting did not finish. It would also be helpful to see your probe map.

**Comment by jacobpennington** [comment]
@yyyaaaaaaa Your probe map is very different from what Kilosort was designed for, so there are a lot of reasons why it could be slower now. In particular, it's going to be difficult to place templates and grouping centers correctly. I'll see if @marius10p has any suggestions.

Just to clarify in the meantime, are you saying version 4.0.6 was running faster? Or were both 4.0.6 and 4.0.12 running slow, and the fast version was something else before that?

**Comment by yyyaaaaaaa** [comment]
@jacobpennington 
Yes, I remember that when using the same probe a month ago, running version 4.0.6 of Kilosort4 was not very slow (if it were too slow, it would have left a strong impression on me at the time :). Currently, both versions 4.0.6 and 4.0.12 are slow.Also, I would like to know, even with such a complex probe, is the sorting result of Kilosort reliable? If so, it's okay for it to be a bit slow.

**Comment by jacobpennington** [comment]
If it's running slower on the same version (i.e. it was fast on 4.0.6 before, but now it's slow on 4.0.6) and you didn't change any parameters, then that sounds like a hardware issue. The code for those versions does not change. Unfortunately there just aren't many guarantees we can make for a probe geometry like that.

**Comment by carlacodes** [comment]
> @jacobpennington Yes, I remember that when using the same probe a month ago, running version 4.0.6 of Kilosort4 was not very slow (if it were too slow, it would have left a strong impression on me at the time :). Currently, both versions 4.0.6 and 4.0.12 are slow.Also, I would like to know, even with such a complex probe, is the sorting result of Kilosort reliable? If so, it's okay for it to be a bit slow.

Have you checked you are running on GPU (nvidia-smi for instance) and not defaulting to CPU?
