### ISSUE TITLE
How to save filtered and whitened data from command prompt?

### ISSUE THREAD

**Issue by hiroyukioya** [MouseLand/Kilosort#726]
### Feature you'd like to see:

I know gui has switch to save the filtered and whitened data. How to do this in command prompt?
I am using most recent kilosort4 without SpikeInterface.

**Comment by hiroyukioya** [comment]
This info is here:
https://kilosort.readthedocs.io/en/latest/api.html

**Comment by jacobpennington** [comment]
This is not possible through the command prompt currently - many features are not. You can use the GUI, or you can use the API in a python script/notebook like `run_kilosort(..., save_preprocessed_copy=True)`.
