### ISSUE TITLE
FEATURE: Upgrade kilosort without reinstalling it?

### ISSUE THREAD

**Issue by NirvikNU** [MouseLand/Kilosort#728]
### Feature you'd like to see:

I see that the repo is undergoing a lot of development and changes since its release. So I was wondering if its possible to have the feature of upgrading the current kilosort installation periodically without having to reinstall it from scratch?

**Comment by jacobpennington** [comment]
Hello @NirvikNU

Yes, the way to do that is to install in editable mode from source and then `git pull` to get the latest changes when you want to update.  There are instructions for that at the bottom of the readme.
