### ISSUE TITLE
Explanation for the output files

### ISSUE THREAD

**Issue by zkcsmxz** [MouseLand/Kilosort#730]
### Feature you'd like to see:

Explanation for the output files

Hi 
I used KS4 in GUI. it is very nice thanks a lot
I have a question: It generates more than 20 Npy files in the Kilosort4 folder. Is there a document explaining each file? It would be very helpful for my further analysis.
Thanks a lot!
zkcsmxz

**Comment by jacobpennington** [comment]
The output files are formatted for use with Phy, so most of them are documented on their github: https://github.com/cortex-lab/phy/blob/a1a8776a7b777c9fa2fe628e3a521219296b0530/docs/sorting_user_guide.md?plain=1#L67

A few are not used by Phy, I will make a note to add documentation for those somewhere.
