### ISSUE TITLE
BUG: <after splitting in phy the amp is not recomputed>

### ISSUE THREAD

**Issue by zkcsmxz** [MouseLand/Kilosort#734]
### Describe the issue:

after splitting in phy the amp is not recomputed
<img width="772" alt="屏幕截图 2024-07-04 085855" src="https://github.com/MouseLand/Kilosort/assets/39118640/4ac40516-451f-4e96-a6d5-22014368500f">

### Version information:

ks 4.013
phy 2.0a1

**Comment by jacobpennington** [comment]
Those values are computed by Phy, you would need to submit a bug request on their github: https://github.com/cortex-lab/phy

**Comment by zkcsmxz** [comment]
ok, thank you
