### ISSUE TITLE
INSTALLATION: Segmentation fault (core dumped) during the initial call

### ISSUE THREAD

**Issue by ekurtgl** [MouseLand/Kilosort#744]
### Describe the issue:

Hello,

Thank you for the great repository. I installed all the requirements and I am getting the following error after the `python -m kilosort` command:

```shell
Segmentation fault (core dumped)
```

Image:
![image](https://github.com/user-attachments/assets/c291b322-e612-460c-9f04-22d6e3cf4bc0)

What might be the reason for this error? Thank you.

Best,
Emre

### Provide environment info:

```shell
     active environment : spike
    active env location : /mnt/aperto/linux/anaconda3/envs/spike
            shell level : 2
       user config file : /home/emre/.condarc
 populated config files : 
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=ivybridge
                          __conda=24.5.0=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /mnt/aperto/linux/anaconda3  (writable)
      conda av data dir : /mnt/aperto/linux/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/aperto/linux/anaconda3/pkgs
                          /home/emre/.conda/pkgs
       envs directories : /mnt/aperto/linux/anaconda3/envs
                          /home/emre/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Linux/5.15.0-116-generic linuxmint/21.3 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```

### Operating system information:

Mint/Linux

**Comment by jacobpennington** [comment]
Unfortunately that can be due to any number of things that may or may not have anything to do with Kilosort. Which version of Kilosort are you using? What commands did you run to set up the environment?

**Comment by ekurtgl** [comment]
Hi @jacobpennington ,

Thank you for the quick response. This is my first time installing Kilosort, I just used the `pip install kilosort[gui]` command, so I believe it is installing v4. I followed the installation steps in the readme file.

**Comment by jacobpennington** [comment]
Did you do that in an existing environment, or did you make a new one for Kilosort?

**Comment by ekurtgl** [comment]
I was able to resolve the issue after creating a new environment. Thank you for the assistance!
