### ISSUE TITLE
BUG: <Kilosort4 Google Colab Example Data Sorting>

### ISSUE THREAD

**Issue by ajcheng1** [MouseLand/Kilosort#751]
### Describe the issue:

I am testing kilosort4 on Google Colab first before deciding whether to download it locally. However when I choose to run all, I get an error without any edits to the code. 
It occurs in the "Run Kilosort" program. I am thinking it has to be an issue with the example data set or the function's signature changed. 

<img width="738" alt="image" src="https://github.com/user-attachments/assets/9451fb7c-245f-41eb-91e0-e89bd89485b1">

### Version information:

Running Kilosort 4 from this link https://colab.research.google.com/github/mouseland/kilosort/blob/main/docs/tutorials/kilosort4.ipynb

**Comment by jacobpennington** [comment]
@ajcheng1 Sorry for the confusion, I guess I missed that one when updating docs. To fix it, you just need to add `kept_spikes` to the returned variables, i.e. change that line to  `...  is_ref, est_contam_rate, kept_spikes = run_kilosort(...)`  (where the ... just indicate leaving the rest unchanged).  I will update that in the repository after double checking that there aren't any other errors in the notebook.
