### ISSUE TITLE
Using Kilosort with HDF5 (.h5) files (from MultiChannelSystem)

### ISSUE THREAD

**Issue by K-Mritunjay** [MouseLand/Kilosort#755]
I use MultiChannelSystems's Mini 2100 to record my data which produces .msrd files. I can easily convert it to .h5 files but I am struggling to convert it to a binary file that can be read by Kilosort (.bin/.bat/.dat/.raw). Does anyone have experience using Kilosort for .h5 data produced by MCS (directly or with easy conversion)? Thanks in advance!

**Comment by dimokaramanlis** [comment]
Sören Zapp (@szapp) has written a conversion tool for converting .msrd files to binaries for kilosort.

Check here: https://github.com/dimokaramanlis/KiloSortMEA/blob/master/dataConversion/convertToRawBinary.m

**Comment by szapp** [comment]
> Sören Zapp (@szapp) has written a conversion tool for converting .msrd files to binaries for kilosort.
> 
> 
> 
> Check here: https://github.com/dimokaramanlis/KiloSortMEA/blob/master/dataConversion/convertToRawBinary.m
> 
> 

Thanks for the tag, @dimokaramanlis !

Just to add, you can also find the source code and download of the conversion tool at https://github.com/gollischlab/ConvertDatMEA

**Comment by jacobpennington** [comment]
It sounds like this has been resolved, if any additional problems come up please let us know and we can re-open the issue.
