### ISSUE TITLE
Restrict template detection to individual shank (kilosort 4)

### ISSUE THREAD

**Issue by Daruum** [MouseLand/Kilosort#757]
Hi,

I'm currently using a 4 shanks Neuronexus probe counting 4 channels on each (A4x4-3mm-50-125-177).

I'd like to restrict the template detection to individual shanks during the spike sorting (to consider each shank as a different dataset).

From what I've read, the `kcoords` variable should handle that in ks4.

Here's what my channel map looks like:

'chanMap': [12, 15, 13, 14, 11, 8, 10, 9, 7, 4, 6, 5, 0, 3, 1, 2]
'xc':             [0, 0, 0, 0, 125, 125, 125, 125, 250, 250, 250, 250, 375, 375, 375, 375]
'yc':             [0, 50, 100, 150, 0, 50, 100, 150, 0, 50, 100, 150, 0, 50, 100, 150]
'kcoords':   [1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]

When I visualize the KS4 sorting in Phy2, I obtained that:

![Screenshot 2024-08-07 140511](https://github.com/user-attachments/assets/34b73a33-8cad-4a03-9c22-d8c06a7baeb1)

The shanks ID of Phy is 0 for all channels and the templates displayed per cluster aren't restricted to the shanks of interest. 

My questions are:

- Does Kilosort analyze each channel signal as part of a specific shank?
- If so, is it normal that the shanks info (kcoords) isn't recognized by Phy2?

Thanks :)

**Comment by jacobpennington** [comment]
Hello,

Thanks for catching this. Shank information was not being exported to Phy, I've pushed a fix for that. However, currently shank information is only used to define where templates are placed relative to the probe. So, there will be instances of "nearest" channels or templates coming from other shanks, for example.

That said, it should not interfere with sorting. Is there a specific problem you're seeing related to this? I'm not sure what you mean by "the templates displayed per cluster."

**Comment by Daruum** [comment]
Ok I see, I was wondering if Kilosort was taking the shank info into account or not for sorting since nothing was visible at the shank ID level in Phy, but it sounds like it's ok. Thanks for the clarification!

So far I don't see any problem, even though I'm super new to these procedures.

For the template I mean, I was wondering if it is normal to have 3 shanks displayed in the waveform view for each cluster (I was expecting one shank per cluster).

**Comment by jacobpennington** [comment]
Ah, I see. Yes that's normal. Each cluster gets assigned a number of channels that it's defined on based on proximity to the channel with the largest peak (the channel number shown in ClusterView). Those other channels may have nothing on them and might be thousands of microns away, but if there are only 12 channels on your probe then those will still be the "nearest" channels.

**Comment by Daruum** [comment]
Ok I see. Thanks for all the explanation!
