### ISSUE TITLE
QUESTION: Does KS4 implement catGT tshift?

### ISSUE THREAD

**Issue by chris-angeloni** [MouseLand/Kilosort#759]
Basically the title, but I was curious if KS4 implicitly re-aligns the data according to NPX sampling for the different banks: https://billkarsh.github.io/SpikeGLX/help/catgt_tshift/catgt_tshift/

I assume it does not because it is a more general purpose algorithm, not necessarily only to be used on Neuropixels, but wanted to be sure.

**Comment by marius10p** [comment]
It does not. I am also not aware of direct evidence that this helps spike sorting outcomes. I could be wrong, but I think the shifts are too small to matter in practice and the artifacts that it rescues too rare to matter as well.
