### ISSUE TITLE
Creating a tuning curve using spike cluster and spike time data

### ISSUE THREAD

**Issue by AidanFishenden** [MouseLand/Kilosort#763]
I have been requested to create a tuning curve with time as the x axis, clusters as the y axis, and each individual channel colored individually. However, when I attempt to export my spike_time.npy file, I get a single line with times that far exceed the time of the actual recording. For example, one recording is 209.34 seconds long, and the final spike time that I see recorded is 1916369. I am assuming this is in milliseconds, which would mean the last spike time is recorded at 31.9 minutes. I've checked in phy, and the recording shows an accurate time frame. Does anyone have an idea how to do this? Attaching my code to create a spreadsheet below. (Possibly important note, my PI requested this be done in MATLAB, so I converted the .npy files to .mat files. I will attach the code i used to do that as well in case I messed something up there.

Conversion code - done in python 
import numpy as np
from scipy.io import savemat
npy_file = 'E:/Dataforkilosort/OneDrive_3_7-15-2023/9_ftc/kilosort4/spike_times.npy'  
data = np.load(npy_file)
mat_file = 'E:/Dataforkilosort/OneDrive_3_7-15-2023/9_ftc/spiketimes.mat'  
savemat(mat_file, {'data': data})

Spreadsheet code - done in matlab 
for ASDF = 1:10
clearvars -except ASDF
filename = ['E:\DataforKilosort\OneDrive_3_7-15-2023\',num2str(ASDF),'_ftc']
    cd(filename)
spike_times = load('spiketimes.mat'); 
spike_clusters = load('spikeclusters.mat'); 
spike_times = spike_times.data;
spike_clusters = spike_clusters.data;
T = table(spike_times, spike_clusters, 'VariableNames', {'SpikeTime', 'ClusterID'});
writetable(T, 'spike_times_clusters.csv');
end

**Comment by jacobpennington** [comment]
Spike times are in units of samples, so you need to divide by the sampling
rate to get seconds.

**Comment by AidanFishenden** [comment]
Oh, that makes sense. My mistake, sorry. Thank you for your help.
________________________________
