### ISSUE TITLE
Confirming Proper Use

### ISSUE THREAD

**Issue by AidanFishenden** [MouseLand/Kilosort#768]
This is my first major project using kilosort, so I wanted to confirm that I ran it properly for my data before I start more analysis. 

Information on my data 
Generated from a 32 channel probe. Probe had two unconnected shanks with 16 channels per shank. Channels were 50 microns apart, from depths of 50-800. The two shanks were 250 microns apart. Sampling rate was 40000, and at specific time points stimuli was administered, there were 420 stimuli per penetration. Recordings averaged around 210-215 seconds long. 

Settings used in Kilosort GUI 

Number of Channels 32
sampling frequency 40000
Batch size 60000
Nblocks 1
Th(universal) 9
Th(learned) 8
Tmin 0
Tmax inf
Nt 61
Shift none
Scale none
Artifact threshold inf
Nskip 25
Whitening range 32
High pass cutoff 300
Binning depth 5
Sig_interp 20
Drift smoothing .5,.5,.5
Nt0min none
Dmin 0
Dminx 32
Min template size 10
Template sizes 5
Nearest chans 10
Nearest templates 100
Max channel distance none
Templates from data true 
N templates 6
Npcs 6
Th(single channel) 6
Act threshold .2
Ccg threshold .25
Cluster downsampling 20
Xcenters none 
Duplicate spike ms .25

**Comment by jacobpennington** [comment]
The settings look fine. If you ran into an error or something looks strange in Phy, please let us know and attach `kilosort4.log` from the results directory.

**Comment by AidanFishenden** [comment]
Ok good, thank you.
