### ISSUE TITLE
Extracting Cluster Spiketimes

### ISSUE THREAD

**Issue by AidanFishenden** [MouseLand/Kilosort#769]
I am trying to find away to extract the spiketimes from the clusters seen in the screenshot. There are many similar clusters throughout the trace view. Each cluster needs to be considered separately, as I am trying to use data to create a frequency/decibel tuning curve. Is there a way to do this? 
![thumbnail_Screenshot 2024-08-28 104418](https://github.com/user-attachments/assets/e90e859b-5353-4520-9330-e3dd56db5ced)

**Comment by jacobpennington** [comment]
@AidanFishenden You can load `spike_times.npy` and `spike_clusters.npy` from the results directory and get that information from there. For example:
```
sampling_rate = 30000
st = np.load('.../spikes_times.npy')
clu = np.load('.../spike_clusters.npy')
cluster_3 = st[clu == 3] / sampling_rate   # spike times in seconds
```

**Comment by AidanFishenden** [comment]
The issue is that my results gave 53 clusters throughout my data, when I went through the data on the trace view it shows over 200, which lines up with the presented stimuli. I'm not sure why what the discrepancy is, especially when the clusters are so distinct on the trace view.

**Comment by jacobpennington** [comment]
Can you please upload `kilosort4.log` from your results directory so I can see the clustering results?

**Comment by jacobpennington** [comment]
Can you please clarify what you mean when you say the trace view shows over 200 clusters? I don't know what you have selected in that first screenshot, and there's no reason why there would be a different cluster for each stimuli. The clusters correspond to putative neurons.

**Comment by AidanFishenden** [comment]
When I said clusters what I meant was what was the small clusters of activity that appear between 160.45 and 160.5. What the experiment is trying to show is what specific pure tones cause neuronal activity. The area shown in the trace view screenshot corresponds with the 60hz, 20db tone. What I am looking for is seeing each of the areas that correspond with the timestamps, and the differences in response.

**Comment by jacobpennington** [comment]
I see. That doesn't really have anything to do with Kilosort, so I'm not sure how to help you. If it's an issue of identifying times from the Phy visualizations, that would be a question to ask on the Phy github. If you're just wanting to do some analysis on the raw traces, you would need to load the data from your .bin file and go from there.

**Comment by AidanFishenden** [comment]
Understood. Thank you for all of your help.
