### ISSUE TITLE
[HELP]  peak to trough time

### ISSUE THREAD

**Issue by Lorena-J** [MouseLand/Kilosort#772]
Hi, I need to calculate the time in ms between peak and trough in a waveform. I have the average of the waveforms and the µV of the peak and valley, but I don't know if there is any file or function to obtain the time from these values.

**Comment by jacobpennington** [comment]
Spike times indicate the peak of the waveforms, which are aligned such that the peak occurs at the 21st bin of the 61-bin waveform snippet by default (based on `settings['nt0min']` and `settings['nt']`). So, you just need to know the bin index at which the trough occurs, which you should be able to get from whatever process you used to find the voltage at those time points. With that information, you can calculate the peak-to-trough time in ms like:
```
t_peak = settings['nt0min']   # in units of bins
t_trough = X                        # also in bins, you'll have to determine this on on your own.
sampling_rate = settings['fs']
peak_to_trough = ((t_trough - t_peak) / sampling_rate) * 1000
```

**Comment by Lorena-J** [comment]
Thank you!!! it has been a great help!
