### ISSUE TITLE
FEATURE: Support very long chronic recordings

### ISSUE THREAD

**Issue by alejoe91** [MouseLand/Kilosort#779]
### Feature you'd like to see:

Hi guys, 

We're currently trying to/aiming to run spike sorting on very long recordings (>10h, ultimately weeks/months long continuous data), and we are experiencing out of memory issues at the optimizing templates stage. 

Do you have any plans to support such long datasets? E.g., by caching spike times/amplitudes as they are fit to disk?

**Comment by jacobpennington** [comment]
Yes, support for long chronic recordings is our main development goal right
now.

**Comment by alejoe91** [comment]
Let us know if you need any help! :)
