### ISSUE TITLE
BUG: <How to assign a better setting based on the probe map>

### ISSUE THREAD

**Issue by Alchemist-Y** [MouseLand/Kilosort#780]
### Describe the issue:
First:
My probe map is a little irregular compared with Neuropixle probe. I want to assign a better settting to fit it. Here is my probe map.
Actually I do not know it clearly about the Group Centers and Universal Templates during sorting. And intuitively it seems better to remove the group centers in the middle(about 50 - 150) and reduce the number of the universal templates.
![image](https://github.com/user-attachments/assets/41c1b728-c838-41d3-a075-2ea493ea56b5)
![image](https://github.com/user-attachments/assets/e5365151-bcbe-4504-9c81-ff887cb45f00)
![image](https://github.com/user-attachments/assets/a9ae07e4-fc31-41e6-b274-5a25b66d4f25)

Second:
only thess channel I can toggle it to exclude, others are not permitted,I don't know the reason.
![image](https://github.com/user-attachments/assets/19f9d139-681f-498d-8835-41e879f8a865)

### Version information:

Kilosort v4.0.15

**Comment by jacobpennington** [comment]
Please upload your probe file so I can reproduce the issue, or paste in the output of "Print Probe" from the GUI.

**Comment by Alchemist-Y** [comment]
hi，jacob, here is my probe file screenshot. Thanks a lot.  actually in the acqusition software Intan, I just find 5-6 spike unit, but after the kilosort process, it output more than 50 unit and with about 10 unit with good refractory.
![image](https://github.com/user-attachments/assets/bb7ff0aa-71d2-4b01-8f33-57a397964560)

**Comment by jacobpennington** [comment]
Please use the "Print Probe" button in the GUI and paste that output here, or upload the .json file for the probe. I can't copy-paste code from an image.

**Comment by Alchemist-Y** [comment]
sorry,jacob. Here is my .json file.
[32 Tetrode 4 shank probe map.json](https://github.com/user-attachments/files/17004640/32.Tetrode.4.shank.probe.map.json)

**Comment by Alchemist-Y** [comment]
@jacobpennington hi,jacob. I want to extract the waveform from the .dat file.I have a question: If I have excluded some bad channels, what is the number of channels will be streamed into disk in the .dat file?

**Comment by Alchemist-Y** [comment]
@jacobpennington,hi jacob, In my stereotype images, is it necessary to keep the map the same with my actural probe? Here is my real probe channels design. So it is 2 tetrodes in one shank. So in this case, could I do the change according to your adivce? BY the way, in your plan B, is this map json meets your advice(this new map json)? But it also seems to obey the origin design of the probe.
![image](https://github.com/user-attachments/assets/a9ac36da-0572-4f86-89d1-81e16e35fb71)
[32 Tetrode 8 shank probe map.json](https://github.com/user-attachments/files/17407232/32.Tetrode.8.shank.probe.map.json)

**Comment by jacobpennington** [comment]
I see. In that case, suggestion a) would not make sense since the contacts do have a fixed geometry. Yes, please try that 8-shank probe map you uploaded. You should also update to the latest version of kilosort4, since I recently fixed the placement of the grouping centers for layouts like this.

**Comment by Alchemist-Y** [comment]
@jacobpennington Bravo. Excellent work! Thanks for your advice! but I seems to meet a new problem, is it due to my  new probe design  submitted above or just for my exclueded channels?  Or is the waring important to be paid attention? Here is my sort parameters file and warning log.
[sorted setting 2version.json](https://github.com/user-attachments/files/17427845/sorted.setting.2version.json)
warning log: C:\Users\alche\anaconda3\envs\kilosort\lib\site-packages\scipy\sparse\_index.py:151: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)
![image](https://github.com/user-attachments/assets/d3087a7c-1366-493b-b253-81cf3bf029ac)

**Comment by Alchemist-Y** [comment]
Follow with the above, I try to restart the kilosort and clear the Cache, and the warning is missing but another error occurs, which is about the CUDA memory. Acutually I have run this data  sucessfully before with the kilosort version of 4.0.17. Here is my log. So I just think is there any imcompatibility in this new version of 4.0.18?
[CUDA out of memory kilosort4 4.0.18 Log.log](https://github.com/user-attachments/files/17430768/CUDA.out.of.memory.kilosort4.4.0.18.Log.log)

**Comment by jacobpennington** [comment]
@Alchemist-Y sorry for the trouble, can you please try updating to `v4.0.19`? There was a bug in the way templates were generated for multi-shank probes which may have caused the memory issue here.
