### ISSUE TITLE
BUG: Kilosort gives the error "Error using indexing. Subscript indices must either be real positive integers or logicals."

### ISSUE THREAD

**Issue by Auxcy1ene** [MouseLand/Kilosort#781]
### Describe the issue:

Just to make sure I don't leave anything out from this mess I'll start from the beginning.
For my MSci project I need to do spike sorting on some electrophysiology data. Unfortunately the data was recorded using a device from Axion Biosystems which stores it in a weird format and requires their own matlab functions to interact with (
[axion_biosystems_functions.zip](https://github.com/user-attachments/files/16970026/axion_biosystems_functions.zip). After figuring how to get the data out of that I came across the Neurodata Without Borders file format (https://pynwb.readthedocs.io/en/latest/) which looked pretty good for my purposes and has a tutorial on building a nwb file from scratch, which I used to write a script to convert from the Axion Biosystems filetype to an nwb file. The first one is a matlab script to extract the necessary data from the Axion Biosystems file (
[Extracting_data_from_raw_axis_file.zip](https://github.com/user-attachments/files/16970090/Extracting_data_from_raw_axis_file.zip) and the second one is a python script which actually builds the nwb file and loads the extracted data into it (
[Building_nwb_file.zip](https://github.com/user-attachments/files/16970129/Building_nwb_file.zip). As I am using spikeinterface to handle everything since I will likely have to run my data through other sorters and compare the results and it seems pretty good in general, I have another python script which generates a probe file from the data in the original Axion Biosystems file with the location data being manually estimated by me as I don't have access to it, this is not an issue though (
[generate_probe_for_experiment_data.zip](https://github.com/user-attachments/files/16970147/generate_probe_for_experiment_data.zip). This is then loaded into spikeinterface and is run through the spikeinterface docker image for kilosort 3 with this script (
[test_with_nwb_file.zip](https://github.com/user-attachments/files/16970179/test_with_nwb_file.zip). After doing this I always receive the following error: "Error using indexing. Subscript indices must either be real positive integers or logicals.". After this I have tried running it through kilosort 4 without docker and I received the same error. When I followed a guide for converting the nwb file to binary and running it and the probe file through kilosort gui and I got a different error: 

"C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\io.py:497: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:212.)
  X[:, self.nt : self.nt+nsamp] = torch.from_numpy(data).to(self.device).float()

Preprocessing filters computed in  2.41s; total  2.41s

computing drift

Re-computing universal templates from data.

Traceback (most recent call last):

  File "C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\gui\sorter.py", line 70, in run

    
ops, bfile, st0 = compute_drift_correction(

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\run_kilosort.py", line 344, in compute_drift_correction

    
ops, st = datashift.run(ops, bfile, device=device, progress_bar=progress_bar)

 
 
 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\datashift.py", line 192, in run

    
st, _, ops  = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\spikedetect.py", line 193, in run

    
ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\kilosort\spikedetect.py", line 70, in extract_wPCA_wTEMP

    
model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)

 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 209, in fit

    
self.fit_transform(X)

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\utils\_set_output.py", line 295, in wrapped

    
data_to_wrap = f(self, X, *args, **kwargs)

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper

    
return fit_method(estimator, *args, **kwargs)

 
 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\decomposition\_truncated_svd.py", line 229, in fit_transform

    
X = self._validate_data(X, accept_sparse=["csr", "csc"], ensure_min_features=2)

 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\base.py", line 633, in _validate_data

    
out = check_array(X, input_name="X", **check_params)

 
 
 
 
 
 
 
 
 
 
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^

  File "C:\Users\sean_\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1072, in check_array

    
raise ValueError(

ValueError
: 
Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD."

It is here that I find myself at a loss for how to continue so if you could help in anyway I would greatly appreciate it. Also it should be noted that I must use kilosort and cannot change to a different spike sorter, although I will use others later the data must first be processed with kilosort. I would upload the source file but it is too big even when compressed so if anyone feels it might help ill upload it to google drives and add a link here.
Many Thanks
From Sean

### Version information:

kilosort 3 
python 3.12

**Comment by jacobpennington** [comment]
Please upload `kilosort4.log` from the results directory for the run that resulted in the last error message you pasted in, as well as a screenshot of the what the Kilosort4 GUI looks like after you load the data that way.

**Comment by Auxcy1ene** [comment]
Hi there,
Yesterday I was playing around with a bunch of settings and it turns out that kilosort wasn't actually able to detect any spikes and adjusting the input parameters was able to give me some results.
