### ISSUE TITLE
BUG: PCA features zero values on relevant channels

### ISSUE THREAD

**Issue by ckwalters** [MouseLand/Kilosort#782]
### Describe the issue:

Hello,
I often see PCA feature values of zero when curating KS4 results in Phy on channels that are on the edge of the template (but for my large amplitude units, relevant to sorting). Is there a setting for increasing the number of channels on which features are actually calculated, or is this unintended behavior? Thanks!

![pca_issue](https://github.com/user-attachments/assets/788107d9-f3e9-44ce-bad2-8437c466b74c)

### Version information:

ks 4.0.17
phy 2.0b5

**Comment by jacobpennington** [comment]
`settings['nearest_chans']` controls the number of channels used.
