### ISSUE TITLE
Question: No good spike clusters sorted

### ISSUE THREAD

**Issue by Hobart10** [MouseLand/Kilosort#783]
### Describe the issue:
KS detects only noise signals as spike clusters, with high ContamPct values in my case.
Could you take a look at my example data and suggest how to obtain better sorting results? Any comments are highly appreciated : )

Example data (~15GB): [bin file link](https://pan.bnu.edu.cn/l/I1XTfS), [probe.zip](https://github.com/user-attachments/files/16959534/probe.zip)

### Version information:
Kilosort v4.0.16

**Comment by jacobpennington** [comment]
First can you please upload `kilosort4.log` from the results directory, and a screenshot of what the Kilosort4 GUI looks like when you load your data?

**Comment by jacobpennington** [comment]
Okay, thanks. I'll take a look at the data soon. In the meantime, can you clarify if you have reason to believe those results are incorrect? I.e. did you sort the data with something else previously and found good clusters?

**Comment by jacobpennington** [comment]
@Hobart10 Just checking, is it possible for you to upload the data to Google Drive instead for sharing it? I'm trying to download it from the link you sent, but it's very slow (~300 KB/s). It's likely the connection will be interrupted before it completes.

**Comment by jacobpennington** [comment]
Sorry it took me so long to respond, this got buried under the other issues. I sorted your data with a few different settings combinations, and unfortunately it looks like the data is just too noisy for sorting to work properly. Every cluster is dominated by similar-looking noise at the same amplitude. There aren't any settings in KS4 that would help with that, you would need to find some other way to remove that noise prior to sorting.
