### ISSUE TITLE
Multiple Issues After Running KS4

### ISSUE THREAD

**Issue by EmmaCondon** [MouseLand/Kilosort#787]
### Describe the issue:

Hello, I am encountering a number of issues with KS4 output that I have not seen before. I would like clarification before moving forward with spike sorting. If you prefer I make these separate issues please let me know.

### **Background**
I am new to KS4 GUI and Neuropixels, previously I have run automatic spike sorting using KS2 & KS3 and manually curated with Phy2 on the following probe types: Cambridge Neurotech 16-channel single shank, NeuoNexus 32- and 64-channel single shank, and NeuroNexus 128-channel multi shank probes. As I am new to KS4 and Neuropixels, I am unsure if what I am seeing is normal, but gauging from the Neuropixels slack and other issues here on github, my results do not look right. Additonally, these results are consistent across a number of recordings.

I am running KS4 via the GUI on acute recordings from NP1 probes (lasting approx 2 hours), not changing any parameters, and using phase3B1 channel map. Here is a view of the GUI after I load the recording. I have not encountered any errors while running KS4. Following automatic spike sorting using KS4 I am manually curating using Phy2. ![KS4 GUI](https://github.com/user-attachments/assets/eef086ed-0777-457c-b631-b6f308a7e0d1)

### **Issue 1: Overmerging of units**
During manual curation in Phy2 I am seeing very clearly in amplitude view and feature view (and sometimes in waveform view) that a unit labelled as good or MUA by KS4 is made up of two, separate units. You can see that after splitting, the autocorrelogram and waveforms of the units are different. 

![clearly 2 units before split](https://github.com/user-attachments/assets/31212704-3fcd-4f3e-bb45-dc98056885b2)
![clearly 2 units after split](https://github.com/user-attachments/assets/fb931c00-0f94-495b-92f0-ba78285e982a)

Here is another example before and after splitting.
![2 units before split 4](https://github.com/user-attachments/assets/a3804eec-bab7-4ff2-9ab2-56c5480a067a)
![2 units after split 4](https://github.com/user-attachments/assets/0ae77360-fba5-4ab2-a72c-ac6204382037)

![2 units before split 6](https://github.com/user-attachments/assets/cde5487a-83b1-4a2b-9707-fcefd4c28b0d)
![2 units after split 6](https://github.com/user-attachments/assets/7fab17f1-1d37-4a4b-ba2d-ecddd9714b68)

However, in other cases when I split, the CCGs and ACGs are the same, indicating that they are the same unit.
![unsure 2 units before split](https://github.com/user-attachments/assets/e48fd0cc-7d5d-4d25-b687-3aeeb67bda4a)
![unsure 2 units after split](https://github.com/user-attachments/assets/7c8525a7-ab3b-4608-a75c-82a681390c17)

**Question: Could you please confirm that this is indeed overmerging and that there splitting here is the best course of action?** I have _alot_ of units like this and it is taking much time to split. My PI suggests that this is not actually 2 different units and splitting should not be done so clarification would be helpful.

### **Issue 2: Amplitude and PCs appearing as single line and dot**
Another very common issue I am having is the appearance of the amplitude as a singular flat line, with a singular dot appearing in feature view. Here is an example, 

Here are some examples:
![amplitude as line 2](https://github.com/user-attachments/assets/4b948ce8-6a5a-41fe-b853-cfc406c49ca3)
![amplitude as line](https://github.com/user-attachments/assets/8108d153-13b9-4b9b-b3b8-221bf237b7f6)

And sometimes these line overlap, and when split are two different units but still appear as a line in amplitude and feature views.
![PC as cross before split](https://github.com/user-attachments/assets/ee4c0b4b-24b1-4a5d-bdbd-d8063a8bb4b4)
![PC as cross after split](https://github.com/user-attachments/assets/cc490b8e-03d2-484d-92ad-59d6a81256d7)

**Question: Are these units still considered acceptable?** My thinking is that this is just a scaling issue with Phy but I have not seen this issue mentioned here in issues.

### **Issue 3: Waveform appearing on incorrect channel**
In a number of different recording sessions, the channel number assigned to the unit does not match up in waveform view.

In the example below, you can see that this unit is labelled as 137 but in the waveform view, there is no waveform on 137, but it appears clearly on 133. 
![wrong channel labels](https://github.com/user-attachments/assets/8ff84033-bf0d-423e-980d-7b8c7dbde60b)

Here is another example, with channel 133 labelled in waveform view as 129.
![wrong channel labelled MUA](https://github.com/user-attachments/assets/b30757ba-8e0e-4ff7-9fe3-65f3ff47b918)

**Question: Is this due to an issue with the channel mapping?** I hesitate to classify these labels as I do not want a mismatch in the channel numbers when analsying the data post spike sorting. I have seen an issue raised here (https://github.com/cortex-lab/phy/issues/866#issue-474267297) but this is related to KS2 and I am unsure if it can be applied to KS4 run via the GUI.

### **Issue 4: Units labelled as good by KS4 actually MUA**
I know that it is common that incorrect labelling can occur in the automatic spike sorting process. However, well over _half_ the units KS4 has assigned to as "good", as actually MUAs and have a clearly contaminated refractory period. For example, in a recording session in which KS4 has assigned 517 units as 'good', following manual curation Phy only 167 units are 'good' with the remainder having a refractory period contaminated by more than 20%.

Here are a few examples.
![KS4 labelled good but MUA 1](https://github.com/user-attachments/assets/d1bc317a-5263-4867-bb64-db3955b91beb)
![KS4 labelled good but MUA 2](https://github.com/user-attachments/assets/dab3cc06-b182-4b5a-b0e0-badd15452ac5)
![KS4 labelled good but MUA 6](https://github.com/user-attachments/assets/790cc46a-4e3f-45d8-adc2-7d4c4a01404f)
![KS4 labelled good but MUA 7](https://github.com/user-attachments/assets/4391f444-6324-4fb4-8cb6-1e1261767ac8)

**Question: Has this issue been reported elsewhere?** It seems KS4 is over classifying units as 'good' even with clearly contaminated refractory periods. I have seen this previously while spike sorting (not using NP and using KS2) but never to the magnitude I am seeing now. 

### Version information:

Operating System: Linux Ubuntu 18.04.6
Kilosort: 4.0.6
Python: 3.9.19
Phy: 2.0b5

**Comment by jacobpennington** [comment]
@EmmaCondon  From your GUI screenshot, it looks like there's an issue with the data. There is a lot of coordinated noise across channels (notice the horizontal bands that all look very similar). That is most likely why a lot of the units in your phy screenshots have waveforms that don't look like spikes. You would need to address that problem with the data first, otherwise the sorting results are not going to be interpretable.

**Comment by EmmaCondon** [comment]
Hi @jacobpennington thank you for the speedy reply and my sincerest apologies I am just responding now! Yes apologies, I see that now in a number of images I have sent it is from a recording with some noise. The noise was present as I ran KS4 across all the recording, but this included 15 mins where the probe was settling prior to behaviour starting.

I have edited the original post, replacing the Phy images with updated images which do not include the settling period (tmin=900) as the same issues are occurring.

**Comment by jacobpennington** [comment]
Sorry, a couple updates after looking at this again:

The periodic peaks in the correlograms do actually look reasonable, they're probably from real oscillatory activity.
As for the strange amplitude distributions, I just noticed that it's centered at 0 and actually includes negative amplitude values, so there's something pretty weird going on there. It might be from some other issue rather than a recording artifact.

Can you please include a screenshot of what the data looks like in the GUI after you excluded the settling period, and upload kilosort4.log from the results directory?

**Comment by EmmaCondon** [comment]
Hi @jacobpennington thank you so much for the replies, I really appreciate your insight and feedback. Of course, please find screenshot of the data in GUI after settling period excluded (whitened and raw versions).

![Main GUI Whitened](https://github.com/user-attachments/assets/7e8ce74c-785c-4731-8b55-8f4793b38465)
![Main GUI Raw](https://github.com/user-attachments/assets/728e7507-885a-470c-9faf-3e67cd7de65d)

I actually don't have a kilosort4.log in my results directory?! I've checked the kilosort4 folder of all other recordings I have run through the KS4 GUI and I also do not have kilosort4.log there. Screenshot below showing what I have in my output folder after running KS4 GUI (manually saved images).

![KS4 ouput folder](https://github.com/user-attachments/assets/b87c325b-4204-4e0b-90db-acb0bd3fcbd1)

**Comment by jacobpennington** [comment]
Which version of Kilosort4 are you using? You can check with `conda list
kilosort` in a terminal.

Also, how are you running kilosort when you sort the data? Are you using
the GUI or the API? Are you using SpikeInterface?

**Comment by EmmaCondon** [comment]
- Kilosort Version 4.0.4
- Running KS4 via the GUI. I have never used Python, and I am not familair with Python, so I use the GUI.
- Not using SpikeInterface.

I have never used Python, and I am not familair with Python, so I use the GUI.

**Comment by jacobpennington** [comment]
Ah... that could explain a lot. Please update to the latest version of
Kilosort (v4.0.18). You can do that with `pip install kilosort --upgrade`.
Then try sorting again, and let me know which problems still show up if any
(and upload the log file, which should be there after sorting with the new
version).

**Comment by EmmaCondon** [comment]
Thanks Jacob! I updated to the latest version (nice feature for being able to turn CAR on and off btw). 

Before sending you anything from Phy/output, when running Kilosort (v4.0.18) GUI, a few errors occurred: 
- one before ´kilosort.spikedetect: Re-computing universal templates from data´
- one after ´kilosort.run_kilosort: first clustering´
- I also got the following error when trying to scroll the _main_.py window and when I tried to minimise the GUI as KS was running.
![Screenshot from 2024-10-09 17-56-44](https://github.com/user-attachments/assets/50741a4d-f58a-47fa-af43-fa2e1af7dbfa)
I've had to force quit as the GUI is frozen and the above dialogue box appears if I try to click on the GUI or any of the generated images (i.e., drfit amount etc.), even after clicking wait.

These errors did not stop KS from running, but I'm wondering if perhaps they can affect the output? I have attached the kilosort4.log. If you could have a look at the errors, I would really appreciate it.
[kilosort4.log](https://github.com/user-attachments/files/17311280/kilosort4.log)

**Comment by jacobpennington** [comment]
I'm not sure what would cause the "not responding" error, I'll try to reproduce it. That wouldn't interfere with the sorting, though. As for the other errors, do you have screenshots of them? There are no errors reported in the log.

**Comment by EmmaCondon** [comment]
I think the not responding error is due to our PC. Yes of course, here are the screenshots of the errors:
![Screenshot from 2024-10-10 16-44-26](https://github.com/user-attachments/assets/0d441863-f516-4611-b029-4a6eb36da02d)

![Screenshot from 2024-10-10 16-45-35](https://github.com/user-attachments/assets/1c4c8e07-0baa-4d02-bc06-09b6b663b638)

**Comment by jacobpennington** [comment]
Thanks. Unfortunately those error messages are not very helpful, hah. Two questions:

1) Can you please tell me what kind of graphics card you're using?
2) If possible, could you try sorting with `device='cpu'` and see if you get a more informative warning at those spots? It will take a lot longer to run, but often pytorch will give more useful information when running on CPU for those obscure CUDA errors.

**Comment by EmmaCondon** [comment]
Hi @jacobpennington , once again apologies for the delay in responding! 

1. Intel® HD Graphics 630 (KBL GT2)
2. Sure, I am running KS4 GUI now overnight with device='cpu'. I´ll update you once the sorting is done!

**Comment by EmmaCondon** [comment]
Hi @jacobpennington, unfortunately, running KS4 GUI with device='cpu' was not successful so I do not have anymore information about the errors. It was running for 36 hours and crashed the computer.

**Comment by jacobpennington** [comment]
Hmm okay, sorry for the trouble. Are you able to share the data so that I can try sorting it myself? I'm not sure how else to proceed with debugging this.

**Comment by EmmaCondon** [comment]
Yes of course @jacobpennington, thank you! What is the best way to send you the data?

**Comment by jacobpennington** [comment]
Either a google drive or dropbox link. You can paste the link here, or e-mail it to me at jacob.p.neuro@gmail.com

**Comment by jacobpennington** [comment]
I was able to sort your data without any problems. There were no errors, the UserWarnings from your screenshots did not show up, and the results look reasonable. I would try the following to get rid of those warnings:
1. Update to the latest version of Kilosort4 (there have been a couple new releases since you posted this).
2. Make sure your graphics card driver is up to date.
3. Try re-installing KS4 in a fresh environment created from `environment.yml` (see instructions at the bottom of the readme).
