### ISSUE TITLE
FEATURE: Will traces view from KS3 be making a return?

### ISSUE THREAD

**Issue by cgallimore25** [MouseLand/Kilosort#791]
### Feature you'd like to see:

Coming from Kilosort3 and just got my environments working properly for KS4.  I am using a 16-channel passive silicon Neuronexus probe (50um inter-contact distance) digitized at 20kHz by an Intan 512 ch recording controller. 

KS3 has performed well on my data in most cases, though one of the reasons i recently decided to give KS4 a shot was because i was finding that KS3 often struggled with narrow spike waveforms (e.g. putative PV interneurons) and positive-going waveforms (usually only identified correctly when the amplitude is massive and accompanied by a negative component). 

I always found the Traces view in the MATLAB GUI very helpful in determining whether kilosort was pulling out what i could see in the data. I would only ever transition to Phy for post-processing once i was satisfied that KS3 had gotten _most_ of what i knew was there from either preprocessed traces (comparing with predictions and residuals) or my observations during recording.  

Will traces view, predictions, and residuals make a return in KS4?  Or is the algorithm for KS4 so fundamentally different that this is no longer part of the spike detection and extraction process?

**Comment by jacobpennington** [comment]
Traces view will be making a return at least and is on the todo list, the others are TBD.
