### ISSUE TITLE
BUG: Odd merging behavior

### ISSUE THREAD

**Issue by Lathomas42** [MouseLand/Kilosort#801]
### Describe the issue:

I am not sure this is a bug, or something wonky with parameters, but I am seeing a reoccurring pattern, and would like to know what parameters to tweak to fix this.
After sorting, I will have units that look like this in phy, which, I would consider noise based on the ISI plot alone
![KSBUG_01](https://github.com/user-attachments/assets/ca31c486-4027-4a33-ad54-0cc4b63bdf7c)
And, as you can see by the feature view, there appears to be one main cluster, and a lot around that. If i just crudely go and isolate the main cluster, the ISI plot changes dramatically. 
![KSBUG_02](https://github.com/user-attachments/assets/e6898da0-3c43-43aa-a181-8a4f7e664807)
I am wondering if there is a parameter i can tune to prevent this kind of merging from happening?

Changed Parameters from default:
settings['nearest_chans'] = 16
settings['batch_size'] = 30000*4 # 4s of data
settings['dminx'] = 18.5

### Version information:

KSVersion: up to comit ddb16d12d06355ee727531e7a3130ed387a9b272
OS: Ubuntu 20.04
GPU: 1080Ti
Probe: Cambridge Neuro 2 shank 64 channels (shanks sorted individually)

**Comment by jacobpennington** [comment]
This looks like a recording artifact that will need to be removed prior to sorting. If you know what is causing it, you should try to remove that from the data yourself. You could also try using the `artifact_threshold` parameter in KS4, but that will simply zero out the whole batch where those big fluctuations occur, which may not be ideal.

**Comment by Lathomas42** [comment]
By "remove it" do you mean zero out the parts of the data where that is occurring? would that be sufficient?

**Comment by jacobpennington** [comment]
That's one option, yes. That's what the `artifact_threshold` parameter does, but it's sort of a last-resort method. Ideally you would apply some kind of filtering or other operation that removes the noise without affecting the rest of the data, but that may or may not be possible and requires knowledge of what's causing it. How you deal with that is up to you.

**Comment by Lathomas42** [comment]
Thank you.
