### ISSUE TITLE
Unrecognized Settings Error

### ISSUE THREAD

**Issue by karmenrai2** [MouseLand/Kilosort#808]
### Describe the issue:

Im trying to use kilosort 4 with this data set. Whenever I try running it, I keep getting this "Unrecognized Settings" error. I was told to post this here as it may be an issue with a new update not working on the GUI. I've tried changing around the settings but I can't seem to make it work. 

### Version information:

Kilosort 4 on Windows 11
![screenshot_2024-10-29_162200-1](https://github.com/user-attachments/assets/fec8373b-0ff2-498e-b0d1-28bb4384dc2e)
![screenshot_2024-10-29_162300-1](https://github.com/user-attachments/assets/5d7b6a91-12a1-4dc6-afa5-c382ef461df6)

**Comment by jacobpennington** [comment]
This is a bug in v4.0.19, it's fixed in v4.0.20. The latest version should be available on PyPi in a few hours after the tests finish running, or you can get the changes immediately by following the developer install instructions at the bottom of the readme.
