### ISSUE TITLE
BUG: <Please replace this text with a comprehensive title>

### ISSUE THREAD

**Issue by MrbioDT** [MouseLand/Kilosort#812]
### Describe the issue:

can't run kilosort4 after loading of binary file
![Screenshot 2024-11-04 at 11 31 24 AM](https://github.com/user-attachments/assets/6eb47138-5575-4871-910a-e0b829fe2b29)

### Version information:

Win10, KS4, python3.9

**Comment by jacobpennington** [comment]
There is a bug in the GUI for v4.0.19. Please update to the latest version, v4.0.20.

**Comment by MrbioDT** [comment]
> There is a bug in the GUI for v4.0.19. Please update to the latest version, v4.0.20.

thanks!!!
