### ISSUE TITLE
Issue installing Phy

### ISSUE THREAD

**Issue by rajagopalana** [MouseLand/Kilosort#814]
I am posting this issue here after reaching out to members of the kilosort team by email, who encouraged me to do so. 

This is an issue regarding the installation of Phy so that I can manually curate kilosort processed data. 

I have been attempting to install Phy for the last week and run into several dependency and deprecation issues. To bypass these issues I attempted to export the conda environment from a machine that has a working version of Phy.  However, the exact environment (see  file in attached .zip folder) that works on my old machine raises an error regarding the version of numpy that is being used on the new one. I have reverted to an older numpy version and am able to get past this version mismatch error but now when the Phy GUI opens a bunch of the windows remain empty.  
[phy_env.zip](https://github.com/user-attachments/files/17667992/phy_env.zip)

Any help with creating a working Phy installation would be appreciated.

**Comment by rajagopalana** [comment]
Alternatively, if anyone can point me to other software that can be used for manual curation of kilosort processed data, that would be useful as well.

**Comment by jacobpennington** [comment]
Hello,

Please submit this issue on the Phy github, not Kilosort's. 
https://github.com/cortex-lab/phy

A couple suggestions I can give, though: if you encounter problems, make sure you're using Phy in a separate environment. I.e. don't install it in the same environment that Kilosort is installed in. You may also need to update anaconda with `conda update --all` prior to creating the Phy environment.
