### ISSUE TITLE
Kilosort2: Input matrix contains NaN or Inf 

### ISSUE THREAD

**Issue by zetonew** [MouseLand/Kilosort#817]
Always meet the same issue with NaN input.
Picture shows many units are empty.

![bug1](https://github.com/user-attachments/assets/490f363a-2584-40e2-ad92-dd747fd0e23e)
![bug2](https://github.com/user-attachments/assets/b99d1e87-3b7d-48a4-b9f3-8c271c8df872)
![bug3](https://github.com/user-attachments/assets/72e90d0c-ea5f-4f27-9221-3bdd244b2638)

**Comment by jacobpennington** [comment]
Hello,
This could come from any number of issues, including problems with matlab. We are not providing support for older versions of Kilosort anymore, we recommend trying to sort your data with Kilosort4. If you encounter problems with the latest version, please let us know.
