### ISSUE TITLE
BUG: log file still open after run_kilosort

### ISSUE THREAD

**Issue by j-moore94** [MouseLand/Kilosort#819]
### Describe the issue:

Hello,
This may be a very simple problem but I'm struggling to figure out whether it is an issue with the code or something I'm doing.

I'm running Kilosort using my own script to define settings and call run_kilosort. With the previous version of the code I was then appending the folder name with a date-time and then copying it elsewhere and removing it. I'm now trying to run this with a version I downloaded the other day, and it shows an error indicating access is denied:

 `[WinError 5] Access is denied: 'C:\\temp_kilosort\\3C028_S31\\kilosort4' -> 'C:\\temp_kilosort\\3C028_S31\\kilosort4_20241120_114253'`

Then when trying to remove the folder, it gives the error:
`[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\temp_kilosort\\3C028_S31\\kilosort4\\kilosort4.log'`

So I'm thinking it is that the logging process didn't close the file properly? But I don't seem to have a file handle to it in my variables and I'm not sure how I would adapt the run_kilosort code to close it.

Would really appreciate any help.

Thanks,
Joe

### Reproduce the bug:

```python
run_kilosort(filename=datfile, settings=settings, probe=probe)
now_time = datetime.datetime.now()
datetime_string = now_time.strftime("%Y%m%d_%H%M%S")
os.rename(os.path.join(datapath, "kilosort4"), os.path.join(datapath, "kilosort4_" + datetime_string))
shutil.copytree(kilosort_folder_local, kilosort_folder_original)
print("Removing local version...")
shutil.rmtree(local_session)
```

### Error message:

```shell
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\temp_kilosort\\3C028_S31\\kilosort4\\kilosort4.log'
```

### Version information:

Kilosort version 4.0.20

**Comment by jacobpennington** [comment]
Thanks for catching this! It was indeed an issue with the way we were using logging handlers, and I just pushed a fix for it. I expect to add a new pypi version later today that will include the changes, but you can get them with `git pull` if you've installed in editable mode.

**Comment by j-moore94** [comment]
Okay great, thanks for that, I'll try out the new version. :)
