### ISSUE TITLE
Question: Running KS4 on PC with multiple GPUs

### ISSUE THREAD

**Issue by nikhilchandra** [MouseLand/Kilosort#821]
### Feature you'd like to see:

The KS4 GUI includes an option "PyTorch device" that defaults to "auto" but allows you to also select a GPU. Does this mean you can choose which GPU to run KS4 on if your PC has multiple GPUs? Is it possible to run it on multiple GPUs simultaneously?

**Comment by jacobpennington** [comment]
Yes, it means you can choose which GPU to run Kilosort4 on. KS4 was not designed to take advantage of multiple GPUs for a single instance, the PyTorch device option is just there to let you choose one. Whether you could launch separate instances each using a different GPU as an unintended side-effect, I'm not sure.
