### ISSUE TITLE
BUG: <no spikes detected with 4*4 distand probes>

### ISSUE THREAD

**Issue by liqun2017** [MouseLand/Kilosort#830]
### Describe the issue:

Hi,

I am a beginner of kilosort. I would like ask how to set the parameters for kilosort4 with 4*4 distand electrodes? I made a probe map with 4*4 (200 microns each) (Fig.1). The data seems to be loaded correctly (Fig. 2), but no spikes detected. I have checked the similar issuses which been brought up, and lowered nearest templates to 50, increased dminx to 200 (Fig. 3). I have awared that the kilosort is designed for high density probes, while it seems can work with tetrodes (people said). I would like kindly ask if it can work with my situtaions? If it is so, how can I define parameters to get the results?  

The kilosort.log file is uploaded here:
[kilosort4.log](https://github.com/user-attachments/files/18072512/kilosort4.log)

Fig.1

![1](https://github.com/user-attachments/assets/947780c1-5e14-4595-9449-c8e612189fc3)

Fig.2

![2](https://github.com/user-attachments/assets/4848e366-22ea-4c12-8f53-bd702632c1c0)

Fig.3

![3](https://github.com/user-attachments/assets/6cdaf65c-a4a6-4232-b487-89e0574ca360)

I would be grateful for your response.

Best,
Qun

### Version information:

python 3.9.20
kilosort  v4.0.20
window 11

**Comment by jacobpennington** [comment]
Can you please check the boxes for "universal templates" and "grouping centers" under the probe preview in the GUI and upload a screenshot of what that looks like?

**Comment by liqun2017** [comment]
Sure, please check if there is anything wrong?

![image](https://github.com/user-attachments/assets/b05cc5a2-5e2d-46ce-8238-6fa14179cd22)

**Comment by liqun2017** [comment]
Hi, I would like ask if this probe map I made is correct or not? Since I realized the y-axis may indicate the depth of recording site located in the brain. However, our probe is made of 4*4 electrodes with the only one recording site in the tip of each shank, it's more like a plane at the same depth in the brain, should I use some kind of 1*16 probe map to indicate this situation, or it will not affect much?

**Comment by liqun2017** [comment]
Sorry for many questions. I went through the docs about "When to adjust default settings" carefully. Then tried to set paramters as follows, seems some results came out, could you please have a look at the parameters if there are good?

Red lines mean the parameters have been modified accroding to those who are metioned in the docs 

![image](https://github.com/user-attachments/assets/32bd5d28-db44-4336-a1dd-9d933d7cfcea)
![image](https://github.com/user-attachments/assets/65401894-b34a-45df-a5a9-f51ba0f62562)

**Comment by jacobpennington** [comment]
@liqun2017 With the spacing of your contacts, a 1x16 probe map would probably work better. I would recommend creating a new probe map for that and sort with default settings again (except for `fs`, `nt`, and `batch_size`, those seem appropriate). In particular, setting `Th_universal` and `Th_learned` to very small values is not likely to be helpful. You're probably just getting spikes detected now because it's incorrectly detecting small noise fluctuations as spikes.

**Comment by liqun2017** [comment]
I see, thank you so much. I will redo it carefully again.
