### ISSUE TITLE
BUG: Unrecognized Settings

### ISSUE THREAD

**Issue by Mia-LF** [MouseLand/Kilosort#836]
### Describe the issue:

I've followed the instructions on downloading and running Kilosort4 but it seems that every time we click run it comes up with an error that says unrecognized settings. 

![image](https://github.com/user-attachments/assets/bd6902f7-0019-41b2-9a91-7e0c24dcfd63)

### Error message:

```shell
kilosort.run_kilosort: Unrecognized keys found in `settings`

kilosort.run_kilosort: See `kilosort.run_kilosort.RECOGNIZED_SETTINGS`

kilosort.gui.sorter: Encountered error in `run_kilosort`:
Traceback (most recent call last):
  File "C:\Users\Neuro-Franks-70\anaconda3\envs\kilosort\lib\site-packages\kilosort\gui\sorter.py", line 78, in run
    ops = initialize_ops(settings, probe, data_dtype, do_CAR,
  File "C:\Users\Neuro-Franks-70\anaconda3\envs\kilosort\lib\site-packages\kilosort\run_kilosort.py", line 396, in initialize_ops
    raise ValueError(f'Unrecognized settings: {unrecognized}')
ValueError: Unrecognized settings: ['data_file_path', 'probe', 'data_dtype', 'save_preprocessed_copy', 'clear_cache', 'do_CAR', 'invert_sign']
```

### Version information:

Version of python is 3.9.20, kilosort4.
Information on the operating system: 
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎1/‎23/‎2022
OS build	19045.5247
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Comment by jacobpennington** [comment]
This was a bug that has already been fixed. Please use the latest version
of Kilosort4, you can update with `pip install kilosort --upgrade`
