### ISSUE TITLE
Sorter output from kilosort2.5 and kilosort4 have different shape.

### ISSUE THREAD

**Issue by MingChingChiang** [MouseLand/Kilosort#837]
### Describe the issue:

Hi
This is Ming-Ching Chiang from OIST, Japan.
Thank you for developing such useful tools.
I'm now working on the Neuropixels dataset and using spikeinterface to run both kilosort2.5 and kilosort4.
After the sorting I'm running the bombcell for quality matrices and then try to run UnitMatch for multiple sessions.
However when I try to run the UnitMatch on kilosort2.5 outputs I always got error.
After several debugging process I found that the output file 'spike_times.npy' from kilosort2.5 and kilosort4 have different shape.
For example form one of my sorting, **the KS25_spike_times.npy.shape is (165379, 1)**, but **the KS4_spike_times.npy.shape is (876132,)**.
The output of kilosort4 is an array of numbers, but the output of kilosort2.5 is an array of arrays. (I hope my explaination make sense...)
![Screenshot 2024-12-12 180744](https://github.com/user-attachments/assets/68469df9-4345-430f-90ef-03907473fccb)

I can manually adjust the output form the kilosort2.5, but I just want to raise this inconsistent ouptut dimension from your codes.

But anyway,
Thank you very much for developing these useful tools.

Best regards,
Ming-Ching

### Version information:

kilosort2.5 and kilosort4

**Comment by jacobpennington** [comment]
Hello,

Many changes have been made to the sorting pipeline since KS2.5, including changes to output formats. There are also some variables output by past versions that are no longer used, and new ones in KS4 that were not present in past versions. Comparing results between versions will not always be straightforward.
