### ISSUE TITLE
QUESTION: Does nt always have to be an odd number?

### ISSUE THREAD

**Issue by nikhilchandra** [MouseLand/Kilosort#838]
### Describe the issue:

I've been playing around with the spike width parameter nt in Kilosort4 and noticed that when I set it to even values (e.g., 80, 78) it always fails whereas when I set it to odd values, it succeeds without problems. Is there a reason for this?

### Reproduce the bug:

```python
N/A
```

### Error message:

```shell
N/A
```

### Version information:

Python 3.12.4
Kilosort 4 via SpikeInterface (Visual Studio Code)
Windows 11

**Comment by jacobpennington** [comment]
Yes, `nt` should always be an odd numbers since it's used for padding in convolutions.
