### ISSUE TITLE
About the channel number in the neuropixel

### ISSUE THREAD

**Issue by TokSakruMai** [MouseLand/Kilosort#841]
Hello everyone,

I'm now doing process on the data recorded from the Neuropixel NHP long and I wonder when I create the channel map for the probe, should I include all the 4416 channels or just the channels I used in one specific recording session (384). Which one is recommended?

If I include all the 4416 channels, can I adjust the kcoords to choose the specific channel I used? And in this case, the 'ChanMap' and the 'n_chan' in the probe dictionary as depicted by the photo should be 4416 or 384?

Thank you!!
![屏幕截图 2024-12-20 200459](https://github.com/user-attachments/assets/8b0aa140-605a-4f3e-a690-5d9d8da41baf)

**Comment by jacobpennington** [comment]
You should only include the 384 channels that were recorded from, and `n_chan` should be 384.

Can you please remind me where you're seeing that documentation of the probe keys so that I can update it?

**Comment by TokSakruMai** [comment]
Thank you very much!!

And the document is on https://kilosort.readthedocs.io/en/latest/tutorials/make_probe.html
