### ISSUE TITLE
preprocessing parameters with GUI

### ISSUE THREAD

**Issue by kiks9012** [MouseLand/Kilosort#93]
How can I change the preprocessing parameters while using the GUI? 

Additionaly, is there a way to skip the preprocessing and sort the data from the raw signal?

And if my signal is already band-pass filtered, is it an issue for the preprocessing stage?

When applying the preprocessing step, all my spikes disappear in the filtered waveform, so I would like to be able to change some of the preprocessing parameters to understand why.

**Comment by marius10p** [comment]
What are your cutoff frequencies? Preprocessing does a lot more than just filtering, it also does channel whitening, which has a big effect. Your spikes don't disappear: they probably just get restricted to the channels which are actually discriminative, as opposed to seeing the haze of the spike over many channels, which does not help with sorting.
